### PR TITLE
Fixes #4514

### LINKED ISSUE #4514: SGroups do not have a way of unsetting properties from Python
SGroups have most of the usual Property methods (Get/Set/Has, GetNames and get as dict), but not the `ClearProp` one, so we can't remove properties from Sgroups.

### PR DESCRIPTION
**Pull request by ricrogz**
Fixes #4514

This just exposes the `ClearProp` method in Python.

### CODE REVIEW

**Review by greglandrum — APPROVED** [review]

**Comment by greglandrum** [comment]
if only they could all be this easy. :-)

**Comment by ricrogz** [comment]
Ha, agreed. Maybe for the next generation of GitHub's Copilot you just need to tell it "Copilot, fix that bug!"...

**Comment by bp-kelley** [comment]
@greglandrum we should probably just wrap the prop as a base class so we don't have to duplicate code.  I'll add this as an area to improve.

**Comment by greglandrum** [comment]
> @greglandrum we should probably just wrap the prop as a base class so we don't have to duplicate code. I'll add this as an area to improve.

makes sense

**Pull request merged**
