### PR TITLE
Improve MCS performance when CompleteRingsOnly is set

### PR DESCRIPTION
**Pull request by ptosco**
This PR stems from the observation that MCS runs on medium size molecules can take a very long time when `CompleteRingsOnly` is set to `true`.
For example, this pair of molecules
image
takes ~12m on my machine with the following `MCSParameters`:
```
MCSParameters p;
p.BondCompareParameters.CompleteRingsOnly = true;
p.AtomTyper = MCSAtomCompareAny;
p.BondTyper = MCSBondCompareAny;
```

So I implemented an early check for `CompleteRingsOnly` in `checkBondRingMatch()`.
With this, the above MCS run completes in ~1.5s.

As often happens when diving deep into the MCS code to remind oneself how it works (as well as reminding oneself how one should _not_ write code), I found a number of things that could be refactored and improved; there's a list below.
I also added some functionality to `RingInfo` regarding fused rings, as I believe it could be useful elsewhere. It is computed lazily and cached, so it won't impact `RingInfo` performance if one does not care about fused rings.

- Changed all `unsigned` to `unsigned int` for clarity
- Switched from dynamic to static allocation for an instance of `MCSParameters`
- Switched to using `auto` where possible
- Added a few `CHECK_INVARIANT` where appropriate before dereferencing pointers
- Moved some inline comments to the previous line to improve readability
- Added a early check for `CompleteRingsOnly` in `checkBondRingMatch()` to improve efficiency
- Removed `RingMatchTableSet` entirely as 1) it is unnecessary since its functionality is already provided by `RingInfo` 2) it abused the `userData` pointer to be passed around. This allows cleaning up and simplifying the code, particularly the Python wrappers which had a significant amount of added complexity to support it
- refactored ringFusionCheck() removing a unnecessary std::find() into a std::set
- Replaced boost::tie with boost::make_iterator_range
- Modernized a few for loops using traditional iterators
- Removed entirely the QueryRings structure as its functionality is already available in RingInfo
- Removed entirely the _DFS() function since the same algorithm can be implemented in a simpler and more efficient way using RingInfo (from 2m28.441s to 2m9.859s for the same task)
- Replaced std::vector<bool> with boost::dynamic_bitset
- Replaced C-style casts with C++ casts
- Replaced some size_t with unsigned int
- Refactored checkIfRingsAreClosed() such that checkNoLoneRingAtoms() is not needed anymore
- Added a test for slow runtimes with CompleteRingsOnly

### CODE REVIEW

**Comment by greglandrum** [comment]
@ptosco : The performance improvements are impressive. 👍 
Since this is a big one, it'll take me a while to review.

**Comment by rachelnwalker** [comment]
@ptosco do you know if these changes fix #3965?

**Comment by ptosco** [comment]
I am going to update this very soon - please don’t spend time in reviewing this as it is going to change significantly.

**Comment by greglandrum** [comment]
@ptosco please ping me (probably on slack or email is best) if you come back to this

**Comment by ptosco** [comment]
@greglandrum This work has become part of #6646, which has already been merged. This PR is now obsolete - I has simply forgot to close it, I am doing it now.

**Pull request closed without merging**
