### PR TITLE
Major MCS refactoring: new features and bug fixes

### LINKED ISSUE #3965: rdFMCS.FindMCS uses huge amounts of memory for this pair of molecules when CompleteRingsOnly is True
When I try to find the MCS between these two mols (only differing in the location of one ring nitrogen), I find that after waiting a couple minutes, the Python process is already using 4 GB of RAM. I've killed it at this point, so I don't know if it ever finishes, but I heard from someone who saw it die from lack of memory, at which point it presumably was taking tens of GB.

image

**To Reproduce**

```
from rdkit import Chem
from rdkit.Chem import rdFMCS

ref = Chem.MolFromSmiles('CC(C)CNC(=O)[C@H](C(C)C)C[C@H](O)[C@@H](NC1=O)COCc(ccc2)cc2[C@@H](c3ccccc3)NC(=O)c(cc14)cc(c4)N(C)S(=O)(=O)C')
lig = Chem.MolFromSmiles('CC(C)CNC(=O)[C@H](C(C)C)C[C@H](O)[C@@H](NC(=O)c(cc12)nc(c1)N(C)S(=O)(=O)C)COCc3cc(ccc3)[C@H](NC2=O)c4ccccc4')

params = rdFMCS.MCSParameters()
params.BondCompareParameters.CompleteRingsOnly = True

result = rdFMCS.FindMCS([ref, lig], params)
print(result)
```

**Expected behavior**

Some kind of MCS result in a reasonable amount of time and memory. :-) Without the CompleteRingsOnly flag, the job completes in less than 2 seconds.

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.1
 - OS: CentOS 7
 - Python version (if relevant): 3.7.10
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? Not sure.
 - If you are not using conda: how did you install the RDKit? I've also reproduced the bug with the RDKit bundled by Schrödinger with its 21-1 suite.

### LINKED ISSUE #5411: Order dependence for rdFMCS.FindMCS with MatchFusedRingsStrict
**Describe the bug**
When trying to find the MCS between two ligands I found that my results differed depending on the order of the molecules in the list passed to FindMCS.
This problem so far has only been reproduced when the `BondCompareParameters.MatchFusedRings` and `BondCompareParameters.MatchFusedRingsStrict` parameters are set to `True`.

Also besides differing results, both results don't match the nitrogen in the conserved indole moiety which I believe is wrong.

**To Reproduce**
```
suppl = Chem.SmilesMolSupplier('mols.smi')
# mols.smi SMILES file:
# [NH3+]CCCCn1c(SCCc2c[nH]c3ccccc23)nnc1-c1cccc2ccccc12 5g
# [NH3+]CCCCn1c(SCCc2c[nH]c3ccccc23)nnc1-c1ccc2ccccc2n1 5m
mola = next(suppl)
molb = next(suppl)

mola_id = mola.GetProp('_Name')
molb_id = molb.GetProp('_Name')

# set FMCS parameters
params = rdFMCS.MCSParameters()
params.BondCompareParameters.MatchFusedRings = True
params.BondCompareParameters.MatchFusedRingsStrict = True

# mola , molb
fmcs_res = rdFMCS.FindMCS([mola, molb], params)
print(f"FMCS [{mola_id}, {molb_id}]: numAtoms: {fmcs_res.numAtoms}, numBonds: {fmcs_res.numBonds}")

# molb, mola
fmcs_res = rdFMCS.FindMCS([molb, mola], params)
print(f"FMCS [{molb_id}, {mola_id}]: numAtoms: {fmcs_res.numAtoms}, numBonds: {fmcs_res.numBonds}")
```

Output:
```
FMCS [5g, 5m]: numAtoms: 29, numBonds: 30
FMCS [5m, 5g]: numAtoms: 30, numBonds: 31
```

**Expected behavior**
I expect the MCS results to be the same and the nitrogen in the indole ring to be included in the MCS.

**Screenshots**
5g_5m_match
5m_5g_match

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.2
 - OS: macOS 12.4
 - Python version (if relevant): 3.8.10
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit? It was part of the bundled python distribution in my Schrodinger Suite installation

**Additional context**
Full script and SMILES file I used to generate the screenshots.
mols.smi:
```
smiles name
[NH3+]CCCCn1c(SCCc2c[nH]c3ccccc23)nnc1-c1cccc2ccccc12 5g
[NH3+]CCCCn1c(SCCc2c[nH]c3ccccc23)nnc1-c1ccc2ccccc2n1 5m
```
python script:
```
from rdkit import Chem
from rdkit.Chem import AllChem, rdFMCS, Draw

def rdkit_FindMCS(mols, seed=''):
    params = rdFMCS.MCSParameters()
    params.InitialSeed = seed
    params.BondCompareParameters.MatchFusedRings = True
    params.BondCompareParameters.MatchFusedRingsStrict = True

    return rdFMCS.FindMCS(mols, params)


def writeFMCSPairImage(mol1, mol2, fmcs_res, filename):
    AllChem.Compute2DCoords(mol1)
    AllChem.Compute2DCoords(mol2)

    matches = [list(m.GetSubstructMatch(fmcs_res.queryMol)) for m in [mol1, mol2]]

    svg = Draw.MolsToGridImage([mol1, mol2], molsPerRow=2, subImgSize=(600,600),
                               legends=[mol1.GetProp("_Name"), mol2.GetProp("_Name")],
                               highlightAtomLists=matches, highlightBondLists=None,
                               useSVG=True)

    with open(filename, mode='w') as fn:
        fn.write(svg)


""" main() """
suppl = Chem.SmilesMolSupplier('mols.smi')
# SMILES file:
# [NH3+]CCCCn1c(SCCc2c[nH]c3ccccc23)nnc1-c1cccc2ccccc12 5g
# [NH3+]CCCCn1c(SCCc2c[nH]c3ccccc23)nnc1-c1ccc2ccccc2n1 5m
mola = next(suppl)
molb = next(suppl)

mola_id = mola.GetProp('_Name')
molb_id = molb.GetProp('_Name')

# mola , molb
fmcs_res = rdkit_FindMCS([mola, molb])
print(f"FMCS [{mola_id}, {molb_id}]: numAtoms: {fmcs_res.numAtoms}, numBonds: {fmcs_res.numBonds}")
writeFMCSPairImage(mola, molb, fmcs_res, f"{mola_id}_{molb_id}_match.svg")

# molb, mola
fmcs_res = rdkit_FindMCS([molb, mola])
print(f"FMCS [{molb_id}, {mola_id}]: numAtoms: {fmcs_res.numAtoms}, numBonds: {fmcs_res.numBonds}")
writeFMCSPairImage(mola, molb, fmcs_res, f"{molb_id}_{mola_id}_match.svg")
```

### LINKED ISSUE #5440: Failed FMCS results with certain seed SMARTS and MatchFusedRings* parameters on
**Describe the bug**
FMCS results with both MatchFusedRings and MatchFusedRingsStrict parameter flags on, fail when also using certain seed SMARTS strings.

Using a seed SMARTS pattern from the MCS of the total ligand set will fail on one of the ligands in the example pair below.
Using no seed or a seed that matches the aliphatic linker will succeed.
Another seed SMARTS that matches the 5-member aromatic ring will also fail.

Once the MatchFusedRings* parameters are turned off again all the cases will succeed.

NOTE: Other non-default MCS parameters are set but conserved across all the calls to FindMCS().
These parameters were set when I discovered the issue and are kept for consistency.

**To Reproduce**
Python script to test and print FMCS matches:
```
from rdkit import Chem
from rdkit.Chem import AllChem, rdFMCS, Draw

def writeFMCSPairImage(mol1, mol1id, mol2, mol2id, fmcs_res, filename):
    AllChem.Compute2DCoords(mol1)
    AllChem.Compute2DCoords(mol2)

    matches = [m.GetSubstructMatch(fmcs_res.queryMol) for m in [mol1, mol2]]
    print("Molecule pair match lists:")
    for m in matches:
        print(m)

    svg = Draw.MolsToGridImage([mol1, mol2], molsPerRow=2, subImgSize=(600,600),
                               legends=[mol1id, mol2id], addAtomIndices=True,
                               highlightAtomLists=matches, highlightBondLists=None,
                               useSVG=True)

    with open(filename, mode='w') as fn:
        fn.write(svg)


""" main() """
mola = Chem.MolFromSmiles("c1cccc(c12)sc(C([O-])=O)c2CCCOc3cccc(c34)cccc4")
molb = Chem.MolFromSmiles("c1cccc(c12)oc(C([O-])=O)c2CCCOc3cccc(c34)cccc4")

print(f"mola has {mola.GetNumAtoms()} atoms and {mola.GetNumBonds()} bonds")
print(f"molb has {molb.GetNumAtoms()} atoms and {molb.GetNumBonds()} bonds")

params = rdFMCS.MCSParameters()
params.MaximizeBonds = False
params.AtomTyper = rdFMCS.AtomCompare.CompareAny
params.AtomCompareParameters.RingMatchesRingOnly = True
params.AtomCompareParameters.CompleteRingsOnly = True
params.BondTyper = rdFMCS.BondCompare.CompareAny
params.BondCompareParameters.CompleteRingsOnly = True
params.BondCompareParameters.MatchFusedRings = True
params.BondCompareParameters.MatchFusedRingsStrict = True

# Test with MCS SMARTS string of entire ligand set as seed
seed = "[#6&!R](=&!@[#8&!R])(-&!@[#8&!R])-&!@[#6&R]1:&@[#6&R](-&!@[#6&!R]-&!@[#6&!R]-&!@[#6&!R]-&!@[#8&!R]-&!@[#6&R]2:&@[#6&R]:&@[#6&R]:&@[#6&R]:&@[#6&R]:&@[#6&R]:&@2):&@[#6&R]2:&@[#6&R](:&@[#7,#8,#16;R]:&@1):&@[#6&R]:&@[#6&R]:&@[#6&R]:&@[#6&R]:&@2"

# Check that seed is a common substructure of both molecules
print(f"\nSeed matches mola: {mola.HasSubstructMatch(Chem.MolFromSmarts(seed))}")
print(f"Seed matches molb: {molb.HasSubstructMatch(Chem.MolFromSmarts(seed))}")

params.InitialSeed = seed
fmcs_res = rdFMCS.FindMCS([mola, molb], params)
print(f"\nFMCS with seed [mola, molb]: numAtoms: {fmcs_res.numAtoms}, numBonds: {fmcs_res.numBonds}")
print(f"FMCS result matches mola: {mola.HasSubstructMatch(fmcs_res.queryMol)}")
print(f"FMCS result matches molb: {molb.HasSubstructMatch(fmcs_res.queryMol)}")
writeFMCSPairImage(mola, 'mola', molb, 'molb', fmcs_res, f"mola_molb_match_seed.svg")

# Test with empty seed
params.InitialSeed = ''
fmcs_res_empty = rdFMCS.FindMCS([mola, molb], params)
print(f"\nFMCS no seed [mola, molb]: numAtoms: {fmcs_res_empty.numAtoms}, numBonds: {fmcs_res_empty.numBonds}")
writeFMCSPairImage(mola, 'mola', molb, 'molb', fmcs_res_empty, f"mola_molb_match_no_seed.svg")

# Test with aliphatic chain seed
params.InitialSeed = 'AAAA'
fmcs_res_ali = rdFMCS.FindMCS([mola, molb], params)
print(f"\nFMCS aliphatic seed [mola, molb]: numAtoms: {fmcs_res_ali.numAtoms}, numBonds: {fmcs_res_ali.numBonds}")
writeFMCSPairImage(mola, 'mola', molb, 'molb', fmcs_res_ali, f"mola_molb_match_ali.svg")

# Test with aromatic ring  seed
params.InitialSeed = 'a1aaaa1'
fmcs_res_aro = rdFMCS.FindMCS([mola, molb], params)
print(f"\nFMCS aromatic seed [mola, molb]: numAtoms: {fmcs_res_aro.numAtoms}, numBonds: {fmcs_res_aro.numBonds}")
writeFMCSPairImage(mola, 'mola', molb, 'molb', fmcs_res_aro, f"mola_molb_match_aro.svg")


# WITHOUT MatchFusedRings*
print("\n########################\nWITHOUT MatchFusedRings*\n########################")
params.BondCompareParameters.MatchFusedRings = False
params.BondCompareParameters.MatchFusedRingsStrict = False

# Test with MCS SMARTS string of entire ligand set as seed
params.InitialSeed = seed
fmcs_res = rdFMCS.FindMCS([mola, molb], params)
print(f"\nFMCS with seed [mola, molb]: numAtoms: {fmcs_res.numAtoms}, numBonds: {fmcs_res.numBonds}")
print(f"FMCS result matches mola: {mola.HasSubstructMatch(fmcs_res.queryMol)}")
print(f"FMCS result matches molb: {molb.HasSubstructMatch(fmcs_res.queryMol)}")

# Test with empty seed
params.InitialSeed = ''
fmcs_res_empty = rdFMCS.FindMCS([mola, molb], params)
print(f"\nFMCS no seed [mola, molb]: numAtoms: {fmcs_res_empty.numAtoms}, numBonds: {fmcs_res_empty.numBonds}")

# Test with aliphatic chain seed
params.InitialSeed = 'AAAA'
fmcs_res_ali = rdFMCS.FindMCS([mola, molb], params)
print(f"\nFMCS aliphatic seed [mola, molb]: numAtoms: {fmcs_res_ali.numAtoms}, numBonds: {fmcs_res_ali.numBonds}")

# Test with aromatic ring  seed
params.InitialSeed = 'a1aaaa1'
fmcs_res_aro = rdFMCS.FindMCS([mola, molb], params)
print(f"\nFMCS aromatic seed [mola, molb]: numAtoms: {fmcs_res_aro.numAtoms}, numBonds: {fmcs_res_aro.numBonds}")
```

Output:
```
mola has 26 atoms and 29 bonds
molb has 26 atoms and 29 bonds

Seed matches mola: True
Seed matches molb: True

FMCS with seed [mola, molb]: numAtoms: 22, numBonds: 24
FMCS result matches mola: True
FMCS result matches molb: False
Molecule pair match lists:
(8, 10, 9, 7, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 5, 4, 6, 3, 2, 1, 0)
()

FMCS no seed [mola, molb]: numAtoms: 26, numBonds: 29
Molecule pair match lists:
(0, 1, 5, 2, 4, 11, 3, 6, 7, 12, 8, 13, 9, 10, 14, 15, 16, 17, 21, 18, 20, 25, 19, 22, 24, 23)
(0, 1, 5, 2, 4, 11, 3, 6, 7, 12, 8, 13, 9, 10, 14, 15, 16, 17, 21, 18, 20, 25, 19, 22, 24, 23)

FMCS aliphatic seed [mola, molb]: numAtoms: 26, numBonds: 29
Molecule pair match lists:
(12, 13, 14, 15, 11, 16, 7, 5, 17, 21, 6, 8, 4, 0, 18, 20, 25, 9, 10, 3, 1, 19, 22, 24, 2, 23)
(12, 13, 14, 15, 11, 16, 7, 5, 17, 21, 6, 8, 4, 0, 18, 20, 25, 9, 10, 3, 1, 19, 22, 24, 2, 23)

FMCS aromatic seed [mola, molb]: numAtoms: 22, numBonds: 24
Molecule pair match lists:
(4, 5, 11, 7, 6, 12, 8, 13, 9, 10, 14, 15, 16, 17, 21, 18, 20, 25, 19, 22, 24, 23)
(4, 5, 11, 7, 6, 12, 8, 13, 9, 10, 14, 15, 16, 17, 21, 18, 20, 25, 19, 22, 24, 23)

########################
WITHOUT MatchFusedRings*
########################

FMCS with seed [mola, molb]: numAtoms: 26, numBonds: 29
FMCS result matches mola: True
FMCS result matches molb: True

FMCS no seed [mola, molb]: numAtoms: 26, numBonds: 29

FMCS aliphatic seed [mola, molb]: numAtoms: 26, numBonds: 29

FMCS aromatic seed [mola, molb]: numAtoms: 26, numBonds: 29
```

**Expected behavior**
With or without any of the seed SMARTS strings I expect the FMCS results to match all atoms and bonds in both example ligands above given the parameter flags set (i.e. match any atom, match any bond, complete rings only, ring match rings only, fused rings strict)

**Screenshots**
MCS match with total ligand set seed:
mola_molb_match_seed

MCS match with no seed:
mola_molb_match_no_seed

MCS match with aliphatic seed:
mola_molb_match_ali

MCS match with 5-member aromatic ring seed:
mola_molb_match_aro

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.2
 - OS: macOS 12.4
 - Python version (if relevant): 3.8.10
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit? It was part of the bundled python distribution in my Schrodinger Suite installation

**Additional context**

### LINKED ISSUE #5457: Seed SMARTS to FindMCS() produces incorrect MCS
**Describe the bug**
Using a certain valid SMARTS as the seed to FindMCS() between two molecules will return a result query that only matches one of the molecules.
In the example below the seed happens to also be a valid MCS for the molecule pair (given the parameters), but the second atom in the seed "[#6,#7;!R]" becomes "[#7&!R]" in the MCS result and therefore no longer matches the second molecule.

**To Reproduce**
```
from rdkit import Chem
from rdkit.Chem import rdFMCS

mola = Chem.MolFromSmiles("c1cccc(c12)ccc(c2)-c3n(CCC[NH3+])c(nn3)SCCc4c[nH]c(c45)cccc5")
molb = Chem.MolFromSmiles("c1cccc(c12)sc(c2)-c3n(CCCC[NH3+])c(nn3)SCCc4c[nH]c(c45)cccc5")

params = rdFMCS.MCSParameters()
params.AtomTyper = rdFMCS.AtomCompare.CompareAny
params.AtomCompareParameters.RingMatchesRingOnly = True
params.AtomCompareParameters.CompleteRingsOnly = True
params.BondTyper = rdFMCS.BondCompare.CompareAny
params.BondCompareParameters.CompleteRingsOnly = True

# MCS SMARTS string over the entire ligand set
mcs_smarts_all_ligands = "[#6&!R](-&!@[#6,#7;!R])-&!@[#6&!R]-&!@[#6&!R]-&!@[#7&R]1:&@[#6&R](-&!@[#16&!R]-&!@[#6&!R]-&!@[#6&!R]-&!@[#6&R]2:&@[#6&R]:&@[#7&R]:&@[#6&R]3:&@[#6&R]:&@2:&@[#6&R]:&@[#6&R]:&@[#6&R]:&@[#6&R]:&@3):&@[#7&R]:&@[#7&R]:&@[#6&R]:&@1"
print(f"MCS SMARTS used as seed for FMCS:\n{mcs_smarts_all_ligands}")

# Check that seed is a common substructure of both molecules
print(f"\nSeed matches mola: {mola.HasSubstructMatch(Chem.MolFromSmarts(mcs_smarts_all_ligands))}")
print(f"Seed matches molb: {molb.HasSubstructMatch(Chem.MolFromSmarts(mcs_smarts_all_ligands))}")

params.InitialSeed = mcs_smarts_all_ligands
fmcs_res = rdFMCS.FindMCS([mola, molb], params)
print(f"\nFMCS result SMARTS:\n{fmcs_res.smartsString}")

# Check that FMCS result is a common substructure of both molecules
print(f"\nFMCS result matches mola: {mola.HasSubstructMatch(fmcs_res.queryMol)}")
print(f"FMCS result matches molb: {molb.HasSubstructMatch(fmcs_res.queryMol)}")
```

Output:
```
MCS SMARTS used as seed for FMCS:
[#6&!R](-&!@[#6,#7;!R])-&!@[#6&!R]-&!@[#6&!R]-&!@[#7&R]1:&@[#6&R](-&!@[#16&!R]-&!@[#6&!R]-&!@[#6&!R]-&!@[#6&R]2:&@[#6&R]:&@[#7&R]:&@[#6&R]3:&@[#6&R]:&@2:&@[#6&R]:&@[#6&R]:&@[#6&R]:&@[#6&R]:&@3):&@[#7&R]:&@[#7&R]:&@[#6&R]:&@1

Seed matches mola: True
Seed matches molb: True

FMCS result SMARTS:
[#6&!R](-&!@[#7&!R])-&!@[#6&!R]-&!@[#6&!R]-&!@[#7&R]1:&@[#6&R](-&!@[#16&!R]-&!@[#6&!R]-&!@[#6&!R]-&!@[#6&R]2:&@[#6&R]:&@[#7&R]:&@[#6&R]3:&@[#6&R]:&@2:&@[#6&R]:&@[#6&R]:&@[#6&R]:&@[#6&R]:&@3):&@[#7&R]:&@[#7&R]:&@[#6&R]:&@1

FMCS result matches mola: True
FMCS result matches molb: False
```

**Expected behavior**
I expect the FindMCS() result to match both ligands. In the case above, the seed SMARTS is already a valid MCS for the given parameters and should be returned as the result.

**Screenshots**
2D depiction of the seed SMARTS:
mcs_seed

MCS result match on the two molecules:
mola_molb_mcs

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.2
 - OS: macOS 12.4
 - Python version (if relevant): 3.8.10
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit? It was part of the bundled python distribution in my Schrodinger Suite installation

**Additional context**

### LINKED ISSUE #5510: FindMCS returns wrong result with monoatomic molecules
**Describe the bug**
Originally reported by James Davidson in #5504.

Simple reproducible:
```python
import rdkit
rdkit.__version__
'2022.09.1pre'

from rdkit import Chem
from rdkit.Chem import rdFMCS
smis = ["C", "O", "N", "CCC"]
mols = [Chem.MolFromSmiles(smi) for smi in smis]
mcs = rdFMCS.FindMCS(mols)
print(mcs.numAtoms, mcs.smartsString)
1 [#6]
```
Interestingly, the following does not raise the bug:
```python
import rdkit
rdkit.__version__
'2022.09.1pre'

from rdkit import Chem
from rdkit.Chem import rdFMCS
smis = ["C", "O", "N"]
mols = [Chem.MolFromSmiles(smi) for smi in smis]
mcs = rdFMCS.FindMCS(mols)
print(mcs.numAtoms, mcs.smartsString)
0
```

### LINKED ISSUE #6082: queryMol from FindMCS doesn't match mols used to generate MCS
**Describe the bug**
The queryMol generated by rdFMCS.FindMCS does not match the mol used to generate the MCS.

**To Reproduce**

```
from rdkit import Chem
from rdkit.Chem import rdFMCS
refMol = Chem.MolFromSmiles("CCc1ccc2nc(CO)cn2n1")
prod = Chem.MolFromSmiles("OCc1cc2nc(C3CC3)ccn2n1")
mcs = rdFMCS.FindMCS([prod, refMol])
print(Chem.MolToSmiles(mcs.queryMol))
refMol.GetSubstructMatch(mcs.queryMol)
prod.GetSubstructMatch(mcs.queryMol)
```

Output:
```
>>> from rdkit import Chem
>>> from rdkit.Chem import rdFMCS
>>> refMol = Chem.MolFromSmiles("CCc1ccc2nc(CO)cn2n1")
>>> prod = Chem.MolFromSmiles("OCc1cc2nc(C3CC3)ccn2n1")
>>> mcs = rdFMCS.FindMCS([prod, refMol])
>>> print(Chem.MolToSmiles(mcs.queryMol))
*~*~*(~*)~*~*~*~*~*(~*)~*
>>> refMol.GetSubstructMatch(mcs.queryMol)
(0, 1, 2, 3, 12, 11, 5, 6, 7, 8, 10)
>>> prod.GetSubstructMatch(mcs.queryMol)
()
>>>
```

**Expected behavior**
Since FindMCS finds the MCS between prod and refMol, the resulting MCS queryMol is expected to match against both of those starting mols. In this case it matches against refMol, but not prod.

**Configuration (please complete the following information):**
 - RDKit version:  2022.03.1
 - OS: Windows 11
 - Python version (if relevant): 3.7.7
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? rdkit

### LINKED ISSUE #6578: partial MCS failure
Here's the reproducible:
```
In [19]: smis = '''Clc1ccc(cc1)c2nn3ncccc3c2c4ccnc(Nc5ccc6OCCOc6c5)n4
    ...: Cc1ccc2c(c3ccnc(Nc4ccccc4)n3)c(nn2n1)c5ccccc5
    ...: Cc1ccc2c(c3ccnc(Nc4cccc(c4)C(F)(F)F)n3)c(nn2n1)c5ccccc5
    ...: c1[nH]ccc1
    ...: '''

In [20]: ms = [Chem.MolFromSmiles(x) for x in smis.split('\n')]

In [21]: rdFMCS.FindMCS(ms,threshold=0.5).smartsString
Out[21]: ''

# if we leave out the pyrrole everything is fine:
In [22]: rdFMCS.FindMCS(ms[:3],threshold=0.5).smartsString
Out[22]: '[#6]-[#6]1:[#6]:[#6]:[#6]2:[#7](:[#7]:1):[#7]:[#6](:[#6]:2-[#6]1:[#6]:[#6]:[#7]:[#6](:[#7]:1)-[#7]-[#6]1:[#6]:[#6]:[#6]:[#6]:[#6]:1)-[#6]1:[#6]:[#6]:[#6]:[#6]:[#6]:1'

# adding another non-pyrrole molecule works:
In [24]: rdFMCS.FindMCS(ms[:3]+[Chem.MolFromSmiles('CON')],threshold=0.5).smartsString
Out[24]: '[#6]-[#6]1:[#6]:[#6]:[#6]2:[#7](:[#7]:1):[#7]:[#6](:[#6]:2-[#6]1:[#6]:[#6]:[#7]:[#6](:[#7]:1)-[#7]-[#6]1:[#6]:[#6]:[#6]:[#6]:[#6]:1)-[#6]1:[#6]:[#6]:[#6]:[#6]:[#6]:1'

# but, yeah, pyrrole is a problem:
In [25]: rdFMCS.FindMCS(ms+[Chem.MolFromSmiles('CON')],threshold=0.5).smartsString
Out[25]: ''
```

**Configuration (please complete the following information):**
 - RDKit version: release and master
 - OS: alll

**Additional context**
This was originally reported in the KNIME forum: https://forum.knime.com/t/problems-with-threshold-parameter-of-rdkit-mcs-node/70738/3

### PR DESCRIPTION
**Pull request by ptosco**
Disclaimer: I know this PR is huge and hard to review.
However, I think it is quite important to merge it as it fixes all current open bugs related to MCS, improves performance and removes a significant amount of cruft from the code (there is plenty still left in, however, in case someone does not know how to spend long winter nights).
I hope the fact it fixes many issues and does not break existing test cases makes it more acceptable.
Thanks in advancing to those who will suffer reviewing this.

- Changed all `unsigned` to `unsigned int` for clarity
- Switched from dynamic to static allocation for an instance of `MCSParameters`
- Switched to using `auto` where possible
- Added a few `CHECK_INVARIANT` where appropriate before dereferencing pointers
- Moved some inline comments to the previous line to improve readability
- Added a early check for `CompleteRingsOnly` in `checkBondRingMatch()` to improve computational efficiency
- Removed `RingMatchTableSet` entirely as 1) it is unnecessary since its functionality is already provided by `RingInfo` 2) it abused the `userData` pointer. This allows cleaning up and simplifying the code, particularly the Python wrappers which had a significant amount of added complexity to support it
- Removed all the code that was deprecated several releases ago
- Reimplemented `ringFusionCheck()` from scratch to address several bug reports; also switched from `std::set` to `boost::dynamic_bitset` for better efficiency
- Replaced `boost::tie` with `boost::make_iterator_range`
- Modernized `for` loops where possible
- Removed entirely the `QueryRings` structure as its functionality is already available in `RingInfo`
- Removed entirely the `_DFS()` function since the same algorithm can be implemented in a simpler and more efficient way using `RingInfo` (from 2m28.441s to 2m9.859s for the same task)
- Replaced `std::vector<bool>` with `boost::dynamic_bitset`
- Replaced C-style casts with C++ casts
- Replaced some `size_t` with `unsigned int`
- Refactored `checkIfRingsAreClosed()` such that `checkNoLoneRingAtoms()` is not needed anymore
- Added a test for slow runtimes with `CompleteRingsOnly`
- Setting `Timeout` to `0` means no timeout, as it should be
- Removed unused `steps` variable from `MaximumCommonSubgraph::growSeeds`
- Storing both `Atom` and `Bond` pointers and their indices on `Seed` and `MCS` data structures is time-consuming and a potential source of inconsistencies; storing pointers is sufficient
- Promoted `MaximumCommonSubgraph::match` from `private` to `public`
- `NewBonds` was declared `mutable`, but `Seed::fillNewBonds()` was incorrectly declared as `non-const`, which caused the need for an ugly (and unnecessary) `const_cast`. I have now removed the `const_cast` and correctly declared functions that alter `NewBonds` as `const`, since `NewBonds` is explicitly `mutable`
- Removed some useless random scoping that was peppering the MCS code
- Removed a significant amount of duplicate code from the Python wrappers by inheriting from a base `PyMCSWrapper` class
- Added support for optional degenerate MCS storage
- Added C++ and Python support for an optional user-defined MCS acceptance criterion
- Fixed #6082
- Fixed #5510
- Fixed #5457
- Fixed #5440
- Fixed #5411
- Fixed #3965
- Fixed #6578

### CODE REVIEW

**Comment by ptosco** [comment]
I must have forgotten to commit something or similar; tomorrow I’ll take a look.

**Comment by ptosco** [comment]
I’ll fix the test failures later today.

**Comment by ptosco** [comment]
This is now ready for review.

**Review by greglandrum — APPROVED** [review]
LGTM

**Pull request merged**
