### PR TITLE
add "RDKit" to the beginning of all library names

### PR DESCRIPTION
**Pull request by greglandrum**
This is connected with #1036, there's a bunch of discussion there.
The change is simple and a good one to make, thought it will break other people's build scripts.
I've confirmed that builds and tests work on linux, the mac, and windows, but having others try would be good.

### CODE REVIEW

**Comment by bp-kelley** [comment]
I'm going to fire this up in the next day or two.

Would it be useful to "auto generate" a CMakeLists.txt file skeleton with the distribution that just does the right thing or at least, links against all of the libraries to make it easier for third party devs?  I've seen this technique used before with decent success.

Will Dave's work with the C++ examples enable this?  If so, I think (after testing) we should just pull the rip cord.

@coleb thoughts?

**Comment by greglandrum** [comment]
I definitely think we should create a FindRDKit.cmake that knows how to pull in all the libraries (and in the right order for static ones). That's been on my todo list for a while but I haven't managed to get around to it yet.

**Comment by coleb** [comment]
We have a variety of build systems and situations so we just compile the binary libraries into a location that other tools link against. So we'll just adapt to whatever is done.

**Comment by bp-kelley** [comment]
@greglandrum @coleb I'm reasonably happy here.  If we make this change, it will probably affect chemfp, next move etc.  How do we want to handle this notification?

**Comment by greglandrum** [comment]
I believe chemfp is using the Python stuff, so it won't affect that.

For the others: I would do a post to the mailing list, just like any other major RDKit change

**Comment by greglandrum** [comment]
Does that seem adequate?

**Comment by bp-kelley** [comment]
I'm ready for this if you are :)

**Comment by greglandrum** [comment]
yeah, I think it's ready to go.

**Pull request merged**
