### PR TITLE
Fixes #3392

### LINKED ISSUE #3392: prepareMolForDrawing() incorrectly adds chiral Hs if no ring info is present
**Configuration:**

- RDKit Version: all

**Description:**

```
In [11]: m = Chem.MolFromSmiles('C[C@H](F)Cl')

In [12]: Draw.PrepareMolForDrawing(m).Debug()
Atoms:
	0 6 C chg: 0  deg: 1 exp: 1 imp: 3 hyb: 4 arom?: 0 chi: 0
	1 6 C chg: 0  deg: 3 exp: 4 imp: 0 hyb: 4 arom?: 0 chi: 2
	2 9 F chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
	3 17 Cl chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
Bonds:
	0 1->0 order: 1 dir: 1 conj?: 0 aromatic?: 0
	1 1->2 order: 1 conj?: 0 aromatic?: 0
	2 1->3 order: 1 conj?: 0 aromatic?: 0

In [13]: m2 = Chem.MolFromSmiles('C[C@H](F)Cl',sanitize=False)

In [14]: m2.UpdatePropertyCache()

In [15]: Draw.PrepareMolForDrawing(m2).Debug()
Atoms:
	0 6 C chg: 0  deg: 1 exp: 1 imp: 3 hyb: 0 arom?: 0 chi: 0
	1 6 C chg: 0  deg: 4 exp: 4 imp: 0 hyb: 0 arom?: 0 chi: 2
	2 9 F chg: 0  deg: 1 exp: 1 imp: 0 hyb: 0 arom?: 0 chi: 0
	3 17 Cl chg: 0  deg: 1 exp: 1 imp: 0 hyb: 0 arom?: 0 chi: 0
	4 1 H chg: 0  deg: 1 exp: 1 imp: 0 hyb: 0 arom?: 0 chi: 0
Bonds:
	0 0->1 order: 1 conj?: 0 aromatic?: 0
	1 1->2 order: 1 conj?: 0 aromatic?: 0
	2 1->3 order: 1 conj?: 0 aromatic?: 0
	3 1->4 order: 1 dir: 1 conj?: 0 aromatic?: 0

In [16]: 
```
This is due to the messed up logic in this line of code:
https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp#L36

### PR DESCRIPTION
**Pull request by greglandrum**
This corrects the logic in `isAtomCandForChiralH()`

There's a bit of code modernization in here too.

### CODE REVIEW

**Comment by bp-kelley** [comment]
Something odd about the OS X segfault, I’m going to investigate

**Comment by greglandrum** [comment]
@bp-kelley makes sense. I also restarted that failing job just in case it’s an intermittent thing

**Comment by bp-kelley** [comment]
@greglandrum Looks good, some conflicts appeared though.

**Comment by greglandrum** [comment]
Yeah, I will fix those tomorrow morning. You ok if I merge after that’s done?

**Comment by greglandrum** [comment]
I will also take a look at that filter catalog test in valgrind

**Review by bp-kelley — APPROVED** [review]

**Pull request merged**
