### PR TITLE
fix boost::bad_any_cast error when CreateAtomIntPropertyList

### PR DESCRIPTION
**Pull request by 0ut0fcontrol**
#### Reference Issue
No Reference Issue.

#### What does this implement/fix? Explain your changes.
```python
from rdkit import Chem
m = Chem.MolFromSmiles("CC")
for a in m.GetAtoms():
     a.SetIntProp("foo", 1)
Chem.CreateAtomIntPropertyList(m, "foo")
````
when `CreateAtomIntPropertyList()` will raise RuntimeError: boost::bad_any_cast: failed conversion using boost::any_cast.

 fae6d6893be927b2aaafdb8ef1f36b5901a4d6d2 change `boost::int64_t` to `int` in getAtomPropertyList() will fix it.

#### Any other comments?
@elifzeng found this bug, and I try to fix it with some help from @mlsoar.

I am not familiar with C++ and not sure is it a reasonable fix.

Any comments and suggestions will be appreciated.😁

### CODE REVIEW

**Comment by 0ut0fcontrol** [comment]
Changing all int to int64_t seems broken many things.

int or int64_t?
Which is preferable?

**Comment by 0ut0fcontrol** [comment]
Changing all `int64_t` to `int` works.

int or int64_t?
Which is preferable?

**Comment by greglandrum** [comment]
Hi @0ut0fcontrol : thanks for the contribution. I need to spend a bit of time looking at the way we use boost::any to see if there's a more general way to solve this problem.

**Comment by 0ut0fcontrol** [comment]
When `setProp<int>("foo1", 1)` and then `getProp<std::int64_t>("foo1")`,  a `boost::bad_any_cast` error will rasie for implicitly casting `int`(int32?) into `int64_t`.

Thank you for your great work on RDKit. 
I am glad that I can contribute to RDKit. Please let me know if there's anything I can do to help.

**Comment by bp-kelley** [comment]
@greglandrum this might be a side-effect of rdvalue specializing int's, I'll take a look.  I don't think this is a real boost::bad_any_cast

**Comment by bp-kelley** [comment]
This is fixed (I think) in

https://github.com/rdkit/rdkit/pull/4194

**Comment by greglandrum** [comment]
@0ut0fcontrol : I'm going to close this since @bp-kelley has done a more robust and flexible solution in #4194.
Thanks, again, for pointing out the problem and proposing a fix we could build on!

**Pull request closed without merging**
