### PR TITLE
Sanitize parameter for LoadSDF (#7019)

### LINKED ISSUE #7019: Allow sanitization to be disabled in PandasTools.LoadSDF
**Is your feature request related to a problem? Please describe.**
I am reading molecules from an SD file into a pandas DataFrame. However, at this stage I do not want to use the sanitization from RDKit. Because I cannot disable it, some of my molecules are not read into the DataFrame (e.g., valence greater than permitted for certain atoms). I want all molecules, no matter if they can be sanitized or not, in the DataFrame.

I am using the Maybridge dataset and the following molecule fails due to invalid valency on the Chlorine atom.
sanitization_error

**Describe the solution you'd like**
A way to also have molecules in the DataFramethat fail sanitization.
The solution I see would be a sanitize boolean argument exposed in LoadSDF (like in Chem.ForwardSDMolSupplier).

**Describe alternatives you've considered**
Another possibility to get all molecules from the SDF into the dataframe.

### PR DESCRIPTION
**Pull request by christophhillisch**
#### Reference Issue
Fixes #7019

#### What does this implement/fix? Explain your changes.
Allows users to set sanitize in PandasTools.LoadSDF. I describe in #7019 what I hope to change with this PR.

Also an unused import is removed in RDLogger.py. Unsure if it should be part of this PR.

### CODE REVIEW

**Review by greglandrum — CHANGES_REQUESTED** [review]
Thanks for the contribution @christophhillisch 
The code changes look fine, but please add a test to UnitTestPandasTools.py that tests the new functionality.

**Comment by christophhillisch** [comment]
Great, yes sure. I should find some time next week to implement the Unit Test.

**Comment by christophhillisch** [comment]
Hi @greglandrum,

I just added a Unittest to check that a structure with a pentavalent carbon is correctly loaded into the DataFrame when the sanitize flag is set to False and also test that this molecule is missing when the flag is set to True.

I hope it's alright like this and that the PR can be merged. Please let me know if further improvements are required.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
Thanks @christophhillisch

**Pull request merged**
