### PR TITLE
Update maeparser & coordgen libraries

### PR DESCRIPTION
**Pull request by ricrogz**
#### What does this implement/fix?
Update maeparser to release v1.1 and coordgen to v1.2.1.

#### Any other comments?

- The update to the latest maeparser comes with a change in the interface: the constructors for MaeParser and Reader that previously took a reference to a stream now take a shared_ptr to a stream. I have updated the MaeMolSupplier with the simplest change I can think of: adding an extra property to hold the shared_ptr to guarantee it is available as long as the object exists. But having the shared_ptr means that, as soon as the object is destroyed, the pointer to the stream will also be deleted. So, now, the MaeMolSupplier(std::istream *inStream, ...) interface always has to take ownership of the stream, so I added a precondition to check that. I'm open to any alternate suggestions on hwo to implement the update, though.

- The latest maeparser also supports reading from compressed mae files (maegz), and now requires acess to Boost iostreams.

- The update to coordgen broke a couple of tests in testCoordGen. I have updated them and added a couple of comments with my understading of what is happening there. Please feel free to correct me.

### CODE REVIEW

**Comment by greglandrum** [comment]
@ricrogz : it looks like the travis failure on the Mac is a real one, not an artifact of something not downloading or a timeout.

**Comment by greglandrum** [comment]
I'm not thrilled about adding the iostreams dependency if we don't need to. Is there anyway to make that optional with maeparser?

**Comment by ricrogz** [comment]
I noticed the Mac build failure, I'm looking into it right now. It looks like I misplaced the iostreams dependency in the CMake file. Also, as far as I can tell, there is no way to avoid that dependency.

**Comment by ricrogz** [comment]
Hm. I should have though of this earlier, but since we will internally handle a shared_ptr to a stream, it makes sense to have a constructor that accepts it.

**Pull request merged**
