### PR TITLE
[Draft] Clean-up all Python modules (99 %)

### PR DESCRIPTION
**Pull request by IchiruTake**
Note: I am not done yet, it still needs more work for further optimization and clean-up to let the code in a consistently written. There are several documentations attached that confused me which needs someone to brief them. I also attached the old code in case the code's author see there is no improvements gained or conflict with the license. Thank you

I am trying to make a large clean-up on every Python modules and codebase.
There are zero net performance changes in functions declarations. However, these changes suggest minimal Python 3 to operate well. 

**First Change**: Clean-up all sub-folders in rdkit.Chem 
Update:
   - Clean-up method call and assignment due to its high cost
   - Merge temporary variables directly into methods
   - Optimize Pythonic generators if performance gained or better understanding
   - One-line if/else (implemented if the code length is short or simple only)
Note:
   - Zero compatibility issues raised
   - F-String can be obtained for faster string-concatenation. However, it is hard to keep track whether it could be used in older Python version in 3.0 - 3.5

However, the change may be caused here:
rdkit.Chem.FeatMaps.FeatMaps.py [WARNING]
   - Code Stability at function `ScoreFeats`: Should not using an empty list for default variables -> Replace the default values to None

### CODE REVIEW

**Comment by greglandrum** [comment]
@IchiruTake, just as an FYI: I think it's absolutely fine to require at least Python 3.6 for the 2022.03 RDKit release. Python 3.5 has not been supported by the python community since September of 2020.

We can actually deprecate 3.6 support in that release and plan for at least python 3.7 in the 2022.09 release.

So, if it makes your life easier as you are doing this cleanup: feel free to assume that the code is running under at least python 3.6

**Comment by IchiruTake** [comment]
> @IchiruTake, just as an FYI: I think it's absolutely fine to require at least Python 3.6 for the 2022.03 RDKit release. Python 3.5 has not been supported by the python community since September of 2020.
> 
> We can actually deprecate 3.6 support in that release and plan for at least python 3.7 in the 2022.09 release.
> 
> So, if it makes your life easier as you are doing this cleanup: feel free to assume that the code is running under at least python 3.6

Thank you for your support. It is kind of hard for me to track whether all of them met the requirements.
Normally, I assumed the code is running under Python 3.7

**Comment by IchiruTake** [comment]
> @IchiruTake, just as an FYI: I think it's absolutely fine to require at least Python 3.6 for the 2022.03 RDKit release. Python 3.5 has not been supported by the python community since September of 2020.
> 
> We can actually deprecate 3.6 support in that release and plan for at least python 3.7 in the 2022.09 release.
> 
> So, if it makes your life easier as you are doing this cleanup: feel free to assume that the code is running under at least python 3.6

@greglandrum, I have seen several data type declaration in numpy array such as `numpy.int` and `numpy.float` which have already been deprecated in Numpy 1.20+. This drives me confusion whether they want what datatype: 32-bit scheme or 64-bit-scheme or even 128-bit scheme? 

Is RDKit contain any standard of which dtype to declare ?

**Comment by greglandrum** [comment]
> @greglandrum, I have seen several data type declaration in numpy array such as `numpy.int` and `numpy.float` which have already been deprecated in Numpy 1.20+. This drives me confusion whether they want what datatype: 32-bit scheme or 64-bit-scheme or even 128-bit scheme?

Ah, the fun of dealing with old code. 

> 
> Is RDKit contain any standard of which dtype to declare ?

There's nothing formal. I would assume 64 bit unless there's something there which indicates that it's trying to get something different (like `np.float`, which is 32bit)

**Comment by IchiruTake** [comment]
It can be updated later in the future:
This is note for remark if there are significant changes:

` Improvement `:
  - Clean-up unused import, temporary variables, one-line if/else --> Improve testing times from 1h17 mins to 1h10 mins. The performance can be better in later version due to the introduction of the new grammar parser.
  - Zero method compatibility issues raised
  - Optimize Pythonic generators if performance gained or better understanding

`Optimization`:
  - We now use `time.perf_counter()` to measure the time more efficient if needed. If it is not available by OS, we switched it to default `time.time()`. This could be changed in the future. Check the Python documentation in cases your project you time measurement.
  - [rdkit.Chem.BRICS.py]: Function `BRICSBuild()`: If `seedIsR2` and `seedIsR1` are both `False`, we have seen a major speed-up, this optimization is available due to the good use of boolean handling logic



` Developer's Improvement `:
  - Optimize Pythonic generators if performance gained or better understanding
  - A test in called `testShorcutImport()` is available in `rdkit.Chem.UnitTestMol3D.py` class TestCase. This test was made to check whether 

` Developer Suggestion `:
  - [Chem.Fingerprints.FingerprintMols]: Optimize `GetMetricName()` and `SetMetricName()` in class `FingerprintDetails`. Expect TwerskySimilarity here  


` Developer Note `:
  -  There are major changes if users/developers use the shortcut import to implement some specific tasks. It is worth noting that this should be change by prevent this code `from rdkit.ABC.DEF import *`, which is memory inefficient and make the code harder to debug and test. We recommend directly import the method (`from rdkit.Chem import MolFromSmiles`) or the full module (`import rdkit.Chem` or `from rdkit import Chem`) used for memory safety.
  - Recommend some harmless test about memory tracking and performance testing to see if there are changes. This tests should be optional.

**Comment by IchiruTake** [comment]
@greglandrum Do you have any further idea about this optimization? As after refactoring all old-standard code (not Pythonic way) in the `rdkit` folder, I found that the whole library contained over 600 Python files, but only 20 % of them are changed. I also fixed several DeprecationWarning raised by `Numpy`. Do we need to upgrade the requirements to get `Numpy=1.20+`  ?

If there are any further suggestion, please let me know.

**Comment by IchiruTake** [comment]
@greglandrum Do you have any further idea about this optimization? As after refactoring all old-standard code (not Pythonic way) in the `rdkit` folder, I found that the whole library contained over 600 Python files, but only 20 % of them are changed. I also fixed several DeprecationWarning raised by `Numpy`. Do we need to upgrade the requirements to get `Numpy=1.20+` 

If there are any further suggestion, please let me know.

**Comment by IchiruTake** [comment]
> @IchiruTake, just as an FYI: I think it's absolutely fine to require at least Python 3.6 for the 2022.03 RDKit release. Python 3.5 has not been supported by the python community since September of 2020.
> 
> We can actually deprecate 3.6 support in that release and plan for at least python 3.7 in the 2022.09 release.
> 
> So, if it makes your life easier as you are doing this cleanup: feel free to assume that the code is running under at least python 3.6

Related to Python deprecation, I think we should push the version to 3.7 in the next major release (2022.03) rather than two different versions. When I cleaned the mess, there are no changes related that cause Python incompatibility issues. Thus, I believe we should push a large twist rather than step-by-step.

**Comment by IchiruTake** [comment]
@greglandrum In the check #0efe649, I don't understand why this test failed on Ubuntu_20_04_x64_cartridge, which did not fail in many previous attempts. The last pull request just fix one issue during refactoring and it got trouble. Can you take a look at it.
The `Ubuntu_20_04_x64_cartridge` failed at the build session

**Comment by IchiruTake** [comment]
@greglandrum Can you help me check and review it for the next release?

**Comment by greglandrum** [comment]
Hi @IchiruTake, sorry, it's going to take me a while to go through this... it's a big one.

**Comment by IchiruTake** [comment]
> Hi @IchiruTake, sorry, it's going to take me a while to go through this... it's a big one.

These are 5 files that are used to keep track the change. Inside is the information of the files changed. Unless the underlying algorithm changed, it would be noticed and probably a `[WARNING]` tag to notice.
The change can be looked up above.

However, there are two main things that caused confusion which is "integer-boolean value" and 'type-hint'.
"integer-boolean value": I am not so confident in which using integer "0" and "1" to replace the need of boolean ("True" and "False") in Python. I am not so sure whether converting Python boolean can cause incompatibility in the C/C++ code but this is hard to differentiate what is the integer used for indexing and calculation and what is the integer for True/False. 

In future, probably my second large fix would aim to provide `type-hint` and fix `integer-boolean`. 


[README.md.txt](https://github.com/rdkit/rdkit/files/7792004/README.md.txt)
[README_2.md.txt](https://github.com/rdkit/rdkit/files/7792005/README_2.md.txt)
[README_3.md.txt](https://github.com/rdkit/rdkit/files/7792006/README_3.md.txt)
[README_4.md.txt](https://github.com/rdkit/rdkit/files/7792007/README_4.md.txt)
[README_5.md.txt](https://github.com/rdkit/rdkit/files/7792008/README_5.md.txt)

**Comment by IchiruTake** [comment]
This is my second update aims to optimize bunch of old codes that cause slowdown. This is still on draft and several update can be made in the future. The optimization is focus on several thing:

Implementation:
- Reduce intermediate memory, unused code/called
- Modify if/else operation to reduce the overall complexity
- Optimize element-wise indexing in numpy
- Fix documentation if possible and resolve compatibility

Result:
- The performance is increased slightly or strongly (reduce Python bytecode)
- Easier to understand the code
- No function incompatibility

Undone Work:
- Add type hint (mypy, manual, ...)


Major Optimization:
- rdkit\Chem\Pharm3D\EmbedLib - Function `DownsampleBoundsMatrix()` 
   - Reason: Slow because of element-wise operation. 
   - Result: Vectorizing operation and Reduce unused memory
      - (1): In small array and indices, we get 5 - 10% speed-up. For large array, the speed-up is varied depend on hyper-parameter `indicies` (Sparser is Faster). 
      - (2): Intermediate mask (boolean array) used 8 bytes (`np.uint64`) --> Now it consumed 1 byte (`np.uint8`)
   - Warning: This function may cause incompatibility. In the previous update, the result always up-rank the datatype to `np.float64` (8 bytes). Now, it will depend on the datatype of the bound matrix

**Comment by greglandrum** [comment]
Hi @IchiruTake,
I'm afraid this PR getting much, much too big. There are just too many changes in here, connected to too many different things, for it to be reviewed and considered for inclusion. 

Based on the short scan I did of what's here it looks like at least some of the changes here are really helpful, but we just can't merge them this way.

My suggestion: break this into a series of PRs, each building on top of each other, which each focus on more or less one thing.
Fortunately, I think this can probably be done by cherry-picking the commits you already have in this branch onto another branch (if you don't know how to do that, I can explain).

It's ok to do a large cleanup PR which changes a lot of files, but this shouldn't have bug fixes or improvements in it. I'd recommend starting with something like this.

The bug fixes or improvements which you've included here are ideally done in individual PRs so that we can easily track what has been changed and why (very important for long term maintainability of the code).

**Comment by IchiruTake** [comment]
> Hi @IchiruTake, I'm afraid this PR getting much, much too big. There are just too many changes in here, connected to too many different things, for it to be reviewed and considered for inclusion.
> 
> Based on the short scan I did of what's here it looks like at least some of the changes here are really helpful, but we just can't merge them this way.
> 
> My suggestion: break this into a series of PRs, each building on top of each other, which each focus on more or less one thing. Fortunately, I think this can probably be done by cherry-picking the commits you already have in this branch onto another branch (if you don't know how to do that, I can explain).
> 
> It's ok to do a large cleanup PR which changes a lot of files, but this shouldn't have bug fixes or improvements in it. I'd recommend starting with something like this.
> 
> The bug fixes or improvements which you've included here are ideally done in individual PRs so that we can easily track what has been changed and why (very important for long term maintainability of the code).

So to sum up, I still don't understand the solution and standardize the solution yet. 
But from your word, I have guessed there are two options:
- (1): Submit multiple PRs to solve one solution
- (2): Submit 1 PR, but submit the commit sequentially on every modules/folders I performed

Related to over 250 files has been changed, I still preferred the second solution as I can decrease the work (+memory) of downloading on my local machine. Although the first solution is much safer and is easier/faster to test them, I still find it hard as a mistake from previous PR can cause incompatibility, then I have to re-check and make new one, and delete the new one to make newer one.

There are many reasons I stated the second option:
- (1) Yes, obviously, compatibility. In my work, most of what I called through-out the code is **"short-cut import"** and **"unused import"**. They are the **import** which is not used in real-time and safe to delete. In the test, I don't make any extra import except these two modules which are "Chem\__init__.py" and "Chem\AllChem.py". Related to other file, most of them are 'delete' action or 'moving' action. In the 'moving' import, all of them are used on the top of the "test" modules.
- (2): Specific compatibility: Across the test, you would see two major bugs is detected through-out the test: "Descriptors.py" and "ML\Descriptors\Parser.py": 
   - The first test related to the **"extra import"** in the file `rdkit/Chem/GraphDescriptors.py` for optimization. This bug cause me confused as the function `_isCallable()` gathers every classes in every Descriptors modules - related. I have fixed it by the function `_belongToRDKit()`. References below: 
   - The second import is in the external module "ML\Descriptors\Parser.py" in which they use dynamic programming in Python: built-in `eval()`. It made me several commits to resolve it as it did not evaluate in real-time (list comprehension), but I need to decode into normal for-loop to make it worked and many fixes to solve it .

To summary, I prefer the second options better. I am not so sure but this is my attempt after your previous message.
- (1): Make a new PR
- (2): Submit each modules or 1 folder separately and test to make it worked independently nicely. I will also make the commit-name to be more clear.
- (3): Repeat step 2 until finishes.

Thank you for reply. Do you have any comments?


``` python
def _belongToRDKit(something):
  try:
    if 'rdkit' in something.__module__:
      return True
  except Exception:
    pass

  try:
    if 'rdkit' in something.__class__.__module__:
      return True
  except Exception:
    pass

  return False
```

**Comment by greglandrum** [comment]
My request is that you do multiple PRs. I can help figure out how to split up what you've done here into separate PRs (if you want), and I can also provide suggestions about how to make this as little extra work as possible. 

If you look at the other PRs that have been merged in the last few years you will see that we try and have PRs be "single purpose": i.e. they fix one bug or a couple of closely related bugs, or they add one feature (or a couple closely related features), or they do the same cleanup task on a large number of files. What we generally don't have is PRs which do a bunch of things at once.

**Comment by IchiruTake** [comment]
> My request is that you do multiple PRs. I can help figure out how to split up what you've done here into separate PRs (if you want), and I can also provide suggestions about how to make this as little extra work as possible.
> 
> If you look at the other PRs that have been merged in the last few years you will see that we try and have PRs be "single purpose": i.e. they fix one bug or a couple of closely related bugs, or they add one feature (or a couple closely related features), or they do the same cleanup task on a large number of files. What we generally don't have is PRs which do a bunch of things at once.

Ok, now I got your idea. My intention is to make each PR fix one module (e.x: Chem/AtomPairs) or one issue (Chem/Descriptors.py) at a time. Is it sound good to go before I schedule my calendar?

**Comment by greglandrum** [comment]
> 
> Ok, now I got your idea. My intention is to make each PR fix one module (e.x: Chem/AtomPairs) or one issue (Chem/Descriptors.py) at a time. Is it sound good to go before I schedule my calendar?

I think that sounds ok. Please start with one PR and then we can be sure that we agree about the way to proceed.

**Comment by IchiruTake** [comment]
> > Ok, now I got your idea. My intention is to make each PR fix one module (e.x: Chem/AtomPairs) or one issue (Chem/Descriptors.py) at a time. Is it sound good to go before I schedule my calendar?
> 
> I think that sounds ok. Please start with one PR and then we can be sure that we agree about the way to proceed.

Ok, I am glad that you and I have share common this time.
Related how to work with minimal effort, I am still getting stuck with it as every sub-modules contained 4 - 5 files. 
If fixed by making the same clean-up task on one PR and continuing doing them, it would need 10 or 20 times refactoring the whole packages and I have to make underlying work to push them, it would be better to make full upgrade on one module/folder instead (1 look-up), but it would need approximately 40 - 50 PRs at a time.

Do you have any further suggestion on how to reduce the effort yet?

**Comment by gedeck** [comment]
Let me share my experience with larger scale changes to the RDKit code base. When I improved the test coverage of the Python modules many years ago, I did this by module. This kept the individual review small and focused. This way, the load on individual reviewers (aka Greg) was lower and led to better reviews.

I suggest you pick a module first where your changes are limited to the module itself to get started with the first PR. Chem/AtomPairs could be a good start. I looked through the suggested changes for this module and they all look reasonable (took me less than 5 minutes). I disagree with some (exception some of the use of tuple unpacking which I think leads to less readable code), but that would be subject of discussion - a discussion that is better to have earlier than later.

If you take your current branch and keep it updated from the main branch, you should be able to copy changes from your existing branch into new branches for individual approval. This won't take much time.

**Comment by IchiruTake** [comment]
@greglandrum I have made two PRs for trial as you mentioned. Is it a good start to push my work ahead to solve all remaining? Or I have to wait?

**Comment by greglandrum** [comment]
> @greglandrum I have made two PRs for trial as you mentioned. Is it a good start to push my work ahead to solve all remaining? Or I have to wait?

It's your call, but I think it would be most efficient if you wait for feedback from @gedeck and myself so that you can see what kinds of comments and suggestions we make. That may save you some work.

**Comment by IchiruTake** [comment]
> > @greglandrum I have made two PRs for trial as you mentioned. Is it a good start to push my work ahead to solve all remaining? Or I have to wait?
> 
> It's your call, but I think it would be most efficient if you wait for feedback from @gedeck and myself so that you can see what kinds of comments and suggestions we make. That may save you some work.

Sorry for slow response but I need to complete all my tests exam before pulling.

**Comment by IchiruTake** [comment]
[Summary]:

`Main Changes`:
- Reduce intermediate memory, unused code/called
- Optimize element-wise indexing in numpy (dtype DeprecationWarning in version 1.20)
- Improve readibility and clean-up doctest and unittest
- Add tons of f-strings: https://grski.pl/fstrings-performance.html & https://bugs.python.org/issue27078 & https://www.scivision.dev/python-f-string-speed/

`Backward Incompatibility`:
- [Breaking Changes]: The use of shortcut import is nearly eliminated, thus several functions cannot be used and it is likely to check your codebase.
- Function `ScoreFeats()` in `Chem\FeatMaps\FeatMaps.py` changed the default variables for data/memory safety
- 

`Bug Fix`:
- Function `DownsampleBoundsMatrix()` in `Pharm3D\EmbedLib.py` now returns the same datatype as input rather than always casting to `numpy.float64` or `numpy.int64`. A doctest has been added to verify this behaviour.
- [Potential]: Now it is safely to add / customize / optimize any descriptor that required another third-party library or module. The change is at functions `_belongToRDKit()` and the call at `_setupDescriptors()` in `Chem\Descriptors.py`


`Optimization`
- Several functions use less intermediate memory and are a little bit faster.
- Remove numpy datatype `DeprecationWarning` raised in numpy 1.20+
- Timer is measured by `time.perf_counter()` which is more accurate than `time.time()`


~~~ Chem sub-folder ~~~
- Function `normalize()` in `MolStandardize\normalize.py` use less memory
- Function `GetUniqueCombinations()` in `Pharm2D\Utils.py` is faster due to the better computation of `math.comb()` (Next line)
- Remove function _fact() of user in `Pharm2D\Utils.py` as it is inefficient and the potential of numerical overflow. We now used the function `math.comb()` which is introduced in Python 3.8. If your Python version is 3.6 or 3.7, we defined the custom function `comb()` which shares high similarity in `math.comb()`. See the attached note.
- Function `CountUpTo()` in `Pharm2D\Utils.py` is now faster if `verbose` is set to True due to the one-time execution of `NumCombinations()` instead of two in the previous version.
- One doctest in function `OrderTriangle()` in `Pharm2D\Utils.py` has been removed as the duplication
- Function `DownsampleBoundsMatrix()` in `Pharm3D\EmbedLib.py` is now faster at least 15% to 11x depending on the unique size of hyper-parameter of `indices` rather than spending time at the worst-case scenario. The speed gained is more significant if `boundMatrix` (bm) is large and `indices` is small.

**Comment by IchiruTake** [comment]
Since the PR has done its mission, so I drop it

**Pull request closed without merging**
