### PR TITLE
Chinese translation of the RDKit documentation

### PR DESCRIPTION
**Pull request by autodataming**
Chinese translation of the RDKit documentation

### CODE REVIEW

**Comment by autodataming** [comment]
Chinese translation of the RDKit documentation

**Comment by autodataming** [comment]
Chinese translation of the RDKit documentation

**Comment by greglandrum** [comment]
Hi @autodataming 
Sorry I've been slow to get to this one.
I really like the idea of having a Chinese translation of the documentation and think it would be helpful for the community.
The current PR is, however, not in a form that it can be merged since it includes a bunch of extra files.
I'd encourage you to take a look at the PR where the Japanese translation of the documents was merged:
https://github.com/rdkit/rdkit/pull/2210
to get a feeling for what should be in this PR.

**Comment by autodataming** [comment]
> 
> 
> Hi @autodataming
> Sorry I've been slow to get to this one.
> I really like the idea of having a Chinese translation of the documentation and think it would be helpful for the community.
> The current PR is, however, not in a form that it can be merged since it includes a bunch of extra files.
> I'd encourage you to take a look at the PR where the Japanese translation of the documents was merged:
> #2210
> to get a feeling for what should be in this PR.

Thank you for your reply. I am a fan of  RDKit and you, RDKit is very useful in my project. 
During the translation process, I made some adjustments and added some new examples and images.

The document can be generated by Sphinx. I built [a web server](http://rdkit.chenzhaoqiang.com/) for this Chinese document http://rdkit.chenzhaoqiang.com/ .

I have upload the document to my [repository]( https://github.com/autodataming/RDKitBook_zhCN),  https://github.com/autodataming/RDKitBook_zhCN .

Could [the repository]( https://github.com/autodataming/RDKitBook_zhCN )  be included in [the repos of rdkit](https://github.com/rdkit)?

**Comment by greglandrum** [comment]
So you would like this repository to be added to the rdkit organization?
i.e. something like: https://github.com/rdkit/RDKitBook_zhCN ?

**Comment by autodataming** [comment]
> 
> 
> So you would like this repository to be added to the rdkit organization?
> i.e. something like: https://github.com/rdkit/RDKitBook_zhCN ?

Yes. 

It's my pleasure if  this repository to be added to the rdkit organization.

**Comment by greglandrum** [comment]
Ok. Sounds good.
We can set that up next week when I am back in the office!

**Comment by autodataming** [comment]
> 
> 
> Ok. Sounds good.
> We can set that up next week when I am back in the office!

Thank you very much!

**Comment by greglandrum** [comment]
Closing due to lack of activity. Feel free to reopen if anyone has the time and inclination to revive this one.

**Pull request closed without merging**
