### PR TITLE
Issue and pull-request templates

### PR DESCRIPTION
**Pull request by gedeck**
Github allows to define templates for issues and pull-requests. In this PR, the files are moved into the `.github` directory.

### CODE REVIEW

**Comment by greglandrum** [comment]
@bp-kelley : I think these make sense. Any comments/objections?

**Comment by bp-kelley** [comment]
I'll have a long flight back to Boston on Sunday, I'll be able to do a proper review at that point, however I have no complaints on my quick review.

----
Brian Kelley

**Comment by bp-kelley** [comment]
Perhaps we should have a code snippet at the top to indicate *how* to get the rdkit version?

**Comment by bp-kelley** [comment]
Otherwise, I'm fine with this.

**Comment by gedeck** [comment]
Good idea about the code snippet. I've updated the issue template. (and fixed a typo).

**Comment by greglandrum** [comment]
Thanks Peter!

**Pull request merged**
