### PR TITLE
Adds some additional canned atom and bond query definitions

### PR DESCRIPTION
**Pull request by greglandrum**
The list:
- queryAtomNumRadicalElectrons
- queryAtomHasChiralTag
- queryBondHasStereo

### CODE REVIEW

**Comment by bp-kelley** [comment]
Any chance for a query(Atom/Bond)HasMissingStereo?

**Comment by greglandrum** [comment]
That would be an atom/bond that could have valid stereo but doesn't?

**Comment by bp-kelley** [comment]
Exactly!

**Comment by greglandrum** [comment]
Certainly doable.

**Comment by greglandrum** [comment]
I'll add the atom query now. The bond query is going to have to wait until assignStereochemistry is modified to flag double bonds that could have stereo and don't. That should be a separate PR

**Pull request merged**
