### PR TITLE
Master

### PR DESCRIPTION
**Pull request by EBjerrum**
Support For molfiles with amino acids as pseudo atoms for condensed representation as e.g. produced by proteax or MDL ISIS/Draw. Marvinsketch also reads them.

### CODE REVIEW

**Comment by bp-kelley** [comment]
It seems like an expandPseudeoAtom is also required for this to be maximally useful.

I'm a bit confused how to reconcile this with the SDFile's concept of SuperAtom ("M  STY") lines.

However, these should probably not be parsed in non-strict mode in any case.

**Comment by greglandrum** [comment]
This is an interesting contribution, but it's easy to imagine that it could end up causing problems with other pieces of the code. Like, for example, the SMILES generator/parser.

It definitely needs some testing code to be added before I would be willing to integrate it.

**Comment by DrBjerrum** [comment]
Thanks for looking at it. I havent contributed before, but yes, theres many things thats not working with the pseudoatoms, smiles only reads up to two letters, so the parser thinks Ala is aluminium. So it may not be production version ready (yet) The idea was not to imlement all the functionality of proteax, but just enable reading of molfiles and some basic functionality. Its a simple patch, so I can just work with it for my own purposes so far.

Best Regards
Esben

**Comment by greglandrum** [comment]
I didn't want to completely discourage you. The pseudoatom/superatom idea is one that's quite interesting and that I could imagine being generally useful. I would, however, want to be sure that it results in something that's flexible and integrated with (at least most) of the rest of the tools.

If you're willing to talk about it further, let's discuss it either here (probably not optimal) or on either the rdkit-discuss list or the RDKit slack (send me email so that I have the write address and I can send an invite).

**Comment by DrBjerrum** [comment]
Cool, I'm on rdkit-discuss mailing list, but not on rdkit slack. e-mail is esbenjannik@rocketmail.com. Esben Jannik Bjerrum
cand.pharm, Ph.D
/Sent from my Ubuntu Touch Phone

Phone +45 2823 8009
http://dk.linkedin.com/in/esbenbjerrum
http://www.wildcardconsulting.dk
 

    On Saturday, January 23, 2016 10:37 AM, Greg Landrum <notifications@github.com> wrote:
 

 I didn't want to completely discourage you. The pseudoatom/superatom idea is one that's quite interesting and that I could imagine being generally useful. I would, however, want to be sure that it results in something that's flexible and integrated with (at least most) of the rest of the tools.If you're willing to talk about it further, let's discuss it either here (probably not optimal) or on either the rdkit-discuss list or the RDKit slack (send me email so that I have the write address and I can send an invite).—

**Pull request closed without merging**
