### PR TITLE
Fix java8 build

### PR DESCRIPTION
**Pull request by greglandrum**
The java8 version of javadoc runs a linter by default on the documentation. The RDKit docs fail this linting step, which causes the wrappers to fail to build.

The patch disables that linting process.

We should, at some point in the undetermined future, figure out how to fix the documentation so that this isn't necessary.

### CODE REVIEW

**Comment by greglandrum** [comment]
@bp-kelley : not sure if you get notifications about these or not. This is a "just-in-case not" message.

**Comment by bp-kelley** [comment]
I'm getting errors on ubuntu12 with java8 (java7 passed fine)

/home/vagrant/devel/rdkit/Code/JavaWrappers/gmwrapper/src/org/RDKit/Atom.java:116: error: tag not allowed here: <li>
<li>this makes no sense if we do not have an owning molecule

**Comment by bp-kelley** [comment]
Looks to be resolved, I was in a state where java8 was being used with the java7 sdk so JAVA was reported as 1.7 but during some portion the java8 linter was being used.  If the tests pass on ubuntu tonight, I'll merge tomorrow morning.

**Comment by greglandrum** [comment]
great, thanks.

**Comment by bp-kelley** [comment]
I think we should also have a java8 travis build as well:

https://blog.travis-ci.com/2013-11-26-test-your-java-libraries-on-java-8/

**Pull request merged**
