### PR TITLE
Add to Cookbook "Include a Bond Index" recipe and image

### PR DESCRIPTION
**Pull request by bertiewooster**
#### What does this implement/fix? Explain your changes.
Adds an example to the Cookbook for numbering bonds by their index on a molecular structure.
RDKitCB_40_im0

#### Any other comments?
To show the image in a Jupyter notebook, I ended the code block with

`display(SVG(svg))`

which required adding as the `testoutput` text `<IPython.core.display.SVG object>`, so that text appears on the page.

I put this in section "Drawing Molecules (Jupyter)" after "Include an Atom Index". It could alternatively go in section "Bonds and Bonding".

### CODE REVIEW

**Comment by greglandrum** [comment]
Any particular reason that you didn't just use the `addBondIndices` draw option?

**Comment by bertiewooster** [comment]
Just that I wasn't aware of `addBondIndices`. I'll play with that and check whether the function in this PR has additional value.

In either case, it may be worth adding a Cookbook article "Include a Bond Index," what do you think?

**Comment by bertiewooster** [comment]
I switched to `addBondIndices` and followed the template of @iwatobipen's "Include an Atom Index" recipe. Screenshot for reference:
Includ a Bond Index recipe

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
Thanks @bertiewooster

**Comment by bertiewooster** [comment]
Great, glad this recipe will be in the Cookbook to help others. Thanks for your guidance.

**Pull request merged**
