### PR TITLE
[fix]  issue #7572, precondition rootAtAtom if more than one fragment exists

### LINKED ISSUE #7572: Chem.MolToSmiles(mol, rootedAtAtom=pos), when the parameter rootedAtAtom is greater than or equal to 20, the range error is reported.
**Describe the bug**
Chem.MolToSmiles(mol, **rootedAtAtom**=pos)
when the parameter **rootedAtAtom** is greater than or equal to 20, the range error is reported.

**To Reproduce**
  mol = Chem.MolFromSmiles(x_str)
  num_atoms = len(mol.GetAtoms())
  pos_list = list(range(num_atoms))
  print(f"num_atoms is : {num_atoms}, pos_list is : {pos_list}")
  for num_try in range(NumTrys) :
    pos = random.choice(pos_list)
    print("^^^^^^^^^", num_try, pos)
    x2_str = Chem.MolToSmiles(mol, rootedAtAtom=pos)
    print("$$$$$$$$$", x2_str)
**out** : 
num_atoms is : 32
^^^^^^^^^ 0 1
$$$$$$$$$ C(C)Oc1c(Cl)c(C(=O)[O-])c(Cl)c(OCC)c1C(=O)[O-].O=C([O-])C#CC#CC(=O)[O-].[Zn][Zn]
^^^^^^^^^ 1 27

then I try: 
**In:** mol = Chem.MolFromSmiles("C(C)Oc1c(Cl)c(C(=O)[O-])c(Cl)c(OCC)c1C(=O)[O-].O=C([O-])C#CC#CC(=O)[O-].[Zn][Zn]")
**In:** Chem.MolToSmiles(mol, rootedAtAtom=1)
**Out[14]:** 'CCOc1c(Cl)c(C(=O)[O-])c(Cl)c(OCC)c1C(=O)[O-].O=C([O-])C#CC#CC(=O)[O-].[Zn][Zn]'
**In:** Chem.MolToSmiles(mol, rootedAtAtom=19)
**Out[15]:** 'O=C([O-])C#CC#CC(=O)[O-].[O-]C(=O)c1c(OCC)c(Cl)c(C(=O)[O-])c(Cl)c1OCC.[Zn][Zn]'
**In:** Chem.MolToSmiles(mol, rootedAtAtom=20)
**Out:**
[21:34:47] 
****
Range Error
idx
Violation occurred on line 209 in file C:\rdkit\build\temp.win-amd64-cpython-39\Release\rdkit\Code\GraphMol\ROMol.cpp
Failed Expression: 20 < 20
****
Traceback (most recent call last):
  File "C:\Users\young\.conda\envs\yj\lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-b5183daf60b5>", line 1, in <module>
    Chem.MolToSmiles(mol, rootedAtAtom=20)
RuntimeError: Range Error
	idx
	Violation occurred on line 209 in file Code\GraphMol\ROMol.cpp
	Failed Expression: 20 < 20
	RDKIT: 2024.03.1
	BOOST: 1_78
******************************************************************
**In:** Chem.MolToSmiles(mol, rootedAtAtom=21)
**Out:**
[21:34:53] 
****
Range Error
idx
Violation occurred on line 209 in file C:\rdkit\build\temp.win-amd64-cpython-39\Release\rdkit\Code\GraphMol\ROMol.cpp
Failed Expression: 21 < 20
****
Traceback (most recent call last):
  File "C:\Users\young\.conda\envs\yj\lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-2ae8dac8f69a>", line 1, in <module>
    Chem.MolToSmiles(mol, rootedAtAtom=21)
RuntimeError: Range Error
	idx
	Violation occurred on line 209 in file Code\GraphMol\ROMol.cpp
	Failed Expression: 21 < 20
	RDKIT: 2024.03.1
	BOOST: 1_78

**Expected behavior**
I would like the parameter rootedAtAtom value to be unrestricted in number because there are a lot of macromolecules that need this arrangement.

**Screenshots**
Quicker_20240626_214024

**Configuration (please complete the following information):**
 - RDKit version: 2024.03.1 &2023.09.X(X for what I forget)
 - OS: [e.g. Ubuntu 20.04]
 - Python version (if relevant) -3.9
 - Are you using conda? -Yes
 - If you are using conda, which channel did you install the rdkit from? -pip
 - If you are not using conda: how did you install the RDKit? -pip

### PR DESCRIPTION
**Pull request by EricBoittier**
#### Reference Issue
Fixes #7572 by adding a precondition to rootAtAtom if more than one fragment exists.

#### What does this implement/fix? Explain your changes.
Prevents users from incorrectly setting rootAtAtom if there is more than one fragment in the Mol.

#### Any other comments?
The issue mentions a range error is thrown at 20 atoms because the first fragment in the example has 20 atoms.

### CODE REVIEW

**Review by greglandrum — APPROVED** [review]
LGTM

**Review by greglandrum — CHANGES_REQUESTED** [review]
@EricBoittier though the changes look good, they have caused the CI builds to fail.
There's a consistent problem with the MHFP code now.

**Comment by EricBoittier** [comment]
@greglandrum the CI builds are passing now. I moved the precondition to the part of the routine where the unsafe indexing occurs

**Comment by EricBoittier** [comment]
image

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
@EricBoittier I just fixed the merge conflict that had arisen since it took me so long to come back to this (sorry for the delay).
I will merge it once the CI builds.

Thanks for the contribution!

**Comment by greglandrum** [comment]
Thanks for this contribution @EricBoittier

**Comment by EricBoittier** [comment]
Thanks for being a legend @greglandrum

**Pull request merged**
