### PR TITLE
This fixes #786

### LINKED ISSUE #786: chiral lexical order for ring closure after branch
RDKit allows ring closures after a branch, like:

    >>> Chem.CanonSmiles("C(I)1.N1")
    'NCI'

This is not a Daylight SMILES, I think, because theory.smiles.html says "The [ring] bonds are numbered in any order, designating ring opening (or ring closure) bonds by a digit immediately following the atomic symbol at each ring closure." Nor is it a valid OpenSMILES.

There's no reason this can't be a valid extension syntax. However, I don't think it works correctly with chiral specifications.  Consider the following:

    >>> smiles = r"CC(C)[C@@](N)1CC[C@]2([C@@H](O2)CCC(=C)[C@H](CC[C@@](/C=C1)(C)O)O)C"
    >>> smiles2 = smiles.replace(r"(N)1", r"1(N)")
    >>> smiles == smiles2
    False
    >>> Chem.CanonSmiles(smiles) == Chem.CanonSmiles(smiles2)
    True

The Daylight documentation says "The chiral order of the ring closure bond is implied by the lexical order that the ring closure digit appears on the chiral atom (not in the lexical order of the "substituent" atom). " I *believe* that means C[C@@]1(N)C should have a different chirality than C[C@@](N)1C because the permutation order of the four bonds has changed.

Honestly, I don't think it's a useful extension because it's hard to even figure out what is the right solution for this case, and I don't think people use it. OpenSMILES doesn't support it.

But I see that Open Babel and SMARTSviewer both support it. OB inverts the chirality between these two cases, while SMARTSviewer shows identical images.

    >>> pybel.readstring("smi", smiles).write("smi")
    'CC(C)[C@]1(N)CC[C@]2([C@@H](O2)CCC(=C)[C@H](CC[C@@](C=C1)(C)O)O)C\t\n'
    >>> pybel.readstring("smi", smiles2).write("smi")
    'CC(C)[C@@]1(N)CC[C@]2([C@@H](O2)CCC(=C)[C@H](CC[C@@](C=C1)(C)O)O)C\t\n'

### PR DESCRIPTION
**Pull request by greglandrum**
The option selected is to reject SMILES where a ring number directly follows a branch.

This solution is not perfect, because it still allows these constructs:
```
C1CC(O)-1
C1CC(O)=1
```
but we will hope there aren't (m)any of those floating around in the wild. (They aren't fixed because detecting them is beyond the ability of bison.)

### CODE REVIEW

**Comment by bp-kelley** [comment]
I'm curious, as far as I know this is perfectly valid smiles.

**Comment by greglandrum** [comment]
Andrew addressed that in the bug report. Do you disagree?

**Comment by bp-kelley** [comment]
It took me a bit to find the bug report.  I did edit my question afterwards.  I'm not directly responding to Rdkit here.  I did notice that other tool kits  also allow parsing these smiles.  I tend to see it as a smiles generation issue not necessarily a parsing one.

For example one thing that my old writer used to do is write the smiles string of a mol file "as is" which created branches of this type, I.e. Atoms and bonds were in the same order as the mol block.  This was an abuse for sure, but was a useful one.

----
Brian Kelley

**Comment by greglandrum** [comment]
I'm about 99% sure that the code will never generate this form (though that needs to be verified).

Which other toolkits accept the SMILES? Can you check what they provide as an output SMILES for: `C1N[C@H](O)1`? This is perhaps unclear (though it seems likely that what the RDKit is currently doing is wrong).

**Comment by greglandrum** [comment]
Closing this based on the comment on the original thread that OpenEye also supports this syntax. that's another solid piece of evidence that this isn't actually wrong.

I'll do a separate PR to fix the ordering problem.

**Pull request closed without merging**
