### PR TITLE
Fixes #6395: Move string index appropriately with molfiles

### LINKED ISSUE #6395: Molfile Unsaturation Query Not Parsed Correctly
I'm having trouble parsing the following molfile, which contains an unsaturation query.

unsaturated.sdf
```

MOESketch           2D                              

  5  5  0  0  1  0            999 V2000
   13.5413    2.8394    0.0000 N   0  0  0  0  0  0  0  0  0  3  0  0
   14.0120    1.4152    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   15.5120    1.4227    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   15.9683    2.8516    0.0000 N   0  0  0  0  0  0  0  0  0  2  0  0
   14.7504    3.7272    0.0000 C   0  0  0  0  0  0  0  0  0  1  0  0
  1  2  8  0  0  0  4
  2  3  8  0  0  0  0
  3  4  8  0  0  0  4
  4  5  8  0  0  0  9
  5  1  1  0  0  0  0
M  SUB  4   1   2   2   2   3   2   4   2
M  UNS  4   2   1   3   1   4   1   5   1
M  END
```

The following python script, which just reads this sdf file gives me an error.
```
from rdkit.Chem.rdmolfiles import MolFromMolFile

mol = MolFromMolFile("unsaturated.sdf")
```

`[18:45:17] Value 3 is not supported as an unsaturation query (only 0 and 1 are allowed). line: 16`

I think the issue is that in the `ParseUnsaturationLine` function in https://github.com/rdkit/rdkit/blob/3b3f6138302dba6e66d9c33c7dbc80fa5eb27b3a/Code/GraphMol/FileParsers/MolFileParser.cpp#L566-L616 there is a missing `spos += 4` at the end of the try block. The code should be parsing the 8 numbers at the end of the unsaturation line in pairs (2 1), (3 1), (4 1), (5 1), but the code is instead parsing the pair (2 1), and then parsing (1 3) [this is the 1 from the (2 1) pair] because it does not move far enough to reach the pair (3 1).

Happy to write a PR for this if this is a bug and the fix I mentioned above is correct. Let me know if I have a misunderstanding of how this code is supposed to work.

### PR DESCRIPTION
**Pull request by timothyngo**
Fixes #6395 

This code gives a fix to molfile parsing, where properties lines might not be processed correctly when they use pairs of values. The old code would fail to increase the string index when certain values were provided, so the code would fail to move completely to the next pair of values.

I've adjusted the code to be similar to the Attachment Points code https://github.com/rdkit/rdkit/blob/d4547e21165cf9cdc04ea6e0bfd1f25bbf2ed14e/Code/GraphMol/FileParsers/MolFileParser.cpp#L903-L973
and the ZCH code https://github.com/rdkit/rdkit/blob/d4547e21165cf9cdc04ea6e0bfd1f25bbf2ed14e/Code/GraphMol/FileParsers/MolFileParser.cpp#L689-L738

This code adjusts the string index close to where the values are being parsed, so that there aren't issues later on with continues skipping the string index incrementing step. Additionally, the code also sets default values in the case that the substring being parsed is too short or consists only of spaces.

### CODE REVIEW

**Comment by timothyngo** [comment]
I'm not familiar with how rdkit runs tests. Is there a place that file parsing is already being tested, and how would I modify and run these tests?

**Comment by greglandrum** [comment]
> I'm not familiar with how rdkit runs tests. Is there a place that file parsing is already being tested, and how would I modify and run these tests?

I'd suggest adding the test to the bottom of this file: https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/FileParsers/file_parsers_catch.cpp

When you run `make test` or `ctest` that's one of the tests which will be run.

**Comment by timothyngo** [comment]
Just added some tests to reflect the changes I made. Let me know if I should change anything else.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
Thanks for the contribution @timothyngo !

**Pull request merged**
