### PR TITLE
Add GetEnantiomer and IsMolChiral

### PR DESCRIPTION
**Pull request by Polydynamical**
#### What does this implement/fix? Explain your changes.

This PR implements two functions: GetEnantiomer and IsMolChiral. The first function generates the enantiomer for a given molecule and returns None if no enantiomer exists for the molecule. The second function uses the first function to determine whether or not a molecule is chiral. 

#### Any other comments?

I'm not completely sure about how I organized all the files since this is the first I have contributed to this repository. All feedback is welcome!

### CODE REVIEW

**Comment by Polydynamical** [comment]
Do you guys think I should also write some tests for these functions?

**Review by IchiruTake — COMMENTED** [review]
I am not so sure whether the function `GetChirality` in Python file `GetChirality.py` is correct. But if so, you should make it as `return GetEnantiomer(m) is not None` to standardize the Python

**Comment by Polydynamical** [comment]
It should work. On all the molecules I have tested, it works.

**Comment by IchiruTake** [comment]
> Do you guys think I should also write some tests for these functions?



> Do you guys think I should also write some tests for these functions?

Related to your request, if your function contained several if/else that could change the result, it is required to make some tests out of them. Otherwise, you just need to write one test to check whether it functioning properly and result matched your expectations. You can also try a push a small dataset in `.csv` to test it

**Comment by IchiruTake** [comment]
> Do you guys think I should also write some tests for these functions?
@Polydynamical 
In general, I found it very interestingly. There are some suggestions from me that you can consider

1) Merge two functions into one Python file, you can named it as `MolChiral.py`. 
2) [Not recommended, but worth to test] In the `__init__.py`, you can make something as `from rdkit.Chem.MolChiral import *`
3) The function named `GetChirality` is not a good name. You can consider `GetChirality()` to be `IsMolChiral()` which matched the RDKit's scheme better. You can adjust the name `GetEnantiomers()` to be `GetEnantiomer`, as it only returned one molecule only

4) Add a warning in `GetEnantiomer` if it does not found your 'Enantiomer'. You can try the function `warning` in `from logging import warning`.
5) If you want to further develop this project, you may want to rename function `GetEnantiomer()` to be `_GetEnantiomer()` (make it protected, add documentation), and make its public version to be better.
6) Your function `GetChirality()` should change doc from `returns the chirality of a molecule. Return True if the molecule is chiral and False if it is not. ` to be `returns whether the molecule is chiral. Return True if the molecule is chiral and False if it is not.`
7) You may want to test the molecule with either hydrogen or not

Suggestion: 
In the file `MolChiral.py`, you can make something as this: (I did not add doc yet.)
``` python

def _GetEnantiomer(m, forceHs: bool = False, silent: bool = False):
   """ ** Your doc here ** """
   m1 = Chem.AddHs(m) if forceHs else rdchem.Mol(m)
   AllChem.EmbedMolecule(m1) # Make sure molecule is in 3D
   m_b = Chem.MolToMolBlock(m1)

   # Reflect the molecule across the origin
   m_b = m_b.replace("-", "+").replace("    ", "   -").replace("+", " ")
   m2 = Chem.MolFromMolBlock(m_b)

   # If an enantiomer does not exist, return None
   if forceHs and Chem.MolToSmiles(m1) == Chem.MolToSmiles(Chem.AddHs(m2)):
         if not silent:
            warning(" **Your message here** "
         return None
   elif not forceHs and Chem.MolToSmiles(m1) == Chem.MolToSmiles(m2):
         if Chem.MolToSmiles(m1) == Chem.MolToSmiles(Chem.AddHs(m2)):
             if not silent:
                  warning(" **Your message here** ")
             return None
         else:
             return m2
         return None
   return m2

def IsMolChiral(m, forceHs: bool) -> bool:
   """ ** Your doc here ** """
   return _GetEnantiomer(m, forceHs=forceHs, silent=True) is not None

def GetEnantiomer(m, forceHs: bool, silent=False):
   """ ** Your doc here ** """
   return _GetEnantiomer(m, forceHs=forceHs, silent=silent)

```

**Comment by greglandrum** [comment]
Hi @Polydynamical,
Thanks for the contribution!

Before I start making suggestions about implementation or nomenclature, It would help if you could explain what problem you are trying to solve with these two new functions, i.e. what you believe your functions are doing.

And, to answer the question you asked: yes, in order for contributions which add new functionality (or which fix existing bugs in existing functionality) to be accepted, there need to be tests in place which verify that the changes actually do what is expected.

**Comment by Polydynamical** [comment]
Note the two checks above did not pass since there was an error downloading the Avalon toolkit (unrelated to this PR)

**Comment by Polydynamical** [comment]
This would be a great feature to get implemented so I'm happy to get any feedback! @greglandrum

**Comment by IchiruTake** [comment]
> Note the two checks above did not pass since there was an error downloading the Avalon toolkit (unrelated to this PR)

I am not the main contributor or the reviewer of the RDKit library. You may want to ask Greg @greglandrum for his help. But based on my observation, doing SMILES comparison is not an optimal way to tackle your problem.

**Comment by Polydynamical** [comment]
Thanks for your response! I'll make sure to let @greglandrum know ;). 

Apologies for the confusion with the SMILES word... there is no operation being done on the SMILES string but everything happens in the mol/molblock format.

**Comment by greglandrum** [comment]
Thanks for the suggestion. Before I go through the code in detail, I think this needs an explanation of how it is different from the stereoisomer enumeration and stereo center enumeration code which is already present in the RDKit

**Comment by Polydynamical** [comment]
Thanks for the response! In chemistry, a stereoisomer refers to a whole class of different 3D arrangements of atoms. I.e. same atoms and bonds but different configurations. However, there are a bunch of types of stereoisomers: diastereomers, cis-trans and e-z isomerism, conformers, anomers, atropisomers, etc _and_ enantiomers. Although the stereoisomer enumeration code you are referring to may generate the enantiomers these functions produce, _it does not distinguish the type of stereochemistry._ In other words, the functions in this PR specifically create one type of stereoisomer: the enantiomer. See above comment for explanation of why such enantiomers are important.

Let me know if you need further clarification/explanation.

**Comment by DavidACosgrove** [comment]
@Polydynamical I would be surprised if most people reading this don't know very well what an enantiomer is.  It's basic chemistry, after all.  The issue we are trying to understand is what additional functionality your PR would bring to the toolkit beyond what is already there.  The RDKit already has a comprehensive set of functions for identifying enantiomers and I would be surprised if your algorithm, by relying on comparing SMILES strings, would capture anything that they miss.  This is mainly because SMILES strings have very limited abilities to show chirality other than tetrahedral chirality at carbons, which the RDKit has very well covered already.  SMILES strings can't capture conformational chirality of the sort exhibited by helicene, for example, or hindered rotations at ortho-substituted bi-phenyls, so your method won't identify those.
 
On a technical level, why are you doing the inversion of the coordinates by string manipulation?  I would imagine that it would be more reliable and efficient to just multiply the conformer coordinates by -1.

**Comment by Polydynamical** [comment]
@DavidACosgrove Thank you for your perspective. 

> The RDKit already has a comprehensive set of functions for identifying enantiomers

Could you please point to these specific functions? I originally wrote this PR as a result of not finding any set of functions for dealing with chirality... but I may be mistaken.

 > SMILES strings can't capture conformational chirality of the sort exhibited by helicene

This is an interesting insight and an oversight on my part. The intention of the SMILES comparison was to check if the generated molecule is equivalent to the original molecule.  Would it make sense to do such a comparison by normalizing the mol variables and doing a comparison from there?

**Pull request closed without merging**
