### PR TITLE
Modified two dot product calls. pbf.py is now compatible with numpy v1.4

### PR DESCRIPTION
**Pull request by mcmont**

### CODE REVIEW

**Comment by greglandrum** [comment]
The rest of the RDKit requires (starting with the next release) numpy 1.7 or above. Do you need to support this older version?

**Comment by mcmont** [comment]
Hi Greg, the numpy installation on the LLAMA server is v1.4. In that version numpy.ndarray doesn't support the dot() method. Without these two small fixes the PBF code won't run. If you'd rather not integrate the changes into the main branch I understand, given that the rest of the codebase requires v1.7.

**Comment by greglandrum** [comment]
Would it be possible for you to install a marginally more recent version of numpy on the LLAMA server? (v1.4 is from 2010, v1.7 is from early 2013)
I'm asking because using the RDKit could be a problem in the future.

**Comment by mcmont** [comment]
The short answer is 'not easily', I'm afraid. The long answer is that I don't have root access to the server, and to build numpy for our environment IT would have to install a lot of extra packages (math libraries, fortran compiler etc). In any case we only use a tiny subset of RDKit's functionality to fill gaps in Indigo's feature set. Chances are we'll probably stick with the version of RDKit that we're using, so I'm not sure upgrading numpy would be worth the risk or effort.

**Comment by hainm** [comment]
Anaconda/miniconda is excellent solution for numpy.

**Comment by greglandrum** [comment]
This has been inactive for quite a while and is probably no longer relevant now that the RDKit only supports Python 3.
I'm going to close it, but feel free to reopen if it's still needed and relevant.

**Pull request closed without merging**
