### PR TITLE
start using boost:stacktrace

### PR DESCRIPTION
**Pull request by greglandrum**
At the moment this is just using the library in the invariants, which is the no-brainer place to add it.

Tracebacks associated with an invariant look like this:
```
[11:31:35] 

****
Range Error
idx
Violation occurred on line 180 in file /scratch/RDKit_git/Code/GraphMol/ROMol.cpp
Failed Expression: 450 < 6
----------
Stacktrace:
 0# Invar::Invariant::toString[abi:cxx11]() const in /scratch/RDKit_git/build/lib/libRDKitRDGeneral.so.1
 1# Invar::operator<<(std::ostream&, Invar::Invariant const&) in /scratch/RDKit_git/build/lib/libRDKitRDGeneral.so.1
 2# RDKit::ROMol::getAtomWithIdx(unsigned int) in /scratch/RDKit_git/build/lib/libRDKitGraphMol.so.1
 3# RDKit::SmilesToMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RDKit::SmilesParserParams const&) in /scratch/RDKit_git/build/lib/libRDKitSmilesParse.so.1
 4# 0x00005585E70741D4 in ./Code/GraphMol/graphmolMolOpsTest
 5# 0x00005585E701AAF2 in ./Code/GraphMol/graphmolMolOpsTest
 6# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
 7# 0x00005585E701AD3E in ./Code/GraphMol/graphmolMolOpsTest
----------
****
```

These aren't particularly attractive, but they are a lot more informative than what we currently have.

### CODE REVIEW

**Comment by bp-kelley** [comment]
Could we run the benchmarks with the patch?  I would expect Invariants to be in the hot path for a lot of operations and am curious what the overhead is.  I hope it's negligible.

**Comment by greglandrum** [comment]
Yeah, I'll run them a bit later.
You expect this to make a difference even if the invariants aren't actually triggered?

**Comment by greglandrum** [comment]
Looks like there are also fun CI problems for me to investigate. :-)

**Comment by ptosco** [comment]
I don't think it should make a difference if the invariant is not triggered. Even if it is triggered, it should not have a big impact unless you use `try..catch` in a loop (which is a bad thing in itself). SireMol was doing that and caused the Windows version to crawl. After I added the WINDBG define also Windows started to behave.

**Comment by greglandrum** [comment]
yeah, and you really really shouldn't be doing `try...catch` with the invariants.

**Comment by greglandrum** [comment]
To address the performance question.
Here's the result of running `new_timings.py` (https://github.com/rdkit/rdkit/blob/master/Regress/Scripts/new_timings.py) on my linux box with master:
```
| 2020.09.1dev1 | 6.6 | 3.1 | 2.9 | 0.0 | 17.0 | 18.2 | 0.0 | 66.2 | 67.7 | 12.2 | 16.2 | 7.2 | 34.2 | 2.1 |
```
and with this branch:
```
| 2020.09.1dev1 | 6.8 | 3.2 | 2.9 | 0.0 | 16.8 | 18.0 | 0.0 | 64.7 | 64.6 | 12.2 | 16.0 | 7.2 | 34.4 | 2.2 |
```
So no impact on performance with code that's not triggering a bunch of invariant failures (and such code should absolutely not exist).

**Comment by bp-kelley** [comment]
@greglandrum just a ping to see if we can get turn this off for OSX/Windows

**Comment by greglandrum** [comment]
Updated the PR to make it linux only. Let's see what happens in CI

**Pull request merged**
