### PR TITLE
Fixes #6816

### LINKED ISSUE #6816: Double bonds should not be depicted as crossed bonds in the presence of wavy bonds
I have compared the ChemDraw depictions to RDKit depictions for a few cases where undefined geometric isomerism at a double bond is represented as:

1. _Either_ single bonds on the stereochemistry-determining atoms (bond stereo 4) (Examples 1-3)
2. _Cis or trans (either)_ double bond (bond stereo 3) (Example 4)

```
from rdkit import Chem
from rdkit.Chem.Draw import IPythonConsole, rdMolDraw2D, rdDepictor
```

# Example 1
### ChemDraw
image

### RDKit
```
mol = Chem.MolFromMolBlock("""double.mol
  ChemDraw10192311132D

  4  3  0  0  0  0  0  0  0  0999 V2000
   -0.7145    0.2062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.6188    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145    0.2062    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7145   -0.6188    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0        0
  2  3  1  4        0
  1  4  1  4        0
M  END
""")
Chem.ReapplyMolBlockWedging(mol)
mol
```
image

# Example 2
### ChemDraw
image

### RDKit
```
mol = Chem.MolFromMolBlock("""double-2.mol
  ChemDraw10192311332D

  4  3  0  0  0  0  0  0  0  0999 V2000
   -0.3572   -0.2062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3572    0.2062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0717    0.6188    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0717   -0.6188    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0        0
  2  3  1  4        0
  1  4  1  4        0
M  END
""")
Chem.ReapplyMolBlockWedging(mol)
mol
```
image

# Example 3
### ChemDraw
image

### RDKit
```
mol = Chem.MolFromMolBlock("""di-imine-2-2000.mol
  ChemDraw10192311522D

  8  7  0  0  0  0  0  0  0  0999 V2000
   -0.9959   -1.0600    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4125   -0.4767    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.4125   -0.4767    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.9959   -1.0600    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7282    0.2855    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9971    1.0600    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7282    0.2855    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.9971    1.0270    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0        0
  2  3  1  0        0
  3  4  1  0        0
  2  5  2  0        0
  5  6  1  4        0
  3  7  2  0        0
  7  8  1  4        0
M  END
""")
Chem.ReapplyMolBlockWedging(mol)
mol
```
image

# Example 4
### ChemDraw
image

### RDKit
```
mol = Chem.MolFromMolBlock("""di-imine-cross-2000.mol
  ChemDraw10192311582D

  8  7  0  0  0  0  0  0  0  0999 V2000
   -1.0099   -1.1129    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5974   -0.3984    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2276   -0.3984    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6401   -1.1129    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8109    0.3984    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.6401    0.3160    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2234    1.1129    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2234    0.8994    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0        0
  2  3  1  0        0
  3  4  1  0        0
  2  5  2  3        0
  3  6  2  3        0
  5  7  1  0        0
  6  8  1  0        0
M  END
""")
Chem.ReapplyMolBlockWedging(mol)
mol
```
image

Example 4 looks correct to me.
In examples 1-3 I believe the crossed bond depicted by RDKit is redundant since the wavy bonds are sufficient to specificy undefined stereochemistry.

### LINKED ISSUE #6893: reapplyMolBlockWedging() should retain ENDDOWNRIGHT, ENDUPRIGHT dirs
**Describe the bug**
(Originally reported by @rvianello)
Currently, CTAB roundtripping of a non-sanitized molecule with a _cis_ or _trans_ double bond fails after `reapplyMolBlockWedging()` is called.
This happens because in the absence of sanitization `aassignStereochemistry()` has not had a chance to mark the double bond stereo as `STEREOCIS` or `STEREOTRANS`. At the same time, `clearSingleBondDirFlags()` clears all bond direction flags on single bonds. Therefore, the molblock is output with the `either` flag set, which should not happen.

**To Reproduce**
```
from rdkit import Chem

molblock = """
     RDKit          2D

  5  4  0  0  0  0  0  0  0  0999 V2000
   -2.4998    2.4772    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.2142    2.0647    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.4998    3.3022    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.2142    3.7147    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.9287    3.3022    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  0
  1  3  2  0
  3  4  1  0
  4  5  1  0
M  END
"""
mol = Chem.MolFromMolBlock(molblock, sanitize=False)
for b in mol.GetBonds():
    print (b.GetIdx(), b.GetBondType(), b.GetStereo(), b.GetBondDir())
0 SINGLE STEREONONE ENDUPRIGHT
1 DOUBLE STEREONONE NONE
2 SINGLE STEREONONE ENDDOWNRIGHT
3 SINGLE STEREONONE NONE ENDUPRIGHT
# here round-tripping works as expected
print(Chem.MolToMolBlock(mol))

     RDKit          2D

  5  4  0  0  0  0  0  0  0  0999 V2000
   -2.4998    2.4772    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.2142    2.0647    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.4998    3.3022    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.2142    3.7147    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.9287    3.3022    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  0
  1  3  2  0
  3  4  1  0
  4  5  1  0
M  END
# roundtripping fails after caling reapplyMolBlockWedging()
Chem.ReapplyMolBlockWedging(mol)
for b in mol.GetBonds():
    print (b.GetIdx(), b.GetBondType(), b.GetStereo(), b.GetBondDir())
0 SINGLE STEREONONE NONE
1 DOUBLE STEREONONE NONE
2 SINGLE STEREONONE NONE
3 SINGLE STEREONONE NONE
# note the 3 flag on the double bond 
print(Chem.MolToMolBlock(mol))

     RDKit          2D

  5  4  0  0  0  0  0  0  0  0999 V2000
   -2.4998    2.4772    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.2142    2.0647    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.4998    3.3022    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.2142    3.7147    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.9287    3.3022    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  0
  1  3  2  3
  3  4  1  0
  4  5  1  0
M  END
```

**Expected behavior**
Round-tripping should work no matter if `reapplyMolBlockWedging()` is called or not.

The fix is to add a `bool` option (defaulting to `false`) to `clearSingleBondDirFlags()` to allow retaining `ENDDOWNRIGHT` and `ENDUPRIGHT` directions on single bonds.

### PR DESCRIPTION
**Pull request by ptosco**
This PR addressees #6816 by making sure that `reapplyMolBlockWedging()` also restores the double bond stereo depiction as originally specified in the molblock, either V2000 (`sss` bond stereo field) or V3000 (through the `CFG` field in the bond block).
Currently, this was happening only partially for the V3000 format, and not at all for the V2000 format.
I added a unit test to make sure things works as expected; here's the gist that I used to set up the unit test:

[Jupyter notebook used for `TEST_CASE("test GitHub6816")` in `Code/GraphMol/Depictor/catch_tests.cpp`](https://gist.github.com/ptosco/aa51700b3fcafa6e0629a638e1f1cc0a)

UPDATE: this PR also fixes #6893, which was found by @rvianello at a later stage.

### CODE REVIEW

**Comment by greglandrum** [comment]
I want to hold off on merging this because there's a fix coming in #6743 which overlaps here.

**Review by tadhurst-cdd — APPROVED** [review]
looks good to me

**Comment by greglandrum** [comment]
@ptosco I think the function `Chirality::shouldBeACrossedBond()` (https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/Chirality.h#L255) added in #6743 provides functionality which you're also adding in this PR

**Comment by ptosco** [comment]
@greglandrum Nope. This PR is about something different: it is not about figuring out which double bonds should be crossed. It is only about undoing the changes made by RDKit and restoring the double bond attributes _exactly_ as they were encoded in the original MDL bond block, no matter if they are sensible or not, as this is what `reapplyMolBlockWedging()` is supposed to do: not trying to be clever, but just stick to what is written in the original bond block.

This first block of changes deals with the V2000 `_MolFileBondStereo` property.
When the double bond MDL `bond stereo` was originally set to 0 (i.e., Use x-, y-, z-coords from atom block to determine
cis or trans) and RDKit set the bond stereo to `Bond::STEREOANY`, we should `setBondDir(Bond::NONE)` and `setStereo(Bond::STEREONONE)`, as the original MDL specification was to not show the bond as crossed.
Instead, when the double bond MDL `bond stereo` was originally set to 3 (i.e., Cis or trans (either) double bond), then the bond should be shown as crossed.
```C++
+      if (b->getBondType() == Bond::DOUBLE) {
+        if (bond_dir == 0 && b->getStereo() == Bond::STEREOANY) {
+          b->setBondDir(Bond::NONE);
+          b->setStereo(Bond::STEREONONE);
+        } else if (bond_dir == 3) {
+          b->setBondDir(Bond::EITHERDOUBLE);
+          b->setStereo(Bond::STEREOANY);
+        }
+      }
```
The second block of changes deals with the case where the`_MolFileBondCfg` property was set to 0 (`CFG=0`), or not set at all (which is the same, as `CFG` defaults to `0`); again in that case the bond should not be set to crossed 
```
+    } else if (bond_dir == -1 && b->getBondType() == Bond::DOUBLE &&
+               b->getStereo() == Bond::STEREOANY) {
+      b->setBondDir(Bond::NONE);
+      b->setStereo(Bond::STEREONONE);
```
The case with `CFG=2` (i.e., either) was already covered by the existing code. What was missing was the case when `CFG=0` (or not specified, which is the same), and RDKit set the bond stereo to `Bond::STEREOANY`; in that case, again we should `setBondDir(Bond::NONE)` and `setStereo(Bond::STEREONONE)`, as the original MDL specification was to not show the bond as crossed.

**Comment by ptosco** [comment]
The two CI failures are not related to this PR

**Review by greglandrum — APPROVED** [review]
LGTM

**Pull request merged**
