### PR TITLE
Potentially chiral bridgehead atoms not being identified.

### LINKED ISSUE #4155: Problem finding potential stereo-centres in bridged bicyclics involving 4-membered rings?
FindPotentialStereo() fails to find centres in bridged bicyclic systems involving a 4-membered ring.
See original rdkit-discuss [here](https://sourceforge.net/p/rdkit/mailman/message/37285715/).

Four test cases are given in the code below:
- Symmetrically-disubstituted 6-membered ring
- A bridged version (using a 1-atom bridge to avoid a completely symmetrical product)
- Symmetrically-disubstituted 4-membered ring
- A bridged version (this time using a 2-atom bridge to avoid symmetry)

```
smi_list = ['CC1CCC(CC1)C(N)=O', 'CC12CCC(CC1)(C2)C(N)=O', 'CC1CC(C1)C(N)=O', 'CC12CC(C1)(CC2)C(N)=O']
for smi in smi_list:
    mol = Chem.MolFromSmiles(smi)
    display(show_mol(mol, size=(450, 200)))  # wrapper function for new drawing code in jupyter
    print(list(Chem.FindPotentialStereo(mol)))
    print(Chem.FindMolChiralCenters(mol, includeUnassigned=True, useLegacyImplementation=False))
```

image

In the case of the bridged 4-membered ring (or bridged 5-membererd ring, depending on your viewpoint!), FindPotentialStereo() fails to identify the two potential stereo atoms (it would be expected to be stereochemically analogous to the other three cases.

 - RDKit version: 2021.03.2
 - OS: Debian GNU/Linux 10 (buster)
 - conda-forge

### PR DESCRIPTION
**Pull request by greglandrum**
removes the shared-bond restriction for potential chiral centers
add support for chiral bridgehead nitrogens

The discussion in the issue has more, but the key change here is being more "permissive" about which centers are potential stereocenters. 
An illustrative example:
image
atoms 2 and 5 are now both considered as possible stereocenters; previously there was a special case which excluded these. The code for this special case wasn't super complex but did have gaps - #4155 shows one of the them - and isn't completely consistent - for example adamantanes were still recognized as having "extra" chiral centers according to the old rules.

With the simplification here the code is now more focused on symmetry and less on what is physically realizable, as suggested by @jepdavison in the original issue.

### CODE REVIEW

**Comment by bp-kelley** [comment]
@greglandrum I'm assuming this may have knock on effects to enumerating stereo + conf generation.  Should that workflow worry about non-physical stereo?

**Comment by bp-kelley** [comment]
i.e. not invert bridge head stereo by default

**Comment by mcs07** [comment]
The `tryEmbedding` option in `EnumerateStereoisomers` gives a way to check for non-physical stereo during enumeration that seems more consistent than a special case rule. But it is slower.

**Comment by greglandrum** [comment]
@bp-kelley : as Matt already indicated, the embedding test can do this already. 
That’s slow and it is definitely worth seeing if we can come up with heuristics to speed that test up; but i haven’t come up with anything there yet. Not part of this PR anyway.

if anything this makes the stereo-enumeration code better because it reduces the number of valid cases that get missed

**Review by bp-kelley — APPROVED** [review]

**Comment by greglandrum** [comment]
@ricrogz, @d-b-w : I know you two are also frequently interested in stereochem related changes: does this look ok to you?

**Comment by ricrogz** [comment]
> @ricrogz, @d-b-w : I know you two are also frequently interested in stereochem related changes: does this look ok to you?

Yeah, Dan mentioned it yesterday and I had a look at it. I think it makes sense.

**Pull request merged**
