### PR TITLE
handle the heavy-atom degree queries differently

### PR DESCRIPTION
**Pull request by greglandrum**
The R-group decomposition PR changed `AdjustQueryParameters::adjustDegree` from bool to int and used the value of the int to determine which type of degree query was added - normal or heavy-atom degree. This was awkward and not backwards compatible.

This PR switches `AdjustQueryParameters::adjustDegree` back to being a bool and adds the new parameter `AdjustQueryParameters::adjustHeavyDegree` to allow heavy-atom degree queries to be added.

### CODE REVIEW

**Comment by greglandrum** [comment]
*sigh*. Hold off on this a bit. Something isn't right.

**Comment by bp-kelley** [comment]
After this is pushed, I'll need to update the RGroupDecomp as well.

**Comment by greglandrum** [comment]
I'll take care of that as part of this PR

**Comment by bp-kelley** [comment]
As an aside, I think I have a way of making these proper smarts queries we may consider at some point.  Currently they can't be smarts-i-fied.

It is alone the lines of for heavy degree 1:

```
>>> m = Chem.MolFromSmiles("CC")
>>> mh = Chem.AddHs(m)
>>> d = Chem.MolFromSmarts("[!#1&X4&H3,!#1&X3&H2,!#1&X2&H1,!#1&X1&H0]")
>>> m.GetSubstructMatches(d)
((0,), (1,))
>>> mh.GetSubstructMatches(d)
((0,), (1,))
```

**Comment by greglandrum** [comment]
The "enumerate the things it's not" approach is a good one. You do have to make some assumptions about possible valence states (not a problem for organics, but stickier for main groups and organometallics) but it's probably the only way to come at it.
Picky one here though: it probably shouldn't start with `!#1`

**Pull request merged**
