### PR TITLE
new file:   Scripts/roundtrip_test.py

### PR DESCRIPTION
**Pull request by UnixJunkie**
#### What does this implement/fix? Explain your changes.
A very simple script to test that we have
rdkit installed and working for Python.

If success, the installed rdkit version is printed out.
Upon failure, if any, we will have an assert failing.

#### Any other comments?
Useful to anyone who has to install rdkit from sources often.

### CODE REVIEW

**Comment by greglandrum** [comment]
I don't really see the usefulness of this script. Anything you write that calls it could achieve the same effect (make sure RDKit is installed correctly) by doing: `python -c 'from rdkit import Chem'`

**Comment by UnixJunkie** [comment]
And does the one liner also checks that rdkit was built inchi support?

**Comment by greglandrum** [comment]
`python -c 'from rdkit import Chem;print(Chem.MolToInchi)`

**Comment by UnixJunkie** [comment]
Ok, fine. I'll put this one-liner somewhere just for myself then.
Also, it still doesn't say the rdkit version that is being used.

**Pull request closed without merging**
