### PR TITLE
Tests for RGD default function failures

### PR DESCRIPTION
**Pull request by jones-gareth**
#### Reference Issue

#3924 (and probably #3896)

#### What does this implement/fix? Explain your changes.

Tests for RGD default scoring.  Added to  `testRGroupDecomp.cpp` explicit tests for the failing decompositions in `testRingMatching3` and `testGeminalRGropups`.  In each a function call to `matchScore` for the desired and actual decomposition is provided.  This provides an easy way to debug the scoring function.

I don't actually fix the scoring function- this is a clear illustration of the issue that can be used as a starting point for debugging.

#### Any other comments?

I'm hoping someone else will pick up fixing the default scoring function.  If no one is able to I can take a look at it.

### CODE REVIEW

**Comment by bp-kelley** [comment]
I'm on it.  Something odd is happening for sure.

**Comment by bp-kelley** [comment]
Here is what I think is happening.  Here is the best scoring match:

```
Scoring permutation  num matches: 3
[22:01:38] Scoring
[22:01:38] Molecule 0 Match coreIdx 0 missing count 2 
	(-6:RG -6 *C([H])([H])C(*)([H])[H])
	(-5:RG -5 *[H])
	(-4:RG -4 *[H])
	(-3:RG -3 *[H])
	(-2:RG -2 *[H])
	(5:RG 5 *[H])
	(6:RG 6 *[H])
[22:01:38] Molecule 1 Match coreIdx 0 missing count 2 
	(-6:RG -6 *C([H])([H])[H].*C([H])([H])[H])
	(-5:RG -5 *[H])
	(-4:RG -4 *[H])
	(-3:RG -3 *[H])
	(-2:RG -2 *[H])
	(5:RG 5 *[H])
	(6:RG 6 *[H])
[22:01:38] Molecule 2 Match coreIdx 0 missing count 2 
	(-6:RG -6 *Cl.*Br)
	(-5:RG -5 *[H])
	(-4:RG -4 *[H])
	(-3:RG -3 *[H])
	(-2:RG -2 *[H])
	(5:RG 5 *[H])
	(6:RG 6 *[H])
```

And here is the match that you are expecting

```
Scoring permutation  num matches: 3
[22:01:35] Scoring
[22:01:35] Molecule 0 Match coreIdx 0 missing count 0 
	(-6:RG -6 *[H])
	(-5:RG -5 *[H])
	(-4:RG -4 *[H])
	(-3:RG -3 *[H])
	(-2:RG -2 *[H])
	(5:RG 5,6 *C([H])([H])C(*)([H])[H])
	(6:RG 5,6 *C([H])([H])C(*)([H])[H])
[22:01:35] Molecule 1 Match coreIdx 0 missing count 0 
	(-6:RG -6 *[H])
	(-5:RG -5 *[H])
	(-4:RG -4 *[H])
	(-3:RG -3 *[H])
	(-2:RG -2 *[H])
	(5:RG 5 *C([H])([H])[H])
	(6:RG 6 *C([H])([H])[H])
[22:01:35] Molecule 2 Match coreIdx 0 missing count 0 
	(-6:RG -6 *[H])
	(-5:RG -5 *[H])
	(-4:RG -4 *[H])
	(-3:RG -3 *[H])
	(-2:RG -2 *[H])
	(5:RG 5 *Br)
	(6:RG 6 *Cl)
```

This later scores worse because simply because more hydrogens are matched in the first one.  Interestingly, these matches are pretty much exactly the same except for reporting issue, i.e. this match incorrectly adds an r-group even when it shouldn't.

I see one thing off the bat

* we should always score user matches before non user ones.  I think because the user labels are negative they come first in the sorting order due to how sets work.  Reversing this will at least match the user label first and help ties.

I'm am a bit unclear how to fix this though.  The scoring function is working as intended but this is a really weird case that will require some thought.

**Comment by bp-kelley** [comment]
Perhaps forcing linker matches to not match the same atom will fix this?

**Comment by bp-kelley** [comment]
@jones-gareth I did a PR against your branch.

**Comment by greglandrum** [comment]
@jones-gareth : just did a PR against your branch to resolve the merge conflict and get the windows DLL builds working.

**Review by greglandrum — APPROVED** [review]

**Comment by jones-gareth** [comment]
@greglandrum @bp-kelley I think was premature to merge this into master.  It is my fault for  merging Brian's changes without commenting, but I was under the impression that he was still working on the ring matching case. The default scoring function still gives the incorrect result for `testRingMatching3Score` in `testRGroupInternals.cpp`:

```cpp
  auto test1 = matchScore(permutation, allMatches1, labels);
  auto test2 = matchScore(permutation, allMatches2, labels);

  // expect test1 to have better score than test2 since all halogens are on R1
  // but this is not the case

  TEST_ASSERT(test1 < test2); // Fix Me!
```

In `testRGroupDecomp.cpp` both `testUserMatchTypes` and `testRingMatching3` will fail if the default scoring function is used.

**Comment by bp-kelley** [comment]
Was this test turned off or was the test incorrect?  I fixed the test that was failing.

**Comment by jones-gareth** [comment]
> 
> 
> Was this test turned off or was the test incorrect? I fixed the test that was failing.

I'd left it in that state- that is passing but with the comment saying it needed to be fixed.  Which was confusing.

**Pull request merged**
