### PR TITLE
Add molecule annotations/notes to MolDraw2D

### PR DESCRIPTION
**Pull request by greglandrum**
Adds the general ability to do molecule annotations based on the `molNote` property:
image
Mol notes are rendered with the same font size as atom labels, not the smaller font size used by atom/bond notes)

Adds an option to add the "ABS" note to renderings when the chiral flag is set:
image

Adds an option to simplify the rendering of molecules where all specified chiral centers are in the same `StereoGroup`. So this rendering:
image
becomes this:
image
The equivalent situation where all atoms are in an `and` group is:
image

### CODE REVIEW

**Comment by bp-kelley** [comment]
@greglandrum some conflicts popped up

**Comment by greglandrum** [comment]
> @greglandrum some conflicts popped up

I'm shocked! Shocked!
;-)

**Comment by greglandrum** [comment]
Conflicts resolved

**Review by DavidACosgrove — APPROVED** [review]
Looks good.

**Comment by gmseabra** [comment]
Thanks a lot for this feature! Does it work with multi-line annotations?

**Pull request merged**
