### PR TITLE
Vdv radii from blue obelisk

### PR DESCRIPTION
**Pull request by UnixJunkie**
related to https://github.com/rdkit/rdkit/issues/1831

### CODE REVIEW

**Comment by UnixJunkie** [comment]
By the way, I have this test code also:
```
import rdkit

from rdkit import Chem

ptable = Chem.GetPeriodicTable()

assert(ptable.GetRvdw(ptable.GetAtomicNumber("H")) == 1.2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("He")) == 1.4)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Li")) == 2.2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Be")) == 1.9)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("B")) == 1.8)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("C")) == 1.7)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("N")) == 1.6)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("O")) == 1.55)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("F")) == 1.5)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Ne")) == 1.54)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Na")) == 2.4)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Mg")) == 2.2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Al")) == 2.1)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Si")) == 2.1)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("P")) == 1.95)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("S")) == 1.8)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Cl")) == 1.8)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Ar")) == 1.88)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("K")) == 2.8)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Ca")) == 2.4)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Sc")) == 2.3)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Ti")) == 2.15)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("V")) == 2.05)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Cr")) == 2.05)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Mn")) == 2.05)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Fe")) == 2.05)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Co")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Ni")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Cu")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Zn")) == 2.1)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Ga")) == 2.1)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Ge")) == 2.1)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("As")) == 2.05)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Se")) == 1.9)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Br")) == 1.9)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Kr")) == 2.02)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Rb")) == 2.9)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Sr")) == 2.55)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Y")) == 2.4)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Zr")) == 2.3)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Nb")) == 2.15)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Mo")) == 2.1)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Tc")) == 2.05)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Ru")) == 2.05)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Rh")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Pd")) == 2.05)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Ag")) == 2.1)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Cd")) == 2.2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("In")) == 2.2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Sn")) == 2.25)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Sb")) == 2.2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Te")) == 2.1)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("I")) == 2.1)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Xe")) == 2.16)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Cs")) == 3)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Ba")) == 2.7)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("La")) == 2.5)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Ce")) == 2.48)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Pr")) == 2.47)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Nd")) == 2.45)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Pm")) == 2.43)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Sm")) == 2.42)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Eu")) == 2.4)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Gd")) == 2.38)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Tb")) == 2.37)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Dy")) == 2.35)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Ho")) == 2.33)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Er")) == 2.32)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Tm")) == 2.3)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Yb")) == 2.28)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Lu")) == 2.27)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Hf")) == 2.25)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Ta")) == 2.2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("W")) == 2.1)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Re")) == 2.05)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Os")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Ir")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Pt")) == 2.05)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Au")) == 2.1)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Hg")) == 2.05)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Tl")) == 2.2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Pb")) == 2.3)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Bi")) == 2.3)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Po")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("At")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Rn")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Fr")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Ra")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Ac")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Th")) == 2.4)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Pa")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("U")) == 2.3)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Np")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Pu")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Am")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Cm")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Bk")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Cf")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Es")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Fm")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Md")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("No")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Lr")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Rf")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Db")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Sg")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Bh")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Hs")) == 2)
assert(ptable.GetRvdw(ptable.GetAtomicNumber("Mt")) == 2)
```

It tests that the new values are taken into account.

**Comment by UnixJunkie** [comment]
Is this good; Travis on Linux:
96% tests passed, 6 tests failed out of 156

**Comment by UnixJunkie** [comment]
```
The following tests FAILED:
	 98 - testDistGeomHelpers (Child aborted)
	 99 - pyDistGeomHelpers (Failed)
	104 - testShapeHelpers (Child aborted)
	105 - pyShapeHelpers (Failed)
	129 - pyGraphMolWrap (Failed)
	155 - pythonTestDirChem (Failed)
```

**Comment by gedeck** [comment]
I would rewrite the test code like this:
```
ptable = Chem.GetPeriodicTable()

expected = {
  'H': 1.2, 'He': 1.4,
  'Li': 2.2, 'Be': 1.9, ...
}
for name, radius in expected.items():
  assert(ptable.GetRvdw(ptable.GetAtomicNumber(name)) == radius)
```

**Comment by UnixJunkie** [comment]
Should the code be added somewhere in the repository?

**Comment by greglandrum** [comment]
Just a clear update on why this hasn't been merged yet... sorry that I haven't done anything so far.
Because these radii are used in the conformation generation process, this changes the conformations that are generated. That will have an impact on conformer quality, which is something we've published on and I want to be very careful about. 

This PR may well improve things, but until someone has time to do a thorough analysis, I don't want to merge these changes.

I will try to do the validation work before we do the 2019.09 release so that we can start using these better-documented values.

**Comment by UnixJunkie** [comment]
I'm fine with this and I understand.

**Comment by greglandrum** [comment]
@sriniker and I have spent some time looking at the impact this has on conformation generation. I'll share the results of what I did and she'll add some additional info later.

I used the Platinum dataset of PDB structures as a reference and compared the results generated with the new vdW parameters with the results from the older parameters. The full details are here: https://gist.github.com/greglandrum/2a0d90365caf3a57d733b2fd722f34d0

Here's the change for DG conformations (new results on Y, old results on X):
image

And for ETKDG:
image

The take home from this for me at least is that the new radius parameters don't have a significant impact on conformation quality in either direction. I think thinks means that it's fine to merge it (after I update the expected results in the tests)

**Comment by UnixJunkie** [comment]
Thanks for the thorough testing.

**Comment by sriniker** [comment]
I checked the performance of the new vdW radii versus the current ones for the two datasets in the ETKDG paper. Below are the results for ETKDG version 2. As with the Platinum dataset, there is no significant impact of the new vdW radii.

CSD dataset (1290 compounds):
image

PDB dataset (238 compounds):
image

**Comment by greglandrum** [comment]
@UnixJunkie : I have created a PR against your branch that should have the changes to get the tests working again. If you merge that PR, it will update this one. That will cause the CI tests to run again and, if they pass, I'll merge here.

**Comment by UnixJunkie** [comment]
OK, I merged it.

**Comment by greglandrum** [comment]
This is now passing the tests, so I'm going to merge it. Post merge I will add something to the Release Notes about the change in results.

**Comment by greglandrum** [comment]
Thanks for the contribution @UnixJunkie!

**Pull request merged**
