### PR TITLE
Enable optional visualization of complex query atoms in a more compact form

### PR DESCRIPTION
**Pull request by ptosco**
This PR adds a new `useComplexQueryAtomSymbols` boolean option to `MolDrawOptions` to enable a more compact visualization of certain complex atom queries supported by MDL molblocks and CXSMILES, e.g.:

```
from rdkit import Chem
from rdkit.Chem.Draw import IPythonConsole

mol = Chem.MolFromMolBlock("""
  MJ201100                      

  6  6  0  0  0  0  0  0  0  0999 V2000
   -1.7633    0.8919    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.4778    0.4794    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.4778   -0.3456    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7633   -0.7580    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0488   -0.3456    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0488    0.4794    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
  3  4  1  0  0  0  0
  4  5  1  0  0  0  0
  1  6  1  0  0  0  0
  5  6  1  0  0  0  0
M  END
""")

# current depiction (that I maintained as default)
mol
```
image

```
# with useComplexQueryAtomSymbols set to True
IPythonConsole.drawOptions.useComplexQueryAtomSymbols = True
mol
```
image

or
```
mol = Chem.MolFromMolBlock("""
  MJ201100                      

  7  7  0  0  0  0  0  0  0  0999 V2000
   -2.1205    2.4545    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.8349    2.0420    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.8349    1.2169    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1205    0.8044    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4060    1.2169    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4060    2.0420    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6916    0.8044    0.0000 X   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
  2  3  1  0  0  0  0
  3  4  2  0  0  0  0
  6  1  1  0  0  0  0
  4  5  1  0  0  0  0
  5  6  2  0  0  0  0
  5  7  1  0  0  0  0
M  END
""")

# current depiction (that I maintained as default)
mol
```
image

```
# with useComplexQueryAtomSymbols set to True
IPythonConsole.drawOptions.useComplexQueryAtomSymbols = True
mol
```
image

### CODE REVIEW

**Comment by ptosco** [comment]
@greglandrum Good point - done (and tested).

**Review by greglandrum — APPROVED** [review]
LGTM
I do think that it's worth considering enabling this option by default.

**Comment by greglandrum** [comment]
@DavidACosgrove do you think it makes sense to enable this by default?

**Comment by DavidACosgrove** [comment]
Yes, makes sense.  I wonder how often Astatine is a hit?

**Pull request merged**
