### PR TITLE
I2366 Preserve enhanced stereo in reactions

### LINKED ISSUE #2366: Preserve Enhanced Stereochemistry information through reactions
**Description:**
It would be useful to be able to preserve enhanced/extended/relative stereochemistry through reactions. This should include proper invalidation of enhanced stereochemistry when required.

I'm actively working on this.

The difficult bit here is basically "when should enhanced stereochemistry information be copied from reactants to products"?

I think that a stereogroup should be copied from reactant to product if:
* All atoms in the stereogroup end up in the same molecule in the product
* No atom in the stereogroup changed number of connections
* All atoms in the stereogroup have defined stereochemistry in the product
* If a reactant is duplicated in the product, these should be considered separate stereo groups.

I don't have any sourcing for these intuitions, and so am flexible about the copying rules.

I'm actively working on this.

### PR DESCRIPTION
**Pull request by d-b-w**
#### Reference Issue
Fixes #2366 

#### What does this implement/fix? Explain your changes.
Copies `StereoGroup`s from reactant to product in reactions.

_Details:_
Atoms in a `StereoGroup` are copied to the product if the reaction does not create
or destroy the stereochemistry of that atom (inversions are fine). Atoms that are
duplicated in the product are put in the same `StereoGroup`.

Uses `ChiralTag` and `molInversionFlag` to decide whether the stereochemistry
of each atom in the `StereoGroup` was destroyed or defined by the reaction,
respectively.

#### Any other comments?
The Python tests associated with this PR are pretty extensive, and should also serve to document the intended behavior.

Also includes an update to the EnhancedStereo.md documentation.

Thanks to Greg, Michael Braden, and Trip Garland for important insights about the appropriate behavior of relative stereochemical markers through reactions.

### CODE REVIEW

**Comment by greglandrum** [comment]
After the offline discussion, I think it makes sense to go with the "possible implementation" here.

**Comment by greglandrum** [comment]
I made a few suggestions via PR against your branch.

**Comment by greglandrum** [comment]
Since I did include something about enhanced stereo in the main documentation, it's probably also a good idea to add the reaction paragraph here: https://github.com/rdkit/rdkit/blob/master/Docs/Book/RDKit_Book.rst#support-for-enhanced-stereochemistry

**Comment by d-b-w** [comment]
I've added a note to RDKit_book.rst. I decided to add it in the enhanced stereo section, not the reactions section.

**Comment by greglandrum** [comment]
makes sense to me
I think this is ready to merge. Any other last-minute additions?

**Comment by d-b-w** [comment]
I think I'm also satisfied with it. Thanks!

**Pull request merged**
