### PR TITLE
RWMol.clear() should reset the numBonds count.

### PR DESCRIPTION
**Pull request by johnmay**
NumBonds needs to be reset in clear(). This has been around for a while (Nov 16?) and took Noel a couple of days to track down.

### CODE REVIEW

**Comment by johnmay** [comment]
Might also want to update 
```
unsigned int ROMol::getNumBonds(bool onlyHeavy) const {
}
```
To use the variable if it can.

**Comment by johnmay** [comment]
Sorry couldn't add test case as did the PR via GitHub editor.

**Comment by johnmay** [comment]
Roger points out you should able to remove all places where the boost num_edges is called, for example the copy constructor.

**Comment by greglandrum** [comment]
I had just figured that doing the C++ was making your eyes burn. :-)

**Comment by johnmay** [comment]
Adding details here as well:

All good - the reason we actually had the issue and was tricky to track down was the numBonds value was used to set the bond index and did not reflect the value returned by ``getNumBonds()``.
 The index values could therefore exceed the bond count - causing a seg fault (or assertion failure in debug mode).

```c++
RWMol mol;
// load molecule with something
mol.clear();
// load molecule with something containing a ring
// sanitize (FindRings breaks due to assertion in boost about bit set size)
```

Essentially in the ring finding code a bitset was created using (``mol.getNumBonds()``) but then the bits were accessed using ``bond.getIdx()``;

**Comment by baoilleach** [comment]
Here's a possibly simpler test:
```
RWMol mol;
unsigned int a0 = mol.addAtom();
unsigned int a1 = mol.addAtom();
mol.addBond(a0, a1);
mol.clear();
a0 = mol.addAtom();
a1 = mol.addAtom();
unsigned int b0 = mol.addBond(a0, a1);
assert (b0 < mol.getNumBonds());
```
The assert fails.

**Comment by johnmay** [comment]
@greglandrum I think you'll also need to watch out for bond deletions? That would cause problems now right.

**Comment by baoilleach** [comment]
Actually, @johnmay, there is a --numBonds at the end of removeBond(), so I think that's fine.

**Comment by bp-kelley** [comment]
As the one partly responsible, I'll help sprinkle num bonds testing where appropriate.  I obviously missed the clear.

FYI: this optimization was added because the old implementation was o(n) which caused massive slowdowns in creating proteins.

----
Brian Kelley

**Comment by johnmay** [comment]
```
++numBonds;
b->setIdx(numBonds - 1);
```

```
b->setIdx(numBonds++);
```

:-)

**Comment by greglandrum** [comment]
My commit dc6bd62 (to use the numBonds member in `getNumBonds()`) makes me super nervous and would require a bunch of additional testing.
I'd suggest we roll that back, merge @johnmay 's changes as originally proposed (with the test I added) and then do a separate PR with the `getNumBonds()` optimization and associated tests.

**Comment by bp-kelley** [comment]
John, Bond deletions are handled correctly it seems.

**Comment by johnmay** [comment]
> My commit dc6bd62 (to use the numBonds member in getNumBonds()) makes me super nervous and would require a bunch of additional testing. I'd suggest we roll that back, merge @johnmay 's changes as originally proposed (with the test I added) and then do a separate PR with the getNumBonds() optimization and associated tests.

Sounds good, but maybe use a test checking the ``bond->GetIdx()`` instead of ``mol->getNumBonds()`` as it will actually change before/after patch.

**Comment by bp-kelley** [comment]
@greglandrum I think we can close this now without merging?

**Comment by greglandrum** [comment]
Agreed. #1463 replaces it.

**Pull request closed without merging**
