### PR TITLE
add Draw.MolsToSVGGrid()

### PR DESCRIPTION
**Pull request by greglandrum**
This assembles the final svg using regexp operations instead of parsing the xml and working directly with the tree.

I think it's ok to do things this way, and suspect that it ends up being faster, but it's probably possible to do things differently if someone else thinks this is horrible.

### CODE REVIEW

**Comment by bp-kelley** [comment]
Ah, you beat me to it :)

Can you make IPythonConsole use this function when use_svg is true?

**Comment by greglandrum** [comment]
Not sure what you mean. This is the equivalent of MolsToImageGrid, which
also has to be explicitly called.

**Comment by bp-kelley** [comment]
I see the issue, there is an option in IPythonConsole to use_svg for the default molecule renderer.  It would be nice if this also altered the default behavior of molstogridimage but I can see that being problematic...

----
Brian Kelley

**Comment by greglandrum** [comment]
Yeah, that's a specific Python function, not part of the IPython
integration.
We could add a new IPython function: DisplayMols() (or something like that)
that picks either PNG or SVG and does the right thing though.

**Comment by bp-kelley** [comment]
Would it make sense to add a target type to molstogridimage?  I.e svg, png...

We could then use some Python magic to reset the default arg so old notebooks could still work and get prettier ...

I can prototype this in another pull request.

----
Brian Kelley

**Comment by greglandrum** [comment]
That could certainly work.
I'll try to get that change done this morning.

**Comment by greglandrum** [comment]
Ok, `MolsToGridImage()` can now return either SVG or the PIL Image it's been using.
I also modified the IPythonConsole integration so that SVG is rendered properly.

**Pull request merged**
