### PR TITLE
Added rankAtoms to ROMol wrapper and added Java test case

### PR DESCRIPTION
**Pull request by sroughley**
This enhancement adds the `rankMolAtoms()` from `new_canon.h` to the Java wrapper of the ROMol object. Currently, the canonical ranks are only available via a call to `ROMol#MolToSmiles()` followed by parsing atom or molecule properties

### CODE REVIEW

**Comment by bp-kelley** [comment]
There is something wrong with the java tests, have you successfully run them outside of the travis environment?

**Comment by greglandrum** [comment]
@sroughley : sorry that this one got lost...
Once the CI builds pass I will merge it.

**Comment by sroughley** [comment]
Thanks @greglandrum  - must admit, I had forgotten about this one too!

**Comment by greglandrum** [comment]
Looks like there's still something wrong with the tests. I'll fix it today.

**Comment by greglandrum** [comment]
Thanks @sroughley !

**Pull request merged**
