### PR TITLE
Added getAlignmentTransform to ROMol.i to expose in Java SWIG wrapper

### PR DESCRIPTION
**Pull request by sroughley**
Adding this method to the Java wrappers will allow RMSD calculations without the need to actually align the probe conformation to the reference

### CODE REVIEW

**Comment by bp-kelley** [comment]
We should probably add a test as well.

**Comment by sroughley** [comment]
Brian,

Definitely should add a test case.  I have just modified to use assertEquals with a tolerance argument.

Steve

**Comment by greglandrum** [comment]
Thanks Steve.

**Comment by sroughley** [comment]
No problem - thanks Greg!

**Pull request merged**
