### PR TITLE
Correct unbranched alkane SMARTS to match the description given

### PR DESCRIPTION
**Pull request by ghost**
Must restrict to only carbon and allow for terminal alkanes

### CODE REVIEW

**Review by greglandrum — CHANGES_REQUESTED** [review]
@levineds-meta the change makes sense to me (thanks for catching this!), but given that this is going to change the results of the descriptor calculation, there should be a mention of it in the "Backwards Incompatible changes" section of `ReleaseNotes.md`

Could you please add that?

**Comment by levineds** [comment]
@greglandrum Can you take another look at this?

**Comment by greglandrum** [comment]
> @greglandrum Can you take another look at this?

@levineds sorry I was so slow there. I just made a PR against your branch with my very minor suggested change and a merge to the current status of master. If you merge that PR, this one will automatically update and I will approve and merge it.

**Comment by levineds** [comment]
Thanks, Greg. Merged now.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
> Thanks, Greg. Merged now.

Great. I will merge this after the CI builds finish

**Comment by greglandrum** [comment]
Thanks for the contribution @levineds

**Pull request merged**
