### PR TITLE
Adds pickling of properties (optional)

### PR DESCRIPTION
**Pull request by bp-kelley**
Beta setup of property-pickling at the base level.  This is somewhat informational, but it would be nice to get feedback of the API and utility.

### CODE REVIEW

**Comment by greglandrum** [comment]
@bp-kelley: I will take a look over the holidays (sorry this got lost)

**Comment by bp-kelley** [comment]
Looks like I broke Java, I'll need to take a look.

**Comment by bp-kelley** [comment]
@greglandrum Looks like it works now, but I can't say I like the commit history.  Should I pull out my patches and reapply?

**Comment by bp-kelley** [comment]
@greglandrum Yeah, I'll do that for both our sanities sake.

**Pull request closed without merging**
