### PR TITLE
Fixes #6773

### LINKED ISSUE #6773: MCS query incorrect when ringCompare=RingCompare.StrictRingFusion
**Describe the bug**
The MCS returned when `ringCompare=RingCompare.StrictRingFusion` may not match all molecules used to generate it. This is new since https://github.com/rdkit/rdkit/pull/6646 . I'm currently using 0a3fe925288c.

**To Reproduce**

```
from rdkit import Chem
from rdkit.Chem.Draw import IPythonConsole
from rdkit.Chem import rdFMCS

IPythonConsole.ipython_useSVG = True

from rdkit import Chem
from rdkit.Chem.Draw import IPythonConsole
from rdkit.Chem import rdFMCS

IPythonConsole.ipython_useSVG = True

mol1 = Chem.MolFromSmiles('Oc1ccc2ccccc2c1')
mol2 = Chem.MolFromSmiles('Oc1cccc2ccccc12')
mcs = rdFMCS.FindMCS([mol1, mol2],
    ringMatchesRingOnly=True,
    # The problem is the ring fusion.
    ringCompare=Chem.rdFMCS.RingCompare.StrictRingFusion)

print('I think this is wrong, the ring fusion seems to have "slipped"')
print('I think the right MCS if ring fusion count is strict is maybe `[#8!R]`')
print(mcs.smartsString)
print(mol1.GetSubstructMatch(mcs.queryMol))
print(mol2.GetSubstructMatch(mcs.queryMol), '<<<< this should match!!')
IPythonConsole.ShowMols((mol1, mol2))

# Previous to https://github.com/rdkit/rdkit/pull/6646, the MCS here was
old_mcs = '[#8&!R]-&!@[#6&R]1:&@[#6&R]:&@[#6&R]:&@[#6&R]:&@[#6&R](:&@[#6&R]:&@1):&@[#6&R]:&@[#6&R]:&@[#6&R]'
# which seems wrong because it doesn't require ring fusion matching.
# but at least it matches both mols??
old_mcs_mol = Chem.MolFromSmarts(old_mcs)
print(mol1.GetSubstructMatch(old_mcs_mol))
print(mol2.GetSubstructMatch(old_mcs_mol))
```

Here's the above in a Jupyter notebook:

mcs_bug

Other context:
This was reported deep inside some internal Schrödinger validation code (PRIME-5144). Definitely let me know if I'm using StrictRingFusion incorrectly.

### PR DESCRIPTION
**Pull request by ptosco**
This PR fixes #6773.
There was a flaw in the logic to generate the ring queries when `BondCompareParameters.MatchFusedRingsStrict` is `true`.
Upon further testing I realized that `Rn` queries with _n_>1 should rather be `R&!R1` as different molecules may have different fusions and the query needs to capture all of them.

Now the test molecules in #6773 yield the expected result (note that by default `CompleteRingsOnly` is set to `False`):
```
from rdkit import Chem
from rdkit.Chem.Draw import IPythonConsole, MolsToGridImage
from rdkit.Chem import rdFMCS

IPythonConsole.ipython_useSVG = True
IPythonConsole.drawOptions.addAtomIndices = True

def get_bond_matches(atom_idx_matches, mol, query):
    inverse_match = [None] * mol.GetNumAtoms()
    for i, atom_idx in enumerate(atom_idx_matches):
        inverse_match[atom_idx] = i
    res = []
    for b in mol.GetBonds():
        bi = b.GetBeginAtomIdx()
        ei = b.GetEndAtomIdx()
        if (bi in atom_idx_matches and ei in atom_idx_matches
            and query.GetBondBetweenAtoms(inverse_match[bi], inverse_match[ei])):
            res.append(b.GetIdx())
    return tuple(res)

mol1 = Chem.MolFromSmiles('OC1CCC2CCCCC2C1')
mol2 = Chem.MolFromSmiles('OC1CCCC2CCCCC12')
mols = [mol1, mol2]

print(f"mcs.numAtoms {mcs.numAtoms} mcs.numBonds {mcs.numBonds}")
print(mcs.smartsString)
atom_matches = [m.GetSubstructMatch(mcs.queryMol) for m in mols]
bond_matches = [get_bond_matches(am, mols[i], mcs.queryMol) for i, am in enumerate(atom_matches)]
for i, m in enumerate(mols):
    print(f"mol{i+1} atom_matches {atom_matches[i]} bond_matches {bond_matches[i]}")
MolsToGridImage(mols, highlightAtomLists=atom_matches, highlightBondLists=bond_matches)

mcs.numAtoms 11 mcs.numBonds 11
[#8&!R]-&!@[#6&R]1-&@[#6&R]-&@[#6&R]-&@[#6&R]-&@[#6&R](-&@[#6&R]-&@1)-&@[#6&R]-&@[#6&R]-&@[#6&R]-&@[#6&R]
mol1 atom_matches (0, 1, 2, 10, 3, 9, 4, 8, 7, 6, 5) bond_matches (0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11)
mol2 atom_matches (0, 1, 2, 10, 3, 5, 4, 6, 7, 8, 9) bond_matches (0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11)
params = rdFMCS.MCSParameters()
params.BondCompareParameters.RingMatchesRingOnly = True
params.AtomCompareParameters.RingMatchesRingOnly = True
params.BondCompareParameters.MatchFusedRingsStrict = True
```
image
```
mcs.queryMol
```
image
This what you get when you add a third molecule with different ring sizes:
```
mol3 = Chem.MolFromSmiles('OC1CCC2CCCCCC12')
mols = [mol1, mol2, mol3]
mcs = rdFMCS.FindMCS(mols, params)
print(f"mcs.numAtoms {mcs.numAtoms} mcs.numBonds {mcs.numBonds}")
print(mcs.smartsString)
atom_matches = [m.GetSubstructMatch(mcs.queryMol) for m in mols]
bond_matches = [get_bond_matches(am, mols[i], mcs.queryMol) for i, am in enumerate(atom_matches)]
for i, m in enumerate(mols):
    print(f"mol{i+1} atom_matches {atom_matches[i]} bond_matches {bond_matches[i]}")
MolsToGridImage(mols, highlightAtomLists=atom_matches, highlightBondLists=bond_matches)

mcs.numAtoms 10 mcs.numBonds 9
[#8&!R]-&!@[#6&R](-&@[#6&R]-&@[#6&R])-&@[#6&R]-&@[#6&R]-&@[#6&R]-&@[#6&R]-&@[#6&R]-&@[#6&R]
mol1 atom_matches (0, 1, 2, 10, 3, 9, 8, 7, 6, 5) bond_matches (0, 1, 2, 5, 6, 7, 8, 9, 10)
mol2 atom_matches (0, 1, 2, 10, 3, 9, 8, 7, 6, 5) bond_matches (0, 1, 2, 5, 6, 7, 8, 9, 10)
mol3 atom_matches (0, 1, 2, 10, 3, 9, 8, 7, 6, 5) bond_matches (0, 1, 2, 5, 6, 7, 8, 9, 10)
```
image
If we set `CompleteRingsOnly` to `True`, the MCS is decalin with the first two molecules;
```
mols = [mol1, mol2]
params.BondCompareParameters.CompleteRingsOnly = True
params.AtomCompareParameters.CompleteRingsOnly = True
mcs = rdFMCS.FindMCS(mols, params)
print(f"mcs.numAtoms {mcs.numAtoms} mcs.numBonds {mcs.numBonds}")
print(mcs.smartsString)
atom_matches = [m.GetSubstructMatch(mcs.queryMol) for m in mols]
bond_matches = [get_bond_matches(am, mols[i], mcs.queryMol) for i, am in enumerate(atom_matches)]
for i, m in enumerate(mols):
    print(f"mol{i+1} atom_matches {atom_matches[i]} bond_matches {bond_matches[i]}")
MolsToGridImage(mols, highlightAtomLists=atom_matches, highlightBondLists=bond_matches)

mcs.numAtoms 10 mcs.numBonds 11
[#6&R]1-&@[#6&R]-&@[#6&R]-&@[#6&R&!R1]2-&@[#6&R&!R1](-&@[#6&R]-&@1)-&@[#6&R]-&@[#6&R]-&@[#6&R]-&@[#6&R]-&@2
mol1 atom_matches (1, 2, 10, 3, 9, 8, 4, 7, 5, 6) bond_matches (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)
mol2 atom_matches (2, 3, 1, 4, 10, 9, 5, 8, 6, 7) bond_matches (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)
```
image
When we add the third molecule, MCS is methanol:
```
mols = [mol1, mol2, mol3]
mcs = rdFMCS.FindMCS(mols, params)
print(f"mcs.numAtoms {mcs.numAtoms} mcs.numBonds {mcs.numBonds}")
print(mcs.smartsString)
atom_matches = [m.GetSubstructMatch(mcs.queryMol) for m in mols]
bond_matches = [get_bond_matches(am, mols[i], mcs.queryMol) for i, am in enumerate(atom_matches)]
for i, m in enumerate(mols):
    print(f"mol{i+1} atom_matches {atom_matches[i]} bond_matches {bond_matches[i]}")
MolsToGridImage(mols, highlightAtomLists=atom_matches, highlightBondLists=bond_matches)

mcs.numAtoms 2 mcs.numBonds 1
[#8&!R]-&!@[#6&R]
mol1 atom_matches (0, 1) bond_matches (0,)
mol2 atom_matches (0, 1) bond_matches (0,)
mol3 atom_matches (0, 1) bond_matches (0,)
```
image

While writing unit tests for #6773 I also noticed a bug in `checkIfRingsAreClosed` when `noLoneRingAtoms` is `true`, and I fixed that as well; now I get the expected result with this test case:
```
smi = ["C1CC2CCC3CC2C(C1)CCCCCC3", "C1CC2CCC3CCCC4CCC(C1)C2C34"]
mols = [Chem.MolFromSmiles(s) for s in smi]
params = rdFMCS.MCSParameters()
params.BondCompareParameters.MatchFusedRingsStrict = True
mcs = rdFMCS.FindMCS([mols[0], mols[1]], params)
print(f"mcs.numAtoms {mcs.numAtoms} mcs.numBonds {mcs.numBonds}")
print(mcs.smartsString)
atom_matches = [m.GetSubstructMatch(mcs.queryMol) for m in mols]
bond_matches = [get_bond_matches(am, mols[i], mcs.queryMol) for i, am in enumerate(atom_matches)]
for i, m in enumerate(mols):
    print(f"mol{i+1} atom_matches {tuple(enumerate(atom_matches[i]))} bond_matches {tuple(enumerate(bond_matches[i]))}")
MolsToGridImage(mols, highlightAtomLists=atom_matches, highlightBondLists=bond_matches)

mcs.numAtoms 15 mcs.numBonds 16
[#6]1-&@[#6]-&@[#6&R&!R1]2-&@[#6]-&@[#6]-&@[#6](-&@[#6]-&@[#6&R&!R1]-&@2-&@[#6](-&@[#6]-&@1)-&@[#6]-&@[#6])-&@[#6]-&@[#6]-&@[#6]
mol1 atom_matches ((0, 0), (1, 1), (2, 9), (3, 2), (4, 3), (5, 7), (6, 4), (7, 6), (8, 8), (9, 5), (10, 10), (11, 15), (12, 11), (13, 14), (14, 13)) bond_matches ((0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 13), (12, 14), (13, 15), (14, 16), (15, 17))
mol2 atom_matches ((0, 0), (1, 1), (2, 13), (3, 2), (4, 3), (5, 14), (6, 4), (7, 15), (8, 12), (9, 5), (10, 11), (11, 6), (12, 10), (13, 7), (14, 8)) bond_matches ((0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 10), (9, 11), (10, 12), (11, 13), (12, 14), (13, 15), (14, 16), (15, 17))
```
image
```
params.BondCompareParameters.CompleteRingsOnly = True
params.AtomCompareParameters.CompleteRingsOnly = True
mcs = rdFMCS.FindMCS([mols[0], mols[1]], params)
print(f"mcs.numAtoms {mcs.numAtoms} mcs.numBonds {mcs.numBonds}")
print(mcs.smartsString)
atom_matches = [m.GetSubstructMatch(mcs.queryMol) for m in mols]
bond_matches = [get_bond_matches(am, mols[i], mcs.queryMol) for i, am in enumerate(atom_matches)]
for i, m in enumerate(mols):
    print(f"mol{i+1} atom_matches {tuple(enumerate(atom_matches[i]))} bond_matches {tuple(enumerate(bond_matches[i]))}")
MolsToGridImage(mols, highlightAtomLists=atom_matches, highlightBondLists=bond_matches)

mcs.numAtoms 10 mcs.numBonds 11
[#6&R]1-&@[#6&R]-&@[#6&R&!R1]2-&@[#6&R]-&@[#6&R]-&@[#6&R]-&@[#6&R]-&@[#6&R&!R1]-&@2-&@[#6&R]-&@[#6&R]-&@1
mol1 atom_matches ((0, 0), (1, 1), (2, 9), (3, 2), (4, 3), (5, 7), (6, 4), (7, 6), (8, 8), (9, 5)) bond_matches ((0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 15), (10, 16))
mol2 atom_matches ((0, 0), (1, 1), (2, 13), (3, 2), (4, 3), (5, 14), (6, 4), (7, 15), (8, 12), (9, 5)) bond_matches ((0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 12), (6, 13), (7, 14), (8, 15), (9, 16), (10, 17))
```
image

Finally, I created the `RingBondCountVect` class as it is much tidier than passing around the same `std::vector<BondCount>&` and `consrt ROMol&` across multiple functions (which are now member functions of `RingBondCountVect`).

@d-b-w It would be great if you could check this against your additional test cases. Thanks in advance!

### CODE REVIEW

**Comment by d-b-w** [comment]
I'm compiling now to test

**Comment by rachelnwalker** [comment]
@d-b-w asked me to take a look at this as well. I just have the same question on whether `&!R1` is necessary since it is only added when a query atom is in >1 topological ring

**Comment by ptosco** [comment]
@d-b-w @rachelnwalker Sorry for the delay - I have come down with COVID and only recovered today. Dan’s point is a valid one, and indeed there are other redundant queries that can be removed (and more useful ones to be added). I have also found and fixed another bug. Tomorrow I should be able to submit a revised PR.

**Comment by ptosco** [comment]
@d-b-w @rachelnwalker I have submitted the updated PR over the weekend; here follow my replies to your comments.

> I've run this over my examples, and the results match my expectations! Thanks! In particular, I see the ring closures in the MCS queryMol, which is what I was hoping to get by using StrictRingFusion. I'll start looking through implementation next.

Great, thanks for confirming that this works for you too.

> After this change, how would you describe the functional difference between StrictRingFusion and PermissiveRingFusion?

This PR actually does not affect the functional difference between `StrictRingFusion` and `PermissiveRingFusion`, which has not changed. I think that the large majority of users are interested in `StrictRingFusion`; `PermissiveRingFusion` may have a role in specific cases, particularly when computing MCS between two molecules only.
In a nutshell, in the following I'll try and clarify the difference between `StrictRingFusion` and `PermissiveRingFusion`.
When the MCS algorithm carries out pairwise comparisons between query and target molecules, ring fusion may be ignored (the default), or enforced. Enforcement can happen in two different ways: in `StrictRingFusion`, _both_ molecules are required not to be missing any fusion bond; in `PermissiveRingFusion` _one_ of the two molecules in the pair is allowed to be missing fusion bonds, but _not both_.
Please find an example below:

### Default (`ringCompare=rdFMCS.RingCompare.IgnoreRingFusion`)
```
smi = ["NC(=O)CCCC1C2CC3CCCCC3C12", "NC(=O)CCCC1CCCC2CCCCC12"]
mols = [Chem.MolFromSmiles(s) for s in smi]
mcs = rdFMCS.FindMCS(mols, completeRingsOnly=True)
display_mcs(mcs, mols)

mcs.numAtoms 16 mcs.numBonds 16
[#7]-&!@[#6](=&!@[#8])-&!@[#6]-&!@[#6]-&!@[#6]-&!@[#6]1-&@[#6]-&@[#6]-&@[#6]-&@[#6]-&@[#6]-&@[#6]-&@[#6]-&@[#6]-&@[#6]-&@1
mol1 atom_matches (0, 1, 2, 3, 4, 5, 6, 7, 15, 8, 14, 9, 13, 10, 12, 11) bond_matches (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
mol2 atom_matches (0, 1, 2, 3, 4, 5, 6, 7, 15, 8, 14, 9, 13, 10, 12, 11) bond_matches (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
```
image

This is the default RDKit behavior with `completeRingsOnly=True`: ring fusion is not considered, and since the two ring systems share a closed ring envelope of the same size; this is returned as the MCS together with the side chain.

### Permissive ring fusion (`ringCompare=rdFMCS.RingCompare.PermissiveRingFusion`)
```
mcs = rdFMCS.FindMCS(mols, completeRingsOnly=True, ringCompare=rdFMCS.RingCompare.PermissiveRingFusion)
display_mcs(mcs, mols)

mcs.numAtoms 12 mcs.numBonds 12
[#7]-&!@[#6](=&!@[#8])-&!@[#6]-&!@[#6]-&!@[#6]-&!@[#6]1-&@[#6]-&@[#6]-&@[#6]-&@[#6]-&@[#6]-&@1
mol1 atom_matches (0, 1, 2, 3, 4, 5, 6, 7, 15, 8, 14, 9) bond_matches (0, 1, 2, 3, 4, 5, 6, 7, 8, 14, 15, 17)
mol2 atom_matches (0, 1, 2, 3, 4, 5, 6, 7, 15, 8, 10, 9) bond_matches (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 16)
```
image

`PermissiveRingFusion` leads to a smaller MCS: the whole decalin envelope is not an option as it neglects fusion in _both_ molecules. However, a cyclohexane ring can be part of the MCS since it only neglects ring fusion in _one_ of the molecules.

### Strict ring fusion (`ringCompare=rdFMCS.RingCompare.StrictRingFusion`)
```
mcs.numAtoms 7 mcs.numBonds 6
[#7]-&!@[#6](=&!@[#8])-&!@[#6]-&!@[#6]-&!@[#6]-&!@[#6]
mol1 atom_matches (0, 1, 2, 3, 4, 5, 6) bond_matches (0, 1, 2, 3, 4, 5)
mol2 atom_matches (0, 1, 2, 3, 4, 5, 6) bond_matches (0, 1, 2, 3, 4, 5)
```
image

Enforcing `StrictRingFusion` removes all rings from MCS, since none can be included while honoring ring fusion in _both_ molecules.

> It looks to me like the queryMol/smartsString includes a ring count expression for StrictRingFusion. However, because the topology of the query already includes multiple rings, I don't understand how the &!R1 could ever affect results.
There were indeed a number of redundant ring queries that are unnecessary; this had already been pointed out by @greglandrum to me before (something along the lines of "all those ring queries that you added to MCS results look horrible" during an RDKit UGM coffee break ;-) ) and I have now left them only where they are needed. Additionally, based on point (2) discussed below, I have added useful ring size queries that enable MCS results returned when `MatchRingFusionStrict=True` to match only where they should.

# The issues I found and fixed while writing these examples
While writing these examples, I found two more issues, one bug and one improvement, that I will describe below:

## (1) Bug: `CompleteRingsOnly` would still return incomplete rings under certain circumstances
I found out that RDKit was yielding the wrong MCS with this pair of molecules:
```
smi = ["C1CCC2CCCCC2C1", "C1CC2CCCC2C1"]
mols = [Chem.MolFromSmiles(s) for s in smi]
params = rdFMCS.MCSParameters()
params.BondCompareParameters.CompleteRingsOnly = True
mcs = rdFMCS.FindMCS(mols, params)
display_mcs(mcs, mols)

mcs.numAtoms 2 mcs.numBonds 1
[#6]-&@[#6]
mol1 atom_matches (0, 1) bond_matches (0,)
mol2 atom_matches (0, 1) bond_matches (0,)
```
image

This is now fixed and the expected empty MCS is returned:

```
display_mcs(mcs, mols)

mcs.numAtoms 0 mcs.numBonds 0

mol1 atom_matches () bond_matches ()
mol2 atom_matches () bond_matches ()
```
image

## (2) Improvement: results returned by `MatchFusedRingsStrict` may match where they ought not to
Currently, MCS queries obtained with `MatchFusedRingsStrict=True` are too generic and may match also where they should not; see the example below:
```
smi = ["NC(=O)CC1C2CC3CCCCC3C12", "NC(=O)CC1CCCC2CCCCC12"]
mols = [Chem.MolFromSmiles(s) for s in smi]
params = rdFMCS.MCSParameters()
params.BondCompareParameters.CompleteRingsOnly = True
params.BondCompareParameters.MatchFusedRingsStrict = True
mcs = rdFMCS.FindMCS(mols, params)
display_mcs(mcs, mols)

mcs.numAtoms 6 mcs.numBonds 6
[#6]1-&@[#6]-&@[#6]-&@[#6]-&@[#6]-&@[#6&R2]-&@1
mol1 atom_matches (4, 5, 13, 6, 12, 7) bond_matches (4, 5, 6, 12, 13, 15)
mol2 atom_matches (4, 5, 13, 6, 8, 7) bond_matches (4, 5, 6, 7, 13, 14)
```
image

Since the cyclohexane query does not contain ring size queries, it actually also matches at the ring where, based on the requested `MatchFusedRingsStrict`, it should not match.

I have therefore added appropriate ring size queries on certain ring atoms to avoid that:
```
smi = ["NC(=O)CC1C2CC3CCCCC3C12", "NC(=O)CC1CCCC2CCCCC12"]
mols = [Chem.MolFromSmiles(s) for s in smi]
params = rdFMCS.MCSParameters()
params.BondCompareParameters.CompleteRingsOnly = True
params.BondCompareParameters.MatchFusedRingsStrict = True
mcs = rdFMCS.FindMCS(mols, params)
display_mcs(mcs, mols)

mcs.numAtoms 6 mcs.numBonds 6
[#6;r6,!R1]1-&@[#6;r6,!R1]-&@[#6;r6,!R1]-&@[#6;r6,!R1]-&@[#6]-&@[#6]-&@1
mol1 atom_matches (7, 8, 12, 9, 11, 10) bond_matches (7, 8, 9, 10, 11, 15)
mol2 atom_matches (4, 5, 13, 6, 8, 7) bond_matches (4, 5, 6, 7, 13, 14)
```
image

**Comment by rachelnwalker** [comment]
@ptosco this write up is very helpful, thank you!! I just have one question -- from your last example on `MatchFusedRingsStrict`, wouldn't that smarts string match a non-fused 6-membered ring? If that is intended, why do we need the "!R1" query (or should it be AND instead of OR)?

**Review by d-b-w — APPROVED** [review]
Thanks for that summary, this is all much more clear now.

This make sense to me, and I'm excited for it to be merged

**Review by greglandrum — APPROVED** [review]
LGTM
I just did a quick skim since @d-b-w and @rachelnwalker have gone through it in more detail

**Pull request merged**
