### PR TITLE
Convert exactmw to amw in tests

### PR DESCRIPTION
**Pull request by bp-kelley**
Converts exactmw -> amw to get the tests running again

### CODE REVIEW

**Comment by bp-kelley** [comment]
@greglandrum This is a trivial enough fix that I'll merge it when the tests build.

**Comment by greglandrum** [comment]
@bp-kelley Please don't merge this... a better fix is to put exactmw back into the descriptor list (something I screwed up in #4200). I will do a PR for that

**Comment by greglandrum** [comment]
Fixed this in #4209, so I'm closing this.
Please reopen if I misunderstood or missed something

**Comment by bp-kelley** [comment]
@greglandrum you can see I had both solutions but didn't know what you we're going for :)

**Pull request closed without merging**
