### PR TITLE
- GetMolFrags now optionally returns atom indices along with mols

### PR DESCRIPTION
**Pull request by ptosco**
…as its C++ counterpart

- added relevant test in rough_test.py

### CODE REVIEW

**Comment by ptosco** [comment]
Sure. Actually, that’s how I originally implemented it: I passed a python::list by reference and I filled it. Then I thought: naaah, this is the C++ way, Greg won’t like it. :-)

**Comment by greglandrum** [comment]
There's just something about having the return type of a function change because of the arguments that makes me nervous. :-)

**Comment by ptosco** [comment]
I have made the change you suggested. The Travis build failed due to an error while compiling FreeSASA; I could build it on my machine and it passed all tests.

**Comment by greglandrum** [comment]
Thanks Paolo!

**Pull request merged**
