### PR TITLE
Add an RGroupDecomp aware  molzip to the FreeWilson Contribution

### PR DESCRIPTION
**Pull request by bp-kelley**
This adds a rgroupdecomp aware molzip to the FreeWilson contrib to better handle broken cycles and chains in the FreeWilson reconstruction.

It also adds better logging to indicate how many of the original molecules were successfully reconstructed to better detect edge cases,

### CODE REVIEW

**Comment by greglandrum** [comment]
I'm a bit confused by this one. It mentions molzip repeatedly, but the changes are all in the FreeWilson contrib module.

**Comment by bp-kelley** [comment]
Sorry, this adds a molzip to the FreeWilson code that solves the issue.  It doesn't fix molzip in code, just shows how to use it with RGroupDecomposition.

**Comment by bp-kelley** [comment]
I updated the description.

**Review by greglandrum — APPROVED** [review]
LGTM

**Pull request merged**
