### PR TITLE
Add minimal JavaScript wrapper

### PR DESCRIPTION
**Pull request by greglandrum**
The idea here is to allow the RDKit to be used from JavaScript so that we can add chemical capabilities to web applications.
Rather than attempting a comprehensive wrapper (like RDKitJS), this exposes a small set of key functionality. I think the general approach, including this actual library, can be useful for other wrapper projects in the future.

This initial set of functionality is not complete, but it's intended to already be directly useful. Here's what's there: https://github.com/greglandrum/rdkit/blob/dev/js_wrappers/Code/MinimalLib/jswrapper.cpp

There's a Dockerfile here that shows how to setup an environment to build this and do a build: https://github.com/greglandrum/rdkit/blob/dev/js_wrappers/Code/MinimalLib/docker/Dockerfile

Some questions/things to think about:
1) This currently uses three different methods to return non-trivial values: `get_substruct_match()` function returns a wrapped std::vector. This results in an API that I find strange on the JS side. `get_descriptors()` returns JSON that can be trivially parsed into a JS object. `get_morgan_fp()` returns a bitstring (e.g. `"01000111010"`). Would it be better to pick a single return value type (i.e. JSON) or, perhaps JSON for `get_descritors()` and `get_substruct_match()` but still the string for `get_morgan_fp()`.
2) Which other pieces of functionality should be there?
3) Is it worth adding build options to the wrapper itself so that people who are really only interested in a subset of what's there can create a super-stripped down version?

I haven't done any benchmarking yet, that would also be interesting at some point in the future.

### CODE REVIEW

**Comment by greglandrum** [comment]
@thegodone : it would be great if you could also take a look at this.

**Comment by greglandrum** [comment]
To give a taste of what the wrapper can do, and to provide pre-built .js and .wasm files for anyone who wants to test, I've put a build online:
https://www.rdkit.org/temp/demo/demo.html

Having a long-term version of this available online makes sense, but that would require a somewhat better styled page. :-)

**Comment by greglandrum** [comment]
Merging after conversations with @bp-kelley and @thegodone

**Comment by edtrawtmam** [comment]
This is amazing!
But, how do I do in win10 with conda3?
I like to use in a Flask project.
Thanks for all!
Ed

**Comment by greglandrum** [comment]
@edtrawtmam I'm not sure what you're asking.
This is a JS wrapper, so operating system and python version aren't really relevant.
There's an RDKit blog post about the wrappers that may be helpful: http://rdkit.blogspot.com/2019/11/introducing-new-rdkit-javascript.html

**Pull request merged**
