### PR TITLE
Speed up boost vector iterators

### LINKED ISSUE #7639: EnumerateLibrary.GetPosition() surprisingly slow
**Describe the bug**
In a simple enumeration loop, if one is iterating over library.GetPosition() in the loop, it takes up to 40% of the runtime of the loop.
For a full enumeration, counting/calculating the position yourself everytime in python is much faster and reduces the overhead to almost zero compared to the actual work in the iterator (i.e. RunReactants).

**To Reproduce**
Will update to a full example soon.

```
    library = EnumerateLibrary(rxn, bbs)
    reagents = library.GetReagents()
    for product_template_results in library:
        # print input reactant monomers and the product
        libpos = library.GetPosition()
        for i, n in enumerate(libpos): # <- this line iterates over a vector of size_t with 3 elements and takes 40% of the runtime
            print(reagents[i][n].GetProp("_Name"))
```

**Expected behavior**
The line taking less than 1% of the runtime.

**Screenshots**
Screenshot 2024-07-20 at 11 26 53

**Configuration (please complete the following information):**
 - RDKit version: 2023.09.6
 - OS: macOS 14.5
 - Python version (if relevant): 3.11
 - Are you using conda? no

### PR DESCRIPTION
**Pull request by bp-kelley**
Fixes #7639 

Boost Iterators are amazingly slow for iteration, but accessing by index is very fast.  This converts the __iter__ protocol to use the __getitem__ protocol and results in a > 300x speedup for iteration.

### CODE REVIEW

**Review by greglandrum — COMMENTED** [review]
What is this supposed to speed up?
Do you have an example of code that it helps with?

I just tried with the example using `rdChemReactions.EnumerateLibrary()` that I've been using all along (and that's derrived from your example), and this PR has no impact on the runtime.

**Comment by bp-kelley** [comment]
I've added the test note book to:

Code/GraphMol/ChemReactions/testData/GetPosition.ipynb 

Here are the tests

```
from rdkit import Chem
m = Chem.MolFromSmiles("CCCCCCCCCCCC")
ps = Chem.FindAllPathsOfLengthN(m, 3)
%timeit [list(x) for x in ps]
```

```
Before: 5.04 ms ± 24.9 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
after: 24.1 μs ± 53.9 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

```
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import rdChemReactions

for N in range(3, 40):
    carbons = [f"[C:{i}]" for i in range(1,N+1)]
    rxn = f"{'.'.join(carbons)}>>{''.join(carbons)}"
    rxn = AllChem.ReactionFromSmarts(rxn)
    mol = Chem.MolFromSmiles("C")
    bbs = []
    for i in range(N):
        bbs.append( [mol] * 5 )
        
    lib = rdChemReactions.EnumerateLibrary(rxn, bbs)
    print(f"{N=}", len(lib.GetPosition()), end=" ")
    %timeit [x for x in lib.GetPosition()]
```

It looks like the bulk of the cost is returning the position as the timings are not dependent on the return size.  On OSX at least, it's about twice as fast.

Before:
```
N=3 3 652 μs ± 465 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
N=4 4 653 μs ± 2.56 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
N=5 5 652 μs ± 1.28 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
N=6 6 652 μs ± 1.28 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
N=7 7 653 μs ± 1.79 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
N=8 8 654 μs ± 1.55 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
N=9 9 655 μs ± 2.49 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
N=10 10 654 μs ± 1.49 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

After:
```
N=3 3 383 μs ± 1.39 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
N=4 4 383 μs ± 879 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
N=5 5 383 μs ± 874 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
N=6 6 383 μs ± 575 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
N=7 7 382 μs ± 668 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
N=8 8 383 μs ± 697 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
N=9 9 383 μs ± 563 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
N=10 10 383 μs ± 840 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
...
```

**Comment by greglandrum** [comment]
Running on linux (using g++) I see a factor of ~4 speedup on the first case (the one with FindAllPathsOfLengthN) and no change for the second example.

**Comment by bp-kelley** [comment]
It looks like the vector wrapped in rdChemReactions isn't in rdBase, adding this adds the speedup

```
rdChemReactions.VectSizeT.__iter__ = __vect__iter__
```
Before
```
N=3 3 24.9 μs ± 283 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
N=4 4 24.9 μs ± 161 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
N=5 5 25.2 μs ± 105 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

After
```
N=3 3 3.64 μs ± 29.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
N=4 4 4.17 μs ± 47.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
N=5 5 4.78 μs ± 81.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

I'll see what I can do here, but fixing the underlying vector indexing suite would be a generic solution I think.

**Comment by bp-kelley** [comment]
I wasn't using the same build for testing which was an oversite.  Maybe
clang got better at optimizing something since the last release.

**Comment by bp-kelley** [comment]
The newer tests used exactly the same build.

**Review by greglandrum — CHANGES_REQUESTED** [review]
I don't think we need the `GetPosition` notebook here, but otherwise this looks good.

**Comment by bp-kelley** [comment]
We use RegisterVector iterators in a lot of places that would need to be monkey patched.  Like GetPositions.  I'll see how hard this is to consolidate, I think most std::vector<number> should be wrapped at the lowest level, i.e. RDBoost.  And we could wrap std::vector<RWMOL_SPTR/ROMOL_SPTR> in rdkit.Chem which should cover most of the major issues.  I'll get this done this weekend.

**Comment by greglandrum** [comment]
@bp-kelley maybe that can be done in a separate PR? If you remove the notebook from this one, I can go ahead and merge it and we'll have the partial solution out there in the upcoming patch release.

**Comment by bp-kelley** [comment]
@greglandrum after this is merged I have a quick follow up where I register numeric vectors in RDBase.cpp, this should fix the original issue.

**Comment by bp-kelley** [comment]
@greglandrum I think removing the notebook was your change request, let me know if there is anything else

**Review by greglandrum — APPROVED** [review]
LGTM

**Pull request merged**
