### PR TITLE
Add prepareMolForDrawing() function to C++

### LINKED ISSUE #772: Prefer wedging bonds to Hs
At the moment they are *not* preferred.

### PR DESCRIPTION
**Pull request by greglandrum**
Captures the standard operations to get ready for doing a molecular rendering:
- kekulization
- generation of coordinates
- wedging bonds
- adding Hs to chiral atoms

Also fixes #772 (so that `wedgeMolBonds()` prefers wedging bonds to Hs)

### CODE REVIEW

**Comment by bp-kelley** [comment]
Overall looks good.  I think what you are doing is adding Depiction Hydrogens required for drawing chirality (wedges).  If this is so, it should be reflected in the documentation.

Also, should we have a function that removes depiction hydrogens?

**Comment by DoliathGavid** [comment]
Is it possible to only a subset of atoms and bonds to be prepared? Eg. there might be already existing wedging/kekulization that a user already deems sufficient.

**Comment by bp-kelley** [comment]
@doliathgavid I believe this only adds hydrogens required by the depiction system for depiction tetrahedral stereochemistry, it doesn't appear to affect others.

If you can think of a good test case for this, that would be great.

**Comment by greglandrum** [comment]
No, if you want to only prepare specific atoms and bonds, you can certainly do that yourself. This is there as a convenience function to handle the 99% case.

**Comment by greglandrum** [comment]
Ok, this is now in sync with the master again. Ok to merge?

**Pull request merged**
