### PR TITLE
feat/github831: Add getSDText() static method.

### LINKED ISSUE #831: Add a GetSDText() static method to the SDWriter class
Here's the thread: http://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg05430.html

### PR DESCRIPTION
**Pull request by greglandrum**
Fixes #831

### CODE REVIEW

**Comment by bp-kelley** [comment]
I think we might regret this later.  What about Smiles or PDB files for instance?

What do you think about adding a:

```
  virtual void write(const ROMol &mol, int confId = defaultConfId) = 0;
  virtual std::string getstring();  // returns the last written data if not using an externally defined stream
```

Method to the mol writers?  Then one could do something like:

SmilesWriter s;
s.write(mol);
s.write(mol);
s.getstring();  // throws an exception if using cout/external stream or filename
s.write(mol);
s.getstring(); // gets everything from the last get
```

And all writers would support it.

**Comment by greglandrum** [comment]
Doesn't work. The point is to be able to get the text without having to
actually create an SDWriter and "write" something.

If there's a need to add similar functionality to either the SMILES or PDB
writers, we can do so.

**Comment by bp-kelley** [comment]
If is this just for encapsulation, sure, but the downside is that there are two pieces of code to maintain, i.e. the constructor args will need to be duplicated in the static functions.  You are correct that this probably isn't a big deal.

I might make the function name just "getText" for consistency:

```
SDWriter::getText
SmilesWriter::getText
```

**Comment by greglandrum** [comment]
Just updated the method name to getText()

**Pull request merged**
