### PR TITLE
allow perception of stereo from T-shaped structures

### LINKED ISSUE #7177: Colinear bonds in depiction cause stereo to be lost when converting to mol block
Hi All,

We have noticed a change in behaviour between rdkit versions when writing and reading molblocks for compounds with a fused trycyclic ring. For example, in version `2023.09.01` importing the below structure from the SMILES below and casting to and from a MolBlock gives a warning and the stereo Hydrogen is lost in the SMILES. However, carrying out the same procedure with mapping to and from SMILES does not remove the stereo Hydrogen.

When running the same code in the previous version, `2023.03.03`, we do not get the warning and the stereo Hydrogen is still present.

Additional observations:
* Adding Hs to the structure preserves the stereo annotation
* `AllChem.Compute2DCoords` does not resolve the issue
* The presence of an aromatic ring is important, removing the aromatic ring and running the same code preserves the stereo H
* Using another toolkit such as `openbabel` to write to sdf does not lose the stereo H when importing the file with RDKit

### Steps to Reproduce
```Python
In [1]: !pip install rdkit==2023.09.01
In [2]: import rdkit
   ...: from rdkit import Chem
   ...: from rdkit.Chem import AllChem
In [3]: rdkit.__version__
Out[3]: '2023.09.1'
In [4]: smi_simple = "C([C@H]1CC3CCC1CC3)(c4ccccc4)"
   ...: smi_no_issue = "C([C@H]1CC3CCC1CC3)C"
In [5]: def mol_to_molblock_and_back(mol):
   ...:     return Chem.MolFromMolBlock(Chem.MolToMolBlock(mol))
In [6]: mol_simple = Chem.MolFromSmiles(smi_simple)
In [7]: mol_issue = mol_to_molblock_and_back(mol_simple)  # creates issue
[15:06:23] Warning: ambiguous stereochemistry - linear bond arrangement - at atom 1 ignored
In [8]: Chem.MolToSmiles(mol_issue)
Out[8]: 'c1ccc(CC2CC3CCC2CC3)cc1'
In [9]: mol_with_hs = Chem.AddHs(mol_simple)  # adding Hs fixes issue
In [10]: Chem.MolToSmiles(mol_to_molblock_and_back(mol_with_hs))
Out[10]: 'c1ccc(C[C@H]2CC3CCC2CC3)cc1'
In [11]: AllChem.Compute2DCoords(mol_simple)  # Compute Coords does not get expected output
   ...: print(Chem.MolToSmiles(mol_to_molblock_and_back(mol_simple)))
[15:31:21] Warning: ambiguous stereochemistry - linear bond arrangement - at atom 1 ignored
c1ccc(CC2CC3CCC2CC3)cc1
In [12]: Chem.MolToSmiles(mol_to_smiles_and_back(mol_no_issue))  # removing aromatic ring does not have same issue
Out[12]: 'CC[C@H]1CC2CCC1CC2'
```
However, in the previous version:
```Python
In [1]: !pip install rdkit==2023.03.03
In [2]: import rdkit
   ...: from rdkit import Chem
In [3]: rdkit.__version__
Out[3]: '2023.03.3'
In [4]: def mol_to_molblock_and_back(mol):
   ...:     return Chem.MolFromMolBlock(Chem.MolToMolBlock(mol))
   ...:
In [5]: smi_simple = "C([C@H]1CC3CCC1CC3)(c4ccccc4)"
In [6]: mol_simple = Chem.MolFromSmiles(smi_simple)
In [7]: mol =  mol_to_molblock_and_back(mol_simple)
In [8]: Chem.MolToSmiles(mol)  # stereo preserved
Out[8]: 'c1ccc(C[C@H]2CC3CCC2CC3)cc1'
```

Thanks for your time!

### Expected behavior:
Stereo H should be preserved in Mol object after exporting to MolBlock and importing from MolBlock.

Configuration:
* RDKit version: 2023.9.1
* OS: MacOS and Linux
* Python version (likely not relevant): 3.10.12
* Are you using conda? No

### PR DESCRIPTION
**Pull request by greglandrum**
The current version of the RDKit does not recognize the tetrahedral chirality on atom 1 in this molecule:
image

Section ST-1.2.12 of the IUPAC guidelines says that this type of environment is wrong because it represents T-shaped configurations. Since we are dealing with tetrahedral stereo, this doesn't apply to us.

With this change, that structure is intepreted like this one:
image

I'm marking the change as an enhancement and not a bug fix because the current behavior isn't *per se* wrong, it just ends up neglecting a coordinate environment which occurs fairly frequently in real molecule drawings

Fixes #7177

### CODE REVIEW

**Comment by greglandrum** [comment]
@bp-kelley @ptosco @ricrogz : since this is a behavior change, it would be great if you could provide feedback on the substance of the change. Oh, and if one of you could actually review the code. :-)

**Review by ricrogz — APPROVED** [review]
This makes sense to me. I've actually seen a couple cases like this and was wondering if we could do something like this. Thanks!

**Comment by rvianello** [comment]
The example you shared makes sense to me and (even though ST-1.2.12 explicitly says this depiction is not acceptable for representing tetrahedral configurations) I would tend to agree with it, but I am wondering if the same depiction could be a bit more confusing and less straightforward to interpret if the stereo bond were not perpendicular to the other two, and if the case of three-coordinated chiral centers (when there is no implicit hydrogen) could make a difference.

**Comment by bp-kelley** [comment]
I curious what the CIP is on these.

**Comment by greglandrum** [comment]
> I'm curious what the CIP is on these.

I don't understand the question. The CIP is determined by the interpretation of the tetrahedral structure for these just like any other structure.

**Comment by bp-kelley** [comment]
@greglandrum I was getting some odd behavior in chemaxon with these structures and just wanted to see if this was correlated.

**Comment by greglandrum** [comment]
> @greglandrum I was getting some odd behavior in chemaxon with these structures and just wanted to see if this was correlated.

@bp-kelley yeah, Marvin Sketch doesn't recognize the T-shaped molecules as chiral. Or, at least it doesn't do so most of the time.

**Comment by brianlahue** [comment]
Hi @greglandrum how would this change interpret t-shaped cyclopropyl example like this (left structure)?

Screen Shot 2024-02-28 at 10 40 22 AM

The left structure gives `Warning: ambiguous stereochemistry - linear bond arrangement - at atom 1 ignored.`   with RDKit 2023.9.1

**Comment by d-b-w** [comment]
I feel like this puts us a bit in a guessing game.

Greg's original example seems reasonable enough, but if I tweak it a little bit it totally changes my expectation of where the secret hydrogen will be:

tbar_vs_janky

The molblocks for this example are in this gist:

https://gist.github.com/d-b-w/808c312accbe1b3d9fd404e1d5c867c2

**Comment by d-b-w** [comment]
oh- here is the janky structure with some guesses about hydrogens:

janky_w_exlpicit_hydrogens

**Comment by greglandrum** [comment]
@d-b-w The rule we are using is that the implicit Hs is always on the *other side* of the three linear atoms and that it has the same wedging as the wedged bond:
image

**Comment by d-b-w** [comment]
I understand that is the rule that we've implemented - I'm just not totally convinced that this placement isn't a guess for molecules drawn this poorly.

I guess the question in my mind is - is it better to silently drop stereo annotation that someone thinks they included, or invert it?

**Comment by greglandrum** [comment]
I just don't think there's any way that the structures you sketched with the wedged bond and the implicit H on the same side of a linear arrangement of three atoms is ever correct. So the only possibility that even kind of makes sense is to have the H on the other side from the wedged bond

**Comment by d-b-w** [comment]
OK, you and Ricardo convinced me :) Sorry, @rvianello ;)

**Pull request merged**
