### PR TITLE
Mem checkup

### PR DESCRIPTION
**Pull request by ricrogz**
I ran a memtest and found some problems. Most of them were mols left over in tests, but there was also some more serious stuff:

- The valgrind command was missing the `--error-exitcode` argument. Without it, valgrind returns "0" even if it found some leaks. Somehow, I failed to include it when I set up the mem testing config.
- Updated the suppressions. These are less specific now, and the suppressions should now match in more environments.
- CX Smiles leaked a mol if the parser was not able to parse the CX extensions.
- PDB and Maestro suppliers leaked mols when the parsing failed.
- Reactions parsing was reading out of bounds (it tried to read one char before the start of the string).

Also, testEnumerate is quite hard for valgrind: it fails after ~10 minutes, and the log only contains  the typical valgrind header, but no leaks or reports. It looks like valgrind dies in the process. I'm suspecting that it might be because the test allocates a vector of 6000 * 500 * 10000 elements, and valgrind might run out of memory trying to store information for each of those. I did reduce each of those dimensions by 1/100, as well as the number of iterations in the two long loops (the ones with 5000 and 1000 iterations), and then the memtest succeeded in a reasonable time, and the log came out complete and clean.

### CODE REVIEW

**Comment by bp-kelley** [comment]
@ricrogz we can take the pressure off the valgrind by making this change to the EvenSampler test

This way only three molecules will be created:

```
  boost::shared_ptr<ROMol> m(SmilesToMol("C=CCN=C=S"));
  boost::shared_ptr<ROMol> m2(SmilesToMol("NCc1ncc(Cl)cc1Br"));
  boost::shared_ptr<ROmol> m3(SmilesToMol("NCCCc1ncc(Cl)cc1Br"));

  for (unsigned long i = 0; i < R1; ++i) {
    bbs[0].push_back(m);
  }

  for (unsigned long i = 0; i < R2; ++i) {
    bbs[1].push_back(m2);
  }

  for (unsigned long i = 0; i < R3; ++i) {
    bbs[2].push_back(m3);
  }
```

**Comment by ricrogz** [comment]
> @ricrogz we can take the pressure off the valgrind by making this change to the EvenSampler test
> 
> This way only three molecules will be created:
> 
> ```
>   boost::shared_ptr<ROMol> m(SmilesToMol("C=CCN=C=S"));
>   boost::shared_ptr<ROMol> m2(SmilesToMol("NCc1ncc(Cl)cc1Br"));
>   boost::shared_ptr<ROmol> m3(SmilesToMol("NCCCc1ncc(Cl)cc1Br"));
> 
>   for (unsigned long i = 0; i < R1; ++i) {
>     bbs[0].push_back(m);
>   }
> 
>   for (unsigned long i = 0; i < R2; ++i) {
>     bbs[1].push_back(m2);
>   }
> 
>   for (unsigned long i = 0; i < R3; ++i) {
>     bbs[2].push_back(m3);
>   }
> ```

Good idea. I'll add it to the PR.

**Comment by ricrogz** [comment]
I added @bp-kelley 's suggestion, and, while it makes the test sensibly faster, valgrind still crashes.

**Comment by bp-kelley** [comment]
Let’s drop the R counts by an order of magnitude say 600, 50, 1000

**Comment by ricrogz** [comment]
Reducing the R counts worked: the mem test took about ~20 minutes (it takes 35 seconds to run the "normal" test in a debug build), but valgrind didn't crash, and the log came out ok (and clean).

**Comment by greglandrum** [comment]
Cool. Then is this ready to merge?

**Comment by ricrogz** [comment]
> Cool. Then is this ready to merge?

On my side, it is good to go, unless you have any requests or suggestions :)

**Pull request merged**
