### PR TITLE
Added documentation files written in Japanese into Book directory

### PR DESCRIPTION
**Pull request by magattaca**
I've been trying to translate "The RDKit Documentation" into Japanese, and recently I published the files on the web. I would appreciate it if you could also store these files under rdkit/Docs directory for future Japanese users.
I'm not sure if this is a good way to share these Japanese files or not. So, if you think this pull-request is inappropriate, please feel free to reject it.
Also, I'm still not used to using github, so there would be big mistakes. Please forgive me in advance.  
Thank you for reading.

### CODE REVIEW

**Comment by greglandrum** [comment]
@magattaca  first thing: thank you for this contribution and the work that you put into it. I think this will be useful to a lot of people.
I, unfortunately, can not review the content of this, but that's ok here.

Some questions/comments that I do have:

1. Once this has been merged, would it be helpful if I start doing builds of this documentation and making it available from the RDKit website like I do with the English docs?
2. I think the contents of the images irectory - https://github.com/magattaca/rdkit/tree/translation-into-Japanese/Docs/Book/Translation_into%20Japanese/images - duplicate the English directory. If that's true, would it be possible to update the translation to use the original images instead of these duplicates. For example instead of `image:: images/cdk2_mol1.png` you would use `image:: ../images/cdk2_mol1.png`

Your supplemental information document (https://github.com/magattaca/rdkit/blob/translation-into-Japanese/Docs/Book/Translation_into%20Japanese/Supplementary_Text_jp.rst) looks like something that I would like an English translation for. That comes later though!

**Comment by magattaca** [comment]
@greglandrum Thank you very much for your quick reply.

Below is the answers to your questions/comments:

1. If you would build and make this documentation available from the RDKit website, that would be a great honor for me. Since I'm just an amateur in the chemoinformatics filed, there are probably a lot of mistranslation. So, I would like to open this documentation to the public and ask for cooperation to correct mistakes.

2. Thank you for your kind advice about the images directory. I removed the images directory in the Japanese directory - [https://github.com/magattaca/rdkit/tree/translation-into-Japanese/Docs/Book/Translation_into_Japanese] - and updated the translation to use the original images. Also, I modified the directory name "Translation_into Japanese" to "Translation_into_Japanese" to remove the space. 

I really appreciate that you kindly refer to the supplemental information document. Due to my poor English, it would take a lot of time but I'd like to try to translate it into English when I have time.

**Comment by greglandrum** [comment]
@magattaca : I'm not sure if you got a notification about this or not, but I made a PR against your repo that moves the new documentation to its own directory so that it can be built separately. This makes the docs themselves look better (more auto-generated text in Japanese, for example) and simplifies the build process for me.
If you think it looks ok, please merge that PR into your branch and this PR will be automatically updated.

**Comment by greglandrum** [comment]
Hi @magattaca , thanks for merging that.
At the moment you don't need to do anything else. I will take another look through the PR over the next day or two and, if everything looks ok, go ahead and merge it.
Thanks again for this very nice contribution.

**Comment by magattaca** [comment]
@greglandrum Thank you for your quick response. Should I remove the Docs/Book/Translation_into_Japanese directory? Now, this directory seems to contain files, which are not used anymore.

**Comment by greglandrum** [comment]
Oh, I missed some files? That's no good.
If they aren't still being used, then please do remove them.

**Comment by magattaca** [comment]
I removed the files. I think that the files contained in the Docs/Book directory are now the same as those inside the master branch.

**Comment by magattaca** [comment]
@greglandrum   Thank you very much for merging!

**Pull request merged**
