### PR TITLE
Fixes #5172

### LINKED ISSUE #5172: Multiple calls to BlockLogs() permanently disable logging
Found with Release 2020_03_1b1:

```
In [3]: Chem.MolFromSmiles('garbage')                                                                                                                        
[11:49:29] SMILES Parse Error: syntax error while parsing: garbage
[11:49:29] SMILES Parse Error: Failed parsing SMILES 'garbage' for input: 'garbage'

In [4]: def blocklogs(): 
   ...:     b = Chem.rdBase.BlockLogs() 
   ...:     b = Chem.rdBase.BlockLogs() 
   ...:                                                                                                                                                      

In [5]: blocklogs()                                                                                                                                          

In [6]: Chem.MolFromSmiles('garbage')                                                                                                                        

In [7]:  
```

This is relevant because we do actually call `BlockLogs()` multiple times in places like https://github.com/rdkit/rdkit/blob/67409c3acfcc65274cda5342c736763db38ffb80/rdkit/Chem/Draw/__init__.py#L447-L460

### PR DESCRIPTION
**Pull request by ricrogz**
Fixes #5172 using Brian's suggestion.

I also made `LogStateSetter` non-copyable (weird and unexpected things may happen, depending on what the compiler decides to do with copies/assignments!), and fixed the `BlockLogs()` in the Draw module that revealed the issue.

### CODE REVIEW

**Comment by ricrogz** [comment]
I had been thinking about wrapping `BlockLogs()` as a context manager, and at some point I just assumed it was already one. After I updated the tests and they failed, I actually updated the wrapping.

**Comment by ricrogz** [comment]
@greglandrum am I missing something here, or is it just that the test is failing because of the static linking? I think there was some discussion about that at some point...

**Comment by bp-kelley** [comment]
It could be the log isn’t flushing.  I’ve seen this before on windows

**Comment by ricrogz** [comment]
> It could be the log isn’t flushing. I’ve seen this before on windows

No, it's not that. I debug-printed the address of `rdErrorLog` in `MolFromSmiles()` and `LogErrorMsg()` (to which I added a call, to make sure the log gets flushed because of the `std::endl` it logs):

```
2022-04-10T14:31:56.6801321Z 168: **** SMILES rdErrorLog=0000000000000000
2022-04-10T14:31:56.6804177Z 168: **** SMILES rdErrorLog=0000000000000000
2022-04-10T14:31:56.6865493Z 168: **** SMILES rdErrorLog=0000000000000000
2022-04-10T14:31:56.6881720Z 168: **** SMILES rdErrorLog=0000000000000000
2022-04-10T14:31:56.7059299Z 168: .............................**** SMILES rdErrorLog=0000000000000000
2022-04-10T14:31:56.7288264Z 168: ......................**** SMILES rdErrorLog=0000000000000000
2022-04-10T14:31:56.7289928Z 168: .**** SMILES rdErrorLog=0000000000000000
2022-04-10T14:31:56.7292698Z 168: .............**** SMILES rdErrorLog=0000000000000000
2022-04-10T14:31:56.9179425Z 168: **** LogErrorMsg rdErrorLog=0000025E433984D0
2022-04-10T14:31:56.9988107Z 168: **** LogErrorMsg rdErrorLog->df_enabled=1
```

So, it seems the log is initialized and enabled in `rdBase`, but not in `rdmolops`, which makes me think the logging issues with static libs are still there, because for the DLL build both `rdErrorLog`s are enabled and have the same address.

**Comment by greglandrum** [comment]
I think this diagnosis is likely correct. I don't think there's any way the logs can be shared (rather than duplicated) across modules unless we use DLLs.

Which reminds me that I still need to figure out how to make the windows conda builds work with DLLs

**Pull request merged**
