### PR TITLE
replaceSidechains creates aromatic dummy atoms

### PR DESCRIPTION
**Pull request by ptosco**
`replaceSidechains` should clear the aromatic flag from dummy atoms.

### CODE REVIEW

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by ptosco** [comment]
Some more testing showed there were a couple further glitches:
1. explicit Hs were not cleared, so the dummy atom that previously was an indole nitrogen would have a spurious H attached
2. the bond to the dummy atom if previously aromatic (or double/triple) would stay as such and keep the aromatic flag
hence I have updated my PR accordingly.

**Comment by ptosco** [comment]
I have just found another issue in `replaceSidechains`, that leaves behind aromatic flags on atoms which are not in a ring anymore:
https://github.com/rdkit/rdkit/discussions/4019#discussioncomment-599642
I will address it later today.
Please do not merge yet!

**Comment by ptosco** [comment]
@greglandrum I made a few more fixes based on further findings in #4019 and added relevant tests.
I have also refactored to replace a `std::set` with a more efficient `boost::dynamic_bitset`.

**Comment by greglandrum** [comment]
Great. will try and review in the next day or so

**Review by greglandrum — APPROVED** [review]

**Pull request merged**
