### PR TITLE
add new oxidation states for Cl, Br, I, Xe, Po, At

### PR DESCRIPTION
**Pull request by greglandrum**
Also changes the allowed value 2->3 for I

These all regularly show up as hypervalent species, might as well make it less painful to use them.

### CODE REVIEW

**Review by ptosco — COMMENTED** [review]
I wished to this myself but I did not dare to :-)
I think you also want to do it for `Cl` then.

**Comment by greglandrum** [comment]
> I wished to this myself but I did not dare to :-)
> I think you also want to do it for `Cl` then.

<sigh> good point. It's there

**Comment by greglandrum** [comment]
I'm going to add the relevant entry to the ReleaseNotes in a separate commit that I'm doing in preparation for the upcoming release.

**Comment by greglandrum** [comment]
@ptosco look ok?

**Comment by ptosco** [comment]
@greglandrum LGTM, just merged.

**Comment by skearnes** [comment]
What's the best way to flag molecules that have unusual valences? This change breaks a lot of our molecule generation code because now we get species like `C#Cl` that parse just fine even though we clearly don't want to be generating stuff like that...

I suppose we could check for halogen valences explicitly, but I'm wondering if there's a way to globally adjust the sanitization to use a "preferred" valence or set of valences?

**Comment by greglandrum** [comment]
@skearnes you're absolutely right. We overshot on this one and need to at least partially back the changes out. At the very least the extra valence states for Cl should probably be removed. Anyone who wants/needs to parse those can still use the usual RDKit approach for handling hypervalent species: triggering the sanitization manually.

**Comment by ptosco** [comment]
Reverting the changes for Cl and Br is probably the best compromise solution, as `C#I` is less likely to appear in standard generative chemistry workflows. I hadn't thought of this unintended consequence.

**Comment by skearnes** [comment]
Note: partially reverted by #3545

**Pull request merged**
