### PR TITLE
Improving atom colors for dark mode.

### PR DESCRIPTION
**Pull request by kaushaleshshukla**
Improving dark mode palette for N, Br and I atoms.

### Current Palette
Current_Colors

### Improved Palette
Improved_colors

### CODE REVIEW

**Comment by greglandrum** [comment]
Hi @kaushaleshshukla : it would be helpful to explain why you think these colors are better than the current values.

**Comment by kaushaleshshukla** [comment]
> Hi @kaushaleshshukla : it would be helpful to explain why you think these colors are better than the current values.

Hi @greglandrum.
New colors are more visible and brighter. 
Basically on small window the letters become quite unreadable and if the colors are dark in dark background it becomes more difficult to read. The new colors will make the letters more readable.

**Comment by greglandrum** [comment]
@kaushaleshshukla thanks for the explanation; I can see how the brighter colors might help with smaller images.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
Thanks @kaushaleshshukla !

**Pull request merged**
