### PR TITLE
PostgreSQL bug fixes

### PR DESCRIPTION
**Pull request by ptosco**
- added a fix for earlier versions of PostgreSQL on Windows in
  CMakeLists.txt
- fixed a bug in Code/PgSQL/rdkit/rdkit_gist.c which did not cause
  issues with PostgreSQL 9.5 on Windows, but does with earlier PostgreSQL
  versions
- removed an unnecessary conditional compilation clause from
  Code/PgSQL/rdkit/rdkit.h as PostgreSQL 8.x is not supported anymore

### CODE REVIEW

**Comment by ptosco** [comment]
Hi Greg, sorry for the delay in replying, but I extensively tested multiple PostgreSQL versions on both Linux and Windows, and as a consequence here's a small pull request.
One observation: even though the README claims that PostgreSQL 9.1 is supported, it fails a test on Linux with the following diff:

*** /build/rdkit-Release_2015_09_2/Code/PgSQL/rdkit/expected/reaction.out       2015-11-14 03:47:39.000000000 +0000
--- /build/rdkit-Release_2015_09_2/Code/PgSQL/rdkit/results/reaction.out        2016-03-31 00:42:59.296264070 +0100
***************
*** 1,10 ****
--- 1,17 ----
  SET rdkit.ignore_reaction_agents=false;
+ ERROR:  unrecognized configuration parameter "rdkit.ignore_reaction_agents"
  SET rdkit.agent_FP_bit_ratio=0.2;
+ ERROR:  unrecognized configuration parameter "rdkit.agent_fp_bit_ratio"
  SET rdkit.difference_FP_weight_agents=1;
+ ERROR:  unrecognized configuration parameter "rdkit.difference_fp_weight_agents"
  SET rdkit.difference_FP_weight_nonagents=10;
+ ERROR:  unrecognized configuration parameter "rdkit.difference_fp_weight_nonagents"
  SET rdkit.move_unmmapped_reactants_to_agents=true;
+ ERROR:  unrecognized configuration parameter "rdkit.move_unmmapped_reactants_to_agents"
  SET rdkit.threshold_unmapped_reactant_atoms=0.2;
+ ERROR:  unrecognized configuration parameter "rdkit.threshold_unmapped_reactant_atoms"
  SET rdkit.init_reaction=true;
+ ERROR:  unrecognized configuration parameter "rdkit.init_reaction"
  SELECT reaction_from_smiles('c1ccccc1>>c1cccnc1');
   reaction_from_smiles
  ----------------------

======================================================================

Please note that the same test fails on PostgreSQL 9.1 using the released RDKit version compiled and tested in the traditional way with make && make install && make installcheck, so the failure does not depend on the CMake-based compilation.
A few more tests fail on Windows, again because of unrecongnized configuration parameters. All tests pass on PostgreSQL >= 9.2 on both Linux and Windows.
Shall I modify the docs mentioning support for PostgreSQL >=9.2 rather than >=9.1?
Thanks,
p.

**Comment by greglandrum** [comment]
Thanks for doing such an extensive set of tests and catching this.
Off the top of my head, I can't think of any reason why those functions shouldn't work on 9.1 too. I'll investigate.

**Comment by greglandrum** [comment]
Ok, I confirmed that. It's now issue #836

**Comment by ptosco** [comment]
I think I have fixed issue #836 now. I fixed the failing test on Windows by adding a PGDLLEXPORT to _PG_init(), while I have added a cartridge function before any parameter is referenced to avoid errors on PostgreSQL 9.1.

**Comment by ptosco** [comment]
Unfortunately the Travis build fails because SourceForge is in disaster recovery mode, so the AvalonTools cannot be downloaded.

**Comment by greglandrum** [comment]
Thanks Paolo. I just restarted the travis build

**Comment by greglandrum** [comment]
Looks good. Merging.
Thanks for doing the fix!

**Pull request merged**
