### PR TITLE
expose EmbedParameters::coordMap to Python

### PR DESCRIPTION
**Pull request by greglandrum**
This should have been done a while ago; it's a simple enough change

### CODE REVIEW

**Review by ptosco — COMMENTED** [review]
I have made a PR against your branch with a proposal for a tidier approach to memory management of `coordMap`.

**Comment by greglandrum** [comment]
> I have made a PR against your branch with a proposal for a tidier approach to memory management of `coordMap`.

Thanks for that.
I agree that it's cleaner

**Comment by greglandrum** [comment]
@ptosco are you ok with this now?

**Comment by ptosco** [comment]
@greglandrum Yes, just approved.

**Pull request merged**
