### PR TITLE
Initial commit of EnumerateHeterocycles

### PR DESCRIPTION
**Pull request by coleb**
#### What does this implement/fix? Explain your changes.

This implements an EnumerateHeterocyles API that makes use of the reaction smarts for enumerating heterocycles described in the lightning talk pull request here: https://github.com/rdkit/UGM_2017/pull/5

### CODE REVIEW

**Comment by coleb** [comment]
Crap, accidentally based these changes off the changes in #1582. 

@greglandrum or @bp-kelley, want me to rebase off of current master or I can just wait for #1582 to finish as I think #1582 is higher priority for inclusion in 2017.09?

**Comment by greglandrum** [comment]
I think it's safe to wait. The stereo changes are reasonable for 2017.09, but this seems better for the next release

**Comment by bp-kelley** [comment]
@coleb You taught me the wisdom of the Torvalds quote "the best thing to do is to wait for the next development cycle" :)

**Comment by coleb** [comment]
@greglandrum and @bp-kelley, just looked over the diff after merging in the latest master and it now only shows EnumerateHeterocycles like intended, so this is ready for review whenever you guys feel is appropriate.

**Comment by greglandrum** [comment]
Just a quick heads-up that I likely won't have a chance to take a look until next week.

**Comment by greglandrum** [comment]
Thanks Brian!

**Pull request merged**
