### PR TITLE
Fix/rhel5 boost python exception issue and BOOST 4.1 FilterCatalogWrap

### PR DESCRIPTION
**Pull request by bp-kelley**
Patches the Release 2015_09_2 (prep branch) to allow builds on 

RHEL5 (gcc 4.1)
Boost 1.42 and earlier that lack support for python wrapping of boost::shared_ptr<const T>

### CODE REVIEW

**Comment by bp-kelley** [comment]
If this is accepted, I should probably do a second pull request to merge this into the master branch since it probably won't merge by default.

**Comment by bp-kelley** [comment]
Looks like I missed a Java spot...

**Comment by greglandrum** [comment]
I'd rather have this PR against the master instead of this branch to test a release that's already been done.

I also think there are two separate pieces to this:
 1) Getting the serialization-based FilterCatalog code to build with older versions of boost
 2) adding RDGeneral/rdkit.h
I think it makes sense to break those out into two separate PRs, because the second needs more discussion.

**Comment by bp-kelley** [comment]
We can get the old code to work by

a) setting the define in CMAKE (which doesn't require the RDGeneral/rdkit.h
but does have the issue with linking)  I suppose I could invert the logic
so that we opt out (i.e. make the current API the default and the older one
the non-default)  This will have the correct behavior 90% of the time.

b) dropping the const from the API which will work on both systems but does
break the api

**Comment by bp-kelley** [comment]
I'll split up this request into the two bits sometime next week when I get back to a RHEL5 machine.

**Comment by bp-kelley** [comment]
@greglandrum I'm going to add the gcc RHEL5 stuff, and split off the rdkit.h for after the next release.  Expect a new pull request soon.

**Pull request closed without merging**
