### PR TITLE
Build documentation preview upon opening a pull request

### PR DESCRIPTION
**Pull request by bertiewooster**
#### Reference Issue

Fixes #6849

#### What does this implement/fix? Explain your changes.
When a pull request is opened, a preview of the documentation will be created on Read the Docs, and linked to in the PR.

### CODE REVIEW

**Comment by bertiewooster** [comment]
@greglandrum I copied in the GitHub Actions file from the [instructions](https://github.com/readthedocs/actions/blob/v1/preview/README.md) you linked to. Two things that the owner of the Read the Docs project (I'm guessing this is you) needs to do:

- Ensure the `project-slug` value is correct on the last line of the GitHub Actions file [.github/workflows/documentation-links.yml](https://github.com/rdkit/rdkit/pull/7217/files#diff-db385bef49fd7ab6efc0338151a618fc693503d724ed03c2555c5ea62a1ef474). I guessed that the slug is `rdkit`. The GitHub Actions README advises 'You can find it on your Read the Docs project's details page in the right menu under "Project Slug".'
- [Configure pull request builds](https://docs.readthedocs.io/en/latest/guides/pull-requests.html):

  > To enable pull request builds for your project, your Read the Docs account needs to be connected to an account with a supported Git provider. See [Limitations](https://docs.readthedocs.io/en/latest/guides/pull-requests.html#limitations) for more information.
  > 
  > If your account is already connected:
  > 
  > Go to your project dashboard
  > 
  > Go to Admin, then Settings
  > 
  > Enable the Build pull requests for this project option
  > 
  > Click on Save

**Comment by greglandrum** [comment]
@bertiewooster I think things should now be setup properly on the read the docs side.

And, yes, "rdkit" is the correct slug for the project.

**Comment by bertiewooster** [comment]
Great, thanks! This PR is ready for review then.

**Comment by greglandrum** [comment]
@bertiewooster if you push a commit to this PR, will it actually run the integration? It would be nice to see if it actually works. :-)

**Comment by bertiewooster** [comment]
I pushed an empty commit and am not seeing a doc preview link yet...you may have to approve the PR before it can do that? We can hold off merging the PR while I push another empty commit.

**Comment by greglandrum** [comment]
> I pushed an empty commit and am not seeing a doc preview link yet...you may have to approve the PR before it can do that? We can hold off merging the PR while I push another empty commit.

Let's try merging it and see what happens; I may still need to change something in the RTD setup

**Review by greglandrum — APPROVED** [review]
LGTM
Let's see if it works

**Pull request merged**
