### PR TITLE
Switch to uint32 for atom index to support more atoms

### LINKED ISSUE #1642: Atom index type is to low for big molecules
**Description:**
The atom indices are uint16 type, which effectively limits the number of atoms to 65535. Crazy enough there is no single precondition that guards it. You can without error (although with sanitize=False for speed) create molecule with more atoms. The magic starts when you want to actually use the atoms.

First this issue started surfacing when I worked with PDB for #1629. When removing hydrogens I started to get "no owner" error for atoms. When I wanted to create self-contained sample I didn't even get this far, as smiles encode all bonds .

```python
smi = 'C.' * 68000 + 'C'
mol = Chem.MolFromSmiles(smi, sanitize=False)
mol = Chem.RWMol(mol)
for i in reversed(range(mol.GetNumAtoms())):
    mol.RemoveAtom(i)
```

> RuntimeError                              Traceback (most recent call last)
> <ipython-input-48-fd00d89bcb52> in <module>()
>       3 mol = Chem.RWMol(mol)
>       4 for i in reversed(range(mol.GetNumAtoms())):
> ----> 5     mol.RemoveAtom(i)
> 
> RuntimeError: Pre-condition Violation
> 	no owner
> 	Violation occurred on line 125 in file Code/GraphMol/Atom.h
> 	Failed Expression: dp_mol
> 	RDKIT: 2018.03.1.dev1
> 	BOOST: 1_63

```python
smi = 'C' * 68000
mol = Chem.MolFromSmiles(smi, sanitize=False)
mol = Chem.RWMol(mol)
for i in reversed(range(mol.GetNumAtoms())):
    mol.RemoveAtom(i)
```

> RuntimeError                              Traceback (most recent call last)
> <ipython-input-47-07f69b10a29c> in <module>()
>       1 smi = 'C' * 68000
>       2 mol = Chem.MolFromSmiles(smi, sanitize=False)
> ----> 3 mol = Chem.RWMol(mol)
>       4 for i in reversed(range(mol.GetNumAtoms())):
>       5     mol.RemoveAtom(i)
> 
> RuntimeError: Pre-condition Violation
> 	bond already exists
> 	Violation occurred on line 350 in file Code/GraphMol/ROMol.cpp
> 	Failed Expression: !(boost::edge(bond_pin->getBeginAtomIdx(), bond_pin->getEndAtomIdx(), d_graph).second)
> 	RDKIT: 2018.03.1.dev1
> 	BOOST: 1_63

I hereby propose to raise the atom index to `uint32`, although the `Mol` memory footprint might be a bit bigger. If this is not an option, then we need a validation of actual number of atoms when adding them.

### PR DESCRIPTION
**Pull request by mwojcikowski**
Resolve #1642

### CODE REVIEW

**Comment by bp-kelley** [comment]
@greglandrum We could move this "fix" to the c++ branch.  The increase in atom size will be offset a lot by the shared_ptr changes.

**Comment by mwojcikowski** [comment]
@bp-kelley I have included requested test.

**Comment by mwojcikowski** [comment]
I think I'll be of little help with memory layout. It would be best, if you could check it yourself.

**Comment by greglandrum** [comment]
Will do. I need to figure out how to do it again, but I’ll post something about that.

**Comment by bp-kelley** [comment]
@greglandrum It's unclear to me how this would be detrimental to the layout as it adds another word boundary (16 bits added to the atom index).

This also affects bonds of course:
```Bond.h

  atomindex_t d_index;
  atomindex_t d_beginAtomIdx, d_endAtomIdx;
```

**Comment by greglandrum** [comment]
If you also change the ordering of the data members in the class `Atom` from
```
  atomindex_t d_index;
  boost::uint16_t d_isotope;
```
to
```
  boost::uint16_t d_isotope;
  atomindex_t d_index;
```
the `Atom` object won't require any additional memory.

Here's the output from `clang++ -cc1 -fdump-record-layouts`.
with `uint16_t`:
```
         0 | class RDKit::Atom
         0 |   (Atom vtable pointer)
         8 |   class RDKit::RDProps (base)
         8 |     class RDKit::Dict dp_props
         8 |       class std::vector<struct RDKit::Dict::Pair, class std::allocator<struct RDKit::Dict::Pair> > _data
         8 |         struct std::_Vector_base<struct RDKit::Dict::Pair, class std::allocator<struct RDKit::Dict::Pair> > (base)
         8 |           struct std::_Vector_base<struct RDKit::Dict::Pair, class std::allocator<struct RDKit::Dict::Pair> >::_Vector_impl _M_impl
         8 |             class std::allocator<struct RDKit::Dict::Pair> (base) (empty)
         8 |               class __gnu_cxx::new_allocator<struct RDKit::Dict::Pair> (base) (empty)
         8 |             pointer _M_start
        16 |             pointer _M_finish
        24 |             pointer _M_end_of_storage
        32 |       _Bool _hasNonPodData
        40 |   _Bool df_isAromatic
        41 |   _Bool df_noImplicit
        42 |   boost::uint8_t d_numExplicitHs
        43 |   boost::int8_t d_formalCharge
        44 |   boost::uint8_t d_atomicNum
        45 |   boost::int8_t d_implicitValence
        46 |   boost::int8_t d_explicitValence
        47 |   boost::uint8_t d_numRadicalElectrons
        48 |   boost::uint8_t d_chiralTag
        49 |   boost::uint8_t d_hybrid
        50 |   atomindex_t d_index
        52 |   boost::uint16_t d_isotope
        56 |   class RDKit::ROMol * dp_mol
        64 |   class RDKit::AtomMonomerInfo * dp_monomerInfo
           | [sizeof=72, dsize=72, align=8,
           |  nvsize=72, nvalign=8]
```
and with `uint32_t` and re-ordered fields:
```
         0 | class RDKit::Atom
         0 |   (Atom vtable pointer)
         8 |   class RDKit::RDProps (base)
         8 |     class RDKit::Dict dp_props
         8 |       class std::vector<struct RDKit::Dict::Pair, class std::allocator<struct RDKit::Dict::Pair> > _data
         8 |         struct std::_Vector_base<struct RDKit::Dict::Pair, class std::allocator<struct RDKit::Dict::Pair> > (base)
         8 |           struct std::_Vector_base<struct RDKit::Dict::Pair, class std::allocator<struct RDKit::Dict::Pair> >::_Vector_impl _M_impl
         8 |             class std::allocator<struct RDKit::Dict::Pair> (base) (empty)
         8 |               class __gnu_cxx::new_allocator<struct RDKit::Dict::Pair> (base) (empty)
         8 |             pointer _M_start
        16 |             pointer _M_finish
        24 |             pointer _M_end_of_storage
        32 |       _Bool _hasNonPodData
        40 |   _Bool df_isAromatic
        41 |   _Bool df_noImplicit
        42 |   boost::uint8_t d_numExplicitHs
        43 |   boost::int8_t d_formalCharge
        44 |   boost::uint8_t d_atomicNum
        45 |   boost::int8_t d_implicitValence
        46 |   boost::int8_t d_explicitValence
        47 |   boost::uint8_t d_numRadicalElectrons
        48 |   boost::uint8_t d_chiralTag
        49 |   boost::uint8_t d_hybrid
        50 |   boost::uint16_t d_isotope
        52 |   atomindex_t d_index
        56 |   class RDKit::ROMol * dp_mol
        64 |   class RDKit::AtomMonomerInfo * dp_monomerInfo
           | [sizeof=72, dsize=72, align=8,
           |  nvsize=72, nvalign=8]
```

The `Bond` class goes from 72 bytes to 80 bytes, which isn't particularly bad.

**Comment by mwojcikowski** [comment]
I've changed the order as @greglandrum have suggested.

**Comment by greglandrum** [comment]
LGTM
@bp-kelley: are you ok with this now?

**Comment by bp-kelley** [comment]
@mwojcikowski @greglandrum I'm good with this, should we apply it after the Atom/Bond storage changes from #1699?

**Comment by greglandrum** [comment]
That makes sense to me

**Comment by mwojcikowski** [comment]
#1713 has been merged, are we ready with this PR?

**Comment by mwojcikowski** [comment]
I've rerun the tests (AppVeyor had 500 Internal error before) and rebased the PR. I think we are ready to merge.

**Comment by greglandrum** [comment]
@mwojcikowski : this is a change that shouldn't happen on master; it's got to be done on the modern_cxx branch (where the rest of the new development is happening).

Once I've cherry-picked your recent changes across to that branch (hopefully today), I'll also cherry-pick this stuff, make sure that it doesn't bloat atoms/bonds too much, and then do a PR from there.

**Comment by greglandrum** [comment]
Closing this since it was merged as #1742.
Thanks @mwojcikowski !

**Pull request closed without merging**
