### PR TITLE
Improvements to bounds-matrix construction for highly constrained systems.

### LINKED ISSUE #697: More ChEMBL molecules that fail bounds smoothing
```python
['C=C1NC(=O)C(C(C)C)NC(=O)C(C(C)CC)NC(=O)c2nc(oc2-c2ccccc2)-c2coc(n2)-c2csc(n2)-c2coc(n2)-c2coc1n2', 
'CCC(C)C1NC(=O)c2nc(oc2-c2ccccc2)-c2coc(n2)-c2csc(n2)-c2coc(n2)-c2coc(n2)CNC(=O)C(C(C)C)NC1=O', 
'CCC(C)C1NC(=O)c2nc(oc2-c2ccccc2)-c2coc(n2)-c2csc(n2)-c2coc(n2)-c2coc(n2)C(COC(C)=O)NC(=O)C(C(C)C)NC1=O', 
'CCC(C)C1NC(=O)c2nc(oc2-c2ccccc2)-c2coc(n2)-c2csc(n2)-c2coc(n2)-c2coc(n2)C(COC(=O)COCCOCCOC)NC(=O)C(C(C)C)NC1=O',
'C=C1NC(=O)C(C(C)C)NC(=O)C(C(C)CC)NC(=O)c2nc(oc2-c2ccccc2)-c2coc(n2)-c2csc(n2)-c2coc(n2)-c2nc1oc2C', 
'C=C1NC(=O)C(C(C)C)NC(=O)C(C(C)CC)NC(=O)c2nc(oc2-c2ccccc2)-c2nc(oc2C)-c2csc(n2)-c2coc(n2)-c2nc1oc2C',
'CCC(C)C1NC(=O)c2nc(oc2-c2ccccc2)-c2coc(n2)-c2csc(n2)-c2coc(n2)-c2coc(n2)C(COC(=O)COCCOC)NC(=O)C(C(C)C)NC1=O',
'C=C1NC(=O)C(C(C)C)NC(=O)C(C(C)CC)NC(=O)c2nc(oc2-c2ccccc2)-c2nc(oc2C)-c2csc(n2)-c2coc(n2)-c2coc1n2',
'CCC(C)C1NC(=O)c2nc(oc2-c2ccccc2)-c2coc(n2)-c2csc(n2)-c2coc(n2)-c2coc(n2)C(COC(=O)C(N)CCCNC(=N)N)NC(=O)C(C(C)C)NC1=O']
```

### PR DESCRIPTION
**Pull request by greglandrum**
Fixes #697

### CODE REVIEW

**Comment by bp-kelley** [comment]
If you're satisfied with the tests and re-perception of the stereo post bounds matrix is not needed, I'm happy to merge.

**Comment by greglandrum** [comment]
Let me do one more commit to remove the duplicated code. My local tests are running now, should be checked in in the next 5-10 minutes.

**Comment by greglandrum** [comment]
ok, those are in.

**Comment by greglandrum** [comment]
Tests pass, so I merged.

**Pull request merged**
