### PR TITLE
Expose RascalMCES singleLargestFrag option to Python.

### PR DESCRIPTION
**Pull request by DavidACosgrove**
#### Reference Issue
No issue.

#### What does this implement/fix? Explain your changes.
Exposes the singleLargestFrag option of RascalMCES::RascalOptions to the Python wrapper.

#### Any other comments?
Writing documentation is always valuable!

### CODE REVIEW

**Review by greglandrum — CHANGES_REQUESTED** [review]
I think it would be useful to have something in the documentation explaining what exactly this means and how/why it's different from what you get by calling `largestFragmentOnly()`

**Comment by DavidACosgrove** [comment]
It might be worth leaving it until I finish writing the documentation and adding all the other bits that turn out to be missing from the Python wrapper.  I'll let you know...

**Comment by DavidACosgrove** [comment]
Ok, I think that is now good for review again.  It's remarkable how much wasn't in the Python wrapper :-(.

**Review by greglandrum — APPROVED** [review]
LGTM

**Pull request merged**
