### PR TITLE
preparing readme for javascript minimallib release 2021.3.2 on npm

### PR DESCRIPTION
**Pull request by MichelML**
#### Reference Issue
None.

#### What does this implement/fix? Explain your changes.
NPM release of minimallib JS for 2021.3.2

#### Any other comments?
Let me know :)

### CODE REVIEW

**Comment by greglandrum** [comment]
@MichelML : it's a pain to have to do this for each release.
Maybe we can think of a way to change the readme so that it doesn't require updating like this?

**Comment by MichelML** [comment]
Agree @greglandrum , but related to https://github.com/rdkit/rdkit/discussions/4124

I plan on moving it out of this repository soon enough, hopefully before the next quarter release. So we can merge this one for now and yes we'll abstract this process out of the repo.

**Comment by MichelML** [comment]
Update:

This still stands https://github.com/rdkit/rdkit/pull/4133#issuecomment-839792638

But if you don't specify the unpkg version , it actually takes the latest version of the npm releases. So, no more PR like this after this one ;) 

You can test here https://unpkg.com/@rdkit/rdkit/Code/MinimalLib/dist/GettingStartedInJS.html

**Comment by MichelML** [comment]
It failed because of timeout only it seems.

**Comment by greglandrum** [comment]
> It failed because of timeout only it seems.

yeah, the mac builds have been doing that a lot lately

**Review by greglandrum — APPROVED** [review]

**Pull request merged**
