### PR TITLE
Fix github1240

### PR DESCRIPTION
**Pull request by greglandrum**
This solves the immediate problem of not being able to embed large aromatic rings and should help with large rings in general.
The simple solution was to no longer by default assume cis geometries in rings with 8 or more members (we can think about changing that threshold).

@sriniker : this is another one for you if you have a few moments.

### CODE REVIEW

**Comment by sriniker** [comment]
Looks good to me. I assume you checked that the relaxed tolerance criteria do not affect the planarity and/chirality of other compounds.

**Comment by greglandrum** [comment]
I looked at some (not a huge number) output structures and they seemed ok.
I believe that this shouldn't change the results of the minimizations at all, it should just allow more highly strained structures to go through.

**Comment by greglandrum** [comment]
@bp-kelley : unless you have objections, I will merge this Tuesday and do the release.

**Comment by bp-kelley** [comment]
Works for me.  I don't have much to say on the dg approaches, so I'll defer to you both.

**Pull request merged**
