### PR TITLE
[CI] add csharp build on windows

### PR DESCRIPTION
**Pull request by greglandrum**
make sure the swig wrappers for csharp build

This is not currently running any tests

### CODE REVIEW

**Comment by greglandrum** [comment]
@jones-gareth : this adds a build of the csharp wrappers on Windows to the CI pipeline.
There aren't any tests built by cmake for those wrappers, so this really just tests that the builds are working.

It probably wouldn't be a terrible idea to add some tests if we can figure out how to do so, but I think having the changes in this PR in place would already help make sure the csharp wrappers don't break. 

What do you think?

**Comment by jones-gareth** [comment]
> @jones-gareth : this adds a build of the csharp wrappers on Windows to the CI pipeline. There aren't any tests built by cmake for those wrappers, so this really just tests that the builds are working.
> 
> It probably wouldn't be a terrible idea to add some tests if we can figure out how to do so, but I think having the changes in this PR in place would already help make sure the csharp wrappers don't break.
> 
> What do you think?

Yes, it will be helpful to know that PRs can no longer break the C# wrappers.  I will take a look and see what is required to create a command line test runner for the small number of tests we have.  It is simple enough, but I don't know it will work in Azure.

**Comment by greglandrum** [comment]
> > 
> 
> > What do you think?
> 
> 
> 
> Yes, it will be helpful to know that PRs can no longer break the C# wrappers.  I will take a look and see what is required to create a command line test runner for the small number of tests we have.  It is simple enough, but I don't know it will work in Azure.

I am happy to play around with figuring that out if you can figure out how to get cmake to build the tests.

**Comment by greglandrum** [comment]
did a self-merge on this one since it's just adding a new CI builds

**Pull request merged**
