### PR TITLE
Allow WriteSDF to create v3000 SDF files

### PR DESCRIPTION
**Pull request by jkhales**
#### What does this implement/fix? Explain your changes.

This allows the sdf files to be saved to v3000 files

### CODE REVIEW

**Review by greglandrum — CHANGES_REQUESTED** [review]
@jkhales thanks for the contribution!
The code change looks good, but it needs a test for the new functionality to be added before it can be merged.
Please add a test in `UnitTestPandasTools.py` that tests that the output SDF is actually being written as V3000. I'm happy to answer any questions you may have about how to do this.

**Comment by jkhales** [comment]
> @jkhales thanks for the contribution! The code change looks good, but it needs a test for the new functionality to be added before it can be merged. Please add a test in `UnitTestPandasTools.py` that tests that the output SDF is actually being written as V3000. I'm happy to answer any questions you may have about how to do this.

Hi @greglandrum how do these tests look?

**Comment by jkhales** [comment]
@greglandrum Just wanted to bump this guy so it's not forgotten! 🙏

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
@jkhales Thanks for the contribution!

**Comment by greglandrum** [comment]
> @greglandrum Just wanted to bump this guy so it's not forgotten! pray

Thanks for the ping.

**Pull request merged**
