### PR TITLE
Make it easy to calculate all 2D descriptors

### PR DESCRIPTION
**Pull request by greglandrum**
Adds `Descriptors.CalcMolDescriptors()`
Also adds a section to the documentation for this use case.

I really should have added this function years ago.

### CODE REVIEW

**Comment by thegodone** [comment]
Is it possible to do spécial handle forIpc => average or log conversion directly in the call ?Envoyé de mon iPhoneLe 23 déc. 2022 à 08:59, Greg Landrum ***@***.***> a écrit :﻿Adds Descriptors.CalcMolDescriptors()
I really should have added this function years ago.



You can view, comment on, or merge this pull request online at:
  https://github.com/rdkit/rdkit/pull/5892

Commit Summary

  cba3dde  remove deprecation warning
  22edb97  add CalcMolDescriptors() function


File Changes  (3 files)

  
    M
    rdkit/Chem/Descriptors.py
    (29)
  
  
    M
    rdkit/Chem/Graphs.py
    (5)
  
  
    M
    rdkit/Chem/UnitTestDescriptors.py
    (7)
  


Patch Links:

  https://github.com/rdkit/rdkit/pull/5892.patch
  https://github.com/rdkit/rdkit/pull/5892.diff

**Comment by bp-kelley** [comment]
As I recall, that was the driving force for the properties class:

https://github.com/rdkit/rdkit/blob/3f3bc3b5a18b9a4afadf40d3e265f679b9f21d96/Code/GraphMol/Descriptors/Property.h#L70

This requires the properties to be registered though.

**Comment by greglandrum** [comment]
Yeah, and that's something that requires a manual step and that we've never really managed to keep up with. 

Still, I will take a look tomorrow and see if I can automate that part

**Comment by greglandrum** [comment]
@bp-kelley : I added code which automates adding all descriptors which are implemented in Python to the Properties registry when `rdkit.Chem.Descriptors` is imported.

I still think the pure python implementation in this PR is useful because it gives you back the dictionary and allows control over what happens when exceptions are thrown during the descriptor calculation.

**Comment by bp-kelley** [comment]
Something odd is happening here, it might take a while to track down.

**Comment by greglandrum** [comment]
Hmmm, yeah, I will check tomorrow. If I can't find it quickly I will back the Property changes out and we can think about doing it in a separate PR. I'm not sure it actually adds that much value (particularly given that we haven't done it until this point)

**Comment by bp-kelley** [comment]
I agree, the properties class also doesn’t cover the python only calculations.

**Comment by greglandrum** [comment]
@bp-kelley I couldn't find a solution to the problems caused my code doing the bulk addition to the property interface, so I ripped that stuff back out of this PR. We can take a look at adding the python descriptors to the property interface separately if we decide that it's useful/relevant.

For future reference, the problem I observed on my windows laptop was that a single call to `_registerDescriptorsAsProperties()` would give a weird GIL error when python exited:
```
(base)
glandrum@ferret MINGW64 ~/RDKit_git/builds/win64_opt (feat/easier_descriptor_calculation)
$ python -c 'from rdkit.Chem import rdMolDescriptors;from rdkit import Chem;from rdkit.Chem import Descriptors;m=Chem.MolFromSmiles("CCCC");ps=rdMolDescriptors.Properties(["Ipc"]);print(ps.ComputeProperties(m)[0])'
6.854752972273345
Fatal Python error: PyThreadState_Get: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)
Python runtime state: finalizing (tstate=0x00000188f65ae0a0)
```
but calling that function a second time would resolve it:
```
(base)
glandrum@ferret MINGW64 ~/RDKit_git/builds/win64_opt (feat/easier_descriptor_calculation)
$ python -c 'from rdkit.Chem import rdMolDescriptors;from rdkit import Chem;from rdkit.Chem import Descriptors;Descriptors._registerDescriptorsAsProperties();m=Chem.MolFromSmiles("CCCC");ps=rdMolDescriptors.Properties(["Ipc"]);print(ps.ComputeProperties(m)[0])'
6.854752972273345
(base)
```


Also for future reference, since that code will vanish when we squash commits, here's the code I just removed:
```
# machinery to add all the descriptors here to the Properties interface:
def _propCtor(self,name,func):
  PropertyFunctor.__init__(self,name,getattr(func,'version','1.0.0'))
  self._func = func

def _registerDescriptorsAsProperties():
  # the cases in property names are sometimes weird, so normalize that
  ps = rdMolDescriptors.Properties()
  allProps = [x.lower() for x in ps.GetPropertyNames()]  
  for nm,func in _descList:
    if nm.lower() in allProps:
      continue
    cls = type("_"+nm+"Prop",(PropertyFunctor,),
        {'__init__':lambda self,name=nm,func=func:_propCtor(self,name,func),
         '__call__':lambda self,mol:self._func(mol)})
    rdMolDescriptors.Properties.RegisterProperty(cls())    

_registerDescriptorsAsProperties()
```

**Review by bp-kelley — APPROVED** [review]

**Pull request merged**
