### PR TITLE
removed unused and outdated file rdkit/Chem/PeriodicTable.py

### PR DESCRIPTION
**Pull request by UnixJunkie**
#### Reference Issue

related to https://github.com/rdkit/rdkit/issues/1831

#### What does this implement/fix? Explain your changes.

rm an unused file that may mislead potential users and contributors

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Rdkit still compiles after I removed this file.
Is there some test suite I should run after such a change?

**Comment by greglandrum** [comment]
There is a test suite that's run automatically (the Travis CI builds), but it's always a good idea to run the tests yourself.
It's currently only straightforward to do this comprehensively if you've run a build (described here: http://rdkit.org/docs/Install.html#testing-the-build-optional-but-recommended), but you can run most of the python tests by doing:
```
cd $RDBASE/rdkit
python ./TestRunner.py 
```

**Comment by greglandrum** [comment]
If you look at the details of the failing travis-ci tests, you'll see that there is at least one place that the `PeriodicTable.py` file was included; that needs to be fixed.

**Comment by UnixJunkie** [comment]
Ok, I pushed some more changes to the branch.

**Comment by greglandrum** [comment]
The tests are still failing; if you look at the log messages in Travis-ci (there’s a link there), you will see where at least one of the problems lies

**Comment by UnixJunkie** [comment]
Ok, I pushed one more change.
Soon, I hope I will manage to run the unit tests locally...

**Comment by UnixJunkie** [comment]
CI tests say:
```
97% tests passed, 4 tests failed out of 156
Total Test time (real) = 382.68 sec
The following tests FAILED:
	 85 - pyMolDescriptors (Failed)
	149 - pythonTestDbCLI (Failed)
	150 - pythonTestDirML (Failed)
	155 - pythonTestDirChem (Failed)
Errors while running CTest
```
Should we have 100% passing?

**Comment by greglandrum** [comment]
Yes, the tests all need to pass. Please check the error messages; they will point to where the problems are.

**Comment by UnixJunkie** [comment]
```
The following tests FAILED:
	 85 - pyMolDescriptors (Failed)
	149 - pythonTestDbCLI (Failed)
	150 - pythonTestDirML (Failed)
	155 - pythonTestDirChem (Failed)
```

**Comment by greglandrum** [comment]
Sorry, I could have been more explicit:
If you go to the build page in travis (linked from the PR page where the build failure is reported), you can open the log. Scrolling to the bottom in that and then back up until you find the first exception message, you find things like this:
https://travis-ci.com/rdkit/rdkit/jobs/156277955#L4741

**Comment by greglandrum** [comment]
This process would go a lot quicker for you if you ran the tests on your local build.

**Comment by UnixJunkie** [comment]
I haven't forgotten this one.
I am just busy with other things.
I have the unit tests working locally, it is just that they force me to use conda, which I don't like.

**Comment by UnixJunkie** [comment]
Sorry for the probably stupid question, but what is the meaning of RBO (a column name in src/rdkit/rdkit/Chem/PeriodicTable.py)?

**Comment by UnixJunkie** [comment]
How can I access this radius for a given atom in modern rdkit?
It seems I need this info to update old code that look like this
```
     rA = PeriodicTable.nameTable[symb][5]
```

**Comment by greglandrum** [comment]
That was the change I made here: https://github.com/rdkit/rdkit/pull/2141/commits/15cd2b8083e91e489cc94e1504f7f12cdd72f186#diff-cc9def0faf51a62060b5de6b2c2ff00fR79
and looks like this: `ptable.GetRb0(mol.GetAtomWithIdx(i).GetAtomicNum())`

**Comment by UnixJunkie** [comment]
I updated the PR.
Sorry for the stupid question, I found this info previously, but since I did not work on the PR for long time, I completely forgot...

**Comment by UnixJunkie** [comment]
This compiles on my machine, however ctest has many failures (104 tests failed out of 156).
But, since I am too lazy and don't have time to make the test suite work on my machine,
I will wait for the CI tests to tell me which tests are really failing.

**Comment by greglandrum** [comment]
Everything looks good. Merging now.

**Comment by greglandrum** [comment]
Thanks @UnixJunkie !

**Pull request merged**
