### PR TITLE
Reaction stereo mapped to non-bonded atoms causes exception

### LINKED ISSUE #3155: Unexpected errors within the substructure matching routine caused by hydrogens
If there are specific inconsistencies between the search query and the query within the database (e.g., explicit hydrogens), then the reaction substructure search routine fails with an error and the expected hit is not present in the results list. Interestingly, a search of the query against itself works fine and also a match of the corresponding DB content against itself works fine. 

RDkit-search-error (1)

I've tried to sanitize these queries but this did not help since the hydrogen did not get removed. How can I ensure that my search finds all relevant hits in the database?

### PR DESCRIPTION
**Pull request by bp-kelley**
fixes #3155 

The fix is to not mapped stereo in these cases.

### CODE REVIEW

**Comment by bp-kelley** [comment]
Now, the real question is:  Is this a borked reaction that we should raise an exception for?

**Comment by greglandrum** [comment]
Are you sure that this isn't a fix related to #3147?

**Comment by bp-kelley** [comment]
It sure is.  Let me fix and recheck in.. Btw there is a seg fault in the standardizer now, I can't see how this is related but I'll check.

**Comment by bp-kelley** [comment]
Moved it to https://github.com/rdkit/rdkit/pull/3196

**Pull request closed without merging**
