### PR TITLE
Add support for Tversky similarity to the FPB reader

### PR DESCRIPTION
**Pull request by greglandrum**
This whole thing could use a bit more testing, but the coverage isn't terrible as-is.

### CODE REVIEW

**Comment by bp-kelley** [comment]
I'm reviewing this now, but it looks like we can't merge to master.  Could you fix this when you have a moment?

**Comment by greglandrum** [comment]
damn it... will do it now

**Comment by greglandrum** [comment]
this is because of the damn line ending problem I fixed (I hope) in testFMCS_Unit.cpp

**Comment by bp-kelley** [comment]
God that file is pissing me off :)

----
Brian Kelley

**Comment by greglandrum** [comment]
Ok, it's ready to go.

**Comment by greglandrum** [comment]
@bp-kelley : you ok with this now?

**Comment by bp-kelley** [comment]
I'm going to do one last test and it should be merged in today.

**Comment by bp-kelley** [comment]
Finally :)

**Comment by bp-kelley** [comment]
I'm still going to profile though :)  Nice work, by the way.

**Pull request merged**
