### PR TITLE
Remove extra calls to python::register_exception_translator

### PR DESCRIPTION
**Pull request by greglandrum**

### CODE REVIEW

**Comment by bp-kelley** [comment]
Looks fine, I'll try to do a windows build just to be sure.  Where is the remaining call to python::register_exception_translator?

**Comment by greglandrum** [comment]
Each of the exceptions used is registered at what I think is the "most generic" point.
For example `ValueError` and `IndexError`, which could appear anywhere, are in rdBase,
`MolSanitizeException` is in rdchem, etc.

**Comment by greglandrum** [comment]
@bp-kelley : ok to merge this?

**Comment by bp-kelley** [comment]
This one completely fell of the radar with the depiction fixes!

**Pull request merged**
