### PR TITLE
Fixes #4785: aromatic bonds no longer set aromatic flags on atoms

### LINKED ISSUE #4785: MDL query with aromatic bond sets aromatic flag on atoms even though they are not in an aromatic ring
This query drawn in MarvinJS
image
resolves to this MDL query that can't be read by RDKit:
```
Chem.MolFromMolBlock("""
  MJ201100                      

  2  1  0  0  0  0  0  0  0  0999 V2000
   -0.3538    0.6163    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0668    0.2012    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  4  0  0  1  0
M  MRV SMA   1 [#6;a;a]
M  MRV SMA   2 [#6;a;a]
M  END
""")
RDKit ERROR: [21:44:20] non-ring atom 0 marked aromatic
[21:44:20] non-ring atom 0 marked aromatic
```
Similarly
```
Chem.MolFromMolBlock("""
  MJ201100                      

  2  1  0  0  0  0  0  0  0  0999 V2000
   -0.3538    0.6163    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0668    0.2012    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  4  0  0  1  0
M  END
""")
RDKit ERROR: [21:44:47] non-ring atom 0 marked aromatic
[21:44:47] non-ring atom 0 marked aromatic
```
Skipping sanitization and removing the aromatic flags from atoms allows to sanitize:
```
mol = Chem.MolFromMolBlock("""
  MJ201100                      

  2  1  0  0  0  0  0  0  0  0999 V2000
   -0.3538    0.6163    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0668    0.2012    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  4  0  0  1  0
M  END
""", sanitize=False)
mol.GetAtomWithIdx(0).SetIsAromatic(False)
mol.GetAtomWithIdx(1).SetIsAromatic(False)
Chem.SanitizeMol(mol)
rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE
mol
```
image
However, attempting to generate a molblock gives the same molblock that can't be parsed:
```
print(Chem.MolToMolBlock(mol))

     RDKit          2D

  2  1  0  0  0  0  0  0  0  0999 V2000
   -0.3538    0.6163    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0668    0.2012    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  4  0  0  1
M  END
Chem.MolFromMolBlock(Chem.MolToMolBlock(mol))
RDKit ERROR: [21:52:26] non-ring atom 0 marked aromatic
[21:52:26] non-ring atom 0 marked aromatic
```

### PR DESCRIPTION
**Pull request by greglandrum**
This also adds a new function: `RDKit::isAromaticAtom()`, which returns true for atoms which either have their aromatic flag set or which have an aromatic bond to them.

### CODE REVIEW

**Comment by greglandrum** [comment]
@ptosco this isn't ready for review yet

**Comment by bp-kelley** [comment]
This looks good to me, my only comment is that 

```
RDKit::isAromaticAtom()
```

behaves differently than

```
atom->getIsAromatic()
```

The name doesn't make it obvious.  perhaps RDKit::isAromaticAtomInContext?  This isn't a big deal for me btw, just a naming observation.

**Comment by greglandrum** [comment]
> The name doesn't make it obvious. perhaps RDKit::isAromaticAtomInContext? This isn't a big deal for me btw, just a naming observation.

Yeah, I struggled to come up with a different/better name for it but totally failed. I guess we could do `RDKit::atomIsAromaticOrHasAromaticBonds()`? That's super descriptive, and if you're using an IDE also not too terrible to type/

**Comment by bp-kelley** [comment]
I can't think of a great name either, so the original might be ok.

**Review by ptosco — APPROVED** [review]
I'd leave it as is - the comment documents what the function does and it is meant for developers (i.e., it is not exposed to Python) so I think it's fine.

**Pull request merged**
