### PR TITLE
fix doxygen comments

### PR DESCRIPTION
**Pull request by e-kwsm**
For example,
```cpp
int x;  //! comment for x
int y;
```
is equivalent to
```cpp
int x;
//! comment for x
int y;
```
i.e. that is a Doxygen comment for *y*; it should be
```cpp
int x;  //!< comment for x
int y;
```

https://www.doxygen.nl/manual/docblocks.html#memberdoc

### CODE REVIEW

**Review by greglandrum — CHANGES_REQUESTED** [review]
The code changes look fine to me, but please provide at least a bit of information in the PR description.

**Comment by e-kwsm** [comment]
For example,
```cpp
int x;  //! comment for x
int y;
```
is equivalent to
```cpp
int x;
//! comment for x
int y;
```
i.e. that is a Doxygen comment for *y*; it should be
```cpp
int x;  //!< comment for x
int y;
```

https://www.doxygen.nl/manual/docblocks.html#memberdoc

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
@e-kwsm I think this is ready to merge. Do you agree?

**Comment by e-kwsm** [comment]
Yes.

**Pull request merged**
