### PR TITLE
update cookbook, draw molecule with atom indices

### PR DESCRIPTION
**Pull request by nbehrnd**
#### Reference Issue

By default, RDKit 2023.09.3 does not explicitly displays atom index 0.

#### What does this implement/fix? Explain your changes.

This updates the corresponding illustration in the RDKit cookbook,
section "Drawing Molecules (Jupyter)", sub section "Include an Atom Index".

#### Any other comments?

Installation of RDKit 2023.09.3-2 as provided by Linux Debian 13/trixie,
branch testing.

### CODE REVIEW

**Review by greglandrum — CHANGES_REQUESTED** [review]
@nbehrnd thanks for fixing this
I think it would be good to briefly mention in the text that atom index zero is not drawn.

Maybe something like "A drawback of this approach is that atom index zero is not shown."

**Comment by nbehrnd** [comment]
@greglandrum Before the addition of a note, the second approach was tested (which displays all atom indices including zero).

However I do not perceive the absence of an explicit marker `C:0` as a drawback.  Because it is not possible to search for an atom by index with `Ctrl + F` in the visual output while running the Jupyter notebook, e.g. with string `N:10`, it actually helps me for me to identify the particular atom; it is the only one which isn't labeled.  This is why the display of the complete set (including index zero) by the second recipe is perceived as a complement to the former.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
Thanks for the contribution @nbehrnd !

**Pull request merged**
