### PR TITLE
Fixes #678

### LINKED ISSUE #678: failure in AddHs when addCoords is true and coords are all zero
```
In [55]:

print(suppl.GetItemText(45))
CHEMBL3186637


 37 39  0     1  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  1  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  8  1  0  0  0  0
  1 19  1  0  0  0  0
  2 20  1  0  0  0  0
  2 25  1  0  0  0  0
  3 19  2  0  0  0  0
  4 24  1  0  0  0  0
  5 25  2  0  0  0  0
  6  7  1  0  0  0  0
  6  8  1  0  0  0  0
  6  9  1  0  0  0  0
  6 30  1  0  0  0  0
  7 10  1  0  0  0  0
  7 13  1  0  0  0  0
  7 31  1  0  0  0  0
  8 11  1  0  0  0  0
  8 32  1  0  0  0  0
  9 14  2  0  0  0  0
  9 15  1  0  0  0  0
 10 16  1  0  0  0  0
 10 17  1  0  0  0  0
 10 33  1  0  0  0  0
 11 12  1  0  0  0  0
 12 14  1  0  0  0  0
 12 21  1  0  0  0  0
 12 34  1  0  0  0  0
 13 18  1  0  0  0  0
 15 16  2  0  0  0  0
 18 20  1  0  0  0  0
 19 22  1  0  0  0  0
 20 23  1  0  0  0  0
 20 35  1  0  0  0  0
 22 27  1  0  0  0  0
 22 28  1  0  0  0  0
 22 36  1  0  0  0  0
 23 24  1  0  0  0  0
 24 26  1  0  0  0  0
 24 37  1  0  0  0  0
 25 26  1  0  0  0  0
 27 29  1  0  0  0  0
M  END
> <chembl_id>
CHEMBL3186637

$$$$

In [56]:

Chem.AddHs(m,addCoords=True)
m = suppl[45]
Chem.AddHs(m,addCoords=True)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-56-0dcb96667c60> in <module>()
      1 m = suppl[45]
----> 2 Chem.AddHs(m,addCoords=True)

RuntimeError: Post-condition Violation

In [57]:

Chem.AddHs(m)
Out[57]:
<rdkit.Chem.rdchem.Mol at 0x7f658eca7ee8>
```

### PR DESCRIPTION
**Pull request by greglandrum**
Checks for degenerate coordinates when trying to figure out where Hs should be placed.

### CODE REVIEW

**Comment by bp-kelley** [comment]
I think this is ok, but I do have two questions.

1. Does adding H coords make sense if the molecules is 1D (smiles) or 2D (drawing)?  This is a relatively simple check.

2. Why are we putting the Hydrogen (I'm assuming) on the heavy atom coordinate?  I'm assuming that this is just convenient and doesn't blow up the math.

**Comment by greglandrum** [comment]
1. The RDKit has no concept of 1D, aside from molecules that just don't have conformations. Though the function ends up being called, it won't actually do anything then. Adding coordinates for Hs in 2D certainly makes sense. This 3D approach is, of course, probably not the best way to do that.

2. Assigning them to the heavy atom coords is arbitrary. I could have just as easily placed them all at the origin.

**Comment by greglandrum** [comment]
@bp-kelley, ok if I go ahead and merge this?

**Comment by bp-kelley** [comment]
Go ahead, interesting github tidbit:

"Pull requests that have a failing status can’t be merged from a phone."

I'm working from the bar protection?

**Comment by greglandrum** [comment]
That's an excellent feature.

**Pull request merged**
