### PR TITLE
Remove the redundant iterator_next header

### PR DESCRIPTION
**Pull request by rvianello**
#### What does this implement/fix? Explain your changes.
I experienced this error while building RDKit with `RDK_BUILD_COMPRESSED_SUPPLIERS=ON`:

```======================================================================
ERROR: test56LazySDMolSupplier (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspaces/rdkit-devel/rdkit/Code/GraphMol/Wrap/rough_test.py", line 2576, in test56LazySDMolSupplier
    for mol in sdSup:
TypeError: iter() returned non-iterator of type '_CompressedSDMolSupplier'

----------------------------------------------------------------------
```
The error was apparently due to `CompressedSDMolSupplier` not implementing the expected `__next__` method.

While fixing it, I decided to take the occasion to clean-up the implementation of these python iterators, and remove the support for python2.

#### Any other comments?
I most often forget to enable the compressed suppliers, but I it was surprising to me that maybe they never worked with python3?

### CODE REVIEW

**Comment by greglandrum** [comment]
@rvianello yeah, I never build these, so it could well be that they never worked with python3.

I'd be happy to merge this as-is, but if you were to do a version of the PR that doesn't remove `iterator_next.h` then we can do that as a bug fix for the next patch release followed by a separate PR that removes the now-redundant header file that can go in the 2020.09 release

let me know if you're ok with that.

**Comment by rvianello** [comment]
@greglandrum yes, of course, I didn't think about the release management, I'll push a change restoring the removed header file.

Or I can also create a separate PR, only including the commit for `CompressedSDMolSupplier`, just let me know which one would work better.

**Comment by greglandrum** [comment]
@rvianello makes no difference to me; whichever is easier for you is fine.

**Comment by rvianello** [comment]
sounds good. I'll then create a second PR, it's simpler and I would be otherwise likely to forget about creating a PR to remove the redundant file again at a later time.

**Pull request merged**
