### PR TITLE
Update CPack to create .deb files correctly

### PR DESCRIPTION
**Pull request by psavery**
#### Reference Issue

#911

#### What does this implement/fix? Explain your changes.
The cmake install components have had their names changed since CPack was last used. "headers" and "static_libs" are in "dev", and "dynamic_libs" are a part of "runtime".

This updates their names to be correct.

### CODE REVIEW

**Comment by psavery** [comment]
The cmake commands you need to generate the cpack files for DEB correctly are as follows (inside a build directory that is in the rdkit root):

`cmake .. -DRDK_INSTALL_INTREE=OFF -DCMAKE_INSTALL_PREFIX=/usr/`
`cpack -G DEB`

This will generate 4 deb files: 
RDKit-2017.9.18-Linux-Development.deb
RDKit-2017.9.18-Linux-Extras.deb
RDKit-2017.9.18-Linux-Python.deb
RDKit-2017.9.18-Linux-Runtime.deb

However, I am not sure that I matched up the components with the packages in the best way possible. For instance, I put "runtime" in both Development and Runtime - because some people might need the .so files in Development if they wish to link dynamically to rdkit. But this adds redundancy. Should the .so files only be in Runtime?

Let me know what you think.

**Comment by psavery** [comment]
And by the way, I tried it out with python. If I installed the Python .deb file and the Development .deb file, and I open up Python and type "import rdkit", it seems to work and loads the .so files correctly.

**Comment by psavery** [comment]
Oh, and about the redundancy - it looks like components can only go in one group anyways. It put the .so files in "Development" and not in "Runtime". Assigning the runtime component to "Development" appears to have overwritten the first assignment to "Runtime".

**Comment by psavery** [comment]
I just pushed an update - the .so files are now only installed in the runtime .deb file.

I think the .deb files that it generates should work, then. The only other think I guess we should add is dependency packages - like if someone were to install the "python" one, it would see that "runtime" is a dependency and install that as well. There may be a way to do this in cpack, but I'm not sure.

I'm also not sure if there are other things we need to do the .deb files to make it accepted in the debian/ubuntu packaging system.

**Comment by greglandrum** [comment]
Thanks for taking this on. I will take a look after this week's UGM.

**Comment by psavery** [comment]
It does look like cmake can handle a lot of deb stuff (including dependencies): https://cmake.org/cmake/help/v3.0/module/CPackDeb.html

We could potentially add a new cmake file with all the deb CPack settings in it. This looks like a good example: https://github.com/thomas-moulard/visp-deb/blob/master/CMakeModules/CPackConfigDeb.cmake

I looked up the dependencies of the rdkit deb files currently on Ubuntu and this is what I get. I guess we will probably have similar dependencies (except maybe some updates to versions - not sure).

$ apt-cache depends librdkit-dev 
librdkit-dev
  Depends: librdkit1

$ apt-cache depends librdkit1
librdkit1
  Depends: libboost-python1.58.0
  Depends: libboost-regex1.58.0
  Depends: libboost-system1.58.0
  Depends: libboost-thread1.58.0
  Depends: libc6
  Depends: libgcc1
  Depends: libpython2.7
  Depends: libstdc++6

**Comment by UnixJunkie** [comment]
That would be nice if this is merged. Then creating a Ubuntu PPA should be a joke.

**Comment by UnixJunkie** [comment]
I also vote for inchi support being on by default.

**Comment by UnixJunkie** [comment]
On ubuntu, I also need this to compile: libeigen3-dev.
Is this only a compile-time dependency?

**Comment by greglandrum** [comment]
Yes, eigen3 is compile-time only.

**Comment by greglandrum** [comment]
Sorry I'm slow on reviewing/merging this. Now that the release is out of the way I should have some more time for it.

**Comment by UnixJunkie** [comment]
someone on the ML just asked for recent binary RPMs ...

**Comment by greglandrum** [comment]
It looks like the .deb for python doesn't include any of the extension modules:
```
ubuntu@ubuntu-xenial:~/rdkit/build$ ls /usr/lib/python2.7/dist-packages/rdkit/
Avalon     DataStructs       ForceField  Numerics     RDRandom.py    VLib            epydoc.config  utils
Chem       Dbase             Geometry    RDConfig.py  SimDivFilters  __init__.py     six.py
DataManip  DistanceGeometry  ML          RDLogger.py  TestRunner.py  _py2_pickle.py  sping
```
This can probably be fixed in `RDKitUtils.cmake`, and I will look into that.

**Comment by psavery** [comment]
I accepted that PR, and it looks like the checks passed!

**Comment by greglandrum** [comment]
As far as I can tell this works, so I'm going to go ahead and merge it. Thanks @psavery

**Comment by UnixJunkie** [comment]
I might look at creating a PPA for Ubuntu tomorrow, thanks to all of this.

**Comment by psavery** [comment]
Okay. I think we would just need to make sure that the appropriate dependencies (the boost libraries and anything else) are downloaded as well.

**Pull request merged**
