### PR TITLE
MolEnumerator::enumerate() should call updatePropertyCache()

### PR DESCRIPTION
**Pull request by greglandrum**
For efficiency reasons we don't want to do a full sanitization, but It doesn't make any sense to require client code to do this.

### CODE REVIEW

**Comment by bp-kelley** [comment]
@greglandrum Is ring detection done as well?

**Comment by greglandrum** [comment]
@bo-Kelley: no, that’s more expensive, and less broadly necessary,  so I hesitate to do it automatically

**Comment by bp-kelley** [comment]
What is the standard workflow post molecule enumeration?  Do you envision
it like reactions where a mol standardization is almost mandatory?  Are all
enumerations "guaranteed" to be sanitizable?

**Comment by greglandrum** [comment]
> What is the standard workflow post molecule enumeration? Do you envision it like reactions where a mol standardization is almost mandatory? Are all enumerations "guaranteed" to be sanitizable?

I think it's very much the same as reactions: the enumeration produces unsanitized molecules. If you need them sanitized, you should do so. The idea with this PR is to make common things a bit easier by making sure the atoms in the molecule at least have the valences assigned since that's not computationally expensive and is used all over the place. Note that we're assigning valence here without checking for chemical correctness (so there won't be any exceptions thrown). It's probably not a bad idea to add the same thing to the reaction code if it's not there already.

It's almost certainly possible to create a situation where enumeration yields a molecule which is not sanitizable (for example: you could create a link node in an aromatic ring).

**Pull request merged**
