### PR TITLE
Minor PandasTools cleanup

### PR DESCRIPTION
**Pull request by ptosco**
This PR is motivated by the need to fix my `PandasTools` integration, which broke this morning due to a `pandas` update in the Python environment occurred during the weekend.
I noticed that the `PandasTools` module already complied with the fact that the `get_adjustment` attribute in the `pandas.io.formats.format` module can have different spellings across `pandas` versions, but in another part of `PandasTools` module the attribute was still referenced with a hardcoded `_get_adjustment` name, which caused it to fail on my `pandas` version (1.3.2).
While going through the code I also did some minor cleanup.

* Use the relevant `get_adjustment/_get_adjustment` attribute consistently across the `PandasTools` module
* Remove some unused code
* Clean up imports a bit

### CODE REVIEW

**Comment by greglandrum** [comment]
@ptosco : the code changes here look reasonable (to the extent that I can make actual sense out of much of the hackery which is in PandasTools). Before I approve/merge it: how much have you tested it? Have you tried more than one pandas version?

**Comment by ptosco** [comment]
@greglandrum I can do that testing without too much effort, I'll do that tonight.

**Comment by ptosco** [comment]
@greglandrum Tried on a older versions (1.1.5, 1.03, 0.25.1) and it works on all three.

**Comment by greglandrum** [comment]
> @greglandrum Tried on older versions (1.1.5, 1.03, 0.25.1) and it works on all three.

Thanks for confirming that @ptosco

**Pull request merged**
