### PR TITLE
Update rdkit_gist.c fixes #7493

### LINKED ISSUE #7493: Index anomaly with mol @= mol operator on PostgreSQL. Exact match is extremely slow!
**Description:**
When a GiST index is present, exact searching with the @= operator is 3x slower than without the index and much slower than @> or <@.

**Reproduction:**
```
create extension rdkit;
create schema chemistry;
create table chemistry.scantest (id SERIAL primary key, smiles text, molecule mol);
```
Import e.g. current ChEMBL 34 into that table: 2409270 records/molecules.
`explain analyze select id, smiles from chemistry.scantest s where molecule @= 'C1=CC=CC=C1'::mol limit 1000;`

_Limit  (cost=1000.00..222107.52 rows=1 width=62) (actual time=27858.392..27861.224 rows=1 loops=1)
  ->  Gather  (cost=1000.00..222107.52 rows=1 width=62) (actual time=27858.390..27861.222 rows=1 loops=1)
        Workers Planned: 2
        Workers Launched: 2
        ->  **Parallel Seq Scan on scantest s**  (cost=0.00..221107.42 rows=1 width=62) (actual time=20019.098..27795.578 rows=0 loops=3)
              Filter: (molecule @= 'c1ccccc1'::mol)
              Rows Removed by Filter: 803090
Planning Time: 0.189 ms
**Execution Time: 15861.480 ms**_

`create index molidx on chemistry.scantest using gist(molecule);`
`explain analyze select id, smiles from chemistry.scantest s where molecule @= 'C1=CC=CC=C1'::mol limit 1000;`

_Limit  (cost=0.41..8.43 rows=1 width=62) (actual time=16535.737..47603.977 rows=1 loops=1)
  ->  **Index Scan using molidx on scantest s**  (cost=0.41..8.43 rows=1 width=62) (actual time=16535.736..47603.974 rows=1 loops=1)
        Index Cond: (molecule @= 'c1ccccc1'::mol)
        Rows Removed by Index Recheck: 2048413
Planning Time: 1.347 ms
**Execution Time: 47604.119 ms**_

Now a substructure search for comparison:
```
explain analyze
select id, smiles from chemistry.scantest s where molecule @> 'C1=CC=CC=C1'::mol limit 1000;
```

_Limit  (cost=0.41..4208.86 rows=1000 width=62) (actual time=0.628..42.577 rows=1000 loops=1)
  ->  **Index Scan using molidx on scantest s**  (cost=0.41..10138.57 rows=2409 width=62) (actual time=0.626..42.498 rows=1000 loops=1)
        Index Cond: (molecule @> 'c1ccccc1'::mol)
Planning Time: 0.137 ms
**Execution Time: 42.892 ms**_

**Expected behavior:**
A search with index should usually be much faster, not slower. Exact search should be faster than substructure searching, not slower.
Substructure searching with @> or <@ for 'C1=CC=CC=C1' takes about 0.04 seconds on ChEMBL 34, so the index is basically working. But exact matching is broken.

**Configuration:**
 - RDKit version: 2024.03.3 / Extension 0.76.0
 - OS: macOS 14.5 (ARM64), but we see it also on Linux x64
 - PostgreSQL 16.3 installed from homebrew
 - RDKit built and installed from source

### PR DESCRIPTION
**Pull request by ergo70**
This fixes #7493, where way too much LEAF-nodes had to be re-checked for structure isomorphism.

#### Reference Issue
Fixes #7493

#### What does this implement/fix? Explain your changes.
This fixes #7493, where way too much LEAF-nodes had to be re-checked for structure isomorphism.

### CODE REVIEW

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
@rvianello this looks good to me, but you've spend more time in the indexing code recently than I have. Do you have an opinion on the PR?

**Comment by rvianello** [comment]
@ergo70 I agree that the `RDKitEquals` strategy in `gmol_consistent()` could be improved with changes similar to what you implemented, but I'm afraid you accidentally modified this strategy in `greaction_consistent()` instead? (note, if `RDKitEquals` in `gmol_consistent()` could be inefficient, I suspect the implementation for the same strategy in `greaction_consistent()` might be also wrong, but that's a different topic).

However, I am not convinced about the changes to `gmol_same()` and I would tend to disagree. Other functions raise an error when the arguments have mismatching length, but I think that happens mainly when comparing an index entry with a query value. In `gmol_same()` two index entries are compared with each other, and because fingerprints formed by all 1s have a short "compressed" representation, it is not unexpected that the arguments may have different length (and when they have different length, they simply can't be the same value).

**Comment by ergo70** [comment]
> @ergo70 I agree that the `RDKitEquals` strategy in `gmol_consistent()` could be improved with changes similar to what you implemented, but I'm afraid you accidentally modified this strategy in `greaction_consistent()` instead? 

Yes, my mistake. Locally I have modified gmol_consistent() of course, and that's what it should be. But I concur that greaction_consistent() might need the same change.

If the fingerprints are compressed, then your disagreement is valid. You know the code better than me. It's just that [pgchem::tigress](https://github.com/ergo70/pgchem_tigress) didn't have FP compression, so I wondered.

**Comment by rvianello** [comment]
compression doesn't apply to all entries, but this index implements a small optimization for fingerprints with all bits set, storing them with a placeholder value formed by the header alone to save some space and skip some operations that become trivial for this fingerprint.

**Review by greglandrum — APPROVED** [review]
LGTM based on @rvianello's feedback

**Comment by greglandrum** [comment]
I reverted this because @rvianello was not, in fact, done reviewing it. That was my mistake. Sorry for the confusion.

**Pull request merged**
