### PR TITLE
Fix shifting of a potentially negative number

### PR DESCRIPTION
**Pull request by ricrogz**
Shifting negative numbers is undefined behavior.

This fixes the issue by shifting the absolute value of the charge, and setting bit 30 (which is unlikely to be touched by any of the previous shifts) if the value was negative.

### CODE REVIEW

**Review by greglandrum — CHANGES_REQUESTED** [review]
The code change looks fine, but I think it would be a good idea to add a test for this one

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
@ricrogz the changes look good, but there are some warnings in the new test that cause the CI builds to fail

**Comment by ricrogz** [comment]
> @ricrogz the changes look good, but there are some warnings in the new test that cause the CI builds to fail

Yup, the typical signed comparison warning in a for loop's variable. Should be fixed now.

**Review by greglandrum — APPROVED** [review]
LGTM

**Pull request merged**
