### PR TITLE
cleanups of RDLog's tee behavior

### PR DESCRIPTION
**Pull request by greglandrum**
- rename RDLog::AddTee()->RDLog::SetTee()
- remove a leak when RDLog::SetTee() (formerly AddTee()) is called twice
- add RDLog::ClearTee() method to allow RDLog::SetTee() to be safely used with a stream that goes out of scope.

### CODE REVIEW

**Comment by bp-kelley** [comment]
Good catch.  I should have used a smart pointer!

**Comment by bp-kelley** [comment]
@greglandrum  I finally have a proper windows machine set up, btw, so I should be able to track down why this doesn't work as expected on ipython windows.

**Comment by greglandrum** [comment]
Let me know if you come up with anything I can do to help.

**Comment by bp-kelley** [comment]
@greglandrum Thanks, first I need to understand the problem,  I expect it is buried deep inside boost::python

**Pull request merged**
