### PR TITLE
Fix a bunch of edge cases in the pseudo 3d chiral assignment code.

### PR DESCRIPTION
**Pull request by greglandrum**
This changes are based on going through the 2 million molecules in the ChEMBL30 SDF and identifying cases where constructing a molecule from the SDF with master generated a different output SMILES than what we got before #6456 was merged.

This turned up a bunch of edge cases, which are more or less all fixed here.

After merging this we'll perceive the same stereo as we were before for all except 671 structures. I've gone through all of those and believe that they are all now correct. The mismatches include:
-  Examples where an atom with a wedged bond to it is directly atop the chiral center. The old code frequently got these wrong, but the new code is correct.

- Examples where bonds which are opposite to each other had different wedging:
image
The old code generated different stereoisomers for this depending on the bond order. The new code ignores the stereo here.

- Examples with "T-shaped" three-coordinate systems:
image
(also instances where the angles to the wedged bond are not 90 degrees).
These are ambiguous and, according to the IUPAC recommendations, wrong. The new code ignores the stereo here. 
This logic does not apply if the wedged bond is involved in the linear arrangement:
image
Here the stereochemistry is not ambiguous.

- Examples where atoms bound to a stereocenter have exactly the same coordinates. 
image
Here atoms 7 and 24 have the same coordinates and so the stereochemistry of atom 6 is ambiguous. The new code ignores the stereo here.

I still believe that the new code is considerably simpler and more robust than the old code we were using was.

### CODE REVIEW

**Review by ricrogz — APPROVED** [review]
LGTM

**Comment by rogersayle** [comment]
Code/GraphMol/Chirality.cpp needs to #include <optional> so that std::optional is defined for the return type of atomChiralTypeFromBondDirPseudo3D [this causes a build failure using g++ 11.4.0].  I guess you're using CLang, where perhaps std::optional is getting pulled in via another standard header?

**Comment by rogersayle** [comment]
Grr mark-up.  needs to #include &lt;optional&gt; so that...

**Comment by ricrogz** [comment]
I'll add that `#include` to https://github.com/rdkit/rdkit/pull/6675, together with the other fixes.

**Comment by greglandrum** [comment]
> [this causes a build failure using g++ 11.4.0]. I guess you're using CLang, where perhaps std::optional is getting pulled in via another standard header?

Nope, I actually use g++ 11.4 for most of my development and the CI builds run with g++ 10... so we do have a pretty good coverage.

But I agree that this definitely should be fixed.

**Pull request merged**
