### PR TITLE
Expose generateOneProductSet

### PR DESCRIPTION
**Pull request by DoliathGavid**
This PR exposes generateOneProductSet

This would be called from the client side via RDKit::ReactionRunnerUtils::generateOneProductSet

### CODE REVIEW

**Comment by DoliathGavid** [comment]
PS what's the policy on rebasing onto master? Is this preferred?

**Comment by DoliathGavid** [comment]
also, hold off on merging this - I'd also like to expose initProduct

**Comment by greglandrum** [comment]
We've been doing PRs against master, just like this.

**Comment by greglandrum** [comment]
Before merging: this should be completed by also including the functionality in the python wrappers.

**Comment by DoliathGavid** [comment]
I need to look into using boost::python to wrap these functions.

Should we expose MatchVectType explicitly or alternatively, let the user pass in a 2-tuple?
How is MOL_SPTR_VECT mapped to the corresponding python equivalent? A list of MOL_SPTRs?
How do shared pointers work with Python's ref-counting mechanism?

**Comment by greglandrum** [comment]
Ok, good point. This isn't super straightforward. Rather than explaining the individual steps, it's probably easiest if I do the wrapper and then point you to the code so that you can see how it works (for future reference).
Sound ok to you?

**Comment by DoliathGavid** [comment]
That works for me. Much appreciated.

**Comment by greglandrum** [comment]
Cool. When you're happy with the status of the PR let me know.
@bp-kelley and/or I will go through the final version before merging.

**Comment by greglandrum** [comment]
hrm, odd, I didn't get a notification about Brian's comment.

Sure, pulling it out of the ReactionRunnerUtils namespace makes sense.
If we're going to expose it as a method on the Python side, then we should do the same on C++. However, given that this is really advanced-user stuff, I'm not sure I like the idea of expanding the class namespace that way.

**Comment by bp-kelley** [comment]
@greg @DoliathGavid it seems we have stale-mated here on a resolution.  Perhaps we can expose C++ and let python wait until this percolates for a bit.

**Comment by greglandrum** [comment]
I was planning on waitin gon the Python until the C++ was merged. I have been holding here per @DoliathGavid's request that we wait until he also adds `initProduct()` to the header.
Agreed that pre-acceptance there should be some documentation.

**Comment by DoliathGavid** [comment]
I've added initProduct - but since we're exposing this as a public API I'm considering renaming this to something more appropriate: convertQueryMolToNormalMol or something?

**Comment by greglandrum** [comment]
Great. Now we just need a bit of documentation for the functions and it's ready to go.

As for a name, how about `convertProductTemplateToMol()`?

**Comment by DoliathGavid** [comment]
I renamed it to convertTemplateToMol (since there's no reason why we can't use it for reactants) - also did a quick rebase to clean up the commits.

**Comment by DoliathGavid** [comment]
I think this is ready to go.

**Comment by greglandrum** [comment]
Thanks for the contribution!

**Pull request merged**
