### PR TITLE
Fixes #1519

### LINKED ISSUE #1519: Missing def_readwrite for backgroundColour in rdMolDraw2D.cpp
Description:
RDKit Version: 2017.09
Platform: All

It seems there is a no option to access drawOptions().backgroundColour using the python wrapper.
It would be nice to be able to set the backgroundColour in rdkit.Chem.Draw.MolDraw2D.MolDrawOptions.

Regards
Jacob

### PR DESCRIPTION
**Pull request by greglandrum**
Adds the ability to set and get background and highlight colors from python.

This isn't the nicest solution imaginable since I was not able to expose the `boost::tuple` based `DrawColour` directly, but it does work.

There is sample code out there that purports to handle `boost::tuple` correctly in python wrappers (http://pyplusplus.readthedocs.io/en/latest/troubleshooting_guide/automatic_conversion/tuples.hpp.html) but I was unable to get that working in both directions. Python->C++ was fine, but the other direction consistently failed.

### CODE REVIEW

**Comment by bp-kelley** [comment]
@greglandrum Since I oddly like this kind of thing, I'll give boost::tuple a whack in python and probably hit the same wall you did :)

**Comment by greglandrum** [comment]
It'd be awesome if you could figure out how to make that work. I beat my head up against it for an hour or so and got nowhere

**Comment by bp-kelley** [comment]
@greglandrum I got it to work in c++11 :)

**Comment by greglandrum** [comment]
@bp-kelley we could switch to using that scheme on the modern_cxx branch (which I am refreshing now)

**Pull request merged**
