### PR TITLE
Add Fuzzing, fixes #2857

### LINKED ISSUE #2857: Integrating with OSS-Fuzz
Greetings rdkit developers and contributors,

We’re reaching out because your project is an important part of the open source ecosystem, and we’d like to invite you to integrate with our [fuzzing](https://www.owasp.org/index.php/Fuzzing) service, [OSS-Fuzz]( https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html ). OSS-Fuzz is a free fuzzing infrastructure you can use to identify security vulnerabilities and stability bugs in your project. OSS-Fuzz will:

- Continuously run at scale all the fuzzers you write.
- Alert you when it finds issues.
- Automatically close issues after they’ve been fixed by a commit.

Many widely used [open source projects]( https://github.com/google/oss-fuzz/tree/master/projects ) like OpenSSL, FFmpeg, LibreOffice, and ImageMagick are fuzzing via OSS-Fuzz, which helps them find and remediate [critical issues]( https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=status%3AFixed%2CVerified+Type%3ABug%2CBug-Security+-component%3AInfra+ ). 

Even though typical integrations can be done in < 100 LoC, we have a [reward program]( https://www.google.com/about/appsecurity/patch-rewards/ ) in place which aims to recognize folks who are not just contributing to open source, but are also working hard to make it more secure.

We want to stress that anyone who meets the eligibility criteria and integrates a project with OSS-Fuzz is eligible for a reward.

If you're not interested in integrating with OSS-Fuzz, it would be helpful for us to understand why—lack of interest, lack of time, or something else—so we can better support projects like yours in the future.

If we’ve missed your question in our [FAQ]( https://google.github.io/oss-fuzz/faq/ ), feel free to reply or reach out to us at oss-fuzz-outreach@googlegroups.com.

Thanks!

Tommy
OSS-Fuzz Team

### PR DESCRIPTION
**Pull request by intrigus-lgtm**
#### Reference Issue

#2857 

#### What does this implement/fix? Explain your changes.
This adds 3 fuzzing targets to rdkit.
They are built by default to prevent bit rot.
To do fuzzing you have define `${LIB_FUZZING_ENGINE}` to point to a fuzzer.
If it is not defined, it will use a standalone fuzz runner that will simply run each file that is passed as an argument without doing actual fuzzing, more like a test runner.
If you compile with clang you can simply use `-fsanitzie=fuzzer` as value for the variable.
If you use afl or have built libFuzzer without clang you should link to the library the fuzzer provides i.e. in the case of libFuzzer this would be something like `/usr/lib/libFuzzingEngine.a`.

## Building
````
# in the root folder of rdkit
mkdir -p build && cd build

export SANITIZER_FLAGS_address=-fsanitize=address -fsanitize-address-use-after-scope
export COVERAGE_FLAGS=-fsanitize=fuzzer-no-link
export CFLAGS=-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION $COVERAGE_FLAGS $SANITIZER_FLAGS_address
export CXXFLAGS_EXTRA=-stdlib=libc++
export CXXFLAGS=$CFLAGS $CXXFLAGS_EXTRA 

cmake -DRDK_BUILD_PYTHON_WRAPPERS=OFF -DLIB_FUZZING_ENGINE=${LIB_FUZZING_ENGINE} -DRDK_BUILD_FUZZ_TARGETS=ON -DRDK_INSTALL_STATIC_LIBS=ON -DBoost_USE_STATIC_LIBS=ON ..
make
make install
````
In the `build/Code/Fuzz/` folder run
`./smiles_string_to_mol_fuzzer -dict=smiles_string_to_mol_fuzzer/`

## Docker 
You should also be able to use docker to build this:
https://github.com/google/oss-fuzz/pull/3747
Use the provided docker file, but switch to this branch instead at https://github.com/google/oss-fuzz/blob/ee4aeac4f7e818b0c0cc8aca14f560bff1ea3ef4/projects/rdkit/Dockerfile#L42

### CODE REVIEW

**Comment by intrigus-lgtm** [comment]
Next steps are adding documentation for others that might want to fuzz this.
Integrating this into the build would also be nice a goal.
Adding a (bigger) corpora for your test cases and looking for more fuzz targets.

**Comment by intrigus-lgtm** [comment]
I'll investigate why Travis is not happy.

**Comment by greglandrum** [comment]
> I'll investigate why Travis is not happy.

As a general point: I'm less concerned about travis than about the Azure DevOps tests also failing. Those are the ones that I pay more attention to.

**Comment by greglandrum** [comment]
General comment:
I would prefer to not build these targets by default. Instead I think it's better to make them optional (disabled by default) and to add a CI target (on the Azure DevOps side) that builds them. That's cleaner while still making sure the tests run on every commit.

**Comment by intrigus-lgtm** [comment]
Looks like I wasted some hours looking for an error that doesn't exist...
I forgot to remove a hardcoded debug link library.

**Comment by intrigus-lgtm** [comment]
> General comment:
> I would prefer to not build these targets by default. Instead I think it's better to make them optional (disabled by default) and to add a CI target (on the Azure DevOps side) that builds them. That's cleaner while still making sure the tests run on every commit.

Ok.
I'd use https://github.com/rdkit/rdkit/blob/master/.azure-pipelines/mac_build_java.yml as a base since all libraries will link to `libc++` by default.
(This is somewhat important because only clang offers this easy way to use fuzzing.
Mixing clang and gcc on linux would probably result in problems, because clang wants `libc++` while gcc wants `libstdc++`)
Then I'd install the newer clang, version 10.0.0 (https://anaconda.org/conda-forge/clang).
(Are there any differences between the `conda-forge` and `anaconda` repositories?)

**Comment by intrigus-lgtm** [comment]
I integrated this into the ubuntu image instead.
It works.
The check is currently failing, due to #3139. 
If this gets fixed, the PR can be merged.

Until then I should probably document this fuzzing somewhere.
Should I create a `Fuzzing.md` inside of https://github.com/rdkit/rdkit/tree/master/Docs/Book ?

**Comment by greglandrum** [comment]
@intrigus-lgtm: the output from the CI build for this includes this message at the bottom of each of the fuzzer runs:
```
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
```
https://dev.azure.com/rdkit-org/RDKit-main-build/_build/results?buildId=1185&view=logs&j=d42b4615-9c42-5e39-433b-1455f2661188&t=252d3907-1082-5b31-96c1-a55ede2a1791

Is that correct?

**Comment by intrigus-lgtm** [comment]
> @intrigus-lgtm: the output from the CI build for this includes this message at the bottom of each of the fuzzer runs:
> 
> ```
> *** NOTE: fuzzing was not performed, you have only
> ***       executed the target code on a fixed set of inputs.
> ```
> 
> https://dev.azure.com/rdkit-org/RDKit-main-build/_build/results?buildId=1185&view=logs&j=d42b4615-9c42-5e39-433b-1455f2661188&t=252d3907-1082-5b31-96c1-a55ede2a1791
> 
> Is that correct?

Yes, that is correct.
The fuzzer can be run in two modes:
1. Fuzzer mode.
This means that the fuzzer actually creates random test cases and feeds them to the program.
2. "Testcase" runner mode.
This means that the fuzzer is not creating new test cases but gets given a list of existings files to test.

CI is running the fuzzer in mode two.
So the fuzzer *only* tests the existing test files to prevent regressions.
The test files would than be periodically updated to the corpora oss-fuzz generates.

Actual fuzzing will be done by Google's oss-fuzz.com

**Comment by greglandrum** [comment]
Great. Thanks for the clarification.

I want to go through one last time to be sure, but I think this is ready to be merged. Any other changes/tweaks you want to make first?

**Comment by intrigus-lgtm** [comment]
@greglandrum
Are you going to squash the commits?
If not, I'd cleanup commit history a little bit.

@Google-Autofuzz 
Hey, you added the `mol_data_stream_to_mol_fuzzer.cc` and `mol_block_to_mol_fuzzer.cc` files.
Is it really useful to have both fuzzers?
One function that is fuzzed (`MolBlockToMol`) seems to be a wrapper for the other function (`MolDataStreamToMol`).
If I understand the [source](https://github.com/rdkit/rdkit/blob/75f03412ef151a4dc14dfee986e29c3690a4c071/Code/GraphMol/FileParsers/MolFileParser.cpp#L2977-L2991) right, the two functions that are fuzzed do more or less the same?

**Comment by greglandrum** [comment]
@intrigus-lgtm : yeah we always squash commits when merging PRs

**Comment by Google-Autofuzz** [comment]
> @greglandrum
> Are you going to squash the commits?
> If not, I'd cleanup commit history a little bit.
> 
> @Google-Autofuzz
> Hey, you added the `mol_data_stream_to_mol_fuzzer.cc` and `mol_block_to_mol_fuzzer.cc` files.
> Is it really useful to have both fuzzers?
> One function that is fuzzed (`MolBlockToMol`) seems to be a wrapper for the other function (`MolDataStreamToMol`).
> If I understand the [source](https://github.com/rdkit/rdkit/blob/75f03412ef151a4dc14dfee986e29c3690a4c071/Code/GraphMol/FileParsers/MolFileParser.cpp#L2977-L2991) right, the two functions that are fuzzed do more or less the same?

You can choose one to use to fuzz then. You have a point. They are similar and do more or less the same.

**Comment by intrigus-lgtm** [comment]
From my side this is ready :)
I have some ideas for additional fuzz targets that can be added in another PR.

**Comment by greglandrum** [comment]
Thanks for this contribution!

**Pull request merged**
