### PR TITLE
Fixes #5819

### LINKED ISSUE #5819: Support writing detailed SMARTS queries to CTABs using the SMARTSQ mechanism
Some discussion of this in #5718  and #5825, but the idea is to allow atom-based SMARTS queries to be serialized into v3000 mol blocks via substance groups. The trick is going to be figuring out which queries get serialized this way.

Implement this using a new CTABWritingParams (or some such name) class.

### PR DESCRIPTION
**Pull request by greglandrum**
This adds SMARTSQ DAT SGroups to the output for atoms which have queries.

It does not do the standard `AtomType` query, so converting the SMARTS `CC` into CTAB and back will give `[#6][#6]` as an output SMARTS. This isn't nice, but otherwise CTABs are going to end up having SMARTSQ queries on almost all atoms constructed from SMARTS, and that's potentially even worse. Something to discuss...

The example from the test starts with the SMARTS `[C,N,O]C[#6]*[$(C(=O)O)]` and produces this CTAB:
```

     RDKit          2D

  0  0  0  0  0  0  0  0  0  0999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 5 4 1 0 0
M  V30 BEGIN ATOM
M  V30 1 [C,N,O] 0.000000 0.000000 0.000000 0
M  V30 2 C 1.299038 0.750000 0.000000 0
M  V30 3 C 2.598076 -0.000000 0.000000 0
M  V30 4 * 3.897114 0.750000 0.000000 0
M  V30 5 * 5.196152 -0.000000 0.000000 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 6 1 2
M  V30 2 6 2 3
M  V30 3 6 3 4
M  V30 4 6 4 5
M  V30 END BOND
M  V30 BEGIN SGROUP
M  V30 1 DAT 0 ATOMS=(1 5) QUERYTYPE=SMARTSQ QUERYOP== -
M  V30 FIELDDATA="[$(C(=O)O)]"
M  V30 END SGROUP
M  V30 END CTAB
M  END
```

### CODE REVIEW

**Comment by greglandrum** [comment]
@cdvonbargen we talked about this on Thursday. Please take a look to see if you agree with how I did this.

**Review by ricrogz — APPROVED** [review]
LGTM

**Comment by cdvonbargen** [comment]
Perhaps a silly question -- is this true for RXN writing as well?

**Comment by greglandrum** [comment]
> Perhaps a silly question -- is this now supported when writing RXN as well?

@cdvonbargen I was about to say: "of course!". Good thing I checked before writing that.
At the moment it looks like the reaction writing code does not do S groups:
```
In [3]: rxn = rdChemReactions.ReactionFromSmarts('[C;$(C([#6])=O):1][OH:2]>>[C:1][NH2:2]')

In [4]: print(rdChemReactions.ReactionToSmarts(rxn))
[C&$(C([#6])=O):1][O&H1:2]>>[C:1][N&H2:2]

In [5]: print(rdChemReactions.ReactionToV3KRxnBlock(rxn))
$RXN V3000

      RDKit

M  V30 COUNTS 1 1
M  V30 BEGIN REACTANT
M  V30 BEGIN CTAB
M  V30 COUNTS 2 1 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C 0.000000 0.000000 0.000000 1
M  V30 2 O 0.000000 0.000000 0.000000 2
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 6 1 2
M  V30 END BOND
M  V30 END CTAB
M  V30 END REACTANT
M  V30 BEGIN PRODUCT
M  V30 BEGIN CTAB
M  V30 COUNTS 2 1 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C 0.000000 0.000000 0.000000 1
M  V30 2 N 0.000000 0.000000 0.000000 2
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 6 1 2
M  V30 END BOND
M  V30 END CTAB
M  V30 END PRODUCT
M  END


In [6]: print(Chem.MolToV3KMolBlock(rxn.GetReactant(0)))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [6], line 1
----> 1 print(Chem.MolToV3KMolBlock(rxn.GetReactant(0)))

AttributeError: 'ChemicalReaction' object has no attribute 'GetReactant'

In [7]: print(Chem.MolToV3KMolBlock(rxn.GetReactantTemplate(0)))

     RDKit          2D

  0  0  0  0  0  0  0  0  0  0999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 2 1 2 0 0
M  V30 BEGIN ATOM
M  V30 1 C 0.000000 0.000000 0.000000 1
M  V30 2 O 1.299038 0.750000 0.000000 2
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 6 1 2
M  V30 END BOND
M  V30 BEGIN SGROUP
M  V30 1 DAT 0 ATOMS=(1 1) QUERYTYPE=SMARTSQ QUERYOP== -
M  V30 FIELDDATA="[C&$(C([#6])=O):1]"
M  V30 2 DAT 0 ATOMS=(1 2) QUERYTYPE=SMARTSQ QUERYOP== FIELDDATA="[O&H1:2]"
M  V30 END SGROUP
M  V30 END CTAB
M  END
```
So I'm going to take a look at that and then update this PR

**Comment by greglandrum** [comment]
@ricrogz : I've made a few changes to make sure the reaction stuff works; could you please take another quick look at this ?

**Review by ricrogz — APPROVED** [review]
Looks good to me, Greg.

**Comment by cdvonbargen** [comment]
Thank you for checking RXN!

**Comment by d-b-w** [comment]
@greglandrum  -
is this a patch for the 2023fall release or part of the 2024spring?

**Comment by greglandrum** [comment]
> @greglandrum - is this a patch for the 2023fall release or part of the 2024spring?

It's in the 2023.09.3 release that I just did.

You can always check the milestone on the issue (or PR if there is no associated issue) to check things like this.

**Pull request merged**
