### PR TITLE
Remove unused ctest: testCanon

### PR DESCRIPTION
**Pull request by ricrogz**
I just noticed that on my Mac graphmoltestCanon was entering an infinite loop:

On investigation, it looks like the main function expects a file argument from which to read some SMILES, but it is never provided in the test.

Still, the process entered an infinite loop in which the messages:
```
...
33: [16:05:53] SMILES Parse Error: syntax error while parsing: 
33: [16:05:53] SMILES Parse Error: Failed parsing SMILES '??' for input: '??'
33: [16:05:53] SMILES Parse Error: syntax error while parsing: 
33: [16:05:53] SMILES Parse Error: Failed parsing SMILES '??' for input: '??'
33: [16:05:53] 1 Parse Failed: <B4><E1>
...
```
were being printed on each cycle: apparently, `tmpstr` was reading two characters and reporting `tmpstr.size() == 2`, although `tmpstr.empty() == true` (?????)

Returning early if no argument is passed completely avoids the problem.

### CODE REVIEW

**Comment by greglandrum** [comment]
It's amazing what you find in the corners of this code base. :-)

These changes look good, but it seems like it also makes sense to remove this test from the CMakeLists.txt: there's no sense running a test that doesn't do anything.

**Comment by ricrogz** [comment]
Oh! I actually though this would go the other way, like "it was supposed to run on these SMILES... let's plug them in". But this is ok too.

**Comment by greglandrum** [comment]
Nope. This is a vestigial thing. The renumbering tests of a set of "interesting" molecules are in `hanoiTest.cpp`

**Comment by ricrogz** [comment]
Ok, ok. I was just an intuitive expectation. I removed the test file and the CMakeFile entry.

**Comment by greglandrum** [comment]
It was a perfectly reasonable thing to expect. :-)
Thanks for the additional cleanup.
I'll merge once the CI builds are done.

**Comment by ricrogz** [comment]
Always a pleasure :)

**Pull request merged**
