### PR TITLE
Adds RDProps to c# wrapper

### PR DESCRIPTION
**Pull request by bp-kelley**

### CODE REVIEW

**Comment by greglandrum** [comment]
@bp-kelley : the change looks good. The (not super important) question is : is this a bug fix or enhancement? I've labeled it enhancement because it adds new features, but it was really a bug that this wasn't in there in the first place.

**Comment by bp-kelley** [comment]
It is a bug, setProp was available before we moved it to RDProps I think.  For the c# wrappers though, any attention is a feature...

**Comment by JimSEOW** [comment]
@bp-kelley How up-to-date is the C# wrapper compared to the java wrapper?

**Comment by bp-kelley** [comment]
It is made by the same swig wrapper, so I would make the claim that it is
fairly up to date.  We are using it in production currently.  However the
tests are woefully out of date and need some major work (time permitting).

C#'s memory model is close but not quite the same as python, so I can't
guarantee that the wrappers don't leak at this point.

Cheers,
 Brian

**Comment by JimSEOW** [comment]
@bp-kelley 
Good to know it is used in production. The last time I checked, I found a few methods missing in the .NET [wrapper](https://github.com/rdkit/rdkit/issues/664).

Without knowing that .NET wrapper is used in production or having seen many feedback from the community on the .NET wrapper, I have been considering using jni4net.

**Pull request merged**
