### PR TITLE
Fix/github879

### PR DESCRIPTION
**Pull request by greglandrum**
A small one to add bits to the pattern fingerprinter for degree 0 atoms.

### CODE REVIEW

**Comment by bp-kelley** [comment]
@adalke should be commenting on this as well considering he has chemfp 3.0 coming out in a few weeks :)

**Comment by bp-kelley** [comment]
Any chance we could support the old and new version?

**Comment by greglandrum** [comment]
It would be possible to add an option to disable the new terms, but that seems likely to increase the risk of confusion (=comparing fingerprints generated with different "versions") rather than decreasing it.
I think it's better to treat this as a bug fix - "The pattern fingerprint was not effective for screening out odd elements" - and regenerate existing indices and collections of fps.
Still, if you assess the risk differently and think it's necessary, I can add a form of the pattern fingerprinter that takes a bit vector describing which patterns should be included. This will clearly be an expert-only thing and would have to be very carefully used.

**Comment by bp-kelley** [comment]
chemfp is really good about versioning, so I expect for my use cases this won't be an issue for me in practice, so I'm going to merge this and then see what happens :)

**Pull request merged**
