### PR TITLE
Refactor the memory management of the postgres cartridge cache module

### PR DESCRIPTION
**Pull request by rvianello**
#### What does this implement/fix? Explain your changes.
The proposed changes mainly replace the existing mechanism for deallocating the cache resources with a similar functionality based on the memory context callback api (available in postgres 9.5 and later). Also, the allocation of the cache holder instances, previously using direct calls to malloc/free, is now delegated to the associated memory context.

#### Any other comments?
So far, I only tested this with postgres 14.1, and verified that the regression tests were unaffected in my development environment. Running some queries under valgrind didn't report any leaks (some memory is reported to be in use at exit, but I think this might be in general expected).

### CODE REVIEW

**Comment by greglandrum** [comment]
Thanks @rvianello. Just so I can be sure I'm classifying it correctly: this is a cleanup PR, not a bug fix, right?

**Comment by rvianello** [comment]
Yes, I think it can be classified as a cleanup PR (I am not aware of any bugs affecting the original version).

**Comment by greglandrum** [comment]
Data point: builds and runs without problems on Postgresql v12 as well.

**Comment by rvianello** [comment]
actually, in reviewing the code I noticed a couple of things that looked suspicious to me, but I thought could be easier to discuss and (if necessary) address after a cleanup. they are mostly related to how the code behaves when `createCache` is passed a non-null pointer to something that doesn't look like a valid cache object. In that case an error is logged, but the code moves forward and it looks like it could end up reassigning the `fcinfo->flinfo->fn_extra` pointer in the caller. A comment in the original `cleanupRDKitCache` code (now removed because made irrelevant by the changes) also suggested that multiple cache instances could exist in the same memory context, but I didn't see any indication that the implementation could actually handle that situation, or that a similar situation could actually happen (maybe that comment was already obsolete, like the unused `resetOrig`/`deleteOrig` pointers in `ValueCache`). this PR is still just a cleanup, but once merged maybe I could create a couple of issues to discuss these points.

**Comment by rvianello** [comment]
Thanks for testing with postgres 12, I'll rebuild my dev container for a couple other versions too.

**Comment by rvianello** [comment]
tests pass for me on linux with the latest releases of postgres 9.6, 10, 11, and 13 too. 

(also, I realized now that when an error is logged the transaction is killed, so the potential issue I mentioned in my earlier comment just doesn't exist).

**Review by greglandrum — APPROVED** [review]

**Comment by greglandrum** [comment]
Thanks @rvianello !

**Pull request merged**
