### PR TITLE
Fixes #1670

### LINKED ISSUE #1670: NumAmideBonds descriptor missing
I am showing some students how to do a PCA on molecular descriptors, so I am using the ones from http://www.rdkit.org/docs/GettingStartedInPython.html#list-of-available-descriptors

Mostly this is ok, but I can't get NumAmideBonds -- is this not accessible via Descriptors?

Apologies if I am missing something obvious.

```
import rdkit 
from rdkit import rdBase
print(rdBase.rdkitVersion)
from rdkit.Chem import Descriptors
m = Chem.MolFromSmiles('c1ccccc1C(=O)O')
Descriptors.NumHAcceptors(m)
Descriptors.NumAmideBonds(m)
```

Output:

> 2017.09.1
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-13-7f5d497b2281> in <module>()
>       5 m = Chem.MolFromSmiles('c1ccccc1C(=O)O')
>       6 Descriptors.NumHAcceptors(m)
> ----> 7 Descriptors.NumAmideBonds(m)
> 
> AttributeError: module 'rdkit.Chem.Descriptors' has no attribute 'NumAmideBonds'

### PR DESCRIPTION
**Pull request by greglandrum**
Adds the missing C++ descriptors to Lipinski.py

### CODE REVIEW

**Comment by bp-kelley** [comment]
If these will get added to the descriptor List in rdkit.Chem.Descriptors we probably need a documentation update.

**Comment by bp-kelley** [comment]
Or a release note.

**Comment by greglandrum** [comment]
> If these will get added to the descriptor List in rdkit.Chem.Descriptors we probably need a documentation update.

Some of them were there already, but a couple were missing. They are now added.

**Comment by greglandrum** [comment]
@bp-kelley are you ok with merging this?

**Review by bp-kelley — APPROVED** [review]

**Pull request merged**
