### PR TITLE
Fixes #908

### LINKED ISSUE #908: AddHs() using 3D coordinates with 2D conformations
```
>>> m = Chem.MolFromSmiles('Br[C@H](F)Cl')
>>> AllChem.Compute2DCoords(m)
>>> mh=Chem.AddHs(m,addCoords=True)
>>> print(Chem.MolToMolBlock(mh))

     RDKit          2D

  5  4  0  0  0  0  0  0  0  0999 V2000
   -1.2990   -0.7500    0.0000 Br  0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2990   -0.7500    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    1.5000    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000   -0.9526 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  2  4  1  0
  2  5  1  6
M  END
```

### PR DESCRIPTION
**Pull request by greglandrum**

### CODE REVIEW

**Comment by greglandrum** [comment]
Wow, that was a great example of the fingers moving faster than the brain.
I didn't run the full test suite before doing the PR.

**Comment by bp-kelley** [comment]
@greglandrum Looks like we hit some conflicts.

**Comment by bp-kelley** [comment]
@greglandrum probably in molopstest

**Comment by greglandrum** [comment]
Sigh... I'll take a look tomorrow morning.

**Comment by greglandrum** [comment]
I screwed up the merge somehow, but commit 339fa081e has it.

**Pull request closed without merging**
