### PR TITLE
Fixes RDK_BUILD_THREADSAFE_SSS=OFF build

### PR DESCRIPTION
**Pull request by ptosco**
This PR fixes some issues that currently affect the RDKit build when `RDK_BUILD_THREADSAFE_SSS=OFF`.

- Currently, non-threaded *nix builds fail because `boost::flyweight` introduces a dependency on `pthreads`:
  https://www.boost.org/doc/libs/1_75_0/libs/flyweight/doc/reference/index.html
  The simple fix is defining `BOOST_DISABLE_THREADS` for non-threaded builds to avoid that.
- make sure that mutexes and futures are only used when `RDK_BUILD_THREADSAFE_SSS` is `ON`.
  This consistently happens in RDKit except in a few places, so I have corrected that and added a test.
- fix `SubstructMatch` failing test when `RDK_BUILD_THREADSAFE_SSS` is `OFF` due to misplaced `#ifdef`s
  This bug was mostly fixed in #3405 but there was a misplaced `#ifdef` that was causing problems.
  I also removed another `#ifdef` around `reserve` as that also applies to non-threaded builds.
- Rename `RDK_TEST_MULTITHREADED` to `RDK_THREADSAFE_SSS` in `inchi.cpp`, which is not a test. This is purely cosmetic.

With these fixes RDKit can be built with `RDK_THREADSAFE_SSS=OFF` and all tests pass,

### CODE REVIEW

**Comment by greglandrum** [comment]
I haven't done the review yet, but could you please modify `linux_build_limitexternal.yml` so that it no longer does the multi-threaded build/tests. That way we can make sure this doesn't become an issue again.

**Comment by ptosco** [comment]
@greglandrum good point, done.

**Review by greglandrum — CHANGES_REQUESTED** [review]
I think the changes in one of the files can be reverted, but otherwise looks good

**Comment by ptosco** [comment]
@greglandrum And now `pySimDivPickers` fails on the Windows DLL build. God knows what this had to do with `testMultithreadedMolSupplier.cpp`. I'll take a look and see if I can reproduce it.

**Comment by greglandrum** [comment]
@ptosco : that test failure probably isn't real. I will re-run it to be sure.

**Review by greglandrum — APPROVED** [review]
LGTM

**Pull request merged**
