### PR TITLE
Include macrocycles in atropisomer calculation by not sanitizing them away

### PR DESCRIPTION
**Pull request by pechersky**
Previously, atropisomeric bonds were sanitized away if they were part of a "ring bond", which happens in macrocyclic systems. None of the existing atropisomer test cases fail if that sanitization check is removed. There are other tests that fail, possibly because of overfitting on expected sanitization. The sanitization step is removed to support biaryls that are part of a larger macrocyclic system. A set of test cases is included that cover potential macrocyclic atropisomeric systems

#### What does this implement/fix? Explain your changes.
Make sure that macrocyclic atropisomeric systems are not sanitized away. A pictorial representation of the relevant molecules are the 3 left-most columns in this scheme:
image

#### Any other comments?
I could not identify why existing test cases required the ring bond branch in the sanitization.

### CODE REVIEW

**Comment by pechersky** [comment]
@tadhurst-cdd Do you have any insight on the better way to implement support for these molecules?

**Comment by pechersky** [comment]
Can you take a look at the implementation now, please? I think it keeps the existing tests working _and_ makes the macrocycle tests I added work too. My tests should cover a variety of macrocycle ring sizes. I think with regards to the SSSR, it is already initialized at that stage of sanitization.

**Comment by tadhurst-cdd** [comment]
That doesn't exactly work either.  Consider:

image

The suggested change correctly removes the atropisomer indication from the bond between 2-9, but also removes the atropisomer from the bond between 1 and 2.

It really is about the size of the ring the bond is in (the smallest size). 

Your comment about the sssr check assumes that you know all of the places this routine is (or ever will be) called from.  That is probably correct,  but it doesn't hurt to check:

So the overall routine would look like:

```
void cleanupAtropisomers(RWMol &mol, MolOps::Hybridizations &hybs) {
  if (!mol.getRingInfo()->isSssrOrBetter()) {
    RDKit::MolOps::findSSSR(mol);
  }
  const RingInfo *ri = mol.getRingInfo();

  for (auto bond : mol.bonds()) {
    switch (bond->getStereo()) {
      case Bond::BondStereo::STEREOATROPCW:
      case Bond::BondStereo::STEREOATROPCCW:
        if (hybs[bond->getBeginAtomIdx()] != Atom::SP2 ||
            hybs[bond->getEndAtomIdx()] != Atom::SP2 ||
            (ri->numBondRings(bond->getIdx()) > 0 &&
             ri->minBondRingSize(bond->getIdx()) < 8)) {
          bond->setStereo(Bond::BondStereo::STEREONONE);
        }
        break;

      default:
        break;
    }
  }
}
```

**Comment by pechersky** [comment]
I included the molecule you drew in a test, and added your ring size based implementation. However, the molecule fails for a different reason -- the N is not recognized as on an atropisomeric bond:
```
Wedge or hash bond found on atropisomer where not expected - atoms are: 12 13
```
Instead, the N is seen as a regular tetrahedral chiral center (this is before sanitization)
```
Atoms:
        0 6 C chg: 0  deg: 2 exp: 2 imp: N/A hyb: 
        1 6 C chg: 0  deg: 2 exp: 2 imp: N/A hyb: 
        2 6 C chg: 0  deg: 3 exp: 3 imp: N/A hyb: 
        3 6 C chg: 0  deg: 3 exp: 4 imp: N/A hyb: 
        4 6 C chg: 0  deg: 3 exp: 4 imp: 0 hyb: 
        5 6 C chg: 0  deg: 2 exp: 2 imp: N/A hyb: 
        6 6 C chg: 0  deg: 2 exp: 2 imp: N/A hyb: 
        7 6 C chg: 0  deg: 2 exp: 2 imp: N/A hyb: 
        8 6 C chg: 0  deg: 2 exp: 2 imp: N/A hyb: 
        9 6 C chg: 0  deg: 2 exp: 2 imp: N/A hyb: 
        10 6 C chg: 0  deg: 2 exp: 2 imp: N/A hyb: 
        11 6 C chg: 0  deg: 3 exp: 4 imp: N/A hyb: 
        12 6 C chg: 0  deg: 3 exp: 4 imp: 0 hyb: 
        13 7 N chg: 0  deg: 3 exp: 3 imp: 0 hyb:  chi: CW nbrs:[3 4 12]
        14 8 O chg: 0  deg: 1 exp: 2 imp: N/A hyb: 
        15 6 C chg: 0  deg: 3 exp: 3 imp: N/A hyb: 
        16 17 Cl chg: 0  deg: 1 exp: 1 imp: N/A hyb: 
        17 17 Cl chg: 0  deg: 1 exp: 1 imp: N/A hyb: 
        18 6 C chg: 0  deg: 1 exp: 1 imp: N/A hyb: 
        19 8 O chg: 0  deg: 1 exp: 2 imp: N/A hyb: 
Bonds:
        0 0->1 order: 1
        1 1->2 order: 1
        2 2->3 order: 1
        3 13->3 order: 1
        4 13->4 order: 1 stereo: CCW bonds: (3 14 5 15)
        5 4->0 order: 1
        6 2->5 order: 1
        7 5->6 order: 1
        8 6->7 order: 1
        9 7->8 order: 1
        10 8->9 order: 1
        11 9->10 order: 1
        12 10->11 order: 1 dir: /
        13 11->12 order: 2
        14 12->13 order: 1 dir: \ stereo: CW bonds: (13 16 3 4)
        15 4->14 order: 2
        16 12->15 order: 1 dir: /
        17 15->16 order: 1
        18 15->17 order: 1
        19 11->18 order: 1 dir: /
        20 3->19 order: 2
```

Your implementation works fine on my examples. What do you think of using your implementation in this PR, and leaving a separate issue for support of your macrocycle example?

**Comment by tadhurst-cdd** [comment]
that nitrogen should be seen as SP2 hybridized, and it is in my tests.   The bond between 1-2 is retained as an atropisomer bond, and the bond between 2 -9 is not retained after cleanup.  The mol I used is:
[MacrocycleTest.txt](https://github.com/rdkit/rdkit/files/14779543/MacrocycleTest.txt)
(change it to .mrv)

**Comment by pechersky** [comment]
Here's the MOL that I am using:
```

  ChemDraw03272412092D

  0  0  0     0  0              0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 20 21 0 0 1
M  V30 BEGIN ATOM
M  V30 1 C -1.779975 0.405609 0.000000 0
M  V30 2 C -1.779967 -0.416526 0.000000 0
M  V30 3 C -1.067977 -0.827596 0.000000 0
M  V30 4 C -0.355990 -0.416523 0.000000 0
M  V30 5 C -1.067987 0.816681 0.000000 0
M  V30 6 C -1.061676 -1.638828 0.000000 0
M  V30 7 C -0.349682 -2.049890 0.000000 0
M  V30 8 C 0.362306 -1.638817 0.000000 0
M  V30 9 C 1.174320 -1.767421 0.000000 0
M  V30 10 C 1.585383 -1.055427 0.000000 0
M  V30 11 C 1.067991 -0.416512 0.000000 0
M  V30 12 C 1.067985 0.405624 0.000000 0
M  V30 13 C 0.355991 0.816687 0.000000 0
M  V30 14 N -0.355996 0.405613 0.000000 0
M  V30 15 O -1.067987 1.638817 0.000000 0
M  V30 16 C 0.355991 1.638822 0.000000 0
M  V30 17 Cl 1.067981 2.049890 0.000000 0
M  V30 18 Cl -0.356000 2.049890 0.000000 0
M  V30 19 C 1.779975 0.816692 0.000000 0
M  V30 20 O 0.356001 -0.827591 0.000000 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 2
M  V30 2 1 2 3
M  V30 3 1 3 4
M  V30 4 1 14 4 CFG=1
M  V30 5 1 14 5
M  V30 6 1 5 1
M  V30 7 1 3 6
M  V30 8 1 6 7
M  V30 9 1 7 8
M  V30 10 1 8 9
M  V30 11 1 9 10
M  V30 12 1 10 11
M  V30 13 1 11 12
M  V30 14 2 12 13
M  V30 15 1 13 14
M  V30 16 2 5 15
M  V30 17 1 13 16
M  V30 18 1 16 17
M  V30 19 1 16 18
M  V30 20 1 12 19
M  V30 21 2 4 20
M  V30 END BOND
M  V30 END CTAB
M  END
$$$$
```

**Comment by pechersky** [comment]
@greglandrum something is awry with the `macOS_x64_java` check, github was never informed about it terminating: 
image

**Comment by tadhurst-cdd** [comment]
I included a test for the mol you indicated, and I get an error as well.  This is unrelated to the issue of macromolecules, and I will fix it in a separate PR.  Thanks for pointing it out

**Review by greglandrum — CHANGES_REQUESTED** [review]
The code changes here look good to me, but the section in `RDKit_Book.rst` that describes the handling of atropisomers: https://github.com/rdkit/rdkit/blob/master/Docs/Book/RDKit_Book.rst#atropisomeric-bonds
should be updated to reflect this change.

**Review by tadhurst-cdd — COMMENTED** [review]
Looks good to me.  I have a fix for the bug that was found coming in a separate PR.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
Thanks for the contribution @pechersky!

**Pull request merged**
