### PR TITLE
yapf formatting of recent changes to Python code in rdkit and Code

### PR DESCRIPTION
**Pull request by gedeck**
No manual changes to the code.

### CODE REVIEW

**Comment by proteneer** [comment]
If possible, it's better if the authors themselves did this (and have CI fail automatically for non-conforming patterns). Having @gedeck do this is both cumbersome and ruins git-blame.

**Comment by coleb** [comment]
In addition and/or CI tests for code style, would be great if we included yapf formatting as a git-hook so I don't have to manually run the formatter, it can happen when I commit.

https://github.com/michalrus/git-hooks-code-autoformat

**Comment by gedeck** [comment]
I would prefer not to enforce an auto-format of the code, however we could include something in the checks that at least tell the submitter that the code is correctly formatted. 

The pull request #1133  contains a script that checks all python files and reports any necessary changes.

**Comment by greglandrum** [comment]
I agree with @gedeck : code formatting is a "nice-to-have", not a correctness thing and could be dealt with in the review.

**Comment by proteneer** [comment]
Are we completely disabling git blame too now?

**Comment by greglandrum** [comment]
I don't understand your question

**Comment by proteneer** [comment]
Sorry I didn't see https://github.com/rdkit/rdkit/pull/1133 being merged in.

I thought for a second that we were going to entirely rely on Peter to do all the yapf and clang formatting :)  in a second pass - thereby making git blame useless (since the most recent author will always be the person who formatted the code, not the actual author).

**Comment by greglandrum** [comment]
If git blame really only allowed you to look at the last commit it would certainly be useless. Fortunately this isn't actually true

**Pull request merged**
