### PR TITLE
Fixes #786

### LINKED ISSUE #786: chiral lexical order for ring closure after branch
RDKit allows ring closures after a branch, like:

    >>> Chem.CanonSmiles("C(I)1.N1")
    'NCI'

This is not a Daylight SMILES, I think, because theory.smiles.html says "The [ring] bonds are numbered in any order, designating ring opening (or ring closure) bonds by a digit immediately following the atomic symbol at each ring closure." Nor is it a valid OpenSMILES.

There's no reason this can't be a valid extension syntax. However, I don't think it works correctly with chiral specifications.  Consider the following:

    >>> smiles = r"CC(C)[C@@](N)1CC[C@]2([C@@H](O2)CCC(=C)[C@H](CC[C@@](/C=C1)(C)O)O)C"
    >>> smiles2 = smiles.replace(r"(N)1", r"1(N)")
    >>> smiles == smiles2
    False
    >>> Chem.CanonSmiles(smiles) == Chem.CanonSmiles(smiles2)
    True

The Daylight documentation says "The chiral order of the ring closure bond is implied by the lexical order that the ring closure digit appears on the chiral atom (not in the lexical order of the "substituent" atom). " I *believe* that means C[C@@]1(N)C should have a different chirality than C[C@@](N)1C because the permutation order of the four bonds has changed.

Honestly, I don't think it's a useful extension because it's hard to even figure out what is the right solution for this case, and I don't think people use it. OpenSMILES doesn't support it.

But I see that Open Babel and SMARTSviewer both support it. OB inverts the chirality between these two cases, while SMARTSviewer shows identical images.

    >>> pybel.readstring("smi", smiles).write("smi")
    'CC(C)[C@]1(N)CC[C@]2([C@@H](O2)CCC(=C)[C@H](CC[C@@](C=C1)(C)O)O)C\t\n'
    >>> pybel.readstring("smi", smiles2).write("smi")
    'CC(C)[C@@]1(N)CC[C@]2([C@@H](O2)CCC(=C)[C@H](CC[C@@](C=C1)(C)O)O)C\t\n'

### PR DESCRIPTION
**Pull request by greglandrum**
This time we accept the ring closures after a branch, but we still get atom chirality right.

### CODE REVIEW

**Comment by bp-kelley** [comment]
I couldn't find regression tests, but I didn't look too hard ;)

**Comment by greglandrum** [comment]
They are here: 
https://github.com/rdkit/rdkit/pull/823/files#diff-604a06d68dae3a8345bdee0b756b335eR3646

**Comment by bp-kelley** [comment]
This looks good, I'm going to do a once over for chirality in the regression test, but that shouldn't take too long.

**Comment by bp-kelley** [comment]
I need to understand this one better,  it is the only one where I get different smiles parsers with different results from our fix. (including chemdraw paste from smiles)  I'm assuming that bonds should be parsed in the order seen below:

smiles:

```
C1CN[C@]12(O).N2
C1CN[C@@](O)12.N2
```

bond orders:

```
C1CN<bond1>[C@]<bond2>12(<bond3>O).N<bond4>2
C1CN<bond1>[C@@](<bond2>O)<bond3>12.N<bond4>2
```

So the chiralities should really be the same, correct?  (This is what the regression tests actually checks for)

**Comment by bp-kelley** [comment]
@greglandrum just want to verify I am understanding this correctly before I merge.

**Comment by greglandrum** [comment]
Hmm, looking at it again, I think there should be a difference there. Currently there's not.
I had convinced myself that this was a different case, but I'm going to have to look again.
This is likely going to need to wait until I'm back in Basel on Monday.
Nice catch.

**Comment by bp-kelley** [comment]
Yeah, I think they should be different as well.

**Comment by greglandrum** [comment]
ok, I think that should do it.
Need to see what the linux tests do though

**Comment by greglandrum** [comment]
That looked good. I just added a couple more tests with variations, but I think it's probably in good shape now.

**Comment by bp-kelley** [comment]
Nice work :)

**Pull request merged**
