### PR TITLE
rename SGroup -> SubstanceGroup

### PR DESCRIPTION
**Pull request by greglandrum**
These haven't been released yet, so we still have the chance to get the naming right.

After mistakenly using "SGroup" for "StereoGroup" a few times, I realized that we should probably pick a better name for the `SGroup` class and related code. The SDF docs call them "Substance Groups", which seemed as descriptive a name as any, so I went with that.

`DataGroup`, something else I considered, was rejected as confusing since the docs discuss "Chemical Sgroups" and "Data Sgroups" and we need to cover both.

We leave the names of the bits connected with reading/writing Mol files as SGroups, since that is
appropriate there, but the more generic pieces are renamed

### CODE REVIEW

**Comment by greglandrum** [comment]
@d-b-w, @ricrogz : does this seem reasonable to you?

**Comment by d-b-w** [comment]
I think matching the name used by the SDF documentation seems reasonable. The only potential downside is if we want this datastructure to represent data that doesn't match SDF V3000 file data. Currently, it's tied pretty closely to the types of things that can be stored in SDF V3000, but we've talked about changing that (maybe these property groups could represent residues in a protein?)

Other options:

* Residue (probably bad. Too restrictive, and doesn't match current usage)
* SubstanceGroup (Matches SDF, which is a pro and a con)
* DepictionData (They include more than depiction data, but some information is purely for depiction, e.g. where to draw brackets or bonds in repeat units.). 
* AtomCollection (But this also includes bonds.)
* AtomGroupProps (But this also includes bonds.)
* SubgraphProps (Because it describes properties that apply to a subgraph. Seems oddly abstract)
* MoietyProps (Usually this makes me think of a functional group, so maybe the scope is too small)
* GroupProps (Maybe this is too generic. It makes me wonder Group of what?)

I find myself drawn towards **SubstanceGroup** or **GroupProps**. If the latter, we could probably do some work to remove some of the methods and members and drop them in as properties rather than defined in the class system.

**Comment by bp-kelley** [comment]
It appears that SubstanceGroup is the current winner.  Agreed?

**Comment by d-b-w** [comment]
Let's do it.

**Pull request merged**
