### PR TITLE
Fixed R-group attachment positions in RGD

### PR DESCRIPTION
**Pull request by jones-gareth**
#### Reference Issue
Fixes https://github.com/rdkit/rdkit/issues/5569

#### What does this implement/fix? Explain your changes.

See summary in next comment

### CODE REVIEW

**Comment by jones-gareth** [comment]
Restoring the order of adding atom positions (first set terminal coordinates, next apply guesses from the `dummyAtomMap`) gives a decent depiction:
image

I noticed that, in master, any coordinates set by `MolOps::setTerminalAtomCoords` would be discarded by the later call to `updateSubMolConfs`.

**Comment by jones-gareth** [comment]
`dummyAtomMap` in `RDKit::replaceCore` maps neighbor indices to dummy atoms.  However, a single neighbor index be mapped to multiple dummy atoms.  I have reversed the map and everything looks good.

image

I'm not sure that we need the terminal coordinate calculation for the dummy atoms at all.

**Comment by jones-gareth** [comment]
**A summary of the changes here**

**Original logic**

In `RDKit::replaceCore` dummy atom coordinates are set firstly using `MolOps::setTerminalAtomCoords` when new bonds are created and secondly (from neighbors in the input structure) using `dummyAtomMap` towards the end of the function.

**Issues**

- The dummy atom coordinates set by `MolOps::setTerminalAtomCoords` were not correct or not calculated as the core atoms were still part of the new molecule (so the neighbor atom had incorrect valence)
- Regardless of what was set by `MolOps::setTerminalAtomCoords` those coordinates were removed by `updateSubMolConfs`
- Because `dummyAtomMap` mapped neighbor index to new atom it was lossy as multiple new atoms can be mapped to a single neighbor index.

**Fixes**

- Reverse `dummyAtomMap` so it is no longer lossy
- Add dummy atom coordinates using `MolOps::setTerminalAtomCoords` after removing the core and calling `updateSubMolConfs`, but before setting coordinates from `dummyAtomMap`

**Remaining Issues**

- Not sure if these is ever a dummy atom that has coordinates set by `MolOps::setTerminalAtomCoords` but not by `dummyAtomMap`, so perhaps we can remove the code that calculates the coordinates using `MolOps::setTerminalAtomCoords`
- If a fragment is cyclic on the same core atom then both dummy atoms will have the same coordinates.  This seems correct to me, but may cause depiction issues.

The rgroup depiction now correctly reflects the input structure coordinates:

image

**Review by bp-kelley — APPROVED** [review]

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
Thanks @jones-gareth

**Pull request merged**
