### PR TITLE
Fix/github1366

### PR DESCRIPTION
**Pull request by greglandrum**
I think this is a better solution to the problem solved by #1374 

Instead of adding a check in the core C++ I switched it to the wrapper code. I think this makes more sense since testing C++ iterators for validity isn't idiomatic. It also allows testing of `BondIterator`s and use of a better error message.

### CODE REVIEW

**Comment by bp-kelley** [comment]
Interesting, this will take me a bit.  I originally thought you were going to do it in the wrappers anyway.  The downside is that this fix doesn't propagate to Java or C# :(

**Comment by greglandrum** [comment]
That's true, but it doesn't worsen the situation there either.
I'd prefer to think about an (at least approximately) idiomatic solution for the SWIG wrappers and solve the problem there instead.

**Comment by bp-kelley** [comment]
Spent some time trying to break this using a bunch of evilness.  Looks good.

**Comment by greglandrum** [comment]
is it worth adding any of that evilness as tests?

**Pull request merged**
