### PR TITLE
Adds removeAllHydrogenRGroupsAndLabels and fixes kekulization issues

### PR DESCRIPTION
**Pull request by ptosco**
1) fixed residual kekulization issues when R-labels are removed from aromatic atoms on the core

2) added `removeAllHydrogenRGroupsAndLabels` flag, which defaults to `True`. If set to `False`,
   unused user-defined labels on the core will be retained. If also `removeAllHydrogenRGroups`
   is set to `False`, all-hydrogen user-defined R-groups will be included in the output.
   Under no circumstance dynamically-added R-groups (when `onlyMatchAtRGroups=false`)
   that are all-hydrogen will be included in the output, as that's not useful (change
   compared to previous behavior)
3) added tests for (1), (2) and for `removeAllHydrogenRGroups`, that had no tests so far
4) fixed a few documentation typos in the Python code and added some documentation
   to the C++ sources

I also refactored `UsedLabelMap` to be a class rather then yet another obscure `std::map<int, std::pair<int, int>>` as I think it makes maintenance of this complex code a bit easier.

### CODE REVIEW

**Comment by greglandrum** [comment]
@jones-gareth : would you mind looking at this one too in order to see if you agree with the changes?

**Comment by jones-gareth** [comment]
> 
> @jones-gareth : would you mind looking at this one too in order to see if you agree with the changes?

The code changes are good, I'm just uncertain about the need for an extra parameter.  Do you see a common scenario where you set `removeAllHydrogenRGroups` true and `removeAllHydrogenRGroupsAndLabels` false?  We did have a discussion about that in a previous PR - I think the conclusion was to remove unused R group labels.

There are numerous RGD parameters that result in different code paths that become hard to maintain and test.

**Comment by ptosco** [comment]
@jones-gareth Yes, I do see a use case. As a chemist, if I supply a user-labelled core, I might find it undesirable that some labels disappear from the core that I have supplied, as I might not recognize my own scaffolds anymore. However, I may be happy not to see the `H` R groups in the results. Setting the additional parameter gives me the flexibility to do so. Also, this has been the RGD behavior until Release 2020.09, and it could be confusing to change it.

**Comment by jones-gareth** [comment]
> 
> 
> @jones-gareth Yes, I do see a use case. As a chemist, if I supply a user-labelled core, I might find it undesirable that some labels disappear from the core that I have supplied, as I might not recognize my own scaffolds anymore. However, I may be happy not to see the `H` R groups in the results. Setting the additional parameter gives me the flexibility to do so. Also, this has been the RGD behavior until Release 2020.09, and it could be confusing to change it.

OK makes sense.

**Review by greglandrum — APPROVED** [review]

**Pull request merged**
