### PR TITLE
Extra rascal option

### PR DESCRIPTION
**Pull request by DavidACosgrove**
#### Reference Issue
Fixes issue #7054 

#### What does this implement/fix? Explain your changes.
Exposes maxBondMatchPairs to the Python wrapper.

### CODE REVIEW

**Comment by DavidACosgrove** [comment]
The test failures are odd, and I don't think they're down to these changes.

**Comment by bp-kelley** [comment]
pandas-2.2.0 Was just released.  Pretty sure this is the culprit

**Comment by greglandrum** [comment]
> pandas-2.2.0 Was just released.  Pretty sure this is the culprit

Yeah, I agree. I will do a PR today to freeze the version of pandas used in the CI builds

We can add fixes for the new pandas version later

**Comment by bp-kelley** [comment]
@DavidACosgrove a merge from main will fix the issue

**Comment by DavidACosgrove** [comment]
Thanks. I’ll do it this evening.

**Review by greglandrum — APPROVED** [review]
LGTM

**Pull request merged**
