### PR TITLE
remove bare excepts

### PR DESCRIPTION
**Pull request by adalke**
Many parts of the RDKit use bare excepts, that is, "except:". This is poor Python style because it often ends up producing overly broad catch/ignore behavior. For example, ^C (KeyboardInterrupt) is an exception that should not be caught and ignored, nor should SystemExit or MemoryError.

There are several ways to fix them. The hammer solution is to replace "except:" with "except Exception", which catches everything but the important exceptions. (KeyboardInterrupt, etc. are derived from BaseException.) This pull request instead specifies more appropriate handling for each case.

For the unit test code, this includes using "self.assertRaisesRegexp()" instead of a long chain of except/else/okay flag/assertTrue, to ensure that the proper exception was raised, and using otherunittest methods which were a better fit to what was needed.

Some of the SMILES and SMARTS code expected that the parser would raise an exception on error, when they instead return None. This can require some code tweaking and indentation changes.

Many of the cleanups were to use the more specific exception, such as ImportError around "import" statements that can fail, or ValueError for int()/float() failures.

Some other fixes included d.get(name, default) or getttr(obj, name, default), instead of catching the KeyError or AttributeError.

Some of the code seems long dead. In a couple of cases I had to make changes just to get the code to run again. However, I could not run all of the code (esp. Windows specific code).

In a few cases I also cleaned up the unit test, most notably in the sparse/explicit fingerprint code where I merged test code, and ended up getting rid of UnitTestcBitVect2.py . (See 3655ff9db60a97639a7a9ffcb994a2235d1b5878 )

Note: kienerj started this work at the UGM 2015 sprint.

### CODE REVIEW

**Comment by greglandrum** [comment]
Thanks Andrew (@adalke) !
Would you mind taking a look at the travis failures (https://travis-ci.org/rdkit/rdkit/builds/79121361) and seeing if you can figure out what's going wrong? This would give me some more confidence in the PR before I start reviewing it in more details.

**Comment by adalke** [comment]
On Sep 9, 2015, at 10:12 AM, Greg Landrum wrote:
> Would you mind taking a look at the travis failures (https://travis-ci.org/rdkit/rdkit/builds/79121361) and seeing if you can figure out what's going wrong? This would give me some more confidence in the PR before I start reviewing it in more details.

I'm about to head out for a few days of hiking. This is likely the last gasp of summer, which ends on Saturday. In other words, I'm not able to dig too deeply into things right now or figure out how to update a patch. Here's what I did see:

  File "/home/travis/build/rdkit/rdkit/rdkit/ML/Data/Stats.py", line 85, in PrincipalComponents
    eivenVals = getattr(eigenVals, "real", eivenVals)
  UnboundLocalError: local variable 'eivenVals' referenced before assignment

  File "/home/travis/build/rdkit/rdkit/rdkit/ML/Data/Stats.py", line 85, in PrincipalComponents
    eivenVals = getattr(eigenVals, "real", eivenVals)
  UnboundLocalError: local variable 'eivenVals' referenced before assignment

  File "/home/travis/build/rdkit/rdkit/rdkit/ML/Data/Stats.py", line 85, in PrincipalComponents
    eivenVals = getattr(eigenVals, "real", eivenVals)
  UnboundLocalError: local variable 'eivenVals' referenced before assignment

Those are a typo combined with copy/paste errors on my side. "eivenVals" should be "eigenVals". This line, btw, replaces

 try:    
   eigenVals = eigenVals.real    
 except:    
   pass


As for the errors in pythonTestDirChem  and pythonTestDirML, I can't find it in my source tree:

[xebulon:~/cvses/rdkit_sprint] dalke% grep pythonTestDirML -r .
./rdkit/CMakeLists.txt:add_pytest(pythonTestDirML
[xebulon:~/cvses/rdkit_sprint] dalke% find . -name '*TestDirML*'
[xebulon:~/cvses/rdkit_sprint] dalke% find . -name '*TestDirChem*'
[xebulon:~/cvses/rdkit_sprint] dalke% grep TestDirChem -r .
./rdkit/CMakeLists.txt:add_pytest(pythonTestDirChem
[xebulon:~/cvses/rdkit_sprint] dalke% 

The last failure I saw was:

ERROR: test4Github252 (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "UnitTestPharmacophore.py", line 117, in test4Github252
    pcophore = Pharmacophore.Pharmacophore(feats)
  File "/home/travis/build/rdkit/rdkit/rdkit/Chem/Pharm3D/Pharmacophore.py", line 20, in __init__
    self._initializeFeats(feats)
  File "/home/travis/build/rdkit/rdkit/rdkit/Chem/Pharm3D/Pharmacophore.py", line 31, in _initializeFeats
    pos = feat.GetPos()
RuntimeError: Pre-condition Violation

That looks like I inverted the test. UnitTestPharmacophore.py was:


try:    
  pcophore = Pharmacophore.Pharmacophore(feats)    
  ok=False    
except:    
  ok=True    
  self.assertTrue(ok)


and I thought it was testing that it did NOT raise an exception, when it actually tests to see if it DOES raise an exception.

The new line  177:

  pcophore = Pharmacophore.Pharmacophore(feats)

should be:

  with self.assertRaisesRegexp(Exception, ""):
     pcophore = Pharmacophore.Pharmacophore(feats)



				Andrew
				dalke@dalkescientific.com

**Comment by greglandrum** [comment]
Enjoy the hiking!
I'll try to find some time to take a look over the next few days.

**Comment by greglandrum** [comment]
Took longer than I thought, but now it's in.
Thanks again @adalke!

**Pull request merged**
