### PR TITLE
script to build from source, install and test rdkit for Linux contributors

### PR DESCRIPTION
**Pull request by UnixJunkie**
This was quite long to get this working.
It should ease the life of Linux contributors (like me). :)
This was tested on Ubuntu.

Regards,
Francois.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
It is OK to squash the commits upon merge.

**Comment by UnixJunkie** [comment]
Now, at last, I can get 100% unit tests passing...

**Comment by thegodone** [comment]
Is this is also working on Mac ? 

Envoyé de mon iPhone

**Comment by UnixJunkie** [comment]
I don't have a Mac, so I cannot test.
Note that the scripted was inspired by rdkit/.travis.yml.
Maybe with only a small change it could work on a Mac.
But I will leave this to Mac users, since they can test.

**Comment by bp-kelley** [comment]
I’m not sure this is the right way to do this.  Travis is a bit different since we are only using it for testing and using conda is an expediency.

If you are using conda to build/deploy it is far easier to use a conda recipe and will likely be more up to date than this script.

We could add the recipe to the rdkit sources so that a simple

conda build .

Would work on all conda based systems. That seems like a decent compromise.

Thoughts?

**Comment by UnixJunkie** [comment]
If someone has a proposal so that new contributors can change the code, compile rdkit and run all tests in a glimpse, I will take it.
Currently, I felt like I needed to read some outdated docs, then somewhat come up with my own script,
that started to work after some much testing effort.

**Comment by greglandrum** [comment]
I'm happy to merge this as is, but I wonder if this isn't a better fit for the wiki than having it here in the codebase.

**Comment by greglandrum** [comment]
Any thoughts on that @UnixJunkie ? 
It's clearly really useful to have these kinds of build scripts available, but it's not trivial to keep them up to date and ensure that they still work

**Comment by UnixJunkie** [comment]
The wiki is not executable, so less useful.
I'll periodically check that this script is working (e.g. in case of a new release).

**Comment by UnixJunkie** [comment]
We have a script to build deb packages already.
And another to run the tests.
Maybe it is OK to close this PR.
I might add comments in the existing build script, if needed.

**Pull request closed without merging**
