### PR TITLE
Add section `How to Build RDKit Documentation Locally`

### PR DESCRIPTION
**Pull request by bertiewooster**
#### Reference Issue

Builds on #7813

#### What does this implement/fix? Explain your changes.
Explains how to build RDKit documentation locally, on the page `Getting Started with Contributing to the RDKit`.

### CODE REVIEW

**Comment by bertiewooster** [comment]
The only test failures were because CI ran for too long, more than 90 minutes.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
Thanks @bertiewooster !

**Comment by bertiewooster** [comment]
My pleasure @greglandrum. After this is published, I won't have to go back to the GitHub issue to remember how to build the docs!😀

**Pull request merged**
