### PR TITLE
add support for generating pattern fps for MolBundles

### PR DESCRIPTION
**Pull request by greglandrum**
The pattern fingerprint for the bundle is generated by anding the pattern fingerprints of the molecules it contains

### CODE REVIEW

**Comment by greglandrum** [comment]
@jones-gareth here's the piece to allow pattern fps to be generated for MolBundles.
Feedback/comments welcome!

**Comment by rvianello** [comment]
just a curiosity, but why the intersection (anding) instead of the union?

**Comment by greglandrum** [comment]
> just a curiosity, but why the intersection (anding) instead of the union?

The match condition for a substructure fingerprint is that all of the bits set by the substructure must be set in the molecule.

Doing the union of the bits would require that every sub-molecule in the bundle have a substructure match in the molecule, but the semantics of doing a substructure search with a `MolBundle` is that at least one of the submolecules in the bundle should be a substructure of the molecule.

**Comment by rvianello** [comment]
ah, right, thank you for the clarification. I haven't used the MolBundle so far, and when I read the description my first thought was about searching across a collection of bundles which doesn't probably make as much sense or might be a less frequent use case.

**Comment by jones-gareth** [comment]
@greglandrum Looks good - do you have a sense of the relative performance of using the anded fingerprints versus each fingerprint (or you could do the anded fingerprint then each individual fingerpint)? The worst case would be that if you had a query that just matched variation bonds or link atoms you could end up with little or no fingerprint screenout.

**Comment by greglandrum** [comment]
@jones-gareth : the question about screenout performance is the big one. It is also unfortunately hard to answer in any particularly satisfying way since I don't have a library of real-word example queries to test.
Here's a quick experiment showing screenout rates for 20K compounds using one query with a linknode and one with a position variation bond:
image
Not super conclusive, but I think it at least shows that the fingerprints aren't getting dramatically worse.

The actual notebook:
https://gist.github.com/greglandrum/050f90b89fb0df913dc207ad1025dd6c

**Comment by jones-gareth** [comment]
@greglandrum It's only one example, but the bundle fingerprint works perfectly for the position variation variation bond example, and somewhere between 90 and 143 extra fingerprint mismatches for the link node query.  Not bad for 20K compounds.  Of course, you have to do atom by atom searches for each molecule in the bundle.  As you say, without more data, it is not possible to quantify the screenout performance.

Since the current solution is the least complex, maybe the best thing is go with this and wait to see if issues are reported.

**Pull request merged**
