### PR TITLE
fix MSVC DLL build after moldraw2d refactor

### PR DESCRIPTION
**Pull request by ricrogz**
I just tried to build on windows using MSVC as the compiler. The build apparently failed because these classes are not DLL exported, and the abstract destructor was not implemented in the child classes (though its in the parent).

### CODE REVIEW

**Comment by greglandrum** [comment]
@ricrogz though I don't think it does any harm to add these, I'm surprised that it was necessary. We do MSVC DLL builds as part of the CI builds and I've been regularly doing them myself as well and no problems have shown up.

Which compiler/cmake options were you using?

**Comment by ricrogz** [comment]
> Which compiler/cmake options were you using?

I'm using VS2017 (`MSVC 19.15.26730.0`) with cmake options:
```
RDK_BUILD_CPP_TESTS: OFF
RDK_BUILD_INCHI_SUPPORT: ON
RDK_BUILD_QT_SUPPORT: ON
RDK_INSTALL_DLLS_MSVC: ON
RDK_INSTALL_INTREE: OFF
RDK_INSTALL_STATIC_LIBS: OFF
RDK_OPTIMIZE_POPCNT: OFF

+ a prefix path, and other paths to find eigen, coordgen, maeparser, zlib, python

+ a path to freetype being set as an env value (CMake's Freetype config is special and doesn't allow passing it through an option).
```

This is the same setup I've been using to build RDKit for some time, except that this time I dropped the Java SWIG wrappers.


The build fails with:
```
[stdout]    Creating library ..\..\..\..\lib\RDKitMolDraw2DQt.lib and object ..\..\..\..\lib\RDKitMolDraw2DQt.exp
[stdout] DrawTextQt.cpp.obj : error LNK2019: unresolved external symbol "public: __cdecl RDKit::MolDraw2D_detail::DrawTextNotFT::DrawTextNotFT(double,double)" (??0DrawTextNotFT@MolDraw2D_detail@RDKit@@QEAA@NN@Z) referenced in function "public: __cdecl RDKit::MolDraw2D_detail::DrawTextQt::DrawTextQt(double,double,class QPainter *)" (??0DrawTextQt@MolDraw2D_detail@RDKit@@QEAA@NNPEAVQPainter@@@Z)
[stdout] DrawTextQt.cpp.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl RDKit::MolDraw2D_detail::DrawTextNotFT::~DrawTextNotFT(void)" (??1DrawTextNotFT@MolDraw2D_detail@RDKit@@UEAA@XZ) referenced in function "int `public: __cdecl RDKit::MolDraw2D_detail::DrawTextQt::DrawTextQt(double,double,class QPainter *)'::`1'::dtor$0" (?dtor$0@?0???0DrawTextQt@MolDraw2D_detail@RDKit@@QEAA@NNPEAVQPainter@@@Z@4HA)
[stdout] DrawTextQt.cpp.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl RDKit::MolDraw2D_detail::DrawTextNotFT::alignString(enum RDKit::MolDraw2D_detail::TextAlignType,class std::vector<enum RDKit::MolDraw2D_detail::TextDrawType,class std::allocator<enum RDKit::MolDraw2D_detail::TextDrawType> > const &,class std::vector<class std::shared_ptr<struct RDKit::MolDraw2D_detail::StringRect>,class std::allocator<class std::shared_ptr<struct RDKit::MolDraw2D_detail::StringRect> > > &)const " (?Code/GraphMol/MolDraw2D/DrawTextNotFT.halignString@DrawTextNotFT@MolDraw2D_detail@RDKit@@UEBAXW4TextAlignType@23@AEBV?$vector@W4TextDrawType@MolDraw2D_detail@RDKit@@V?$allocator@W4TextDrawType@MolDraw2D_detail@RDKit@@@std@@@std@@AEAV?$vector@V?$shared_ptr@UStringRect@MolDraw2D_detail@RDKit@@@std@@V?$allocator@V?$shared_ptr@UStringRect@MolDraw2D_detail@RDKit@@@std@@@2@@6@@Z)
[stdout] ..\..\..\..\bin\RDKitMolDraw2DQt.dll : fatal error LNK1120: 3 unresolved externals
```

This was solved when I added the exports to `Code/GraphMol/MolDraw2D/DrawTextNotFT.h` and made the destructor virtual (not abstract). I added the exports to the child classes preventively ("better safe than sorry"), as I am not sure if we'd need those when building with different configs.

**Comment by greglandrum** [comment]
@ricrogz : the flags for the CI windows DLL build are here:
https://github.com/rdkit/rdkit/blob/master/.azure-pipelines/vs_build_dll.yml
Those are currently running with VS2019. I do builds with VS2022, but was using VS2017 until recently

**Comment by ricrogz** [comment]
> @ricrogz : the flags for the CI windows DLL build are here: https://github.com/rdkit/rdkit/blob/master/.azure-pipelines/vs_build_dll.yml Those are currently running with VS2019. I do builds with VS2022, but was using VS2017 until recently

Qt is disabled in these, and it was `RDKitMolDraw2DQt.dll` that failed in my build.

**Comment by ricrogz** [comment]
I gave this another look:

- `DrawTextNotFT` needs to be exported because it is built into library `MolDraw2D` (https://github.com/rdkit/rdkit/blob/240377115adf53916c2e462192f838eef6dbfa06/Code/GraphMol/MolDraw2D/CMakeLists.txt#L37), but used in `MolDraw2DQt` (e.g. https://github.com/rdkit/rdkit/blob/240377115adf53916c2e462192f838eef6dbfa06/Code/GraphMol/MolDraw2D/Qt/DrawTextQt.h#L22). All other added exports in my first commit are not required, since all classes are not really required, since it seems these classes are only internal to the same dll in which they are defined.
- `~DrawTextNotFT()` still needs to be defined, since it is inherited by child classes.
- `DrawTextFTQt` and `DrawTextQt` also need to be exported, since they are declared in public headers, and should therefore be accessible from code that includes these headers.

**Comment by greglandrum** [comment]
@ricrogz : I just did a PR against your branch which, I think, further cleans things up.

**Comment by ricrogz** [comment]
@greglandrum, I merged your changes. I had a look at the diff against master, and they make sense to me. I also tried my build with them, and it passed.

**Review by greglandrum — APPROVED** [review]

**Comment by greglandrum** [comment]
Thanks @ricrogz !

**Comment by ricrogz** [comment]
np!

**Pull request merged**
