### PR TITLE
make MolsMatrixToGridImage() work in notebook

### PR DESCRIPTION
**Pull request by greglandrum**
this was an oversight when we did the original review

### CODE REVIEW

**Comment by greglandrum** [comment]
@ptosco this is a small one

**Comment by greglandrum** [comment]
> LGTM. This was more a `spot out the only few real changes from all the irrelevant formatting changes` exercise :)

yeah, that's definitely the downside of the auto code formatters.

**Comment by bertiewooster** [comment]
I just now noticed this PR; thanks for getting MolsMatrixToGridImage working in notebooks! I understand a unit test for IPython was added, so if I add any more drawing features, I'll think whether an IPython test is required.

Out of curiosity, what was the substantive change in `__init__.MolsMatrixToGridImage()`? The only thing I noticed besides `the irrelevant formatting changes` :) was using the keywords for arguments:

```
return MolsToGridImage(mols, molsPerRow=molsPerRow, subImgSize=subImgSize, legends=legends,
                         highlightAtomLists=highlightAtomLists,
                         highlightBondLists=highlightBondLists, **kwargs)
```

**Comment by greglandrum** [comment]
> 
> Out of curiosity, what was the substantive change in `__init__.MolsMatrixToGridImage()`? The only thing I noticed besides `the irrelevant formatting changes` :) was using the keywords for arguments:

The monkey patching done in `IPythonConsole.py` adds another argument to `MolsToGridImage()` which comes before the other **kwargs. This broke the way you were calling `MolsToGridImage()`.

I think that it's in general good practice to call use keywords when calling functions with keyword arguments

**Comment by bertiewooster** [comment]
Got it, thanks!

> I think that it's in general good practice to call use keywords when calling functions with keyword arguments

Good point, will do. Over the past few months I've found that helpful in other scenarios too, for example when I add a parameter to the function signature; using the keywords then ensures that the parameter order is not a problem.

**Comment by greglandrum** [comment]
> Good point, will do. Over the past few months I've found that helpful in other scenarios too, for example when I add a parameter to the function signature; using the keywords then ensures that the parameter order is not a problem.

Exactly. :-)

**Pull request merged**
