### PR TITLE
Add java builds to azure devops

### PR DESCRIPTION
**Pull request by greglandrum**
Adds two new pieces to the Azure DevOps build matrix: Linux and Mac builds for the Java SWIG wrappers.

Some notes:
- We should add windows builds to this at some point in the future, but I wanted to at least get something in place now. When we do them, those could also test the C# bindings.
- Note that this also tests that building/using static linkage actually works. That's been a rude surprise a couple of times in the past.
- The rude surprises mentioned above explain why there are also a couple of changes to the cmake files associated with this PR.

I'm attaching this PR to the next milestone on the release branch. Having automated builds/testing of the SWIG wrappers there would definitely be a good thing and the changes to the cmake files are already there anyway.

### CODE REVIEW

**Comment by greglandrum** [comment]
The appveyor build here is failing, but given that the Azure DevOps windows build, which covers more, works I'm having a hard time motivating myself to try and fix that.
I'm tempted to disable the appveyor connection since that's really just testing whether or not a subset of the code builds on Windows.

**Comment by bp-kelley** [comment]
I would drop it.  I can easily set up the rdkit-csharp repo to make c# builds.  There is a swig bug with one of the enums that needs to be patched, I’ll see if I can sort that out as well.

----
Brian Kelley

**Comment by greglandrum** [comment]
I think we can add another entry to the azure devops build matrix that does both the Java and C# SWIG wrappers.

**Comment by greglandrum** [comment]
Let me confirm that this builds on my "normal" windows box. If that works I will remove the appveyor builds

**Comment by greglandrum** [comment]
windows build worked fine for me.
The most recent commit removes `appveyor.yml`. I will disable the github connection when this PR is merged.

**Comment by bp-kelley** [comment]
You’ll need to merge by hand here as GitHub doesn’t want to merge when tests are failing.

**Comment by greglandrum** [comment]
> You’ll need to merge by hand here as GitHub doesn’t want to merge when tests are failing.

That is, fortunately, just a "feature" of the mobile UI. The standard web UI lets you merge despite failing tests. It's done.

I'll disable the appveyor connection.

**Pull request merged**
