### PR TITLE
Make AvalonTools source handling like the InChI source handling

### PR DESCRIPTION
**Pull request by greglandrum**
@bp-kelley and @rvianello : this is a first pass at what could be a solution to how to handle the Avalon source (Re: #524). It's not perfect, but it at least has the virtue of being consistent with the way the InChI code is handled.

### CODE REVIEW

**Comment by bp-kelley** [comment]
I'll see how this merges with our internal version which uses CMAKE to download avalon unless it already is in place.

**Comment by rvianello** [comment]
@greglandrum fwiw the approach looks good to me, thanks for this. btw, in building the Avalon 1.2.0 distribution, the conda recipe overwrites file reaccsio.c to remove a deallocation that was reported to cause a crash on windows (https://github.com/rdkit/conda-rdkit/blob/master/rdkit/avalon_reaccsio.c#L2). Is this patching unnecessary or should the README file mention it? (best would probably be an Avalon 1.2.1 package fixing the problem, if not solved already)

**Comment by greglandrum** [comment]
@rvianello I think it certainly makes sense to use the patched version, at least until a new version of the avalon toolkit is released (as you know, my ability to influence that is now extremely limited).

Any particular reason you chose to include the actual file instead of a diff in the conda-rdkit version?

**Comment by rvianello** [comment]
@greglandrum the choice was mainly due to the unavailability of the patch utility in the windows environment (the avalontools source distribution is fetched after the build script has started executing, but conda-build applies the bundled patch files at an earlier stage, so the build script would have been required to apply the patch autonomously). Apparently, win32/win64 'patch' packages are now available from the anaconda channels, so replacing the whole file with a diff should be much easier (I'll look into this).

**Comment by bp-kelley** [comment]
@ptosco is using the internal CMake download scripts as opposed to wget, if this works out perhaps we should do the same for both.

**Comment by bp-kelley** [comment]
I finally have time to test the CMake download system from our internal builds, if that passes would this work here become vestigial?

**Comment by greglandrum** [comment]
Yeah, it certainly would.

**Comment by ptosco** [comment]
The one upside of the CMake download as implemented in this pull request is that it only uses native tools available within the CMake toolchain or within the respective OSs (i.e., the curl fallback for Linux/OS X in case OpenSSL support is not built into CMake), such that it does not introduce any external dependencies. Also the AvalonTools patch is applied through a CMake regex.

**Comment by greglandrum** [comment]
After @ptosco made the changes in #785 this is no longer needed.

Closing it

**Pull request closed without merging**
