### PR TITLE
Update MDLParser.cpp

### PR DESCRIPTION
**Pull request by jungb-basf**
Fix length of expected strings "BEGIN AGENT" and "END AGENT"

### CODE REVIEW

**Comment by jungb-basf** [comment]
fixes #4183

**Review by greglandrum — CHANGES_REQUESTED** [review]
@jungb-basf : thanks for the contribution!
this code change looks good, but it needs to have a test or two added before we merge it
Please take a look in either Code/GraphMol/ChemReactions/catch_tests.cpp or Code/GraphMol/ChemReactions/testReaction.cpp for examples of what these look like

**Comment by greglandrum** [comment]
Feel free to ask if you have questions about what I'm asking for.

**Comment by greglandrum** [comment]
Hi @jungb-basf : you also need to actually add a test which uses the test data file you added

**Review by greglandrum — APPROVED** [review]

**Comment by greglandrum** [comment]
Thanks for the contribution @jungb-basf !

**Pull request merged**
