### PR TITLE
Dev/filter catalog java wrapper

### PR DESCRIPTION
**Pull request by bp-kelley**
Add basic Java support for FilterCatalog (creating new FilterCatalogs is not implemented yet)

This patch includes minor changes to FilterCatalog.h to enable easier shared_ptr<FilterCatalogEntry> support an a clean up of typedefs that were causing Swig issues.

```java
  FilterCatalog catalog = new FilterCatalog(
        FilterCatalogParams.FilterCatalogs.PAINS_A);

  // go through a mol supplier
  while (!molSupplier.atEnd()) {
   ROMol m = suppl.next();
   FilterCatalogEntry_Vect matches = catalog.getMatches(mol);
   if( matches.size() ) {
      // reject -- get descriptions of rejection
      for (int entryIdx = 0; entryIdx < matches.size(); ++entryIdx) {
          entry = matches.get(entryIdx);
          String description = entry.getDescription(); // why
          // optional properties
          String reference  = entry.getProp("Reference");
          String scope = entry.getProp("Scope");
      }
   }
   else {
     // accept
   }
  }
```

Serialization support is also available.
```java
                byte pickle[] = catalog.Serialize();
                FilterCatalog catalog2 = FilterCatalog.Deserialize(pickle);
```

Catalogs can be created in Python or C++ and deserialized in Java.  You may wish to use Base64 encoding when transferring binary data.  See java.util.Base64 for more details.

### CODE REVIEW

**Comment by bp-kelley** [comment]
It looks like there are dependency issues on linux/windows.  Looking for a fix.

**Comment by greglandrum** [comment]
I just got a linux build working with these changes:
```
glandrum@Otter:/scratch/RDKit_git/build$ git diff
diff --git a/Code/GraphMol/FilterCatalog/CMakeLists.txt b/Code/GraphMol/FilterCatalog/CMakeLists.txt
index fcd6260..d6ce021 100644
--- a/Code/GraphMol/FilterCatalog/CMakeLists.txt
+++ b/Code/GraphMol/FilterCatalog/CMakeLists.txt
@@ -26,7 +26,7 @@ rdkit_library(FilterCatalog
               FilterCatalog.cpp
               FilterCatalogEntry.cpp
               FilterMatchers.cpp
-              LINK_LIBRARIES ${Boost_SERIALIZATION_LIBRARY} Subgraphs SubstructMatch SmilesParse GraphMol RDGeometryLib Catalogs RDGeneral )
+              LINK_LIBRARIES Subgraphs SubstructMatch SmilesParse GraphMol RDGeometryLib Catalogs RDGeneral )
 
 rdkit_headers(FilterCatalogEntry.h
               FilterCatalog.h
@@ -37,5 +37,6 @@ rdkit_headers(FilterCatalogEntry.h
 add_subdirectory(Wrap)
 
 rdkit_test(filterCatalogTest filtercatalogtest.cpp
-           LINK_LIBRARIES ${Boost_SERIALIZATION_LIBRARY} FilterCatalog
-           Catalogs SubstructMatch FileParsers SmilesParse GraphMol RDGeometryLib RDGeneral)
+           LINK_LIBRARIES FilterCatalog 
+           Catalogs SubstructMatch FileParsers SmilesParse GraphMol RDGeometryLib RDGeneral 
+           ${Boost_SERIALIZATION_LIBRARY})
diff --git a/Code/GraphMol/FilterCatalog/Wrap/CMakeLists.txt b/Code/GraphMol/FilterCatalog/Wrap/CMakeLists.txt
index 98109f0..1fccb6c 100644
--- a/Code/GraphMol/FilterCatalog/Wrap/CMakeLists.txt
+++ b/Code/GraphMol/FilterCatalog/Wrap/CMakeLists.txt
@@ -12,9 +12,10 @@ rdkit_python_extension(rdfiltercatalog
                        FilterCatalog.cpp
                        DEST Chem 
                        LINK_LIBRARIES
-                       ${Boost_SERIALIZATION_LIBRARY} 
                        FilterCatalog 
-Subgraphs SubstructMatch SmilesParse Catalogs FileParsers GraphMol DataStructs RDGeometryLib RDGeneral 
- RDBoost) 
+Subgraphs SubstructMatch SmilesParse Catalogs FileParsers GraphMol DataStructs
+RDGeometryLib RDGeneral RDBoost  
+${Boost_SERIALIZATION_LIBRARY} 
+) 
 
 add_pytest(pyFilterCatalog ${CMAKE_CURRENT_SOURCE_DIR}/rough_test.py)
diff --git a/Code/JavaWrappers/CMakeLists.txt b/Code/JavaWrappers/CMakeLists.txt
index 2aab506..f97a2bc 100644
--- a/Code/JavaWrappers/CMakeLists.txt
+++ b/Code/JavaWrappers/CMakeLists.txt
@@ -1,8 +1,6 @@
 find_package(SWIG REQUIRED)
 include(${SWIG_USE_FILE})
 
-# we want to link java statically...
-set(Boost_USE_STATIC_LIBS   ON)
 set(T_LIBS ${Boost_LIBRARIES})
 find_package(Boost 1.39.0 COMPONENTS serialization)
 if (Boost_SERIALIZATION_LIBRARY)
@@ -18,6 +16,8 @@ SET(CMAKE_SWIG_FLAGS "")
 
 if(WIN32)
        set(RDKit_Wrapper_Libs
+        FilterCatalog
+        Catalogs
         ${Boost_SERIALIZATION_LIBRARY} 
         FMCS MolDraw2D
         FileParsers SmilesParse
@@ -39,9 +39,9 @@ if(WIN32)
         endif(RDK_BUILD_AVALON_SUPPORT)
 else()
        set(RDKit_Wrapper_Libs
-        ${Boost_SERIALIZATION_LIBRARY}
         Catalogs_static
         FilterCatalog_static
+        ${Boost_SERIALIZATION_LIBRARY}
         FMCS_static MolDraw2D_static
         FileParsers_static SmilesParse_static
        Depictor_static SubstructMatch_static ChemReactions_static Fingerprints_static ChemTransforms_static
diff --git a/Code/JavaWrappers/gmwrapper/CMakeLists.txt b/Code/JavaWrappers/gmwrapper/CMakeLists.txt
index 885c742..45261db 100644
--- a/Code/JavaWrappers/gmwrapper/CMakeLists.txt
+++ b/Code/JavaWrappers/gmwrapper/CMakeLists.txt
@@ -82,7 +82,7 @@ SWIG_ADD_MODULE(GraphMolWrap "java" GraphMolJava.i )
 # as of Oct 2012 using boost 1.51 under at least ubuntu 12.04 we get a
 # link error if they aren't there.
 SWIG_LINK_LIBRARIES(GraphMolWrap ${RDKit_Wrapper_Libs}
-      ${RDKit_THREAD_LIBS})
+      ${Boost_SERIALIZATION_LIBRARY} ${RDKit_THREAD_LIBS})
 
 # code adapted from the wrapper code for
 # GDCM: http://gdcm.svn.sf.net/viewvc/gdcm/trunk/Wrapping/Java/CMakeLists.txt?view=markup
```

If they look ok to you, can you please add to the PR?

**Comment by bp-kelley** [comment]
This still links boost_serialization dynamically.  I'm trying to make a fix for Java to link statically to avoid the new dependency.

**Comment by greglandrum** [comment]
The dynamic link dependencies are there already anyway due to boost threading. I'm not sure it's worth the effort.

**Comment by bp-kelley** [comment]
As I feared, it's failing in travis due to the missing dependency:

java.lang.UnsatisfiedLinkError: /home/travis/build/rdkit/rdkit/Code/JavaWrappers/gmwrapper/libGraphMolWrap.so: libboost_serialization.so.1.55.0: cannot open shared object file: No such file or directory

**Comment by greglandrum** [comment]
yes, the travis build uses the rdkit conda recipe. That needs to be updated, along with the binstar builds that are being used. We will need help from @rvianello here.

**Comment by rvianello** [comment]
I will update the boost recipe from conda-rdkit to include the serialization library, but i think that the boost 1.55.0 package available from the rdkit channel on anaconda.org and that is used by travis-ci still includes boost-serialization (I think it predates the changes to the recipes that limited the build to boost-python, -regex, -thread and -system). 

I don't know the reason for the link error in building the java wrapper, but the output from the cmake configuration step seems to confirm that boost-serialization is found
https://travis-ci.org/rdkit/rdkit/jobs/79854926#L526

**Comment by bp-kelley** [comment]
@rvianello It's not an error in building the Java wrapper, it's an error in running the tests.  I expect we need to put the path to libboost_serialization.so in the java library path ala "java -Djava.library.path=/path/to/boost"

**Comment by bp-kelley** [comment]
Hooray, the travis builds passed.

**Pull request merged**
