### PR TITLE
Fix #4570 Segfault on Property Getters/Setters

### LINKED ISSUE #4570: Segmentation fault using None as property name in SetProp
```
>>> from rdkit import Chem
>>> m = Chem.MolFromSmiles("CCC")
>>> m.SetProp(None, "foo")
Segmentation fault: 11
```

This happens at least on OSX.

### PR DESCRIPTION
**Pull request by bp-kelley**
Fixes #4570 

It turns out that any Boost python function that has a signature

```
T func(const char * value)
```

will segfault when called with

```
func(None)
```

Switching to:
```
T func(const std::string &value)
```

is the easy solution here as boost will not permit the type cast.  We should probably have a once over for char * in exposed functions.

### CODE REVIEW

**Review by greglandrum — CHANGES_REQUESTED** [review]
This PR somehow overwrites the changes added to the documentation in #8005 
please undo that

**Comment by bp-kelley** [comment]
Good catch, that’s really odd.

**Comment by bp-kelley** [comment]
@greglandrum should be fixed now

**Review by greglandrum — APPROVED** [review]
LGTM

**Pull request merged**
