### PR TITLE
Use submodule for External (#2133)

### PR DESCRIPTION
**Pull request by e-kwsm**
#### Reference Issue
#2133

#### What does this implement/fix? Explain your changes.
Try to perform `git submodule init` for the following:
- External/CoordGen/coordgen
- External/CoordGen/maeparser
- External/catch/catch

### CODE REVIEW

**Comment by e-kwsm** [comment]
Submodules are pinned so that they are consistent with the corresponding tar balls.

[CI failure](https://travis-ci.com/rdkit/rdkit/jobs/255620947#L217) is due to maeparser submodule leftovers 
in coordgenlibs, which is fixed by schrodinger/coordgenlibs@589e7ca4f3737c7566baab85e2fe22ddc6f19011 (schrodinger/coordgenlibs#41).
The change is not versioned yet.

**Comment by bp-kelley** [comment]
There is a consistent failure during configuration:

```
The command "eval git submodule update --init --recursive " failed. Retrying, 2 of 3.

fatal: No url found for submodule path 'External/CoordGen/coordgen/maeparser' in .gitmodulesFailed to recurse into submodule path 'External/CoordGen/coordgen'

The command "eval git submodule update --init --recursive " failed. Retrying, 3 of 3.

fatal: No url found for submodule path 'External/CoordGen/coordgen/maeparser' in .gitmodules
Failed to recurse into submodule path 'External/CoordGen/coordgen'

The command "eval git submodule update --init --recursive " failed 3 times.

The command "git submodule update --init --recursive" failed and exited with 1 during .
```

**Comment by e-kwsm** [comment]
The issue is fixed by pinning coordgen to schrodinger/coordgenlibs@a45ecd9a738317c17b5e16b9675a4f8694b9422a, try `git clone --branch=_submodule_a45ecd9 --recursive https://github.com/e-kwsm/rdkit.git`.
But it is not compatible with the current tarball.

**Comment by d-b-w** [comment]
Would it be helpful if I issue releases for coordgen & maeparser?

**Comment by e-kwsm** [comment]
@d-b-w  I appreciate if the issue is fixed, but priority is not high—current mechanism (download tarball) is working.

**Pull request closed without merging**
