### PR TITLE
Fixes #713

### LINKED ISSUE #713: Molecule serialization doesn't read/write atomic numbers above 128
Here's the mailing list thread: http://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg05207.html

### PR DESCRIPTION
**Pull request by greglandrum**

### CODE REVIEW

**Comment by bp-kelley** [comment]
I see you are having travis java issues as well, except this time on 2.7..

**Comment by bp-kelley** [comment]
It's a bit lame, but there should be a test for this :)

**Comment by greglandrum** [comment]
It's odd, because there's not really an error. The first `make` fails for mysterious reasons, but then when `make install` runs everything is fine. It's almost like there's a race condition around the SWIG output.

I used to see things like this reasonably often while building under Windows too.

**Comment by greglandrum** [comment]
Right you were. There's now a test.

**Comment by greglandrum** [comment]
@bp-kelley Did you intentionally close this without merging it?

**Comment by bp-kelley** [comment]
I actually had intended to merge it!

**Comment by greglandrum** [comment]
Yeah, that's have I've figured. I've clicked "Close" instead of "merge" a few times.

**Pull request merged**
