### PR TITLE
Patch/pains updates

### PR DESCRIPTION
**Pull request by johnmay**
#### Reference Issue
n/a

#### What does this implement/fix? Explain your changes.

Improved PAINS filters

#### Any other comments?

Will upload slides from talk today later.

### CODE REVIEW

**Comment by johnmay** [comment]
Sorry left a fixup up in there that i've now squashed down.

**Comment by johnmay** [comment]
Here are the slides which explain more: [PAINS in the butt](https://www.nextmovesoftware.com/talks/Mayfield_PainsInTheButt_201902.pdf). Still more could be done particularly with regards to Tautomers.

Here are the count difference in eMolecules and PubChem Compound. When only one is present it's because it didn't change (normally still zero) in that database. For example I mention het_5_inium in the slides and show the PubChem standard form doesn't match.

<table>
<tr><td>anil_OC_alk_B</td><td>0</td><td>1099</td><td>PubChemCompound (Oct 2018, 96M)</td></tr>
<tr><td>anil_OC_alk_B</td><td>0</td><td>982</td><td>eMolecules (Jan 2019, 22M)</td></tr>
<tr><td>anil_di_alk_D</td><td>247897</td><td>136436</td><td>PubChemCompound (Oct 2018, 96M)</td></tr>
<tr><td>anil_di_alk_D</td><td>46600</td><td>20393</td><td>eMolecules (Jan 2019, 22M)</td></tr>
<tr><td>anthranil_acid_I</td><td>0</td><td>26</td><td>PubChemCompound (Oct 2018, 96M)</td></tr>
<tr><td>anthranil_acid_I</td><td>0</td><td>8</td><td>eMolecules (Jan 2019, 22M)</td></tr>
<tr><td>het_5_inium</td><td>0</td><td>3</td><td>eMolecules (Jan 2019, 22M)</td></tr>
<tr><td>het_thio_666_A</td><td>11139</td><td>4721</td><td>PubChemCompound (Oct 2018, 96M)</td></tr>
<tr><td>het_thio_666_A</td><td>877</td><td>569</td><td>eMolecules (Jan 2019, 22M)</td></tr>
<tr><td>het_thio_676_A</td><td>1138</td><td>1134</td><td>PubChemCompound (Oct 2018, 96M)</td></tr>
<tr><td>hzone_enamin</td><td>3256</td><td>3063</td><td>PubChemCompound (Oct 2018, 96M)</td></tr>
<tr><td>quinone_A</td><td>166279</td><td>172315</td><td>PubChemCompound (Oct 2018, 96M)</td></tr>
<tr><td>quinone_A</td><td>9058</td><td>9313</td><td>eMolecules (Jan 2019, 22M)</td></tr>
<tr><td>quinone_C</td><td>0</td><td>6</td><td>eMolecules (Jan 2019, 22M)</td></tr>
<tr><td>thiaz_ene_A</td><td>0</td><td>7189</td><td>eMolecules (Jan 2019, 22M)</td></tr>
<tr><td>thiaz_ene_A</td><td>80</td><td>21071</td><td>PubChemCompound (Oct 2018, 96M)</td></tr>
<tr><td>thiaz_ene_C</td><td>0</td><td>193</td><td>eMolecules (Jan 2019, 22M)</td></tr>
<tr><td>thiaz_ene_C</td><td>0</td><td>413</td><td>PubChemCompound (Oct 2018, 96M)</td></tr>
<tr><td>thio_urea_K</td><td>0</td><td>3</td><td>eMolecules (Jan 2019, 22M)</td></tr>
<tr><td>thiophene_E</td><td>1144</td><td>1138</td><td>PubChemCompound (Oct 2018, 96M)</td></tr>
</table>

**Comment by bp-kelley** [comment]
@greglandrum Ok to merge?

**Comment by greglandrum** [comment]
yeah, I actually thought I had done so already

**Pull request merged**
