### PR TITLE
Include element name in atomic data

### PR DESCRIPTION
**Pull request by rachelnwalker**
Hi Greg — I’m taking over the PR Chris made here https://github.com/rdkit/rdkit/pull/5281 and trying to incorporate your suggestion. I think it makes sense to have the element names in a separate data structure, which I tried to do here — let me know if this is what you were thinking.

I got the ordering of the elements from Chris’ original PR.

### CODE REVIEW

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
I like this form a lot better than the original one. Thanks @rachelnwalker !

**Comment by rachelnwalker** [comment]
Thanks @greglandrum!

**Comment by cdvonbargen** [comment]
Awesome, thanks @rachelnwalker and @greglandrum

**Pull request merged**
