### PR TITLE
std::map::at() and msvc9 compatibility

### PR DESCRIPTION
**Pull request by rvianello**
this should fix a minor regression

### CODE REVIEW

**Comment by rvianello** [comment]
the travis-ci build failed for py34 only, due to a network timeout while fetching the avalontools sources.

**Comment by greglandrum** [comment]
You once again have a bunch of extra commits showing up in the PR. There's still only one file modified, but it might be worth tracking down what's causing this.

**Comment by rvianello** [comment]
yes, it's the same set of extra commits that appears for #727 (both are detached from the same point), I'll try and have a look. It is also strange that this specific use of std::map::at has been changed and reverted a couple of times already, but the history for MMPA.cpp doesn't detail these modifications after the initial fix (anyway, at the moment I think I have no relevant/original code in my own fork, so I could also just delete and recreate it)

**Comment by greglandrum** [comment]
Yeah, I thought that we'd fixed this before.
Here's the issue: https://github.com/rdkit/rdkit/issues/655
And here's the commit where @bp-kelley broke it again:
https://github.com/rdkit/rdkit/commit/fe42eb87ef359f84967e5682a3a1e6379eacce56
(of course, I'm ignoring my culpability in this since I nominally reviewed Brian's PR)

**Comment by greglandrum** [comment]
Could you rebase your local repo in order to get the commit history here somewhat cleaner?

**Comment by bp-kelley** [comment]
While fully accepting the blame, at least it passed AppVeyor :)  I'm not even sure I have access to msvc 9 anymore.

**Comment by rvianello** [comment]
msvc 9 is unfortunately the officially recommended compiler for python 2.7 (maybe one more reason to move to python 3.5+).

the extraneous commits are on my master branch, I think part of changes I didn't contribute with a PR, but have been pulled at some point (one is here 00fbab4248), I'll erase my github repo and fork again (I should have avoided committing changes directly onto the master).

**Pull request closed without merging**
