### PR TITLE
Fixes #1886

### LINKED ISSUE #1886: Mark cartridge functions as being parallel safe
Here's the explanation:
https://www.postgresql.org/docs/10/static/parallel-safety.html

An illustration that it works (this is querying ChEMBL23 on my windows laptop):
```
chembl_23=# CREATE OR REPLACE FUNCTION substruct(mol, mol)
chembl_23-# RETURNS bool
chembl_23-# PARALLEL SAFE
chembl_23-# AS 'rdkit.dll', 'mol_substruct'
chembl_23-# LANGUAGE C STRICT IMMUTABLE;
CREATE FUNCTION
chembl_23=# set max_parallel_workers_per_gather=0;
SET
chembl_23=# explain analyze select count(*) from rdk.mols where substruct(m,'O=c1cnn(-c2ccccc2)c(=O)[nH]1');
                                                     QUERY PLAN
--------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=122706.76..122706.77 rows=1 width=8) (actual time=55856.376..55856.376 rows=1 loops=1)
   ->  Seq Scan on mols  (cost=0.00..121267.52 rows=575694 width=0) (actual time=0.169..55856.201 rows=334 loops=1)
         Filter: substruct(m, 'O=c1cnn(-c2ccccc2)c(=O)[nH]1'::mol)
         Rows Removed by Filter: 1726748
 Planning time: 0.073 ms
 Execution time: 55856.796 ms
(6 rows)


chembl_23=# set max_parallel_workers_per_gather=2;
SET
chembl_23=# explain analyze select count(*) from rdk.mols where substruct(m,'O=c1cnn(-c2ccccc2)c(=O)[nH]1');
                                                                QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------
 Finalize Aggregate  (cost=110274.11..110274.12 rows=1 width=8) (actual time=27040.923..27040.923 rows=1 loops=1)
   ->  Gather  (cost=110273.90..110274.11 rows=2 width=8) (actual time=27040.775..27040.918 rows=3 loops=1)
         Workers Planned: 2
         Workers Launched: 2
         ->  Partial Aggregate  (cost=109273.90..109273.91 rows=1 width=8) (actual time=27018.903..27018.903 rows=1 loops=3)
               ->  Parallel Seq Scan on mols  (cost=0.00..108674.22 rows=239872 width=0) (actual time=67.592..27018.808 rows=111 loops=3)
                     Filter: substruct(m, 'O=c1cnn(-c2ccccc2)c(=O)[nH]1'::mol)
                     Rows Removed by Filter: 575583
 Planning time: 0.237 ms
 Execution time: 27048.993 ms
(10 rows)
```

This is clearly only relevant for versions 9.6 and beyond, so we'll have to be careful there.

### PR DESCRIPTION
**Pull request by greglandrum**
This adds the "PARALLEL SAFE" flag to all functions in the cartridge where I'm certain that there are no thread safety problems.

It also bumps the version number of the cartridge.

### CODE REVIEW

**Comment by bp-kelley** [comment]
@greglandrum Perhaps @rvianello should look at this, I'm not savvy at postgres cartridges.

**Comment by rvianello** [comment]
I couldn't yet find an occasion to work with parallel query support in postgres, but fwiw the changes look good to me. The modified functions should be stateless, and therefore paralell safe (the only ones I'm not fully confident with are the fmcs aggregate functions, but just because I ignore the exact implementation).

**Comment by bp-kelley** [comment]
@greglandrum  Do you want me to look at the aggregate functions for parallel safety?

**Comment by rvianello** [comment]
yes, I agree, sorry in case my comment sounded negatively, I didn't mean to delay this PR.

**Comment by greglandrum** [comment]
ok, looks like we agree this should be merged... it's done.

**Pull request merged**
