### PR TITLE
make "R" in CTABs an AtomNull query

### PR DESCRIPTION
**Pull request by greglandrum**
This comes out of the discussion around #2527

Instead of converting "R" into a dummy atom, which by default only matches dummy atoms, this turns it into a query that matches any atom. This seems to me to more closely match what people expect when they draw an "R" in a query structure.

This does mean that you can no longer easily draw a Mol file query that specifically matches dummy atoms, but I think that's a minor use case.

Note that although this is definitely a "changes results" modification, it didn't require me to change any existing tests.

### CODE REVIEW

**Comment by bp-kelley** [comment]
I think this is handled in SanitizeRxn using adjustQueryParameters.  Perhaps we should combine sanitizeRxn with the default readers as it allows control of these params?

**Comment by greglandrum** [comment]
Going to have to think about that for a bit.
This is a simpler thing that just does what the user almost certainly intends.

**Comment by bp-kelley** [comment]
Agreed, but I think in practice the kekule->aromatic is pretty essential as well.

**Comment by greglandrum** [comment]
Agreed, but I don’t think sanitizeRxn() actually does that. (I was surprised to discover this because I expected it to)

**Comment by greglandrum** [comment]
Ah, and here's why `sanitizeRxn()` wasn't aromatizing things for me...
The aromatization is done as part of a call to `adjustQueryProperties()` inside of `adjustTemplate()` and that call isn't made if either adjustDegree or adjustRingCount aren't set:
https://github.com/rdkit/rdkit/blob/320fa22eade8b1022719fe7c2a5b3248ca4b1d49/Code/GraphMol/ChemReactions/SanitizeRxn.cpp#L349
We should clear that up in a separate bug fix

**Comment by bp-kelley** [comment]
Well, crap.  That’s a bug :)

**Comment by greglandrum** [comment]
@bp-kelley: questions answered? This ok to merge?

**Comment by bp-kelley** [comment]
@greglandrum I'm unsure if the question was answered, but I don't see much harm to this change and we can always "fix" it later if it is an issue by solidifying the sanitizerxn and merging that into the mainstream.

The counter question, btw, is that if the bug didn't appear in santizerxn would we use that by default?

**Comment by greglandrum** [comment]
This applies to everything read from mol blocks, so it's considerably broader than sanitizeRxn

**Comment by bp-kelley** [comment]
@greglandrum Once you resolve the conflicts we can merge :)

**Pull request merged**
