### PR TITLE
Fixes #5812

### LINKED ISSUE #5812: Stop using recommonmark in the documentation
recommonmark is used to include markdown in the RDKit's sphinx-based documentation. It has, unfortunately, been deprecated: https://github.com/readthedocs/recommonmark/issues/221

Looks like we should switch from recommonmark to myst-parser

### PR DESCRIPTION
**Pull request by greglandrum**
switch to using myst and do a bunch of cleanup

Now that myst is available and supported we could consider looking into how bad it would be to translate the rst docs into myst-compatible markdown.

### CODE REVIEW

**Comment by bertiewooster** [comment]
+1 on using MyST--I wrote all the documentation for [SymPy's 2022 Season of Docs](https://docs.sympy.org/dev/guides/solving/index.html) in Markdown using MyST, and it worked well. It certainly seems less finicky about white space than rst.

There are options for [automatically converting rst to markdown](https://www.google.com/search?q=convert+rst+to+markdown); I haven't evaluated them.

**Review by bp-kelley — COMMENTED** [review]
LGTM

do we want to version lock sphinx and the must-parser?

I don’t have comments on the changes to the markup yet.  I’ll try and look at the output this weekend.

**Review by bp-kelley — APPROVED** [review]

**Comment by greglandrum** [comment]
> do we want to version lock sphinx and the must-parser?

I removed the old version lock on sphinx since I don't think it's necessary with the new setup. I'd suggest that we leave it without the locks until such a point that it becomes a problem.

**Comment by greglandrum** [comment]
> I don’t have comments on the changes to the markup yet. I’ll try and look at the output this weekend

This PR primarily had small changes to fix things which obviously broken when moving from recommonmark to myst, so there shouldn't be too much there.

We could think about switching the pieces of documentation which are currently in RST to myst-flavored markdown (probably using one of the tools that @bertiewooster mentioned), but that strikes me as a lower priority at the moment.

**Pull request merged**
