### PR TITLE
Allow static building of coordgen and maeparser (with a small upstream

### PR DESCRIPTION
**Pull request by ptosco**
change)

#### What does this implement/fix? Explain your changes.
This PR allows statically building `maeparser` and `coordgen` without need to patch the `maeparser` and `coordgen` headers within the RDKit. However, this requires the following modifications of the upstream headers:

```
--- MaeParserConfig.hpp        2018-06-12 22:25:38.427487000 +0100
+++ MaeParserConfig.hpp     2018-06-12 22:25:46.168272500 +0100
@@ -1,5 +1,7 @@
 #pragma once

+#ifndef STATIC_MAEPARSER
+
 #ifdef IN_MAEPARSER

 #ifdef WIN32
@@ -12,9 +14,12 @@

 #ifdef WIN32
 #define EXPORT_MAEPARSER __declspec(dllimport)
-#else
-#define EXPORT_MAEPARSER
 #endif

 #endif

+#else
+
+#define EXPORT_MAEPARSER
+
+#endif
and CoordgenConfig.hpp

--- CoordgenConfig.hpp      2018-06-12 22:25:22.311649800 +0100
+++ CoordgenConfig.hpp   2018-06-12 22:25:29.512342200 +0100
@@ -1,6 +1,9 @@
 #pragma once

+#ifndef STATIC_COORDGEN
+
 #ifdef IN_COORDGEN
+
 #ifdef WIN32
 #define EXPORT_COORDGEN __declspec(dllexport)
 #else
@@ -11,8 +14,12 @@

 #ifdef WIN32
 #define EXPORT_COORDGEN __declspec(dllimport)
+#endif
+
+#endif
+
 #else
+
 #define EXPORT_COORDGEN
-#endif

-#endif
\ No newline at end of file
+#endif
```

This PR should *not* be merged before the upstream change is made.

### CODE REVIEW

**Comment by bp-kelley** [comment]
I think it's okay, but I also think swig may be upset at the following constructs:
```
class RDKIT_RDGEOMETRYLIB_EXPORT Point
```

Because it can't see the macros.  Have we tried building java lately? 

We may need to %include <windows.i> now

**Comment by bp-kelley** [comment]
Details are in section 3.4 here:

http://www.swig.org/Doc3.0/Windows.html

I'm in favor of merging and then fixing these after the fact.

**Comment by ptosco** [comment]
@bp-kelley SWIG is kept happy by the following `%include` in `Code/JavaWrappers/gmwrapper/GraphMolJava.i`:

```
/* undefine RDKIT_<LIBNAME>_EXPORT macros */
%include <RDBoost/export.h>
```

As `RDBoost/export.h` has

```
#if defined(BOOST_HAS_DECLSPEC) && defined(RDKIT_DYN_LINK) && !defined(SWIG)
```

checks, it will define `RDKIT_RDGEOMETRYLIB_EXPORT` to blank, thus keeping SWIG happy. Java wrappers do build with the current code.
I haven't thought of the C# wrappers, but if you add the same `%include` in the relevant `.i` file it should work.

**Comment by ptosco** [comment]
@bp-kelley Clarification: this PR (#1910) should *not* be merged before `MaeParserConfig.hpp` and `CoordgenConfig.hpp` are patched as shown above, i.e. A PR needs to be submitted to the Schroedinger repo. Merging this PR without fixing the upstream Schroedinger headers will break the RDKit build.

Instead, the PR that allows building the RDKit with the current Schroedinger headers is #1909, which patches the Schroedinger headers on-the-fly after their download.

**Comment by ptosco** [comment]
@bp-kelley Could you please paste here your `cmake` line? Thanks.

**Comment by bp-kelley** [comment]
Let me check the actual link line here, I may not be actually linking to coordgen.

**Comment by bp-kelley** [comment]
It appeared that the coordgen libs were commented out in JavaWrappers/CMakeLists.txt

```if(RDK_BUILD_COORDGEN_SUPPORT)
  set(swigRDKitLibList "${swigRDKitLibList};${RDK_COORDGEN_LIBS}")
endif(RDK_BUILD_COORDGEN_SUPPORT)```

Correcting this did not appear to solve the issue.  I wonder if this is because C# actually links statically.  I don't think this is true of the java wrappers.

If you want to try a build, use this repository:

https://github.com/bp-kelley/rdkit-csharp

The requirements are cmake/swig and msvc 2015 (although 2017 will probably work)

**Comment by bp-kelley** [comment]
From the build.bat

```
cmake -G "Visual Studio 14 Win64" -DCMAKE_INSTALL_PREFIX=%P% -DRDK_BUILD_PYTHON_WRAPPERS=OFF -DRDK_BUILD_SWIG_WRAPPERS=ON -DRDK_BUILD_SWIG_JAVA_WRAPPER=OFF -DRDK_BUILD_SWIG_CSHARP_WRAPPER=ON -DBOOST_INCLUDEDIR="%BOOST_INCLUDEDIR%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%64" -DEIGEN3_INCLUDE_DIR="%EIGEN3_INCLUDE_DIR%" -DRDK_INSTALL_INTREE=OFF -DCPACK_INSTALL_PREFIX=rdkit -DRDK_BUILD_THREADSAFE_SSS=ON -DRDK_BUILD_AVALON_SUPPORT=ON -DRDK_BUILD_INCHI_SUPPORT=ON -DRDK_BUILD_CPP_TESTS=OFF -DRDK_BUILD_CAIRO_SUPPORT=ON -DCAIRO_INCLUDE_DIRS="%CAIRO_INCLUDE_DIRS%" -DCAIRO_LIBRARIES="%CAIRO_LIBRARIES%64" ..\..\rdkit
```

**Comment by ptosco** [comment]
@bp-kelley Thanks Brian, I have cloned your branch and will give it a go later tonight.

**Comment by ptosco** [comment]
@bp-kelley Hi Brian, I can build C# wrappers from the current `master` with #1914.

**Comment by bp-kelley** [comment]
Great.  I’ll double check the build and then merge tonight if all goes well.

**Comment by greglandrum** [comment]
It looks like this was resolved

Closing due to lack of activity. Feel free to reopen if anyone has the time and inclination to revive this one.

**Pull request closed without merging**
