### PR TITLE
ET(K)DG implementation

### PR DESCRIPTION
**Pull request by sriniker**
Implementation of new conformer generator approaches:
- ETDG
- ETKDG
- KDG

### CODE REVIEW

**Comment by malteseunderdog** [comment]
I am going to have to write another paper !  Is this finalized, will it be in the next release ?

**Comment by greglandrum** [comment]
Don't worry, we cite your paper. :-)

And, yes, it will be in the next release.

**Comment by malteseunderdog** [comment]
Tell me that RDKit generated cis (secondary) amides are a thing of the past ! 

(Presumably not if DG is Distance Geometry, but perhaps KDG is a knowledge based method, which knows we do not see these?)

**Comment by greglandrum** [comment]
I keep forgetting that you weren't at the UGM this year; Sereina's presentation explains all: https://github.com/rdkit/UGM_2015/blob/master/Presentations/ETKDG.SereinaRiniker.pdf

**Comment by malteseunderdog** [comment]
Fantastic work Sereina.  Looks great.  Quick question - on the use of the t tests; are the RMSDs normally distributed (when I did the conf gen analysis I hadn't seen this behaviour) ?

**Comment by sriniker** [comment]
We do paired t-tests. The difference between the RMSD values is normal distributed.

**Pull request closed without merging**
