### PR TITLE
run yapf on all Python code

### PR DESCRIPTION
**Pull request by ricrogz**
We usually run `clang_format` on C++ code, and we just merged a commit to reformat a bunch of files. It might be a good idea to do the same for the Python scripts.

The changes are all automatic, made by running `yapf -i -r -p -vv .` from the root of the repo (using `yapf` version 0.32.0).

### CODE REVIEW

**Comment by ricrogz** [comment]
I also ran `isort .` with isort v. 5.6.4

**Comment by bp-kelley** [comment]
I’m happy to commit to a python code formatter, but we need to decide as a community which one it is.  Flake8, yapf, black are all valid choices with different levels of linting.  I find yapf is a bit too low on that level.

**Comment by ricrogz** [comment]
Sounds good. I ran yapf because there's a config for it in setup.cfg. For isort, I used the "black" profile, since it is the one that seems to be the most similar to the current format of the imports.

**Comment by greglandrum** [comment]
> I’m happy to commit to a python code formatter, but we need to decide as a community which one it is. Flake8, yapf, black are all valid choices with different levels of linting. I find yapf is a bit too low on that level.

I believe that yapf is what @gedeck ran the last time we did this exercise. Maybe without the import reordering (which seems gratuitous to me, but that's fine).

Whether or not we want linting, which I think you raise, is a different and perhaps more contentious discussion.

**Review by greglandrum — COMMENTED** [review]
My two cents on this PR: I think having the code consistently formatted is a good idea, but I would prefer to hold off on making a change this sweeping until just before a release. Doing something which touches this number of files more or less guarantees that any bug fixes which we end up making in Python code will have merge conflicts when I cherry pick them back onto the 2021.09 production branch. This makes patch releases a pain.

I guess an alternative that we could discuss is applying pure code-formatting changes (maybe not import reordering?) to the production branch as well with the theory that it's a safe thing to do.

**Pull request closed without merging**
