### PR TITLE
Remove SWIG kludge on Windows

### PR DESCRIPTION
**Pull request by ptosco**
With reference to https://github.com/rdkit/rdkit/pull/4356#pullrequestreview-716105789, I have found the reason for the different behavior of MinGW _vs_ MSVC compilers when building C# SWIG wrappers, and it lies within RDKit itself, namely in
* `Code/JavaWrappers/gmwrapper/GraphMolJava.i` https://github.com/rdkit/rdkit/blob/0b934953a264e0e8c59e31c009bf9cb285e978c4/Code/JavaWrappers/gmwrapper/GraphMolJava.i#L34
* `Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i` https://github.com/rdkit/rdkit/blob/0b934953a264e0e8c59e31c009bf9cb285e978c4/Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i#L35
```
#if defined(SWIGWORDSIZE64)
%{
// There's a problem with SWIG, 64bit windows, and modern VC++ versions
//   This fine, fine piece of code fixes that.
//   it's ok to think this is horrible, we won't mind
#ifdef _MSC_VER

#ifndef LONG_MAX
#include <limits.h>
#endif

#if LONG_MAX==INT_MAX
#define LONG_MAX (INT_MAX+1)
#endif

#endif
%}
#endif
```
This code is meant to elude a check in the SWIG header file `Lib/swigarch.i` https://github.com/swig/swig/blob/90cdbee6a69d13b39d734083b9f91069533b0d7b/Lib/swigarch.i#L50
```
#ifdef SWIGWORDSIZE64
%{
#define SWIGWORDSIZE64
#ifndef LONG_MAX
#include <limits.h>
#endif
#if (__WORDSIZE == 32) || (LONG_MAX == INT_MAX)
# error "SWIG wrapped code invalid in 32 bit architecture, regenerate code using -DSWIGWORDSIZE32"
#endif
%}
#endif
```
On the Windows platform, `LONG_MAX == INT_MAX`, and so attempting to compile with `-DSWIGWORDSIZE64` results in a compiler error, that the above kludge avoids by redefining `LONG_MAX` when building with MSVC, but not with MinGW that does not define `_MSC_VER`, hence the MinGW compiler error.

I think the kludge is conceptually wrong and potentially harmful, and I will try to explain why below.
The `SWIGWORDSIZE64` macro is referenced in 3 files, apart from `Lib/swigarch.i` that I have just discussed.
```
$ grep -wlr SWIGWORDSIZE64 .
./swigwin-3.0.12/Lib/inttypes.i
./swigwin-3.0.12/Lib/r/std_vector.i
./swigwin-3.0.12/Lib/stdint.i
./swigwin-3.0.12/Lib/swigarch.i
```
In these files, if `SWIGWORDSIZE64` is defined, `long int` is used instead of `long long int`, e.g.:
```
#ifdef SWIGWORDSIZE64

  /* We have to define the `uintmax_t' type using `ldiv_t'.  */
  typedef struct
  {
    long int quot;              /* Quotient.  */
    long int rem;               /* Remainder.  */
  } imaxdiv_t;

#else

  /* We have to define the `uintmax_t' type using `lldiv_t'.  */
  typedef struct
  {
    long long int quot;         /* Quotient.  */
    long long int rem;          /* Remainder.  */
  } imaxdiv_t;

#endif
```
and
```
#if defined(SWIGWORDSIZE64)
typedef long int                int64_t;
#else
typedef long long int           int64_t;
#endif
```
just to show a couple of examples.
This means that in 64-bit binaries on `*nix` platforms 64-bit integers are defined as `long int`, which is what we want, given that on 64-bit `*nix` `long int` is 8-byte in size:
```
$ uname -sp
Linux x86_64
$ cat types.c
#include <stdio.h>

int main() {
  printf("sizeof(int) %d\n", sizeof(int));
  printf("sizeof(long int) %d\n", sizeof(long int));
  printf("sizeof(long long int) %d\n", sizeof(long long int));
  return(0);
}
$ gcc types.c -o types
$ ./types
sizeof(int) 4
sizeof(long int) 8
sizeof(long long int) 8
```
If we build a 32-bit binary on `*nix`, we do not define `SWIGWORDSIZE64`, and we correctly use `long long int` to store a 64-bit type, since `long int` is 32-bit in 32-bit binaries:
```
$ uname -sp
Linux x86_64
$ gcc -m32 types.c -o types32
$ ./types32
sizeof(int) 4
sizeof(long int) 4
sizeof(long long int) 8
```
So defining `SWIGWORDSIZE64` for 64-bit `*nix` builds makes perfect sense.

Instead, in a Windows 64-bit binary `long int` is 32-bit just as in a 32-bit binary, so `long long int` is always needed to define a 64-bit type, no matter if the build is 32 or 64-bit. Note that this <b>depends on the platform, not on the compiler</b>, and both binaries built with MSVC and gcc yield the same result:
```
$ uname -sp
MINGW64_NT-10.0-19042 unknown
$ ./gcc/types.exe
sizeof(int) 4
sizeof(long int) 4
sizeof(long long int) 8
$ file msvc/types.exe
types.exe: PE32+ executable (console) x86-64, for MS Windows
$ ./msvc/types.exe
sizeof(int) 4
sizeof(long int) 4
sizeof(long long int) 8
$ file types32.exe
types32.exe: PE32 executable (console) Intel 80386, for MS Windows
$ ./msvc/types32.exe
sizeof(int) 4
sizeof(long int) 4
sizeof(long long int) 8
```

To summarize, this means that we do not want to define `SWIGWORDSIZE64` on 64-bit Windows, as this will cause 64-bit values to be stored into a 32-bit type. It only makes sense to define `SWIGWORDSIZE64` on 64-bit `*nix` platforms.

After all this rant, I wish to emphasize that tests pass before and after this PR.
The reason is that the plain `int64_t` type is not actually used by RDKit wrappers, as `boost::(u)int64_t` and `std::(u)int64_t` are used instead:
```
$ grep int64_t \
  Code/JavaWrappers/csharp_wrapper/swig_csharp/GraphMolCSharpCSHARP_wrap.cxx \ 
  Code/JavaWrappers/gmwrapper/src/org/RDKit/GraphMolJavaJAVA_wrap.cxx \
  | grep -vE '::int64_t|::uint64_t|_int64_t|_uint64_t' | wc -l
0
```
and those types are correctly defined depending on the platform.
This is why no-one ever noticed any problem.

Still, I believe it's worth cleaning up the code and removing the conceptually incorrect (and potentially harmful) kludge.

### CODE REVIEW

**Comment by ptosco** [comment]
Not sure why the macOS build was canceled.

**Comment by bp-kelley** [comment]
@ptosco I'd almost be in favor of NOT compiling 32bit at all.  I used to make both 32 and 64 for the C# builds, but the reality is that most if not all users target 64 bits now, even on windows.

**Comment by ptosco** [comment]
@bp-kelley This PR is indeed about the 64-bit RDKit build. I have never done a 32-bit RDKit build.
I only built the small `types.c` test program in 32-bit mode to show the difference between `long int` and `long long int` on `*nix` _vs_ no difference on Windows, in order to provide a rationale to my PR.

**Review by greglandrum — APPROVED** [review]
Verified that this builds and passes the tests on my windows machine.

**Comment by greglandrum** [comment]
@ptosco thanks for putting in the time to dig into the guts of this and figure out what was going on.

**Pull request merged**
