### PR TITLE
Added two projects that use rdkit which I have authored

### PR DESCRIPTION
**Pull request by vandan-revanur**
#### What does this implement/fix? Explain your changes.
This PR adds two projects that use rdkit in the README.md

#### Any other comments?
Both of the projects are authored by me

### CODE REVIEW

**Comment by vandan-revanur** [comment]
@greglandrum Could you or someone from your team please have a look at this? 
I am not able to add a reviewer.

**Review by greglandrum — CHANGES_REQUESTED** [review]
@vandan-revanur please add these at the top of the list (we add new projects at the top)

**Comment by vandan-revanur** [comment]
> @vandan-revanur please add these at the top of the list (we add new projects at the top)

I have now moved it. Please review.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
Thanks @vandan-revanur!

**Pull request merged**
