### PR TITLE
Fix bug in StereoGroup wrapper

### PR DESCRIPTION
**Pull request by ricrogz**
Ooops! This one slipped through!

### CODE REVIEW

**Review by greglandrum — CHANGES_REQUESTED** [review]
Could you please add a test for this function?
If we'd done that originally, this would have been noticed immediately.

**Comment by ricrogz** [comment]
> Could you please add a test for this function? If we'd done that originally, this would have been noticed immediately.

Done. I definitely have a memory of having added a test... but I just noticed it didn't go into the PR. I guess it got lost at some point.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by ricrogz** [comment]
> @ricrogz will merge once the last of the CI tests have finished. The win64_dll failure isn't real

Sounds good!

**Pull request merged**
