### PR TITLE
Add a collection of new 3D descriptors

### PR DESCRIPTION
**Pull request by greglandrum**
This should be viewed as a replacement for #1317 

These should be viewed as beta still (and the docs need to be updated to reflect that before they are merged).

We will want to refactor the code as we have time, but we have regression tests here to make that doable.

### CODE REVIEW

**Comment by bp-kelley** [comment]
Ton of work here.  What is the plan for review?  Perhaps we should do one valgrind run?

**Comment by greglandrum** [comment]
Thanks for the reminder: I've run valgrind over all of the new regression tests and there are no warnings or leaks related to this code.

**Comment by greglandrum** [comment]
This is now in sync with master and I've added the new descriptors to the list in the Getting Started document. I think it's ready for merging.
@bp-kelley : what's your take?

**Comment by greglandrum** [comment]
Many, many thanks to @thegodone for both the contribution and his patience during the very long review/revision process.

**Pull request merged**
