### PR TITLE
Faster version of Pharm2D.Utils.GetUniqueCombos

### PR DESCRIPTION
**Pull request by mitchondra**
Smarter implementation of function GetUniqueCombinations in
Chem.Pharm2D.Utils which makes it significantly faster.

### CODE REVIEW

**Comment by gedeck** [comment]
Do you timing results comparing the new and old implementation?

Did you check test coverage? If not, I will  this once your PR is included.

**Comment by mitchondra** [comment]
I have compared time for generating fingerprints with old/new implementation. For a dataset of 15000 molecules old implementation took aprox. 8-9 hours while with new it took about 1-2 hours (but I did no thorough benchmark). cProfile showed that, when generating fingerprints, with old implementation 75 % of time was spent in that function, while with new it was only aprox. 16 %.

What is "test coverage"? (Sorry, I'm quite new to this...)

**Comment by gedeck** [comment]
I think these differences qualify as significant ;-). No need for further benchmarking. 

Test coverage is a measure of how much of the code is covered by tests. There were no tests and you added at least one doctest, so coverage improved a bit and I guess covers the main program flow. What is missing are edge cases (eg empty lists) and I can look into adding them. 

It would be good if you could improve the explanation. Just looking at the old code, I don't really understand at first glance what the code is supposed to do. With the newer one it is probably even more difficult.

**Comment by gedeck** [comment]
There are inputs where the result of the code is different:
```
    choices = [[1,2],[3,4],[5,6],[7,8]]
    classes = [0,1,1,2]
```
gives for the old code:
```
[[(0, 1), (1, 3), (1, 5), (2, 7)],
 [(0, 1), (1, 3), (1, 5), (2, 8)],
 [(0, 1), (1, 3), (1, 6), (2, 7)],
 [(0, 1), (1, 3), (1, 6), (2, 8)],
 [(0, 1), (1, 4), (1, 5), (2, 7)],
 [(0, 1), (1, 4), (1, 5), (2, 8)],
 [(0, 1), (1, 4), (1, 6), (2, 7)],
 [(0, 1), (1, 4), (1, 6), (2, 8)],
 [(0, 2), (1, 3), (1, 5), (2, 7)],
 [(0, 2), (1, 3), (1, 5), (2, 8)],
 [(0, 2), (1, 3), (1, 6), (2, 7)],
 [(0, 2), (1, 3), (1, 6), (2, 8)],
 [(0, 2), (1, 4), (1, 5), (2, 7)],
 [(0, 2), (1, 4), (1, 5), (2, 8)],
 [(0, 2), (1, 4), (1, 6), (2, 7)],
 [(0, 2), (1, 4), (1, 6), (2, 8)]]
```
and for the new code:
```
[[(0, 1), (1, 3), (1, 4), (2, 7)],
 [(0, 1), (1, 3), (1, 4), (2, 8)],
 [(0, 2), (1, 3), (1, 4), (2, 7)],
 [(0, 2), (1, 3), (1, 4), (2, 8)]]
```
It could be that the input doesn't make sense in tough.

**Comment by mitchondra** [comment]
Thanks, I'll try to improve the explanation :-)

>     
`choices = [[1,2],[3,4],[5,6],[7,8]]`
`classes = [0,1,1,2]`
<
This is invalid input, `choices[1]` and `choices[2]` has to be same since they have same class (`class[1] == class[2]`). I didn't check for those, since the function is used only in one place, but I'll add some checks for invalid input.

**Comment by gedeck** [comment]
If you look at my example, you can see that the existing code behaves very differently. In your code, 5 and 6 are not included in the combinations. Compare the third tuples in the results. Maybe Greg can comment what the code is supposed to produce.

**Comment by gedeck** [comment]
I have a new implementation of the GetUniqueCombinations function. It uses `itertools` and is a lot more compact.
```
def GetUniqueCombinations(choices, classes):
  """  Does the combinatorial explosion of the possible combinations
  of the elements of _choices_.  """
  #   print(choices, classes)
  assert len(choices) == len(classes)
  combos = set()
  for choice in itertools.product(*choices):
    # If a choice occurs in more than one of the fields, we ignore this case
    if len(set(choice)) != len(choice):
      continue
    combos.add(tuple(sorted((cls, ch) for cls, ch in zip(classes, choice))))
  return [list(combo) for combo in combos]
```
The result is the same as in the old implementation, however the order is different. While switching the code keeps all the tests working fine, I have the suspicion that the order is important as we have three more methods `CountUpTo`, `GetIndexCombinations`, and `GetAllCombinations` that are structurally similar to the original implementation of `GetUniqueCombinations`. @greglandrum can you comment on this?

**Comment by gedeck** [comment]
Hello @mitchondra 

I reviewed the Pharm2D and Pharm3D code and submitted a pull request #1201. It contains a modified version of GetUniqueCombinations. It was now merged into master. Can you run your timings on the newest master? 

Best,

Peter

**Comment by bp-kelley** [comment]
@mitchondra I'm closing this for now as it is superseded by #1201.  Please reopen if you have any issues.

**Pull request closed without merging**
