### PR TITLE
Fixes #7989 Incorrect benzyl deprotection reaction

### LINKED ISSUE #7989: Wrong SMARTS pattern in O-benzyl deprotection reaction
Hi everyone, 

I have created this issue following the discussion in https://github.com/rdkit/rdkit/discussions/7982:
I have noticed that in the benzyl deprotection reaction the SMARTS pattern is wrong, matching phenylethers instead:

```python
import rdkit
from rdkit import Chem
from rdkit.Chem import Draw, rdDeprotect

mol = Chem.MolFromSmiles("Nc1ccccc1Oc1ccccc1")
```

This is the mol:
image

```python
Draw.MolsToGridImage(
    mols = [rdDeprotect.Deprotect(mol = mol, deprotections = [dep]) for dep in rdDeprotect.GetDeprotections()],
    legends = [dep.full_name for dep in rdDeprotect.GetDeprotections()],
    molsPerRow = 7
)
```
This is the output:
image

This compound should not be deprotected by the benzyl reaction at all, since this is a phenyl ether.
Looking at the [SMARTS in the code:](https://github.com/rdkit/rdkit/blob/b16b6026e8d58ddba73a7ba6b24f5c0412fd4951/Code/GraphMol/Deprotect/Deprotect.cpp#L53)

```
      {"alcohol", "[O;!$(*C(=O)):1]c1[c;H1][c;H1][c;H1][c;H1][c;H1]1>>[O;H1:1]",
       "Bn", "benzyl", "NOc1ccccc1>>ON"}
```

It looks like the SMARTS pattern is wrong and it's missing a CH2 group between the O and the phenyl group.
Can someone confirm that this is indeed uncorrect?

_Originally posted by @marcobICR in https://github.com/rdkit/rdkit/discussions/7982_

### PR DESCRIPTION
**Pull request by bp-kelley**
Fixes #7989

### CODE REVIEW

**Review by greglandrum — CHANGES_REQUESTED** [review]
The change looks good, but please add a test.

**Comment by bp-kelley** [comment]
The test is in the definition, I can add a negative test though.

**Comment by greglandrum** [comment]
> The test is in the definition, I can add a negative test though.

Ah, nice. I hadn't noticed that.
I think it's fine as is

**Review by greglandrum — APPROVED** [review]
LGTM

**Pull request merged**
