### PR TITLE
make boost::iostreams optional

### PR DESCRIPTION
**Pull request by greglandrum**
We shouldn't have made this new boost binary dependency mandatory.
This rolls that back so that it's built by default but can be toggled off if you don't want to have to have builds of boost::iostreams and boost::system

### CODE REVIEW

**Comment by bp-kelley** [comment]
Ug.  The whole point of this was to make iostreams contained to the a single module and not contaminate the rest of the code.   So this is the right approach for now.

**Comment by bp-kelley** [comment]
Maybe we need some azure templates that make sure we can compile with non default options :)

**Comment by greglandrum** [comment]
> Ug. The whole point of this was to make iostreams contained to the a single module and not contaminate the rest of the code. So this is the right approach for now.

Unfortunately since iostreams needs to be linked against, it can't really be limited to one place

**Comment by greglandrum** [comment]
> Maybe we need some azure templates that make sure we can compile with non default options :)

"And that was the point that the builds started taking 3 days to run." :-)

**Pull request merged**
