### PR TITLE
Fixes Issue 694

### PR DESCRIPTION
**Pull request by greglandrum**
Accounting for the mass of the electron when calculating exact mol wt.

### CODE REVIEW

**Comment by bp-kelley** [comment]
No problem merging, but the "add a test" doesn't appear involved with this PR.

**Comment by bp-kelley** [comment]
Once #778 is tidied up, I'll merge this since this has the extraneous commit also included in #778

**Comment by bp-kelley** [comment]
@greglandrum we have conflict now sadly.

**Comment by greglandrum** [comment]
@bp-kelley Conflicts should now be resolved.

**Comment by greglandrum** [comment]
@bp-kelley : ok to merge this now?

**Pull request merged**
