### PR TITLE
Fix/aromatic "[as]" in smiles

### PR DESCRIPTION
**Pull request by greglandrum**

### CODE REVIEW

**Comment by bp-kelley** [comment]
I think some of these issue might be from me some warning suppressions (void)yyscanner and register keywords came back, I might have missed them in the original yy file.  I'm going to have to spend some cycles checking this.

**Comment by greglandrum** [comment]
sorry, was looking at the files first and missed you last comment here.
Yes: some of these are from the flex/bison output. I think we're probably better off just suppressing warnings for those files.

**Comment by bp-kelley** [comment]
Ok, fix the dummyLabel, I'll merge it and then squash the warnings in my next go around.

**Comment by greglandrum** [comment]
done

**Pull request merged**
