### PR TITLE
fix 1,3- 1,5- conjugated cation normalizer transforms

### PR DESCRIPTION
**Pull request by rvianello**
#### What does this implement/fix? Explain your changes.
This PR should hopefully fix an oversight introduced with #7287 (sorry)

### CODE REVIEW

**Review by greglandrum — CHANGES_REQUESTED** [review]
I think it's worth adding a test for this too

**Comment by rvianello** [comment]
would you mind if I added some local scopes to `test1()` in [testNormalize.cpp](https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/MolStandardize/testNormalize.cpp#L29) and removed the sequential numering of local variables that refer to the same test case, changing for example:

```
  // Test normalization of 1,5-conjugated cations
  std::string smi15 = "C[N+](C)=c1cc[nH]cc1";
  std::shared_ptr<ROMol> m15(SmilesToMol(smi15));
  ROMOL_SPTR normalized15(normalizer.normalize(*m15));
  TEST_ASSERT(MolToSmiles(*normalized15) == "CN(C)c1cc[nH+]cc1");

  // Test normalization of 1,5-conjugated cations doesn't
  // affect diazo groups
  std::string smi16 = "[N-]=[N+]=c1cc[nH]cc1";
  std::shared_ptr<ROMol> m16(SmilesToMol(smi16));
  ROMOL_SPTR normalized16(normalizer.normalize(*m16));
  TEST_ASSERT(MolToSmiles(*normalized16) == "[N-]=[N+]=c1cc[nH]cc1");
```

into

```
  // Test normalization of 1,5-conjugated cations
  {
    std::string smi = "C[N+](C)=c1cc[nH]cc1";
    std::shared_ptr<ROMol> m(SmilesToMol(smi));
    ROMOL_SPTR normalized(normalizer.normalize(*m));
    TEST_ASSERT(MolToSmiles(*normalized) == "CN(C)c1cc[nH+]cc1");
  }

  // Test normalization of 1,5-conjugated cations doesn't
  // affect diazo groups
  {
    std::string smi = "[N-]=[N+]=c1cc[nH]cc1";
    std::shared_ptr<ROMol> m(SmilesToMol(smi));
    ROMOL_SPTR normalized(normalizer.normalize(*m));
    TEST_ASSERT(MolToSmiles(*normalized) == "[N-]=[N+]=c1cc[nH]cc1");
  }
```

?

**Comment by rvianello** [comment]
alternatively, I could wrap those four lines in a support function taking the input and output smiles as args (duplication may sometimes help keep the different tests decoupled from each other, but in this case it's all inside the same function).

**Comment by greglandrum** [comment]
> alternatively, I could wrap those four lines in a support function taking the input and output smiles as args (duplication may sometimes help keep the different tests decoupled from each other, but in this case it's all inside the same function).

I'd vote for this.

**Review by greglandrum — APPROVED** [review]
LGTM

Will merge after the CI builds finish

**Comment by rvianello** [comment]
Thank you @greglandrum

**Pull request merged**
