### PR TITLE
Removed some code duplication between Depictor.cpp and common.h

### PR DESCRIPTION
**Pull request by ptosco**
This is to get rid of some duplicated code between `Depictor.cpp` and `common.h`. In passing I also did a bit of code cleanup.

### CODE REVIEW

**Comment by ptosco** [comment]
@greglandrum The PR porting the MinimalLib code for aligned depictions to the main C++ core is now ready for review; as discussed, it would be good to merge it before releasing the beta.

**Comment by greglandrum** [comment]
@ptosco it looks like the test failure, curiously only on one system, may be legit. It is at least in a test you added here

**Comment by ptosco** [comment]
@greglandrum I’ll fix it this evening, thanks for the heads up.

**Comment by ptosco** [comment]
@greglandrum I figured out: I was running some `CoordGen` tests even in the case the build does not support `CoordGen`. Since molecules were still being drawn by RDKit, the angle tests (which were expecting a `CoordGen` layout) were failing.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
@ptosco I approved this and then was too quick with merging it, so I reverted the merge.
We should figure out whether or not this is safe for the upcoming 2023.09.1 release

**Pull request merged**
