### PR TITLE
Update CXSMARTS test in MinimalLib

### PR DESCRIPTION
**Pull request by ptosco**
It looks like something changed based on the Python results so I am updating the MinimalLib test accordingly.

### CODE REVIEW

**Comment by greglandrum** [comment]
Hi @ptosco, I think the output here is actually wrong: the `$;;;;;;;$` block shouldn't be there. This is something I must have introduced with a recent change.
I'll fix the underlying problem.

**Comment by greglandrum** [comment]
Hi @ptosco, I think the output here is actually wrong: the `$;;;;;;;$` block shouldn't be there. This is something I must have introduced with a recent change.
I'll fix the underlying problem.

**Comment by ptosco** [comment]
I thought that might be the case as that output didn’t look particularly useful  :-)

**Comment by greglandrum** [comment]
@ptosco I think we can close this one, right?
Please re-open if I missed something

**Comment by ptosco** [comment]
@greglandrum Yes, thanks for fixing the original issue.

**Pull request closed without merging**
