### PR TITLE
Add a reader for FPB files

### PR DESCRIPTION
**Pull request by greglandrum**
This provides a reader for the FPB files produced by Andrew Dalke's chemfp package.
The reader class also enables some very basic search capabilities.

### CODE REVIEW

**Comment by greglandrum** [comment]
The failing build associated with that last commit isn't real; it looks like another instance of the race condition that sometimes afflicts the java wrapper builds.

**Comment by bp-kelley** [comment]
@greg I think I meant boost::static_vector

**Comment by bp-kelley** [comment]
Ok, I added some comments a while back, but don't know where they are.

1) What happens if chunkNM is not one of "AREN", "FPID", "POPC"?  I think chunk should be deleted and an exception thrown as the file is obviously bad.

2) On a side note, perhaps we should check the chunkNM before reading the chunk data, as the size will most likely be completely bogus.

3) should we catch out of memory errors from chunk allocation?  Note: this is probably not worthwhile as linux likes to lie: http://stackoverflow.com/questions/1655650/linux-optimistic-malloc-will-new-always-throw-when-out-of-memory

4) Fun fact.  FEND, POPC, AREN, FPID are all expressible as integers and switch statements could be used as opposed to strings :)

If you (again) verify that valgrind works, I'd be happy to accept the pull request.  I'm pretty sure you did this before, but I'm just checking.

**Comment by greglandrum** [comment]
@bp-kelley, on valgrind: the basic testFPB tool runs clean under valgrind, as does the program that I've been using to benchmark search performance.

**Comment by greglandrum** [comment]
Added a warning for unrecognized chunks as well as specifically skipping a couple that are part of chemfp's .FPB files.

**Comment by greglandrum** [comment]
Pls hold off on merging this. I'm going to (try and) do a version that has a somewhat cleaner commit history.

**Comment by greglandrum** [comment]
Ok, so the current status is what should be merged. It's essentially what was there before, but with the following changes:
- I did a rebase to get rid of all the merge commits, which were making me unhappy
- There's an optimization to the construction of ExplicitBitVects from FPS text (doesn't really need to be part of this PR, but it's a small change): 4ae3318
- I added support for doing fingerprint screening operations (for speeding up SSS)

**Comment by greglandrum** [comment]
If/when the CI tests pass, I think this one is ready to merge

**Comment by greglandrum** [comment]
@bp-kelley The appveyor build succeeded when I re-ran it and a windows build worked without problems for me. As discussed, I'm going to go ahead and merge this.

**Comment by bp-kelley** [comment]
Nice.  I have plans for this ...

----
Brian Kelley

**Pull request merged**
