### PR TITLE
Fix typo in 4.5.0--4.6.0 sql upgrade script

### PR DESCRIPTION
**Pull request by esiaero**
The original script references RDKIT_PG_ALTER_OPERATOR_ATEQ_MOL twice instead of RDKIT_PG_ALTER_OPERATOR_ATEQ_REACTION.

#### Reference Issue
Related to https://github.com/rdkit/rdkit/pull/7596 and https://github.com/rdkit/rdkit/issues/7459

#### What does this implement/fix? Explain your changes.
The script has a typo; this fixes it so the @= operator for reaction can have its commutator/negator correctly changed in the upgrade script.

### CODE REVIEW

**Comment by rvianello** [comment]
Thank you, @esiaero

And sorry about the oversight @greglandrum

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
>
> And sorry about the oversight @greglandrum

No worries. That's something I could/should have caught in the review

**Comment by greglandrum** [comment]
Thanks @esiaero!

**Pull request merged**
