### PR TITLE
Fix stereo bond corruption on RGD.

### PR DESCRIPTION
**Pull request by jones-gareth**
#### What does this implement/fix? Explain your changes.

This PR fixes an issue with RGD and stereo bonds on R groups close to an attachment point.  If one the atoms defining bond stereochemistry is an attachment point for an R group then that bond definition is lost when creating the R Groups in `ChemTransforms::replaceCore` if the stereo bond is in an R group.  Or in `RGroupCore::extractCoreFromMolMatch` if the bond is in the core.  In either case we are left with a bond with absolute stereo chemistry set but missing defining stereoatoms.

This PR patches both `ChemTransforms::replaceCore` and `RGroupCore::extractCoreFromMolMatch` to rebuild the correct bond definition when adding the attachment point.  In  `ChemTransforms::replaceCore`  I also set a stereo bond to STEREOANY if one of its atoms is an attachment point as it no longer possible to define absolute stereo chemistry for that bond.

There is a test for the new code, which uses these three examples.

Here the bond stereo chemistry is defined by an attachment dummy atom in R1.

image

Here the attachment point is one end of a double bond and the bond stereochemistry is lost on decomposition.

image

Here the bond stereo chemistry is defined by an attachment dummy atom in the extracted core.

image

#### Any other comments?

Prior to this fix I was getting error messages about "bond found with stereo spec but no stereo atoms".  I was also getting a hard crash in the C# wrapper, though I was unable to reproduce in a small test system.

This fix will also benefit people who use `ChemTransforms::replaceCore` outside of RGD.

### CODE REVIEW

**Review by greglandrum — CHANGES_REQUESTED** [review]
I've suggested a switch in how loop over the neighboring bonds, but otherwise this LGTM

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
will merge after the CI builds go through

**Comment by jones-gareth** [comment]
> will merge after the CI builds go through

Thanks!

**Pull request merged**
