### PR TITLE
Fix/github1366

### PR DESCRIPTION
**Pull request by greglandrum**
This fixes the error that was reported by detecting when the number of atoms changes from underneath an AtomIterator and throwing a `ValueErrorException()` instead of seg faulting or doing something undefined.

I'm not sure this is the best solution to the problem and would love input.

### CODE REVIEW

**Comment by gedeck** [comment]
Do you think that the error message is understandable by a typical Python user? You could point out that the reason the error happens is that the array was modified in an unsafe way.

**Comment by bp-kelley** [comment]
If we care, the pythonic way is to raise a runtimeerror ala:

RuntimeError: dictionary changed size during iteration

**Comment by tentrillion** [comment]
I'm obviously not an RDKit developer but am a user and do have a preference
for pythonic behavior.  So for whatever its worth, I vote for Brian's error
message.

**Comment by greglandrum** [comment]
Ok, just pushed a version that uses a RuntimeError.
Though I agree that it's not the best error message on the Python side, a python-specific message wouldn't work on the C++ or Java side either. 

Instead of doing something fancy (and with a performance impact on common operations) to improve a rarely encountered error message, I would advocate that we stick with this and count on the fact that google will turn up the answer if/when questions arrive.

**Comment by gedeck** [comment]
Ok for me. Python actually doesn't complain if a list is modified/elements deleted during iteration.

**Comment by greglandrum** [comment]
That's true; but in this case the return value isn't actually a list

**Comment by coleb** [comment]
Change looks good to me. Should we insert the same check into BondIterator while we're here? 

I do worry about the performance implication of the ```_mol->getNumAtoms()``` in every iterator dereference. Have you run your set of performance tests with and without the change to see if it registers there?

**Comment by greglandrum** [comment]
Good question. I just ran my longer benchmarks and there's no real change.
However, this is likely because that GetAtoms() isn't called that much.

I created a simple new one that does use GetAtoms():
```
  for mol in mols:
    for at in mol.GetAtoms():
      at.GetAtomicNum()
```
and there's no significant change in runtime.

**Comment by greglandrum** [comment]
And, yes, doing `BondIterator` as well makes sense.

**Pull request merged**
