### PR TITLE
An alternate approach to fixing #805

### PR DESCRIPTION
**Pull request by greglandrum**
Modifies the fix for #805 to continue to allow stereochemistry on the `P=C` double bond. Instead it modifies `cleanUp()` to modify the bonding pattern in this rarely encountered substructure.

Based on the mailing list thread and some searches I did, I'm no longer 100% comfortable just removing the stereochemistry of these double bonds. This approach modifies the `cleanUp()` function to convert the `P=O` bond to the zwitterionic form `[P+][O-]` when substructures like `C=P(=O)R` or `N=P(=O)R' are found.

### CODE REVIEW

**Comment by greglandrum** [comment]
Since I did the searches...
Here are result counts for some pubchem substructure searches:
- `C=P(=O)O`: 348 hits
- `C=P(=O)C`: 174 hits
- `N=P(=O)C`: 52 hits
- `N=P(=O)O`: 423 hits

**Comment by bp-kelley** [comment]
I'm pretty leery of changing bond orders, but since it can be turned off:

```
>>> a = 0
>>> for k,v in rdkit.Chem.rdmolops.SanitizeFlags.values.items():
...   if v not in [rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_CLEANUP,
...                rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_ALL]:
...     a |= v
... 
>>> m = Chem.MolFromSmiles("O=P(/O)=C/C", sanitize=False)
>>> Chem.SanitizeMol(m, sanitizeOps=a)
rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE
>>> Chem.MolToSmiles(m, isomericSmiles=True)
'C/C=P(=O)\\O'
>>> m.HasSubstructMatch(m)
True
>>> 
```

I'm pretty ok with it.  Although "SANITIZE_CLEANUP" seems to not really describe what is going on, I would suggest adding this to the documentation for the sanitization operations.

**Comment by greglandrum** [comment]
Good point about the docs. The perchlorate thing also wasn't documented.
I just updated that.

**Comment by bp-kelley** [comment]
Cool, you found two for the price of one.

**Pull request merged**
