### PR TITLE
Image tostring/fromstring methods replaced by tobytes/frombytes

### PR DESCRIPTION
**Pull request by rvianello**
In Pillow 3.0.0 some deprecated parts of the API have been removed (http://pillow.readthedocs.org/en/3.0.x/releasenotes/3.0.0.html#deprecated-methods). This pr replaces calls to tostring/fromstring with tobytes/frombytes. 

this changeset might be not backward compatible with the older PIL implementation (I didn't verify) and it's been only verified to the extent of the tests coverage.

### CODE REVIEW

**Comment by greglandrum** [comment]
I just tried this on an Ubuntu 12.04 VM that has PIL installed. The calls to tobytes() fail.
I suppose we could deprecate support for PIL, but would it be better (for another release or so?) to continue to support it?

**Comment by rvianello** [comment]
yes, PIL is probably only required when using the system python2 in some linux distributions, but a deprecation period may make sense. 

do you think the rdkit conda recipe could anticipate these changes with a patch (conda users should have no issue in upgrading from PIL to the current pillow release)?

**Comment by greglandrum** [comment]
On Wed, Oct 21, 2015 at 3:44 AM, Riccardo Vianello <notifications@github.com
> wrote:

> do you think the rdkit conda recipe could anticipate these changes with a
> patch (conda users should have no issue in upgrading from PIL to the
> current pillow release)?
>

You mean apply the patch in the conda recipe?

**Comment by rvianello** [comment]
yes, I could add a patch file to the conda recipe and apply these changes on the fly. Alternatively, I could specify some constraints in the rdkit package dependencies (at build-time at least, otherwise pillow 3.0.0 would be used causing some tests to fail).

**Comment by greglandrum** [comment]
I think going with the patch in the conda recipe makes sense for now.

**Comment by samoturk** [comment]
I would prefer if this was merged with master since it fixes problems not just with anaconda but also on distros with up to date packages. I don't think that people using by (computing standards) ancient distro will go and update just their RDKit installation..

**Comment by greglandrum** [comment]
Point taken.
@rvianello: how about supporting both ways. I've attached an (basically untested) diff as a suggestion on how this might work.
[frombytes.diff.txt](https://github.com/rdkit/rdkit/files/19162/frombytes.diff.txt)

does this look reasonable/make sense?

**Comment by rvianello** [comment]
yes, I think the proposed approach makes totally sense, I will send an update to the PR.

**Pull request merged**
