### PR TITLE
use RDK_BUILD_COORDGEN_SUPPORT=OFF

### PR DESCRIPTION
**Pull request by UnixJunkie**
fix for https://github.com/rdkit/rdkit/issues/3063

the added options is RDK_BUILD_COORDGEN_SUPPORT=OFF

I feel that if this thing is turned ON by default, then a library is missing from the source tree.

### CODE REVIEW

**Comment by greglandrum** [comment]
Seems like it makes more sense to figure out what's wrong and fix the recipe than it does to disable this useful functionality. Are you sure you want to do this?

**Comment by UnixJunkie** [comment]
We cannot compile rdkit after a fresh checkout anymore?

Is some new external library needed, and not installed automatically like the inchi one?

**Comment by UnixJunkie** [comment]
This header is missing on my machine: <maeparser/MaeConstants.hpp>
It is not in the source tree of rdkit, or I missed it.

**Comment by e-kwsm** [comment]
[If maeparser is not found, CMake downloads https://github.com/schrodinger/maeparser/archive/v1.2.3.tar.gz](https://github.com/rdkit/rdkit/blob/9ce1955e8d88b8113900b152f228a2ab49a747ea/External/CoordGen/CMakeLists.txt#L34-L62).

The file seems new in v1.1, so I guess CMake finds older maeparser at somewhere in your machine.
Removing `External/CoordGen/maeparser` (or path from `CPATH` etc) will re-download the latest version.

**Comment by UnixJunkie** [comment]
@e-kwsm thanks, it works. The fix to the problem is completely non trivial though.

**Pull request closed without merging**
