### PR TITLE
Fix: GetDonor2FeatVects heavy atoms confusion

### PR DESCRIPTION
**Pull request by josan82**
#### What does this implement/fix? Explain your changes.
Dear Greg,

First of all, as is the first time I write you, I want to present me. I am starting my PhD of bioinformatics in Barcelona, and I am using the RDKit library in some aspects of my work.

ConcreteIy, I am using the FeatDirUtilsRD to calculate the feature vectors of a feature and I have found some apparent mistakes in the function GetDonor2FeatVects.

I think that there is a confusion with the "nbrs" list. The first thing that the function does is to create a "hydrogens" list to use it after. But after the while loop, the list "nbrs" doesn't contain anymore the all neighbours (including hydrogens) of the donor, but only the heavy neighbour atoms. The "nbrs" list is used after the while with two meanings: as if it contained all the neighbours or only the heavy ones (I think here is the confusion).

I propose to change the "while" loop by a "for" one, creating a "heavy" list with the heavy neighbours atoms and keeping the meaning of "nbrs" list as all the neighbours (including hydrogens). After the loop, I have changed the "nbrs" list by the "heavy" one where I find that is correct.

I would be grateful if you could review my proposed changes and say me if I am right with these.

Many thanks,

José Emilio Sánchez

#### Any other comments?

I have created another pull request in rdkit-orig repository a few moments ago, but I realized that the good place was here. Sorry for the inconvenience.

### CODE REVIEW

**Comment by greglandrum** [comment]
Hi José, thanks for the PR (and for introducing yourself!).
Sorry my reply is so slow; this got lost in the end-of-year pile of stuff.

The PR looks good, and I would be happy to merge it as-is, but it would be even better if there was a test that went along with it to show that it works. Unfortunately the existing `rdkit.Chem.Features` code is one of the few places in the RDKit where there aren't any tests, so this would require adding some from scratch. That's a non-trivial exercise, so I'd understand if you didn't want to do it. :-)
Let me know if you want to give adding a test a try, otherwise I will happily merge this as is.

**Comment by josan82** [comment]
Hi Greg,

sorry for the delay, I was on vacation until today. 

I can try to add the test that you say, I'll get on it right now.

Thanks for your comments.

**Comment by josan82** [comment]
Hi Greg,

I've added the unittests of the function GetDonor2FeatVects. I've tried to follow the same schema as in other modules like FeatMaps.

I start the test creating a molecule from smiles with the necessary heavy atoms to test all the sub-cases of the function GetDonor2FeatVects. After it, I fix the positions of the atoms by hand to facilitate the tests afterwards.

In the tests, I check the 4 sub-cases separately. For each case, I check that the number of vectors returned by the function, their starting points, their directions and their lengths are correct.

When I was making the tests, I realized a mistake in the Case 1 and I also changed the tolerance when calling _checkplanarity function because in some cases the function returned an erroneous value due to the precision of the atoms' positions.

I hope that this kind of test is correct. If not, let me know how can I improve it.

Many thanks,

José Emilio Sánchez

**Comment by greglandrum** [comment]
Thanks!

**Pull request merged**
