### PR TITLE
Add sanitize option to molzip

### PR DESCRIPTION
**Pull request by bp-kelley**
This code allows non sanitizable fragments to be combined.  This is useful when combining multiple fragments that may eventually become a sensible molecule.

### CODE REVIEW

**Review by greglandrum — COMMENTED** [review]
I'm not convinced that `sanitize` is the best name for this option since it's not really sanitizing the molecule: you're just changing how `updatePropertyCache()` is called

Unfortunately I don't have a great alternative suggestion. Maybe `enforceValenceRules`?

**Comment by bp-kelley** [comment]
Give me the weekend to think of a better name, if not let’s merge Monday.

----
Brian Kelley

**Comment by greglandrum** [comment]
@bp-kelley : any thoughts on a new name? Should we go ahead and merge as-is?

**Comment by bp-kelley** [comment]
I'm fine with enforceValences, it was the best of all options I thought of.  I'll make the change.

**Comment by bp-kelley** [comment]
@greglandrum changed.  Just waiting on the checks.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
> @greglandrum changed. Just waiting on the checks.

Thanks!

**Pull request merged**
