### PR TITLE
Expose mappings of atom/bond indices abbreviated mol->original mol

### PR DESCRIPTION
**Pull request by ptosco**
This PR enables relating the atom/bond indices after abbreviations have been applied to atom/bond indices in the original molecule.
This is very useful, for example, to relate substructure matches on the full molecule to substructure matches on the molecule with abbreviations, such that, for example, substructure highlighting can be performed on both the original and the abbreviated molecule without incurring into mismatches.
The same mechanism adopted for `_smilesAtomOutputOrder` and `_smilesBondOutputOrder` is adopted, i.e. two properties are set on the molecule (`_origAtomMapping`, and `origBondMapping`).
I have added relevant tests, Python and JS wrappers.

### CODE REVIEW

**Comment by ptosco** [comment]
Please hold on a bit before reviewing - I am still working on this.

**Comment by ptosco** [comment]
None of the CI failures is related to this PR - it's either `smiCatchTest` segfaulting (see #5286) or the usual `DiversityPicker` failure.

**Comment by greglandrum** [comment]
I see the use case and think having access to this information would be useful.
I'm wondering why you went with adding this information as properties instead of just using additional optional arguments (or adding overloads) to `condenseMolAbbreviations()` and 'applyMatches()`.
Given that the property values don't make any sense unless you have the original molecule to refer to, maybe using the optional arguments/overloads would be better?

To be explicit, I mean something like this:
```
      std::vector<unsigned int> atomMapping;
      std::vector<unsigned int> bondMapping;
      Abbreviations::applyMatches(*m, matches, atomMapping, bondMapping);
```

**Comment by ptosco** [comment]
@greglandrum interestingly, that’s exactly how I originally did it: you could pass refs to vectors in C++ and Python lists from Python that would be filled as in `GetMolFrags()`.
However, then I realized that the code already sets a property on abbreviated mols, so I thought I could use the same mechanism.
Additionally, I have always thought that the mechanism of passing Python lists as references that get filled is not very pythonic so it woul be better to avoid it if possible.
Finally, if abbreviations are applied in multiple steps (there is a unit test for that) you need to use the existing mappings to produce new mappings that point to the indices in the molecule without abbreviations, so you need to pass the vectors in all steps. I thought using a property reduces the odds that users may pass them only in the second step and wonder why the mappings are not as expected. Also, it makes things simpler from JS so you do not have to pass the mappings as parameters for multi-step operation.

Overall, I think the current way is more practical.
We could add an optional `mapToUnabbrevMol` boolean defaulting to `false` to make the property addition optional, and rename the props to `unabbrevMolAtomMapping` and `unabbrevMolBondMapping` to further clarify.

**Comment by greglandrum** [comment]
gotcha. That makes sense.

**Review by greglandrum — APPROVED** [review]

**Pull request merged**
