### PR TITLE
added the matchFormalCharge option in the MCS algorithm

### PR DESCRIPTION
**Pull request by jbDelafosse**
I had issues with the FindMCS function as I wanted it to see the formal charge of atoms in the returned SMARTS. I added a `matchFormalCharge` option to the function whose default is `False` so it doesn't affect people that used it previously.

```
>>from rdkit import Chem
>>from rdkit.Chem import MCS
>>mol1 = Chem.MolFromSmiles("[C-][C+]CC")
>>mol2 = Chem.MolFromSmiles('[C-][C+]C')
>>mcsResult = MCS.FindMCS([mol1,mol2],matchFormalCharge=True)
>>print(mcsResult.smarts)
```
`[#6-1]-[#6+1]-[#6+0]`

Feel free to tell me what needs to be done differently if needed. I'll try to do it asap

### CODE REVIEW

**Comment by gedeck** [comment]
Can you also add a test for the new functionality?

**Comment by jbDelafosse** [comment]
Yes, I'll do this as soon as possible

**Comment by gedeck** [comment]
The two files have a lot of whitespace changes. I can give you the two files reformatted using yapf. This hopefully makes them consistent with the previous formatting and make them easier to review.

**Comment by gedeck** [comment]
Let's see if this works:

[fmcs.py.txt](https://github.com/rdkit/rdkit/files/581930/fmcs.py.txt)
[MCS.py.txt](https://github.com/rdkit/rdkit/files/581931/MCS.py.txt)

**Comment by gedeck** [comment]
Instead of:
```
      formalCharge = atom.GetFormalCharge()
      if formalCharge >= 0:
        charge_str = "+%d" % formalCharge
      else:
        charge_str = "%d" % formalCharge
```
you can use
```
    charge_str = '%+d' % atom.GetFormalCharge()
```
[See here](http://stackoverflow.com/questions/2763432/how-to-print-the-sign-of-a-digit-for-positive-numbers-in-python)

**Comment by greglandrum** [comment]
Unfortunately these changes are all relative to the python-based MCS implementation, which is no longer supported and has been deprecated (but, obviously, not yet removed).

It does make sense to be able to require charge matches in the MCS . That would be a good one for us to add to the C++ code.

**Comment by jbDelafosse** [comment]
I was afraid it would be the case. 

For the record, the C++ version does not show the valence in the smartsString when using `matchValences=True`:
```
>>from rdkit import Chem
>>from rdkit.Chem import rdFMCS
>>mol1 = Chem.MolFromSmiles("CCCC")
>>mol2 = Chem.MolFromSmiles('CCC')
>>mcsResult = rdFMCS.FindMCS([mol1,mol2],matchValences=True)
>>print(mcsResult.smarts)
```
`[#6]-[#6]-[#6]`

while the python version does as shown below:
```
>>from rdkit import Chem
>>from rdkit.Chem import MCS
>>mol1 = Chem.MolFromSmiles("CCCC")
>>mol2 = Chem.MolFromSmiles('CCC')
>>mcsResult = MCS.FindMCS([mol1,mol2],matchValences=True)
>>print(mcsResult.smarts)
```
`[#6v4]-[#6v4]-[#6v4]`

Which behavior is expected ?

I will still submit the changes requested by @gedeck to the python version. I might try to have a look at the C++ version this weekend.

**Comment by jbDelafosse** [comment]
OK i modified the python version.

**Comment by bp-kelley** [comment]
@greglandrum is this safe to merge or close in favor of #1311 ?

**Comment by greglandrum** [comment]
Assuming that @jbDelafosse agrees, I think we can close this

**Comment by jbDelafosse** [comment]
yes. close this one in favor of #1311 please

**Pull request closed without merging**
