### PR TITLE
Add prop related method into JSMol

### PR DESCRIPTION
**Pull request by hhk7734**
#### Reference Issue

Fixes: #5369

#### What does this implement/fix? Explain your changes.

MinimalLib doesn't have Get/SetProp. So I added it.

#### Test

```js
var initRDKitModule = require("../demo/RDKit_minimal.js");
var util = require("util");
var RDKitModule;

initRDKitModule().then(function (instance) {
  RDKitModule = instance;
  console.log(RDKitModule.version());

  var mol = RDKitModule.get_mol(`
  MJ201100

  8  8  0  0  0  0  0  0  0  0999 V2000
   -1.0491    1.5839    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7635    1.1714    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7635    0.3463    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0491   -0.0661    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3346    0.3463    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3346    1.1714    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3798    1.5839    0.0000 R#  0  0  0  0  0  0  0  0  0  0  0  0
    0.3798   -0.0661    0.0000 R#  0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
  2  3  1  0  0  0  0
  3  4  2  0  0  0  0
  4  5  1  0  0  0  0
  5  6  2  0  0  0  0
  6  1  1  0  0  0  0
  6  7  1  0  0  2  0
  5  8  1  0  0  2  0
M  RGP  2   7   1   8   2
M  END
`);

  console.log(`Name: ${mol.get_prop("Name")}`);
  console.log(`set Name to test`);
  mol.set_prop("Name", "test");
  console.log(`Name: ${mol.get_prop("Name")}`);
  console.log(util.inspect(JSON.parse(mol.get_json()), false, 3, true));
});
```

```shell
❯ node Code/MinimalLib/tests/test_prop.js
2022.09.1pre
Name: 
set Name to test
Name: test
{
  commonchem: { version: 10 },
  defaults: {
    atom: {
      z: 6,
      impHs: 0,
      chg: 0,
      nRad: 0,
      isotope: 0,
      stereo: 'unspecified'
    },
    bond: { bo: 1, stereo: 'unspecified' }
  },
  molecules: [
    {
      name: '',
      atoms: [
        [Object], [Object],
        [Object], [Object],
        {},       {},
        [Object], [Object]
      ],
      bonds: [
        [Object], [Object],
        [Object], [Object],
        [Object], [Object],
        [Object], [Object]
      ],
      conformers: [ [Object] ],
      properties: { Name: 'test' },
      extensions: [ [Object], [Object] ]
    }
  ]
}
```

### CODE REVIEW

**Comment by bp-kelley** [comment]
You should add has_prop and get_prop_names as well.  Get prop is of limited utility unless you can get a list of the property names.

**Comment by hhk-hits** [comment]
@bp-kelley 
Thanks, I got it. I will find and add those functions.

**Comment by hhk7734** [comment]
@bp-kelley 
Thanks, I got it. I will find and add those functions.

**Comment by hhk7734** [comment]
@greglandrum please check this :)

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
Thanks for the contribution @hhk7734 !

**Pull request merged**
