### PR TITLE
Use MODULARIZE and EXPORT_NAME

### PR DESCRIPTION
**Pull request by ptosco**
As explained here: https://github.com/rdkit/rdkit/issues/3561
I am opening this PR just to show more easily what I have done, rather than to ask for merging.

### CODE REVIEW

**Comment by greglandrum** [comment]
@ptosco : did you forget something? This just modifies the test file. Aren't there changes needed to the Dockerfile as well to make this work?

**Comment by ptosco** [comment]
@greglandrum I put a comment on the issue rather than on this PR, so I'll clone it here:
I have added the following flags to build the modularize branch: -s MODULARIZE=1 -s EXPORT_NAME=\"'initRDKitModule'\"
These flags are not part of the PR as I haven't used the Dockerfile in my build but rather a local build system.

**Comment by ptosco** [comment]
I'll add it now to the draft PR as it is easier.

**Review by greglandrum — CHANGES_REQUESTED** [review]
Changes look good to me. `Code/MinimalLib/demo/demo.html` needs to be updated for this change too though.

**Comment by ptosco** [comment]
@greglandrum Thanks Greg. OK, will update `demo.html` then and remove the Draft label.

**Comment by ptosco** [comment]
@greglandrum This seems to work for me. Testing with the updated Dockerfile now on a vanilla machine.

**Comment by ptosco** [comment]
@greglandrum The library has built OK with the new `Dockerfile`, and `demo.html` works.

**Pull request merged**
