### PR TITLE
Fixes #6049

### LINKED ISSUE #6049: Cyclobutyl group in a macrocycle triggers a stereo center
**Describe the bug**
Adding a cyclobutyl group into a macrocycle causes the nitrogen to be treated as a stereo center.

**To Reproduce**
```
>>> from rdkit import Chem
>>> mol = Chem.MolFromSmiles("O=S1(=O)C=CC=C2CCCCC3CC(C3)N21")
>>> [Chem.MolToSmiles(x) for x in Chem.EnumerateStereoisomers.EnumerateStereoisomers(mol)]
['O=S1(=O)C=CC=C2CCCCC3CC(C3)[N@@]21', 'O=S1(=O)C=CC=C2CCCCC3CC(C3)[N@]21']
```
The nitrogen isn't necessary, the following variation also treats the same position as a carbon as a stereo center:
```
>>> mol = Chem.MolFromSmiles("C1=CCC2C(=C1)CCCCC1CC2C1")
>>> [Chem.MolToSmiles(x) for x in Chem.EnumerateStereoisomers.EnumerateStereoisomers(mol)]
['C1=CC[C@@H]2C(=C1)CCCCC1CC2C1', 'C1=CC[C@H]2C(=C1)CCCCC1CC2C1']
```
**Screenshots**
Screenshot 2023-02-02 at 2 19 16 PM

**Configuration:**
```
>>> rdkit.__version__
'2022.09.4-sch'
```

### PR DESCRIPTION
**Pull request by greglandrum**
Updates the query for bridgehead atoms to resolve the issue.
This also impacts the `NumBridgeheadAtoms` descriptors, so the version on that gets bumped as well.

### CODE REVIEW

**Comment by greglandrum** [comment]
@ricrogz sorry to tag you again, but since this one is from @cdvonbargen I thought you'd want to review it

**Review by ricrogz — APPROVED** [review]
LGTM.

I always have a hard time wrapping my head around these bridgehead issues.

Somehow, this fix seems like a more complicated explanation of the intuition I keep coming back to: the idea that for a degree 3 N atom to be a bridgehead it is a necessary condition that each possible pair of bonds coming out of the atom is part of at least one common ring. I think this implies the condition the the N atom is part of 3 different rings, as it doesn't seem possible that three converging bonds/lines are part of the same ring.

In the case of the last image you posted (which is similar to the case described in the bug report), this condition is violated: bond pair (14, 0),(14, 4) is part of one 6-ring, bond pair (14, 4),(14, 11) is part of two overlapping 9-rings, but pair (14, 0),(14, 11) doesn't have any common rings, so the N atom cannot possibly be a bridgehead.

**Comment by greglandrum** [comment]
@ricrogz I agree that your description of the conditions for something to be a bridgehead seems correct. and that it is a bit simpler to explain. It's likely also easier to implement. I'll take a look at changing the implementation (and documentation) to this formulation.

**Comment by greglandrum** [comment]
Of course it's never that easy. Here's the counter-example for that formulation (this is one of the edge cases in the tests and it broke a number of my previous attempts
image
Looking around the N: bond pairs (4,6) and (3,6) share a ring, but (3,4) do not (since the six-ring isn't part of the set of small rings)

**Comment by ricrogz** [comment]
Ah, right. I didn't take SSSRs into account.

**Comment by bp-kelley** [comment]
Roger, I expect, would just do a bfs search for # rings a particular atom
is in as opposed to finding all rings.

i.e. something like

```
int getNonSSSRRingCount(const Atom *atom);
```

Cheers,
 Brian

**Pull request merged**
