### PR TITLE
Fixes #4273

### LINKED ISSUE #4273: [Enhancement]: Allow every bit-vect fixed-size fingerprints can be directly embedded || attached into the (Numpy) Array or return the Numpy Array
I am thinking about expanding extra hyper-parameter called 'destArray' which would be used to directly embedded the bit vectors of the fixed-size fingerprint into it without surpassing "ConvertToNumpyArray". 

Hyper-parameter:
"destArray": If destArray=None, everything runs normal without performance change. If destArray is a Numpy array, check the size for verification, then do the task where result was attached on "destArray". (Default dtype: int8, uint8 is preferred)

Reason: 
---> Support Faster Data Extraction on Big Data for ML + Avoid Function Call Switching of Python. Estimated Performance Improvement: 10 - 15 %

Original approach:
```
N = 1024
mol = AddHs(MolFromSmiles("COC"))
array = np.zeros(shape=(N, ), dtype=np.uint8))
bitVect = GetMorganFingerprintAsBitVect(mol, radius=2, nBits=N)
ConvertToNumpyArray(bitVect, array)
```

New approach:
```
N = 1024
mol = AddHs(MolFromSmiles("COC"))
array = np.zeros(shape=(N, ), dtype=np.uint8))
GetMorganFingerprintAsBitVect(mol, radius=2, nBits=N, destArray=array)
```

Default Call:
```
N = 1024
mol = AddHs(MolFromSmiles("COC"))
array = np.zeros(shape=(N, ), dtype=np.uint8))
GetMorganFingerprintAsBitVect(mol, ..., destArray=None)
```

The function "GetMorganFingerprintAsBitVect" is just a sample, I hope it would be implemented for AtomPairs, TopologicalTorsion, RDKFingerprint, LayeredFingerprint, etc ....

### PR DESCRIPTION
**Pull request by greglandrum**
This supports getting fingerprints or count fingerprints as Numpy arrays directly from the fingerprint generator interface.

### CODE REVIEW

**Review by bp-kelley — APPROVED** [review]

**Comment by thegodone** [comment]
Hello Greg can you also add this feature for RDKFingerprint (Topology FP) please ?

**Comment by greglandrum** [comment]
@thegodone : this is there for anything which uses the fingerprint generator interface: morgan, rdkit, atom pairs, and topological torsions.

**Comment by mwojcikowski** [comment]
@greglandrum how about getting indexes from sparse FPs? That would help generating sparse matrices from scipy without passing through explicit bit/count vector.

**Comment by greglandrum** [comment]
@mwojcikowski : that's part of the fingerprints themselves:
```
In [15]: sfp = fpgen.GetSparseFingerprint(m)

In [16]: sfp.GetOnBits()
Out[16]: <rdkit.rdBase._vecti at 0x7fc00c220430>

In [17]: list(sfp.GetOnBits())
Out[17]: [1047372116, 1048314628]
```
and
```
In [19]: scv = fpgen.GetSparseCountFingerprint(m)

In [20]: scv.GetNonzeroElements()
Out[20]: {4437622816: 1, 13027524640: 1}
```

**Comment by mwojcikowski** [comment]
@greglandrum Yes, I know these. The problem with them is that they are super slow, as per discussion in #3863. What I'm looking for is something similar to `sfp.GetOnBits()` that would return sparse numpy vector. I will benchmark this PR when I have the time to see how it performs vs `.ToBitString()` hack which was used in linked discussion.

**Comment by greglandrum** [comment]
@mwojcikowski I'm not enthusiastic about adding a direct dependency on another package, but if there's a form we can provide the data in which makes creation of a sparse scipy matrix more efficient, I'd be happy to look into adding it.

**Pull request merged**
