### PR TITLE
Further cmake improvements

### PR DESCRIPTION
**Pull request by avaucher**
This is a follow-up for PR #1488.

It mainly consists in using (more) modern CMake style to import dependencies:
* Boost
* Qt
* Threads
* Eigen
* Cairo

as well as a few other modifications.

### CODE REVIEW

**Comment by greglandrum** [comment]
@avaucher : the current travis build failures is a result of the cmake code trying to pull in some additional boost libraries - date_time, chrono, and maybe atomic - that I believe are not actually required. At least they've never been required before.

Any idea what's going on here? It's causing build failures because the boost builds that I use only include a minimal subset of boost libraries.

**Comment by avaucher** [comment]
Yes, it looks strange - I will take a detailed look at this later this evening.

**Comment by avaucher** [comment]
@greglandrum Are `date_time`, `chrono` and `atomic` installed on the CI machine?  
Actually, they appear to be required indirectly through Boost::thread (f.i., have a look [here](https://github.com/Kitware/CMake/blob/master/Modules/FindBoost.cmake#L693)). 

As to why this problem didn't appear before, I guess that rdkit uses a subset of Boost::thread that doesn't use those libraries (I haven't looked further into it).

**Comment by greglandrum** [comment]
I'm not sure, but I think that Boost::thread uses head-only portions of those libraries.

The libraries are not installed on the CI machine: The boost libraries that are used are brought in through the conda boost build that I do for the RDKit, and I have kept the compiled libraries to a minimum. I would really prefer not to have to re-do all of those builds and add new compiled libraries that are only there to keep cmake happy.

**Comment by avaucher** [comment]
I get your point, really.
Strangely, I must say that this very issue is one of the reasons I like to use imported targets - let's say I want to use `boost::filesystem`, I just need to mention this and CMake will include `boost::system` automatically. I will not run into a linking error from which I will deduce that I must also link the `system` library - CMake handles this for me directly. Also, if in a future version `boost::filesystem` requires some further library, I won't need to change anything - CMake will know it.

The bit about the parts of `boost::thread` used in `rdkit` requiring only header-only portions of the other libraries is a bit unfortunate. If it were just for me, I would go the discomfort of including the other compiled parts of boost - in the end, it's only half an additional dependency, since it's still only boost. In my eyes it's not just about making CMake happy, it's more than that. But this is your library, not mine, so I understand if you don't.  
However, not doing so kind of defeats the whole point of this PR, and also partly that of #1488 .

**Comment by greglandrum** [comment]
you make a good argument. I'll take a look at updating the boost recipes for conda.

**Comment by greglandrum** [comment]
Thanks again for the contribution.

**Pull request merged**
