### PR TITLE
fixes #3967

### LINKED ISSUE #3967: Double bond stereo gets flipped by SMILES reader/writer
**Describe the bug**
Double bond stereo is flipped if you roundtrip a SMILES and double bond is located at the ring closure in canonical SMILES

**To Reproduce**
```python
print(Chem.CanonSmiles('C=c1s/c2n(c1=O)CCCCCCC\\N=2'))
```
Output: `C=c1s/c2n(c1=O)CCCCCCC/N=2`

**Expected behavior**
Double bond stereo should be retained

**Screenshots**
image

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.5
 - OS: MacOS
 - Python version (if relevant): 3.8
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

### PR DESCRIPTION
**Pull request by jfkonecn**
Reference Issue
fixes #3967

What does this implement/fix? Explain your changes.

Seems like the two reported smiles issues are caused by two different bugs.

For "C=c1s/c2n(c1=O)CCCCCCC\\N=2" the bug seems like it's cause by the ring closure happening on the double bond. This condition is checked on line 384 in Canon.cpp

I struggled quite a bit figuring out exactly why "C1=C\\C/C=C2C3=C/C/C=C\\C=C/C\\3C\\2\\C=C/1" isn't working. It seems like it's a similar issue to the first one, but only because "secondFromAtom1" is not aromatic and is closing the ring. The condition for checking this is on lines 385-387 in Canon.cpp

I wanted to refactor this line into an inline function since it is use many times, but I didn't want to make this PR too big.
atom2Dir = (atom2Dir == Bond::ENDUPRIGHT) ? Bond::ENDDOWNRIGHT
                                                : Bond::ENDUPRIGHT;

### CODE REVIEW

**Comment by greglandrum** [comment]
@jfkonecn : thanks for tracking this one down and submitting a fix.
Your changes mostly look good. I submitted a PR against your branch to modernize the tests a bit.

You're right about that pattern occuring frequently. I'd be fine with that being refactored to be an inline function, but it would be better as a separate PR. That allows me to classify this one as a bug fix and us to get the change out in the next patch release.

**Comment by jfkonecn** [comment]
Sounds good. I have a few questions

1. I'm not too experienced with c++..... What does this line do?
auto mol = "C=c1s/c2n(c1=O)CCCCCCC\\N=2"_smiles;

2. Do I need to make an issue ticket for a refactor? 

Thank you for reviewing this PR so quickly!

**Comment by greglandrum** [comment]
> Sounds good. I have a few questions
> 
> 1. I'm not too experienced with c++..... What does this line do?
>    auto mol = "C=c1s/c2n(c1=O)CCCCCCC\N=2"_smiles;

That's a user-defined literal (https://www.modernescpp.com/index.php/user-defined-literals) that we define in the RDKit. It tells the compiler to call `SmilesToMol()` and then return an `std::unique_ptr` to the resulting molecule. It's defined here:
https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/SmilesParse/SmilesParse.h#L114

> 2. Do I need to make an issue ticket for a refactor?

No, don't worry about that. I will just tag the PR appropriately.

**Review by greglandrum — APPROVED** [review]

**Comment by mwojcikowski** [comment]
Thanks @jfkonecn for fixing the bug!

**Comment by jfkonecn** [comment]
You're welcome!

**Pull request merged**
