### PR TITLE
Remove O(N) behavior of getNumBonds

### PR DESCRIPTION
**Pull request by bp-kelley**
Small tweak to fix the O(N) behavior or getNumBonds

### CODE REVIEW

**Comment by bp-kelley** [comment]
@greglandrum Roger will like this one...

**Comment by d-b-w** [comment]
Would it make sense to update the copy constructor at the same time? I suppose it's not rate-limiting there.

**Comment by greglandrum** [comment]
Amazing that this ended up being forgotten

**Comment by bp-kelley** [comment]
@greglandrum I was hyper focused on the addBond case!

**Pull request merged**
