### PR TITLE
Add a new parameter to mol_adjust_query_properties for generic query parameters

### PR DESCRIPTION
**Pull request by bjonnh-work**
Adds a new parameter to mol_adjust_query_properties:"setGenericQueryFromProperties"
that defaults to false (so no change of behavior until used).

This PR also removes the previous way of doing it that involved reprocessing the query molecule for every comparison.

On datasets of 200k molecules the speed-up is between 2 (large complex substructure searches with repeating units) to 5 times (tiny substructures search).

### CODE REVIEW

**Comment by bjonnh-work** [comment]
This is not working probably because we call:
```
extern "C" Mol *deconstructROMol(CROMol data) {
  auto *mol = (ROMol *)data;
  ByteA b;

  try {
    MolPickler::pickleMol(mol, b);
  } catch (MolPicklerException &e) {
    elog(ERROR, "pickleMol: %s", e.what());
  } catch (...) {
    elog(ERROR, "deconstructROMol: Unknown exception");
  }

  return (Mol *)b.toByteA();
}
```

**Comment by greglandrum** [comment]
@bjonnh-work The cartridge changes look good (though I haven't thoroughly reviewed them yet), but I'm not a fan of adding the dependency on the generic groups library to the main GraphMol code. Unfortunately since GenericGroups is a separate library, with a dependency on GraphMol, you can't just use the library.

Some alternatives I can think of:
1. Move the functionality in GenericGroups to GraphMol. I don't particularly like this because the code does seem somewhat specialized (not of interest to everyone). But it is a possibility 
2. Add a version of adjustQueryProperties() to GenericGroups which calls the standard version and also makes the setGenericQueriesFromProperties(mol) call.
3. Just make the change in the cartridge itself.

I think I'd prefer 2. What do you think?

**Comment by bjonnh-work** [comment]
2 sounds ok for me, I'll work on that

**Comment by greglandrum** [comment]
> Do you think it is ok to have the parameter staying in AdjustQueryParameters ? or should I make a new parameter to that new function in GenericGroups?

Which parameter?
I think it would be fine if the one in the `GenericGroups` namespace always called `setGenericQueriesFromProperties` if that's what you're asking.

**Comment by bjonnh-work** [comment]
https://github.com/rdkit/rdkit/pull/6332/files#diff-0626b4c6975c96645ba7dc011d3c604412a1381d9f6194a05bb19772517d94dbR18

I liked the idea to be able to set that as a flag in the JSON configuration of the function.

**Comment by bjonnh-work** [comment]
If not that mean we need two separate functions in the cartridge as well as I don't think it should be made the default in it.

**Comment by bjonnh-work** [comment]
this is the parameter I am referring to: https://github.com/rdkit/rdkit/pull/6332/files#diff-49dd85b91b1783997326b31fedd6c6e2fac6703d9b22291a7a1c690fab840606R379-R384

**Comment by bjonnh-work** [comment]
But I think you are right, that's a bit ugly like that, I'll fix all that and make two entirely different functions.

**Comment by greglandrum** [comment]
@bjonnh-work, I just did a PR against your branch with some suggested changes.

**Review by greglandrum — CHANGES_REQUESTED** [review]
Two very small suggestions.

**Comment by greglandrum** [comment]
Thanks @bjonnh-work !

**Pull request merged**
