### PR TITLE
Added cstdint include

### PR DESCRIPTION
**Pull request by vedranmiletic**
Required for uint64_t, fixes compile error

### CODE REVIEW

**Comment by vedranmiletic** [comment]
Why was the operation cancelled on macOS?

**Comment by greglandrum** [comment]
> Why was the operation cancelled on macOS?

It timed out. That happens occasionally and isn't due to your PR. Don't worry about it.

**Comment by vedranmiletic** [comment]
> @vedranmiletic out of curiosity: which system/compiler were you getting the compile error on and where did the error occur?

It's on Arch Linux (x86_64) and GCC 13.1.1. It occurs in the beginning of the build, I can check the exact object/file name if it helps.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
@vedranmiletic thanks for the contribution!

**Comment by greglandrum** [comment]
> It's on Arch Linux (x86_64) and GCC 13.1.1. It occurs in the beginning of the build, I can check the exact object/file name if it helps.

Don't worry about it, I was just curious since we hadn't seen that problem reported previously.

**Pull request merged**
