### PR TITLE
massive simplification of README.md

### PR DESCRIPTION
**Pull request by greglandrum**
While talking to @RPirie96 at the UGM I realized that our README.md and README files were confusing and less than useful.

This aims to strip them down so that they are actually approachable and useful.

It's not unlikely that I've forgotten something, so feedback is very welcome. :-)

### CODE REVIEW

**Comment by RPirie96** [comment]
@greglandrum this looks great, definitely much easier to follow! Wondering (if its not a massive pain to do, and would happily pull together myself) whether it would be worth moving the past UGMs to a single repo to link in the README? Appreciate the list of links is clunky but they are a really useful resource!

**Comment by greglandrum** [comment]
> Wondering (if its not a massive pain to do, and would happily pull together myself) whether it would be worth moving the past UGMs to a single repo to link in the README? Appreciate the list of links is clunky but they are a really useful resource!

I agree that they are a useful resource. They are linked from rdkit.org (well, except for last year and this year... I need to update that page), but maybe we could figure out some other place in the docs for those links

**Comment by greglandrum** [comment]
> 
> I agree that they are a useful resource. They are linked from rdkit.org (well, except for last year and this year... I need to update that page), but maybe we could figure out some other place in the docs for those links

Oh! I can actually add the links to the very bottom of the README (in the community section) without having it be distracting... I will do that.

**Comment by RPirie96** [comment]
> > I agree that they are a useful resource. They are linked from rdkit.org (well, except for last year and this year... I need to update that page), but maybe we could figure out some other place in the docs for those links
> 
> Oh! I can actually add the links to the very bottom of the README (in the community section) without having it be distracting... I will do that.

I agree that works

Final really pedantic suggestion, if you're trying to encourage people towards Discussions rather than the mailing list (I vaguely remember this getting mentioned at the UGM) I'd swap these so the link to GitHub discussions is first!

""
If you have questions, comments, or suggestions, the best places for those are:

The [mailing list](https://sourceforge.net/p/rdkit/mailman/)
[GitHub discussions](https://github.com/rdkit/rdkit/discussions)

""

**Comment by greglandrum** [comment]
@ricrogz are you ok with these changes?

Since this is just documentation, do you have any objections to me pushing this into the 2024.09.1 release?

**Review by ricrogz — APPROVED** [review]
The changes look good to me, and I have no objection about this being in 2024.09.1

**Comment by DavidACosgrove** [comment]
More pedantry- since you mention how the python and java wrappers are created, maybe mention emscripten for the JavaScript?

**Comment by vandan-revanur** [comment]
@greglandrum I notice the section called `Projects using RDKit` is removed in this change. 
It would be really nice if we could list them in some other markdown file. 
I am asking since two python packages written by me , were mentioned in that list. 

Do you have some good suggestions where we could list them?

**Comment by greglandrum** [comment]
> @greglandrum I notice the section called `Projects using RDKit` is removed in this change. It would be really nice if we could list them in some other markdown file. I am asking since two python packages written by me , were mentioned in that list.
> 
> Do you have some good suggestions where we could list them?

That's a good question. It's not really part of the RDKit docs, but we could maybe add a page to the [wiki](https://github.com/rdkit/rdkit/wiki)?

**Pull request merged**
