### PR TITLE
Enhanced Similarity Maps depiction

### PR DESCRIPTION
**Pull request by gerebtzoff**
- White background 
 - “Zero” contour line removed
 - White boxes around labels removed
 - Dark square with ticks surrounding the image removed
 - Shorter dashes for negative contour lines

### CODE REVIEW

**Comment by greglandrum** [comment]
I think these look great. 
Here's an example corresponding to the first figure in Similarity Maps section of the Getting Started doc (http://www.rdkit.org/docs/GettingStartedInPython.html#generating-similarity-maps-using-fingerprints):
image
@sriniker : if you agree that this is an improvement, I'll go ahead and merge it.

**Comment by sriniker** [comment]
These look great indeed!

**Comment by greglandrum** [comment]
Thanks for the contribution!

**Comment by EDubx** [comment]
Hi,

Thank you very much for this very useful and beautiful feature !

One suggestion: 
For some molecules, maps are cropped. 
I found that this can be solved by increasing the extraGridPadding parameter at line 174:
_ps.extraGridPadding = 0.5_

I suggest that the padding value could be passed as an optional parameter, such as:

_def GetSimilarityMapFromWeights(mol, weights, colorMap=None, scale=-1, size=(250, 250),
                                sigma=None, coordScale=1.5, step=0.01, colors='k', contourLines=10,
                                alpha=0.5, draw2d=None, **extraGridPadding = 0.5**, **kwargs):_

Example with the current default value (0.5):
image

With increased value (1.5):
image

With kind regards,
Eric

**Pull request merged**
