### PR TITLE
Fix/urange check

### LINKED ISSUE #1461: URANGE_CHECK not doing its job in RWMol::addBond
The following code fails a PRECONDITION in addBond with "bond already exists". 
```
  RDKit::RWMol mol;
  unsigned int b0 = mol.addBond(0U, 1U);
```

In fact, the atoms don't exist, but the URANGE_CHECK is underflowing.

### PR DESCRIPTION
**Pull request by bp-kelley**
#### Reference Issue

Fixes #1461

#### What does this implement/fix? Explain your changes.

This is a complicated one.  Basically URANGE_CHECK when
 used on unsigned integers has a problem when the size of
 the range it’s checking is 0.  The standard operations is
 to check
 
```   
    URANGE_CHECK(num, size-1, "...")
```

Which (for unsigned integers) obviously rolls over.  This fixes all usage cases to be

```    
    URANGE_CHECK(num+1, size, "...")
```
    
And fixes the bugs found.  (addBond and the mmff tests).

This may not be the correct way we really want to fix this, I could have done a cast to:

ssize_t in the URANGE_CHECK MACRO for instance.  We would still have needed to fix the mmff tests and addBonds though.

### CODE REVIEW

**Comment by greglandrum** [comment]
I don't like the `num+1` part, because it makes the intent of the operator unclear. 
How about including the `num+1` in the `#define` itself:
```
  if ((x+1) > (hi)) {                                                         \
```

**Comment by bp-kelley** [comment]
Will do.

**Comment by greglandrum** [comment]
@bp-kelley : I was going to try and do the 2017.03.4 release this week before I leave for vacation. Any chance you can finish this in the next day or so or should we move #1461 to the 2017.09.1 release?

**Comment by greglandrum** [comment]
Actually: I just checked what's been fixed for that release and it's hardly worth doing it as is. We can probably safely hold off and do everything with the 2017.09.1 release

**Comment by bp-kelley** [comment]
There is only one known bug that it fixes (but it is a seg fault) in the
python api.  I'm happy holding off.

**Comment by greglandrum** [comment]
@bp-kelley : just a quick reminder that this is waiting on one "small" change (the `if ((x+1) > (hi)) {` thing mentioned above)

**Comment by bp-kelley** [comment]
@greglandrum Should be good to go now.

**Pull request merged**
