### PR TITLE
Make the defaults for some functions less error prone.

### PR DESCRIPTION
**Pull request by greglandrum**
The changes are listed in #1679

### CODE REVIEW

**Comment by greglandrum** [comment]
I had originally done this against the wrong branch. That's cleared up now.

**Comment by bp-kelley** [comment]
@greglandrum looks like one of the merges I just did caused some conflicts.

**Comment by greglandrum** [comment]
I'll clear them up. You ok with the changes?

**Comment by bp-kelley** [comment]
I’ll do another once through and merge today if I don’t find anything.

----
Brian Kelley

**Comment by greglandrum** [comment]
ok, I rebased it back onto `modern_cxx` and fixed the one conflict. Let's see how travis does, everything looks fine on my linux box

**Pull request merged**
