### PR TITLE
fix a memory problem with RDProps

### PR DESCRIPTION
**Pull request by greglandrum**
there was some double deletion going on that led to problems on windows.

### CODE REVIEW

**Comment by bp-kelley** [comment]
Do you know the chain for this?  When we copy a value, we need to destroy the old one.  I just can't seem to find the trace where this is done.

I suppose I would be happier to set the pointers to 0 as opposed to removing the destroy() call.

**Comment by bp-kelley** [comment]
I mean I can't find the double delete case.

**Comment by bp-kelley** [comment]
Now I'm double confused.  When destroy is called, it sets the tag to:

```
type = RDTypeTag::EmptyTag;
```

Which means that no deletes should every be called again on the same value when destroy is called.  Time for me to run valgrind I think unless you have a trace.

**Comment by bp-kelley** [comment]
I.e. it (should be) safe to call destroy twice in a row.

**Comment by greglandrum** [comment]
I don't have a saved one. The problem happened with the `update()` method with values that are INT_VECTS
This results in two different dictionaries holding onto a pointer to the same object (I think) and then deleting it twice.

**Comment by greglandrum** [comment]
if you want to see the problem, just run testDict under valgrind.
The old version has the double delete for the INT_VECT cases, this version is clean (and does not leak)

**Comment by bp-kelley** [comment]
I expect it leaks when a key is reset to another value though.  I'll check under valgrind.

**Comment by greglandrum** [comment]
The double deletion happens because of this:
https://github.com/rdkit/rdkit/blob/master/Code/RDGeneral/Dict.h#L74

That copies an RDValue, which copies the pointer to an INT_VECT, then the next line resets the value, which deletes the pointer in the copy. The original RDValue then deletes it again when it is cleaned up after the dictionary is destroyed.

**Comment by greglandrum** [comment]
I certainly don't want to introduce a leak in this data structure, but I thought we covered most everything in testDict and that was clean (at least for me) in valgrind.

**Comment by bp-kelley** [comment]
Duplicated.  I'll see what the underlying issue is tonight and see if there is a better solution.

**Comment by bp-kelley** [comment]
Oh man, it's stupider than I thought.

```
          _data.push_back(pair);
          copy_rdvalue(_data.back().val, pair.val);
```

I'm copying a value onto itself!

**Comment by bp-kelley** [comment]
Fix will come tonight.

**Comment by bp-kelley** [comment]
Superseded by #1571

**Pull request closed without merging**
