### PR TITLE
Cart fixes

### PR DESCRIPTION
**Pull request by jones-gareth**
#### Additional Java API features

Small changes to improve Java API

* Expose Tversky operator for sparse fingerprints
* Allow ExplicitBitVect to be converted to/from Java byte arrays (Java cannot process binary strings)

Thanks,
Gareth

### CODE REVIEW

**Comment by greglandrum** [comment]
I'm going to make the "executive decision" that this is fixing a bug - these should have been in the JavaWrappers all along - and not a new feature. :-)

**Comment by greglandrum** [comment]
Question: this is solving the same problem as the molecule serialization (https://github.com/rdkit/rdkit/blob/master/Code/JavaWrappers/ROMol.i#L382) but in a different way. I am not enough of a SWIG expert to understand which of these is the better solution. @jones-gareth : is that something you can speak to?

**Comment by jones-gareth** [comment]
@greglandrum Yes, this is a different approach to serialization.  I think there are a couple of advantages to my approach.

 1. In the ROMol case each C byte is transferred into an int (4 bytes), taking up 4 times as much memory as needed.
2. ExplicitBitVect now returns a Java byte array which I can directly persist using Java's serialization mechanism, however ROMol returns a native swig object and I'd have to copy to a Java int array prior to Java serialization.

On the other side the advantage of the ROMol approach is that the SWIG wrapper code is a little easier to deal with.  

I'd be happy to add the byte array stuff to ROMols, I guess I would want that if I was saving a bunch of ROMols to disk.

I've been using ROMols and fingerprints in a Java multi-threaded environment and I'm really pleased with their performance and thread safety.

**Comment by greglandrum** [comment]
Thanks for the explanation. I agree that what you've done for ExplicitBitVects sounds better.

Given that there are a bunch of RDKit mols out there that have been serialized from Java within KNIME, if we were to make a change in ROMol it would need to maintain backwards compatibility. I guess the easiest way to do this would be to leave the current serialization mechanism in place (thus allowing existing java code to continue working) and add the new mechanism for use in new code.

I'm glad that the ROMols and fingerprints are working in a multi-threaded environment for you; thanks for the feedback! Having KNIME as a test platform (really the major test platform for the Java code) has really helped there. :-)

**Comment by bp-kelley** [comment]
I believe I started using java byte arrays when I did the FilterCatalog serialization.  It seemed to be More java friendly.

**Comment by jones-gareth** [comment]
@greglandrum I forgot that you work for KNIME.  Anyway nice work.

**Comment by jones-gareth** [comment]
Oops I don't think I should have closed this

**Comment by greglandrum** [comment]
@jones-gareth : thanks for the contribution!

**Pull request merged**
