### PR TITLE
Fix/github685

### PR DESCRIPTION
**Pull request by greglandrum**

### CODE REVIEW

**Comment by bp-kelley** [comment]
Ug, my brain hurts.  Basically if chirality isn't specified in a reaction where one of the reactant's chiral atoms gets removed (and perhaps replaced with an atom that removes chirality Cl->C here) and a reagent has chirality, the internal mappings get messed up.

If chirality is defined in the product template, the product will get that defined template's chirality but in the case where chirality is not in the product template, we don't simply copy the chirality of the reagent?

Did that make any sense whatsoever?

**Comment by bp-kelley** [comment]
@greglandrum I'll try and make a reactant/product matrix when I have some free time tomorrow to see if we can document the logic I tried to explain earlier.

**Comment by bp-kelley** [comment]
I'm not finding the time for this, I might have to defer to you for this one.

**Comment by greglandrum** [comment]
I think it may be less complicated than that.
There are some circumstances when stereochemistry information from the reactant molecules can safely be carried over (or perhaps carried over with a swap of chirality) into the products of a reaction:
0. Unmapped atoms connected either to other unmapped atoms or to mapped atoms that are present in both the reactant template and the product template are fine: their chirality remains untouched 
1. The degree of the atom in the reactant and the product must be the same.
2. The number of new bonds in the product (i.e. those not corresponding to bonds in the reactant) must be <=1.

There may well be other cases as well that could be handled, but this is what's in place now. I'd rather discard stereochemistry that theoretically could be preserved than screw things up.

This particular bug fix is about correctly recognizing a new bond formed in the product template.

**Comment by bp-kelley** [comment]
Yes, it certainly fixes that problem.  I'll mark the matrix I was talking about as a documentation enhancement and accept the pull.  I certainly have seen stereo issues with some photochem reactions that needed to be fixed after the fact, and these do look resolved.

**Pull request merged**
