### PR TITLE
Fixes #3531

### LINKED ISSUE #3531: Newest RDKIT version allowing chemically invalid smiles
The version 2020.09.1 considers many invalid molecules to be valid, wheres older versions don't. For a particular example,
running 

    from rdkit import Chem
    s = 'CCOOOOSOSCCl=C=O'
    Chem.MolToSmiles(Chem.MolFromSmiles(s))

throws an error on the 2020.03.3 version (correctly), but returns the original smile on the 2020.09.1 version.

### PR DESCRIPTION
**Pull request by greglandrum**
Removes the new valences for Cl

### CODE REVIEW

**Review by ptosco — APPROVED** [review]
Are you sure you do not want to revert also for `Br`? It is certainly less of an issue than `Cl`, but probably also the usefulness of the additional valences on `Br` is smaller than with `I`. `C#Br`

**Review by bp-kelley — APPROVED** [review]

**Comment by greglandrum** [comment]
> Are you sure you do not want to revert also for `Br`?

Good point. I did that. Will merge once the tests pass.

**Comment by skearnes** [comment]
This change breaks some parsing of hypervalent halogens in USPTO; see for instance https://client.open-reaction-database.org/id/ord-906d0607de20494ab469360066161c93

@brilee

**Comment by brilee** [comment]
I understand that C#Br is an undesirable outcome, but arguably, the thing that's wrong here is the triple bond to Br, not that Br is hypervalent. The Br3- anion is a perfectly cromulent chemical species.

**Comment by brilee** [comment]
(this is issue https://github.com/rdkit/rdkit/issues/4420)

**Pull request merged**
