### PR TITLE
Update distance bounds calculation for conjugated double bonds in macrocycles

### PR DESCRIPTION
**Pull request by fwaibl**
# Summary
In a system with conjugated double bonds, the single bond in the middle can be either "trans" (180 degrees) or "cis" (0 degrees). In a non-cyclic system, the trans configuration is preferred. In a small ring (like benzene), the single bond needs to be cis. However, in a macroycle both options should be possible. However, ETKDG previously only generated the "cis" conformer.

# Changes
* Previously, `C=C([#1])C([#1])=C` groups in a macrocycle were always cis because of a bug in the bounds calculation. Although the bounds within the main chain (carbon-carbon) allowed cis or trans, the 1-4 bounds of the H atoms were always set to trans, which forces the carbons into the cis position. This change fixes this behavior to allow cis or trans conformations.
* Furthermore, the useMacrocycle14config flag could only be used from Python by creating an ETKDGv3 object, and defaulted to False otherwise. This change adds the flag to EmbedMolecule, EmbedMultipleConfs, and the EmbedParameters Python interface.
* This also adds a test case for the changed behavior. The test uses the molecule `C1/C=C/C=C/CCCCCCCCC1` (fails with the old code, but succeeds with the new one)
* I also updated the docstring in EmbedMolecule according to https://www.rdkit.org/docs/RDKit_Book.html#parameters-controlling-conformer-generation (copying the description of useMacrocycleTorsions and useMacrocycle14config)

I made the default `useMacrocycle14config=True` in EmbedMolecule, to be consistent with the default for useMacrocycleTorsion. However, it was previously False, so this could change the behavior of existing scripts. How should we deal with this?

# To-do
* I only made a test case from the C++ side, but if you want, I could also add a test case with the same content for the Python side to test the useMacrocycle14config flag.
* Run the macrocycle conformer generation test set.

### CODE REVIEW

**Comment by fwaibl** [comment]
I just saw that there was recently a commit that made `useMacrocycle14config=True` the default. In my testing, it seemed like this is not the case, but I am not sure why this was the case...

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
We've also checked these changes against our macrocycle validation set and made sure that they don't adversely impact the performance of the conformer generator when it comes to reproducing crystal conformers.

**Comment by greglandrum** [comment]
Thanks for the fix @fwaibl !

**Comment by greglandrum** [comment]
changing the milestone on this one since it makes more sense together with the changes to make ETKDGv3 the default (#6985)

**Pull request merged**
