### PR TITLE
Allow celery and rdkit coexist in Python 2.7

### LINKED ISSUE #1434: _isCallable clashes with Celery
with Celery version `4.0.2`

    from celery import Celery
    from rdkit.Chem import Descriptors

gives this error:

```
Traceback (most recent call last):
  File "/tmp/abc.py", line 5, in <module>
    from seacore.run.scoring import (
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/seacore/run/scoring.py", line 23, in <module>
    from fpcore.rdkit_common import tc_matrix_rdkit
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/fpcore/rdkit_common.py", line 20, in <module>
    from rdkit.Chem import Descriptors, inchi
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/rdkit/Chem/Descriptors.py", line 195, in <module>
    _setupDescriptors(locals())
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/rdkit/Chem/Descriptors.py", line 62, in _setupDescriptors
    if _isCallable(thing):
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/rdkit/Chem/Descriptors.py", line 25, in _isCallable
    return (hasattr(collections,'Callable') and isinstance(thing,collections.Callable)) or \
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/abc.py", line 144, in __instancecheck__
    return cls.__subclasscheck__(subtype)
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/abc.py", line 180, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/abc.py", line 161, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/celery/utils/abstract.py", line 54, in __subclasshook__
    return cls._subclasshook_using(CallableTask, C)
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/celery/utils/abstract.py", line 23, in _subclasshook_using
    all(_hasattr(C, attr) for attr in cls.__required_attributes__)
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/celery/utils/abstract.py", line 23, in <genexpr>
    all(_hasattr(C, attr) for attr in cls.__required_attributes__)
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/celery/utils/abstract.py", line 12, in _hasattr
    return any(attr in B.__dict__ for B in C.__mro__)
AttributeError: class _Feature has no attribute '__mro__'
```

Modifying `rdkit/Chem/Descriptors.py` by replacing

```
def _isCallable(thing):
  return (hasattr(collections,'Callable') and isinstance(thing,collections.Callable)) or \
                hasattr(thing,'__call__')
```

with 

```
def _isCallable(thing):
  try:
    is_callable = (hasattr(collections,'Callable') and isinstance(thing,collections.Callable)) or \
              hasattr(thing,'__call__')
  except:
    return False
  return is_callable
```

no longer gives an error.

### PR DESCRIPTION
**Pull request by gedeck**
Using celery and rdkit.Chem.Descriptors in Python 2.7 fails due to problems with `print_function` in the `isCallable` test. This fix removes `print_function` before the `isCallable` test.

Fixes #1434

### CODE REVIEW

**Comment by greglandrum** [comment]
Though the fix is small and won't break anything, this seems to me like we're adding a hack to the RDKit in order to workaround a bug in Celery. That doesn't seem really right.

**Comment by gedeck** [comment]
I can see your point, however I wouldn't call it a bug - just a lot of incompatibilities. 

- RDkit uses wild cards imports. Something that isn't so great, however simplifies the descriptor setup immensly
- RDkit in general doesn't control the export of modules. That's why the `print_function`, `os`, `numpy`, and a few other things leak into the Descriptors module. Usually, not a problem, but due to the wildcard import, it has consequences here.
- `print_function` uses objects that are old-style classes. As the `__future__` module supports Python 2.6, there is no way around it. Moving everything to python 3, will resolve it (but that is not for here to discuss).
- `celery` support 2.7 and 3.x only. That's why there code relies on `__mro__` here: http://docs.celeryproject.org/en/latest/_modules/celery/utils/abstract.html. 

So how do we resolve the problem. 

1. We can leave the code as-is and move what we learned into our collective knowledge so that if anyone has the problem in the future, we know the solution. 
1. We apply the fix (and hope that we remove it should we ever stop supporting Python 2.
1. We file a bug report with the celery team (hahaha - I'm not really serious here).
1. We address the wild card import / export (not worth it in my opinion)

**Comment by bp-kelley** [comment]
I can't  say I completely understand, but you could omit the test for all feature names in __future__ which may be a tad less hacky.

https://docs.python.org/2/library/__future__.html

----
Brian Kelley

**Comment by greglandrum** [comment]
Ok, that logic makes sense to me.

**Pull request merged**
