### PR TITLE
Update C# exception handling

### LINKED ISSUE #7069: CSharp Wrapper ExtendedQueryMol  Read Access Violation
**Describe the bug**

This C# code will result in a hard crash

```
Exception thrown: read access violation.
**this** was nullptr.

An unhandled exception of type 'System.AccessViolationException' occurred in RdkitTests.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

```C#
        [Fact]
        public void TestKekulizeError()
        {
            var block = @"
  ChemDraw01052410132D

  0  0  0     0  0              0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 9 8 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C 0.247500 0.428587 0.000000 0
M  V30 2 C -0.466950 0.016087 0.000000 0
M  V30 3 C -0.466950 -0.808913 0.000000 0
M  V30 4 C 0.247500 -1.221413 0.000000 0
M  V30 5 N 0.961950 -0.808913 0.000000 0
M  V30 6 C 0.961950 0.016087 0.000000 0
M  V30 7 C -1.181400 0.428587 0.000000 0
M  V30 8 * 0.604725 0.222337 0.000000 0
M  V30 9 Cl 1.181400 1.221413 0.000000 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 2
M  V30 2 2 2 3
M  V30 3 1 3 4
M  V30 4 2 4 5
M  V30 5 1 5 6
M  V30 6 2 1 6
M  V30 7 1 2 7
M  V30 8 1 8 9 ENDPTS=(2 6 1) ATTACH=ANY
M  V30 END BOND
M  V30 END CTAB
M  END
";
            var query = RWMol.MolFromMolBlock(block);
            var adjustQueryParameters = new AdjustQueryParameters()
            {
                aromatizeIfPossible = false,
                adjustDegree = false,
                adjustSingleBondsBetweenAromaticAtoms = true,
                adjustSingleBondsToDegreeOneNeighbors = true,
                makeDummiesQueries = true,
                adjustConjugatedFiveRings = true
            };
            var xqm = RDKFuncs.createExtendedQueryMol(query, true, true, true,
                adjustQueryParameters);
            Assert.NotNull(xqm);
        }
    }
```

**To Reproduce**
Run the test

**Expected behavior**
You should be able to try and create a ExtendedQueryMolecule without a memory error.

**Configuration (please complete the following information):**
 - RDKit version:  master as of 01/18/2024
 - OS: MS Windows

**Additional context**

The problem is that when `createExtendedQueryMol` is called with these options a Kekulization exception is thrown. `createExtendedQueryMol` returns a value not a pointer.  In the wrapper a `SwigValueWrapper` object contains the RDKit `ExtendedQueryMol`.  After the Kekulization error is caught the `SwigValueWrapper` object contains a `nullptr` and not a value.

The RDKit csharpwrapper defines custom exception handling which catches the Kekulization error and continues executing the function.  This breaks SWIG's pass and return by value (https://swig.org/Doc4.0/SWIGDocumentation.html#SWIGPlus_nn19) by passing a `nullptr` to `ExtendedQueryMol`'s copy constructor. 

This is the SWIG wrapper.  

```C++
SWIGEXPORT void * SWIGSTDCALL CSharp_GraphMolWrap_createExtendedQueryMol__SWIG_0(void * jarg1, unsigned int jarg2, unsigned int jarg3, unsigned int jarg4, void * jarg5) {
  void * jresult ;
  RDKit::RWMol *arg1 = 0 ;
  bool arg2 ;
  bool arg3 ;
  bool arg4 ;
  RDKit::MolOps::AdjustQueryParameters arg5 ;
  RDKit::MolOps::AdjustQueryParameters *argp5 ;
  SwigValueWrapper< RDKit::GeneralizedSubstruct::ExtendedQueryMol > result;
  
  
  arg1 = (RDKit::RWMol *)(((boost::shared_ptr< const RDKit::RWMol > *)jarg1) ? ((boost::shared_ptr< const RDKit::RWMol > *)jarg1)->get() : 0);
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "RDKit::RWMol const & reference is null", 0);
    return 0;
  } 
  arg2 = jarg2 ? true : false; 
  arg3 = jarg3 ? true : false; 
  arg4 = jarg4 ? true : false; 
  argp5 = (RDKit::MolOps::AdjustQueryParameters *)jarg5; 
  if (!argp5) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null RDKit::MolOps::AdjustQueryParameters", 0);
    return 0;
  }
  arg5 = *argp5; 
  {
    try {
      result = RDKit::GeneralizedSubstruct::createExtendedQueryMol((RDKit::RWMol const &)*arg1,arg2,arg3,arg4,SWIG_STD_MOVE(arg5));
    }
    catch (RDKit::ChemicalReactionException &e) {
      std::string err="ChemicalReactionException: ";
      err+=e.what();
      SWIG_CSharpSetPendingException(SWIG_CSharpApplicationException, err.c_str());
    }
    catch (RDKit::ChemicalReactionParserException &e) {
      std::string err="ChemicalReactionParserException: ";
      err+=e.what();
      SWIG_CSharpSetPendingException(SWIG_CSharpApplicationException, err.c_str());
    }
    catch (RDKit::ConformerException &e) {
      std::string err="ConformerException: ";
      err+=e.what();
      SWIG_CSharpSetPendingException(SWIG_CSharpApplicationException, err.c_str());
    }
    catch (RDKit::MolPicklerException &e) {
      std::string err="MolPicklerException: ";
      err+=e.what();
      SWIG_CSharpSetPendingException(SWIG_CSharpApplicationException, err.c_str());
    }
    catch (RDKit::MolSanitizeException &e) {
      std::string err="MolSanitizeException: ";
      err+=e.what();
      SWIG_CSharpSetPendingException(SWIG_CSharpApplicationException, err.c_str());
    }
    catch (RDKit::SmilesParseException e) {
      std::string err="SmilesParseException: ";
      err+=e.what();
      SWIG_CSharpSetPendingException(SWIG_CSharpApplicationException, err.c_str());
    }
    catch (KeyErrorException e) {
      std::string err="KeyError: ";
      err+=e.key();
      SWIG_CSharpSetPendingException(SWIG_CSharpApplicationException, err.c_str());
    }
    catch (std::exception e) {
      SWIG_CSharpSetPendingException(SWIG_CSharpApplicationException, "error");
    }
  }
  jresult = new RDKit::GeneralizedSubstruct::ExtendedQueryMol(result); 
  return jresult;
}
```

A Kekulization exception is thrown in
```C++
result = RDKit::GeneralizedSubstruct::createExtendedQueryMol((RDKit::RWMol const &)*arg1,arg2,arg3,arg4,SWIG_STD_MOVE(arg5));
```
The variable `result` is not set.  The exception is caught in 
```C++
catch (RDKit::MolSanitizeException &e) {
```
and code execution goes on to 
```c++
result = new RDKit::GeneralizedSubstruct::ExtendedQueryMol(result); 
```
And this point `result` is still `nullptr` , and we end up calling (XQMol.h)
```C++
  ExtendedQueryMol(const ExtendedQueryMol &other) { initFromOther(other); }
```
with `other` as a  `nullptr` not a reference, to get the memory error.

I think the only way to fix this is to use `%ignore` and `%extend` to have `createExtendedQueryMolecule` return a pointer and not a value.  I'll put in a PR for this, unless anybody has a better solution.

Note that this type of bug could affect any wrapped RDKit function that returns by value.

Lastly, I'm not sure why the query produces the Kekulization error, but will investigate.

image

### PR DESCRIPTION
**Pull request by jones-gareth**
#### Reference Issue

Fixes #7069 

#### What does this implement/fix? Explain your changes.

Currently, after posting `SWIG_CSharpSetPendingException`, execution of wrapped methods continues.  This can result in memory access errors as seen in #7069.

In SWIG you can use `return $null` to return from the wrapped method immediately after posting `SWIG_CSharpSetPendingException`.  `$null` resolves to the appropriate null value or pointer (or nothing for a void method).  I've added it to all the catch clauses.

### CODE REVIEW

**Comment by jones-gareth** [comment]
I can't see how my changes caused the tests to fail, as neither file is used in any of the checks.

**Comment by bp-kelley** [comment]
Pandas was just updated, Greg has an MR to fix it.

**Comment by bp-kelley** [comment]
@jones-gareth a merge from main will fix the issue

**Review by greglandrum — APPROVED** [review]
LGTM
(I'm deferring to your SWIG expertise here, of course)

**Pull request merged**
