### PR TITLE
Fixes #6309 and #6310

### LINKED ISSUE #6309: CXSMILES: atom with labels should not also have `dummyLabel` property set
Here's the demo:
```
In [68]: Chem.MolToCXSmiles(Chem.MolFromSmiles('F* |$;foo_p$|'))
Out[68]: '*F |$foo_p;$,atomProp:0.dummyLabel.*|'

In [69]: Chem.MolToCXSmiles(Chem.MolFromSmiles('F* |$;HAR_p$|'))
Out[69]: '*F |$HAR_p;$,atomProp:0.dummyLabel.*|'
```
Here's an example which is handled properly:
```
In [67]: Chem.MolToCXSmiles(Chem.MolFromSmiles('F* |$;XH_p$|'))
Out[67]: '*F |$XH_p;$|'
```

**Configuration (please complete the following information):**
 - RDKit version: master and releases
 - OS: all

### PR DESCRIPTION
**Pull request by greglandrum**
This also renames the psql update script added in #6269

### CODE REVIEW

**Comment by greglandrum** [comment]
@ptosco : do you have time to take a look at this?

**Comment by greglandrum** [comment]
@bjonnh-work : this gets it so that the changes you made in #6269 work with CXSMILES as input too.
Since it changes what's in the serialized data stored by the cartridge, you may want to take a look.

The changes are backwards compatible: molecules serialized with previous versions of the cartridge can still be read by this version (though, of course, they still don't have the atom or bond properties that were previously not being serialized).

**Review by ptosco — APPROVED** [review]
LGTM.

**Comment by greglandrum** [comment]
I'm going to put the larger part of this PR on hold until we get a handle on #6312 .
I'll create a smaller separate one for the psql update script rename, which we certainly want in the next release.

**Comment by bp-kelley** [comment]
@greglandrum I’m testing a fix for #6312 should be ready today or tomorrow.

**Comment by bjonnh-work** [comment]
I'll get some popcorn for the competition.

**Comment by bjonnh-work** [comment]
So what I thought is that we may not actually want to add the properties all the time, just when we need them because of the querying.

What I did is something like that:
```
Mol *deconstructROMolWithProps(CROMol data, bool keepAllProperties = false) {
    auto *mol = (ROMol *)data;
    ByteA b;

    try {
        auto pkl_opts = keepAllProperties ? MolPickler::getDefaultPickleProperties() : PicklerOps::AllProps;
        MolPickler::pickleMol(mol, b, pkl_opts);
    } catch (MolPicklerException &e) {
        elog(ERROR, "pickleMol: %s", e.what());
    } catch (...) {
        elog(ERROR, "deconstructROMol: Unknown exception");
    }

    return (Mol *)b.toByteA();
}

extern "C" Mol *deconstructROMol(CROMol data) {
    return deconstructROMolWithProps(data, false);
}

extern "C" Mol *deconstructROMolWithAllProperties(CROMol data) {
    return deconstructROMolWithProps(data, true);
}
```

Which now gives us an interface to decide what and when we want to store the properties.
This is what I want to add to :https://github.com/rdkit/rdkit/pull/6332 
So the properties get added when we do something like adjusting query properties but not for normal indexing.
Which should probably also make it work for CXSMILES and not inflate molecules that do not need those extra props.
Another approach I thought about was to add a new prop called "needExtraProperties" once we add the query labels/parameters that deconstructROMol would look for and would pickle the extra properties when it is present.

**Comment by bjonnh-work** [comment]
patching mol_in, mol_recv and mol_from_smiles to use deconstructROMolWithQueryProperties is sufficient to be able to do querying with the cxsmiles and get the conversion to work.
The only thing is that I don't see any exported C function that would allow for gathering properties. If we add that and check on "_cxsmilesLabelsProcessed" we should be able to pickle the query properties conditionally.

**Comment by greglandrum** [comment]
> So what I thought is that we may not actually want to add the properties all the time, just when we need them because of the querying.

If we can avoid bloating the molecule index all the time, I'm definintely +1 on the idea.

I will pull the fix for #6309 into a separate PR and then hold off on #6310 until we all have a chance to look at your proposed solution. Sound reasonable?

**Comment by bjonnh-work** [comment]
I think this can be closed as all the issues were solved in separate PRs?

**Pull request closed without merging**
