### PR TITLE
first pass, using google style

### PR DESCRIPTION
**Pull request by greglandrum**
@bp-kelley , please take a look at this and see what you think of the formatting.

This is the result of running clang-format with the google style. I think I'd be willing to live with this if you are.

### CODE REVIEW

**Comment by bp-kelley** [comment]
Nice.  Could you make sure that the docs aren't affected?  It was hard to tell if comments were affected or unaffected (it looks like they were, at least for line length)  If this is the case, I'd be happy to merge the request.

Perhaps we should include a top level RDKIT-Coding-Style document indicating the coding style we are adopting with links to ( and the warning that contributions may be reformatted at will :) )

https://github.com/google/styleguide
https://raw.githubusercontent.com/google/styleguide/gh-pages/google-c-style.el

**Comment by greglandrum** [comment]
It definitely does reformat comments due to line length. Was this what you were asking?

**Comment by greglandrum** [comment]
And it definitely makes sense to include a style guide.

Re: auto-formatting
I'm using this: https://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/clang-format.el , which is pretty cool

**Comment by bp-kelley** [comment]
The real question is does this Bork the documentation system?

----
Brian Kelley

**Comment by greglandrum** [comment]
I'll check with doxygen this evening/tomorrow morning. If it looks good, I'll go ahead and merge the PR.

**Comment by greglandrum** [comment]
One change I will make before merging though: I want to add indentation for namespaces. I think it helps with readability.

**Comment by bp-kelley** [comment]
It's a two edged sword,  I used to agree with your sentiment, however it
does become second nature and focuses the reader/programmer on the classes
and not the namespaces while not taking away 4 columns.

I tend to use indentation for nested namespace that has constants,  i.e.
fully completed namespace that is a small part of the codebase.

namespace Foo {
namespace FooConst {
  const int A=1;
  const int B=2;
}

class FilterCatalog {
};

}

This works because the first namespaces are "superfluous" i.e. everything
should be in a namespace anyway, so why indent.  Basically if everything is
in a namespace, the indentation doesn't buy you anything except, "hey", I'm
in a namespace which is always true, so why waste the real estate..

namespace RDKit {
namespace FilterCatalog {

class FilterCatalog {
};

}
}

I agree it is a hard mental model, but I do think it works better (except
for the constant example above, this would look weird to me) which I think
you are getting at.

namespace Foo {
namespace FooConst {
const int A=1;
const int B=2;
}

class FilterCatalog {
};

}

by the way, I just learned about namespace aliases:

// Shorten access to some commonly used names in .cc files.
namespace baz = ::foo::bar::baz;

**Pull request merged**
