### PR TITLE
GetConformerRMS() documentation is misleading

### PR DESCRIPTION
**Pull request by greglandrum**
Reported by @unixjunkie

### CODE REVIEW

**Comment by greglandrum** [comment]
Just a documentation change, so I'll merge this later today unless someone has a problem with the new wording.

**Comment by UnixJunkie** [comment]
So this is already a true minimum RMSD currently: each pair x,y of conformers are optimally superimposed 
together prior to RMSD calculation?

**Comment by greglandrum** [comment]
There's a discussion about that here:
http://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg06925.html

**Comment by greglandrum** [comment]
or were you asking about the matrix calculation?

**Comment by UnixJunkie** [comment]
ok, I now understand, and I should not use this function.

**Comment by bp-kelley** [comment]
Francois, what is your goal?

There are really two (really three) options:

(1) get the current rmsd between two molecules/conformers
(2) get the rmsd of the optimal alignment between two molecules/conformers
(3) get the rmsd of the optimal alignment between two molecules and get the
transform that achieves this rmsd.

Cheers,
 Brian




On Thu, Jun 15, 2017 at 4:29 AM, Francois BERENGER <notifications@github.com

**Comment by UnixJunkie** [comment]
My goal was (2) for two conformers of the same molecule, so I use AllChem.GetBestRMS(mol, mol, i, j)

**Pull request merged**
