### PR TITLE
Fix vulnerabilities found by fuzzer.

### PR DESCRIPTION
**Pull request by thomp-j**
#### Reference Issue

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49783
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44520

#### What does this implement/fix? Explain your changes.

(1) During fuzzing, it's possible that one atom object is added to the same Stereo group multiple times. The replaceAtom function only replaces a single occurrence. The code later references the second copy of the atom in the stereo group (which wasn't replaced) which accesses deleted memory. This change replaces all copies of an atom during the replaceAtom process.

(2) Catches situations during fuzzing where index values for text substrings in ParseOldAtomList could go out of range.

### CODE REVIEW

**Comment by greglandrum** [comment]
@thomp-j thanks for the contribution.
There's a typo in the code which is causing the builds to fail

**Comment by greglandrum** [comment]
@thomp-j : the most recent CI failure (after da73c6d) may not be real. I'm re-running the failing test to verify

**Comment by thomp-j** [comment]
Thanks for re-running. I was hoping that was the case - things look better now.

**Comment by greglandrum** [comment]
> Thanks for re-running. I was hoping that was the case - things look better now. 

Yep. If you are ready I will go ahead and do the "review" and merge the fix

**Comment by thomp-j** [comment]
> > Thanks for re-running. I was hoping that was the case - things look better now.
> 
> Yep. If you are ready I will go ahead and do the "review" and merge the fix

I think we are ready to go!

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
@thomp-j thanks for the contribution!

**Pull request merged**
