### PR TITLE
Fixes #1162 (resMolSupplierTest failing with boost 1.62)

### PR DESCRIPTION
**Pull request by ptosco**
This PR fixes #1162. At a closer look, the resMolSupplier test were fine. It was the underlying code not coping correctly with degenerate structures. Indeed, the two degenerate Kekule structures should be in the first two places when enumerating as they are degenerate. Boost 1.62 was just the trigger of two underlying bugs:
- fixed issue with weighted formal charges being stored as unsigned rather than as signed int
- the sum of formal charge and multiple bond indices is now used as last resort sort criterion to achieve stable sorting of degenerate resonance structures

### CODE REVIEW

**Comment by ptosco** [comment]
@greglandrum, @mcs07: I believe #1162 can be closed if this PR is accepted, as the latter fixes the cause rather than the symptom, which is always preferrable :-)

**Comment by mcs07** [comment]
Thanks Paolo, works great for me.

**Comment by greglandrum** [comment]
@ptosco : the code looks good. Is it possible to add a unit test that demonstrates the problem this is intended to fix (and that it's fixed)?

**Comment by ptosco** [comment]
@greglandrum Done, added C++ and Python tests for this issue #1166.

**Comment by greglandrum** [comment]
Thanks Paolo!

**Pull request merged**
