### PR TITLE
Update install.md; .deb installation in Python3

### PR DESCRIPTION
**Pull request by nbehrnd**
#### Reference Issue
Providing RDKit as a .deb package, Linux Debian and Ubuntu replace python-rdkit by python3-rdkit.

#### What does this implement/fix? Explain your changes.
Changes occur in the documentation only.  The earlier instruction to the CLI is retained as a legacy.  An updated instruction to the CLI is added which was tested and has shown to work (Debian 10 (bullseye), branch testing to run RDKit 2020.03.6 in Python 3.8.6.).

### CODE REVIEW

**Comment by UnixJunkie** [comment]
related to https://github.com/rdkit/rdkit/pull/3588

**Comment by UnixJunkie** [comment]
Looks fine to me.

**Comment by greglandrum** [comment]
@nbehrnd this got lost, sorry.
 if these instructions are still accurate, I will merge the PR

**Comment by UnixJunkie** [comment]
Looks correct to me.

**Comment by nbehrnd** [comment]
Thanks for getting back in touch.

The three packages mentioned are what is displayed when installing RDKit from the `synaptic` package manager in Linux Debian and Ubuntu.  With today's experience, however, I would like to edit this PR a little because `apt` (or its GUI, `synaptic`) *might* install additional dependencies if not already present.

On the example of a live image of Xubuntu 20.04.2 LTS fossa (log attached below), searching for their equivalents in even older Xubuntu18.04LTS would relate to e.g., `libboost-python` to (then .deb installed) Avogadro molecule viewer, or `libboost-regex` in contemporary Debian 12/bookworm to help working with Jupyter notebooks, or with no apparent equivalence *by name* (e.g., `libschroedinger-coordgenlibs1`).

Thus I would like to rearrange the said .and. add a line in line of «according to your set up, the package manager resolves the packages dependencies automatically, too».  Because the original PR dates back this long and I do not longer have access to the underlying fork locally, or on GitHub (deletion predates the range accessible for the restoration outlined [here](https://docs.github.com/en/repositories/creating-and-managing-repositories/restoring-a-deleted-repository) I'm fine with 

1) I agree on the merge of the old PR as provided.
2) when the PR is merged into the current form, I open a new fork to rearrange the said and add the line.

[2022-10-30_RDKit_test_Xubuntu20042.txt](https://github.com/rdkit/rdkit/files/9896054/2022-10-30_RDKit_test_Xubuntu20042.txt)

**Comment by nbehrnd** [comment]
@greglandrum  Running [markdownlint](https://github.com/markdownlint/markdownlint) on `Docs/Book/Install.md` mentions a couple of trailing spaces, nags about long lines, etc.  Indeed there are a few lines presenting a whole paragraph with more than 200 characters each.  The default limit of 80 chars per line in `mdl` is adjustable (or may be muted altogether) though side-by-side comparison of two versions, or reading git's diff log is easier compared to the one of a long snake.  And .md (like .tex or .org) won't start a new paragraph until there is an explicit blank line, either.

If eventually done with my edit, would be such a subsequent check/adjustment of the .md of benefit for RDKit?

**Pull request closed without merging**
