### PR TITLE
Allow extra R-groups in unlabelled positions if they do not interfere with RGD

### PR DESCRIPTION
**Pull request by ptosco**
I have recently run into an RGD issue that I will briefly describe below; more examples can be found in the following gist:
https://gist.github.com/ptosco/cc5bdd0f3d12a8add2e4be113dab3fa2

When the `onlyMatchAtRGroups` parameter is set to `true`, no substituents are allowed in position which are not labelled as R-groups.
However, there are cases where it would be desirable to be less strict and allow substituents in unlabelled positions if they do not interfere with RGD, i.e. if they do not introduce ambiguities regarding the R-groups to be extracted.
For example, with this core definition:

image

the attempt to `RGroupDecomp::add` this molecule:

image
fails.
I believe it should not fail, as only the CH<sub>3</sub>- and -NH<sub>2</sub> substituents fit the core, and the -OH group should simply be ignored.
There are other cases, described in the gist and in the added tests, that should still fail.
This PR allows unambiguous, unlabelled R-groups to be ignored when it is possible to do so, preventing legitimate molecules from being rejected just because they bear extra R-groups at unlabelled positions that do not interfere with R-group decomposition.

### CODE REVIEW

**Comment by bp-kelley** [comment]
I don't think this should be the behavior for match only at the specified rgroups.  If someone says "only match at the specified R Groups" that's exactly what the code should do, otherwise it doesn't match what's on the tin.

This seems to add a lot of complexity though for something that onlyMatchAtRGroups=false seems to take care of.

I'm a bit flexible here though, but for my free Wilson analysis at least, I think I need the former behavior.

**Comment by ptosco** [comment]
@bp-kelley In its initial incarnation the new code in this PR would be executed only if the `ignoreUnlabelledRGroups` flag was set (in addition to `onlyMatchAtRGroups`). Then I became over-enthusiastic about the new code and decided it deserved to be executed under all circumstances. Due to 1) the added complexity 2) the fact that it breaks existing use cases (such as yours), would you be happy if I reintroduce again the `ignoreUnlabelledRGroups` flag? This would keep the original behavior adding flexibility to those interested.

**Comment by greglandrum** [comment]
> @bp-kelley In its initial incarnation the new code in this PR would be executed only if the `ignoreUnlabelledRGroups` flag was set (in addition to `onlyMatchAtRGroups`). Then I became over-enthusiastic about the new code and decided it deserved to be executed under all circumstances. Due to 1) the added complexity 2) the fact that it breaks existing use cases (such as yours), would you be happy if I reintroduce again the `ignoreUnlabelledRGroups` flag? This would keep the original behavior adding flexibility only fort those interested in the proposed new behavior.

I agree with Brian that we shouldn't change the current behavior of the code. 
I'm also not thrilled about adding another binary flag because I think it's confusing *why* `onlyMatchAtRGroups` and `ignoreUnlabelledRGroups` interact in the way they do. Plus there's the whole question of what should happen when 'ignoreUnlabelledRGroups=false` and `onlyMatchAtRGroups=true`.

@ptosco : the use case of "I want only matches at labelled R groups or positions that are otherwise unambiguous" really something that happens frequently? I ask because I haven't encountered it and off the top of my head can't think of why I'd want to do this. Plus I'm imagining trying to explain to a user why some molecules have new R groups added and others are rejected...

**Comment by ptosco** [comment]
> I agree with Brian that we shouldn't change the current behavior of the code.

Yesterday I have updated the PR such that the current behavior is not altered.

> I'm also not thrilled about adding another binary flag because I think it's confusing _why_ `onlyMatchAtRGroups` and `ignoreUnlabelledRGroups` interact in the way they do.
> Plus there's the whole question of what should happen when 'ignoreUnlabelledRGroups=false`and`onlyMatchAtRGroups=true`.

Not sure why this would be a problem. This would actually lead to the current behavior (i.e., the one without this PR): the molecule is rejected if an extra, non-ambiguous  R-group which is not labelled is present. The new behavior would be enforced only explicitly setting the new `ignoreUnlabelledRGroups` flag to `true` in addition to the familiar `onlyMatchAtRGroups=true`.
Did you by any chance mean the opposite? (i.e., `ignoreUnlabelledRGroups=true` and `onlyMatchAtRGroups=false`)
If that's the case, to avoid confusion one could rename `ignoreUnlabelledRGroups` to `onlyMatchAtRGroupsTolerant` to make it clearer that the new flag only applies when `onlyMatchAtRGroups=true`.

> @ptosco : is the use case of "I want only matches at labelled R groups or positions that are otherwise unambiguous" really something that happens frequently? I ask because I haven't encountered it and off the top of my head can't think of why I'd want to do this. Plus I'm imagining trying to explain to a user why some molecules have new R groups added and others are rejected...

While one could always set `onlyMatchAtRGroups` to `false` to accept such a molecule, this can potentially lead to multiple, non-SAR-relevant R-groups (i.e., solubilizing groups pointing at solvent) cluttering the RGD table for no real reason. These R-groups would be simply ignored out by setting `onlyMatchAtRGroups` to `true`, and the molecules bearing them still accepted in the RGD table. I hope this is understandable and makes sense.
I am totally with you on the last point: this is difficult to understand. However, it is probably more so in forged cases such as those I put in the test, less in real world cases (the odd substituent sprouting from a non-labelled, non-SAR relevant region of the core).

**Comment by greglandrum** [comment]
> > I agree with Brian that we shouldn't change the current behavior of the code.
> 
> Yesterday I have updated the PR such that the current behavior is not altered.
> 
> > I'm also not thrilled about adding another binary flag because I think it's confusing _why_ `onlyMatchAtRGroups` and `ignoreUnlabelledRGroups` interact in the way they do.
> > Plus there's the whole question of what should happen when 'ignoreUnlabelledRGroups=false`and`onlyMatchAtRGroups=true`.
> 
> Not sure why this would be a problem. This would actually lead to the current behavior (i.e., the one without this PR): the molecule is rejected if an extra, non-ambiguous R-group which is not labelled is present. The new behavior would be enforced only explicitly setting the new `ignoreUnlabelledRGroups` flag to `true` in addition to the familiar `onlyMatchAtRGroups=true`.
> Did you by any chance mean the opposite? (i.e., `ignoreUnlabelledRGroups=true` and `onlyMatchAtRGroups=false`)
> If that's the case, to avoid confusion one could rename `ignoreUnlabelledRGroups` to `onlyMatchAtRGroupsTolerant` to make it clearer that the new flag only applies when `onlyMatchAtRGroups=true`.

Yes, I meant the opposite. <sigh> sorry.

> 
> > @ptosco : is the use case of "I want only matches at labelled R groups or positions that are otherwise unambiguous" really something that happens frequently? I ask because I haven't encountered it and off the top of my head can't think of why I'd want to do this. Plus I'm imagining trying to explain to a user why some molecules have new R groups added and others are rejected...
> 
> While one could always set `onlyMatchAtRGroups` to `false` to accept such a molecule, this can potentially lead to multiple, non-SAR-relevant R-groups (i.e., solubilizing groups pointing at solvent) cluttering the RGD table for no real reason. These R-groups would be simply ignored out by setting `onlyMatchAtRGroups` to `true`, and the molecules bearing them still accepted in the RGD table. I hope this is understandable and makes sense.
> I am totally with you on the last point: this is difficult to understand. However, it is probably more so in forged cases such as those I put in the test, less in real world cases (the odd substituent sprouting from a non-labelled, non-SAR relevant region of the core).

I'd agree with this 100% if there were some way to determine what's "SAR relevant" and what not. But I don't see how what you've added is actually doing that. What did I miss?

**Comment by ptosco** [comment]
@greglandrum Well, that would be left to the user. A knowledgeable user would use the `onlyMatchAtRGroupsTolerant` only after making sure that the pre-labelled core he supplied bears labels at all SAR-relevant positions (or all positions that he deems may be potentially SAR-relevant).
In the absence of such information, he would either use `onlyMatchAtRGroups=true` (which would lead to molecules having unexpected R-groups to be rejected) or `onlyMatchAtRGroups=false` (which would lead to molecules having unexpected R-groups to be accepted and the unexpected R-groups to be extracted as well).
Somehow my 6th sense tells me this PR is not getting much love ;-)

**Comment by bp-kelley** [comment]
I have to admit I'm not understanding why these cases are special. I do see that there is no real understanding of why a match was rejected.  We could have the return value explain this.

-1 no substruct match
-2 substructure match extra r-groups 

I also, personally, have no problem changing a boolean argument into an integer or enumeration.  But we could also deprecate match at groups and move this into the options class/enumeration.

I still might be not getting why we need this as opposed to the default behavior without matching r-groups.  Might this be better as a post processing tool?

**Comment by ptosco** [comment]
@bp-kelley I am thinking too that probably post-processing the output of a `onlyMatchAtRGroups=false` run keeping only the R-groups of interest is the best option. Also giving more information about the rejection is a good idea. I'll rethink this over the next few days; meanwhile, I have changed the status of this PR to draft so it is not accidentally merged. Thanks everyone for the useful discussion.

**Pull request closed without merging**
