### PR TITLE
Fix chirality handling when the chiral atom is the first one in a SMARTS

### PR DESCRIPTION
**Pull request by johnmay**
The SMARTS should set the _SmilesStart property to handle inverted chirality on the first atom.

#### Reference Issue

None but #760, #1489 are related

#### What does this implement/fix? Explain your changes.

Chirality on the first atom should invert in SMARTS like it does in SMILES. It seems there was intention for this in the code (logic in ``Canon::chiralAtomNeedsTagInversion``) but the parser was not setting the property.

```python
from rdkit import Chem

smi = "[C@H](C)(O)N"
qry = Chem.MolFromSmarts(smi)
mol = Chem.MolFromSmiles(smi);
print(mol.HasSubstructMatch(qry, useChirality=True))
# was False now True, the SMILES matches it's self as a SMARTS
```

I conda installed bison/flex but still seemed to be an older version than was currently used. May be worth someone else regenerating ``smarts.?pp.cmake`` with the minor changes to the smarts.yy.

#### Any other comments?

I have many failures when I run ``ctest`` (SegFault/Exceptions) so not sure if they breaks anything else.

I would also consider the following questionable behaviour:

```java
smi = "[C@H](C)(O)N"
qry = Chem.MolFromSmarts("[C@!H0](C)(O)N")
mol = Chem.MolFromSmiles(smi);
print(mol.HasSubstructMatch(qry, useChirality=True))
# False

smi = "[C@H](C)(O)N"
qry = Chem.MolFromSmarts("[C@h](C)(O)N")
mol = Chem.MolFromSmiles(smi);
print(mol.HasSubstructMatch(qry, useChirality=True))
# False

smi = "[C@H](C)(O)N"
qry = Chem.MolFromSmarts("[C@](C)(O)N")
mol = Chem.MolFromSmiles(smi);
print(mol.HasSubstructMatch(qry, useChirality=True))
# False
```

You could handle this this by updating ``Canon::atomHasFourthValence()`` / ``Canon::hasSingleHQuery()`` but I think the correct logic for this is normally:

```c++
bool chiralAtomNeedsTagInversion(const RDKit::ROMol &mol,
                                 const RDKit::Atom *atom, bool isAtomFirst,
                                 size_t numClosures) {
  PRECONDITION(atom, "bad atom");
//  return atom->getDegree() == 3 &&
//         ((isAtomFirst && atom->getNumExplicitHs() == 1) ||
//          (!details::atomHasFourthValence(atom) && numClosures == 1 &&
//           !details::isUnsaturated(atom, mol)));
  return atom->getDegree() == 3 && isAtomFirst;
}
```

However that would break a lot of existing code, include sulfoxides like this: ``[S@](=O)(C)CC`` invert from what RDKit currently says they are. Daylight did not support these so there is no **right** answer to what that means.

The ``numClosures`` logic doesn't look correct, but it's late and I need to look deeper. Tracking the ring closures (which it looks like the parser does) means this shouldn't be needed.

### CODE REVIEW

**Comment by mwojcikowski** [comment]
Pinning an issue I opened some time ago as well, as it is the same #3096
@johnmay I think I had an example with mix of ring closures and first atom chirality, but I would need to dig a little deeper to find them again.

**Comment by johnmay** [comment]
> Pinning an issue I opened some time ago as well, as it is the same #3096
> @johnmay I think I had an example with mix of ring closures and first atom chirality, but I would need to dig a little deeper to find them again.

So this changes the carbon case.

```python
>>> from rdkit import Chem
>>> Chem.MolToSmarts(Chem.MolFromSmarts('[S@@](=O)(-C)-CC'))
'O=[S@@](-C)-CC'
>>> Chem.MolToSmarts(Chem.MolFromSmarts('[C@@H](-O)(-C)-CC'))
'O-[C@&H1](-C)-CC'
```

This patch I am just making the SMARTS <=> SMILES consistent. My opinion is the S=O should invert like the carbon, however not all toolkits agree on this and Daylight did not support it.

```
>>> qry = Chem.MolToSmarts(Chem.MolFromSmarts('[S@@](=O)(-C)-CC'))
>>> Chem.MolFromSmiles('[S@@](=O)(-C)-CC').HasSubstructMatch(Chem.MolFromSmarts(qry), useChirality=True)
True
```

**Comment by greglandrum** [comment]
@ricrogz I think you should be aware of this one too. It relates to some of the discussion we had around #2570

Here's the behavior if this patch is applied:
|  mol (SMILES)  |  query (SMARTS)  |  current behavior | post-patch behavior |
|---|---|---|---|
| `C[C@](F)(Cl)O` | `[C@](F)(Cl)O` | False | False | 
| `[H][C@](F)(Cl)O` | `[C@](F)(Cl)O` | False | False | 
| `[H][C@](F)(Cl)O` | `[C@H](F)(Cl)O` | False | True | 

I went back and looked at the [SMARTS documentation](https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html) and found this example in the section on Atomic Primitives:
|   |   |
|---|---|
| `C[C@H](F)O` | match chirality (H-F-O anticlockwise viewed from C) |

I'm not sure how I overlooked this before, but it is clear guidance on how that particular case should be handled and indicates that the changes here are correct when Hs are present in the query.

We should still figure out whether or not the first two examples should be changed, but that's something different.

**Review by greglandrum — CHANGES_REQUESTED** [review]
The code changes look good to me, but the PR needs a test for the changed output SMARTS.
Here's a post-change example:
```
In [5]: Chem.MolToSmarts(Chem.MolFromSmarts('[C@H](F)(Cl)O'))
Out[5]: 'F[C@@&H1](Cl)O'
```
master does this:
```
In [8]: Chem.MolToSmarts(Chem.MolFromSmarts('[C@H](F)(Cl)O'))
Out[8]: 'F[C@&H1](Cl)O'
```
I think the new behavior is correct, but it does need to be tested

**Comment by greglandrum** [comment]
> I conda installed bison/flex but still seemed to be an older version than was currently used. May be worth someone else regenerating `smarts.?pp.cmake` with the minor changes to the smarts.yy.

I re-ran bison/flex on my box. I will do a PR against your branch with the updated `.cmake` files.

**Comment by johnmay** [comment]
Thanks for the PR and I'll add the test. I did try that but got the same error on the CI that now happens. Not sure what the issue is there.

```
2023-09-29T07:32:18.8069247Z In file included from /home/vsts/work/1/s/Code/GraphMol/SmilesParse/SmilesParse.cpp:43:
2023-09-29T07:32:18.8071005Z smarts.yy:75: error: "YY_DECL" redefined [-Werror]
2023-09-29T07:32:18.8071690Z In file included from /home/vsts/work/1/s/Code/GraphMol/SmilesParse/SmilesParse.cpp:38:
2023-09-29T07:32:18.8072257Z smiles.yy:78: note: this is the location of the previous definition
```

> @ricrogz I think you should be aware of this one too. It relates to some of the discussion we had around #2570
> 
> Here's the behavior if this patch is applied:
> 
> | mol (SMILES)	| query (SMARTS)       | current behavior  | post-patch behavior  |
> |---------------------| ---------------------|-------------------|----------------------|
> |`C[C@](F)(Cl)O`	|`[C@](F)(Cl)O`	       | False	           | False                |
> |`[H][C@](F)(Cl)O`	|`[C@](F)(Cl)O`	       | False	           | False                |
> |`[H][C@](F)(Cl)O`	|`[C@H](F)(Cl)O`       | False	           | True                 |
>
> I went back and looked at the [SMARTS documentation](https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html) and found this example in the section on Atomic Primitives:
> 
> `C[C@H](F)O`	match chirality (H-F-O anticlockwise viewed from C)
> I'm not sure how I overlooked this before, but it is clear guidance on how that particular case should be handled and indicates that the changes here are correct when Hs are present in the query.


> We should still figure out whether or not the first two examples should be changed, but that's something different.

Yep that is a longer debate/discussion due to the larger change in behaviour. For reference this is what CDK and Arthor do:

|                   | `[C@](F)(Cl)O` SMA |  `[C@](F)(Cl)O` SMA  |  `[C@H](F)(Cl)O` SMA | 
|-------------------|--------------------|----------------------|----------------------|
| `C[C@](F)(Cl)O`   |  Y                 |  Y                   |  N                   |
| `[H][C@](F)(Cl)O` |  Y                 |  Y                   |  Y                   |                   
| `[H][C@](F)(Cl)O` |  Y                 |  Y                   |  Y                   |                          

Our normal contact for testing the Daylight toolkit is unavailable ATM so can't confirm what the OG behaviour was. Been trying to convince @rogersayle to get our own license for such things.

In RDKIT this does work like that when the chiral atom isn't first:

```python
>>> Chem.MolFromSmiles("F[C@H](Cl)O").HasSubstructMatch(Chem.MolFromSmarts("F[C@](Cl)O"), useChirality=True);
True
>>> Chem.MolFromSmiles("F[C@H](Cl)O").HasSubstructMatch(Chem.MolFromSmarts("F[C@!H0](Cl)O"), useChirality=True);
True
```

But not if there is a single ring closure:

```python
>>> Chem.MolFromSmiles("F[C@H]1CCCCO1").HasSubstructMatch(Chem.MolFromSmarts("F[C@]1CCCCO1"), useChirality=True);
False
```

Unless it's the first atom:

```python
>>> Chem.MolFromSmiles("[C@H]1(F)CCCCO1").HasSubstructMatch(Chem.MolFromSmarts("[C@]1(F)CCCCO1"), useChirality=True);
True
```

The biggest issue with making things more consistent here is you invert the meaning on sulfoxides at the first position (``C[S@](=O)CC`` is unchanged but ``[S@](C)(=O)CC`` flips). I think those are rare enough (i.e. S in first position) it's a reasonable albeit major change.

**Comment by greglandrum** [comment]
@johnmay looks like merging my patch broke the CI. I will try and figure that out/fix it an do an alternate PR
sorry about that

**Review by johnmay — COMMENTED** [review]
Added test case for stereo inversion

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by greglandrum** [comment]
It's not directly connected to this PR, but I want to raise one of the points @ricrogz and I discussed in #2570 again since we're talking about what Daylight does/did: there's still a question about how chiral queries with 3 neighbors should match 4-coordinate chiral atoms.

What is the correct behavior here:
```
Chem.MolFromSmiles('C[C@@](F)(Cl)O').HasSubstructMatch(Chem.MolFromSmarts('[C@@](F)(Cl)O'),useChirality=True)
```
The current behavior is that the above does not match, but this does:
```
Chem.MolFromSmiles('[C@@](F)(Cl)(O)C').HasSubstructMatch(Chem.MolFromSmarts('[C@@](F)(Cl)O'),useChirality=True)
```
i.e. the fourth ligand is implicitly always "at the end"

I'm curious if this is comparable to what Daylight does/did, if the three-coordinate chiral query always matches a four-coordinate chiral atom (one could make the argument that it should), or if something else happens.

Note that this is NOT associated with the C being at the front of the SMARTS; we get (and should get) the same behavior here:
```
Chem.MolFromSmiles('C[C@@](F)(Cl)O').HasSubstructMatch(Chem.MolFromSmarts('F[C@@](Cl)O'),useChirality=True)
```

**Comment by ricrogz** [comment]
> @ricrogz I think you should be aware of this one too. It relates to some of the discussion we had around #2570

Sorry that it has taken me this long to comment back, I've been off a few days, and I'll probably be still half off for a few more days.

I haven't yet been able to get into the details in this PR, but I think I remember some of the discussion in #2570, and if I remember it correctly, and judging by the case of Daylight's hint on `C[C@H](F)O`, I think this change makes sense.

My only concern is to merge such a breaking change this late in the release cycle, mostly because I'm worried about checking the effect of this change in downstream code.

**Comment by greglandrum** [comment]
> My only concern is to merge such a breaking change this late in the release cycle, mostly because I'm worried about checking the effect of this change in downstream code.

I will defer to you on this one if you feel strongly about it, but I would argue that it's worth including given that:
- this ought to only affect a small number of cases (places where the first atom in the SMARTS is the chiral atom)
- the current behavior is wrong, so any behavior changes should be from wrong->correct. The exception to this would be if someone has built a test into their own code to detect these situations and fix them.

**Comment by ricrogz** [comment]
> I will defer to you on this one if you feel strongly about it, but I would argue that it's worth including given that

I think you should merge it. I agree that this is now doing the right thing, so any issues cause by this change should be fixed. I just wished this had been merged earlier in the release cycle.

**Comment by greglandrum** [comment]
Thanks @johnmay !

**Pull request merged**
